import { PrismaClient } from '@prisma/client'

export async function seedAbuse(prisma: PrismaClient) {
  const slug = 'abuse'
  const courseData = {
    slug,
    title: '高齢者虐待防止研修（2024年度）',
    description: '〜自分と利用者の笑顔を守るために〜',
    introduction: `
        <div class="flex flex-col items-center justify-center text-center space-y-3 pt-4 px-4">
          <div class="flex items-center gap-4">
            <span class="h-px w-8 lg:w-12 bg-blue-700 rounded-full"></span>
            <p class="text-blue-800 font-black tracking-widest text-lg lg:text-2xl uppercase">高齢者虐待防止研修</p>
            <span class="h-px w-8 lg:w-12 bg-blue-700 rounded-full"></span>
          </div>
          <h2 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight">「自分だけは大丈夫」と<br/>思っていませんか？</h2>
          <div class="max-w-2xl space-y-2 text-slate-800 text-sm lg:text-base leading-relaxed font-bold">
            <p>日々の忙しい業務の中で<br class="lg:hidden" />つい言葉が強くなってしまったり、<br class="lg:hidden" />動作を急かしてしまったりしたことは<br class="lg:hidden" />ありませんか？</p>
            <div class="p-4 lg:p-5 bg-blue-50 rounded-[1.5rem] lg:rounded-[2rem] border-2 border-blue-200 shadow-inner relative overflow-hidden text-[10px] lg:text-xs text-left">
              <div class="absolute top-0 right-0 w-16 h-16 lg:w-24 lg:h-24 bg-blue-100/50 rounded-bl-full"></div>
              <p class="relative z-10 italic text-blue-900 font-black text-xs lg:text-sm">虐待は、疲れやストレス、そして「良かれと思って」やっている習慣が、知らぬ間に虐待に繋がってしまうことがあります。</p>
            </div>
            <p class="text-[10px] lg:text-sm text-slate-900 font-black">この研修は、あなた自身と利用者様の笑顔を守るためのものです。<br/>今の自分のケアを、一度一緒に振り返ってみましょう。</p>
          </div>
        </div>
      `,
    learningObjectives: `
        <div class="flex flex-col items-center justify-center text-center space-y-4 pt-4 px-4 w-full">
          <div class="bg-blue-700 text-white px-6 py-2 rounded-full text-[10px] font-black tracking-[0.3em] uppercase mb-2 shadow-lg shadow-blue-200">Learning Objectives</div>
          <div class="grid grid-cols-1 gap-3 w-full max-w-2xl">
            <div class="group p-4 bg-white border-2 border-slate-200 rounded-[1.5rem] lg:rounded-[2rem] shadow-sm flex items-center gap-4 lg:gap-6 hover:shadow-xl hover:border-blue-400 transition-all duration-500">
              <div class="w-10 h-10 lg:w-12 lg:h-12 bg-blue-700 text-white rounded-xl flex items-center justify-center text-base lg:text-lg font-black shrink-0 shadow-lg shadow-blue-200">1</div>
              <div class="text-left">
                <h4 class="text-sm lg:text-lg font-black text-slate-900">自信を持って判断できる</h4>
                <p class="text-slate-800 text-[10px] lg:text-xs font-bold leading-relaxed">何が虐待に当たるのか、その明確な定義を正しく説明できるようになる。</p>
              </div>
            </div>
            <div class="group p-4 bg-white border-2 border-slate-200 rounded-[1.5rem] lg:rounded-[2rem] shadow-sm flex items-center gap-4 lg:gap-6 hover:shadow-xl hover:border-blue-400 transition-all duration-500">
              <div class="w-10 h-10 lg:w-12 lg:h-12 bg-blue-700 text-white rounded-xl flex items-center justify-center text-base lg:text-lg font-black shrink-0 shadow-lg shadow-blue-200">2</div>
              <div class="text-left">
                <h4 class="text-sm lg:text-lg font-black text-slate-900">虐待の芽を見つけ、ケアを磨ける</h4>
                <p class="text-slate-800 text-[10px] lg:text-xs font-bold leading-relaxed">不適切なケアにいち早く気づき、日々の言葉掛けを改善できるようになる。</p>
              </div>
            </div>
            <div class="group p-4 bg-white border-2 border-slate-200 rounded-[1.5rem] lg:rounded-[2rem] shadow-sm flex items-center gap-4 lg:gap-6 hover:shadow-xl hover:border-blue-400 transition-all duration-500">
              <div class="w-10 h-10 lg:w-12 lg:h-12 bg-blue-700 text-white rounded-xl flex items-center justify-center text-base lg:text-lg font-black shrink-0 shadow-lg shadow-blue-200">3</div>
              <div class="text-left">
                <h4 class="text-sm lg:text-lg font-black text-slate-900">自分と仲間を守る行動がとれる</h4>
                <p class="text-slate-800 text-[10px] lg:text-xs font-bold">周囲で違和感を感じた際、適切な対応（報告）ができるようになる。</p>
              </div>
            </div>
          </div>
        </div>
      `,
    videoUrl: 'https://www.youtube.com/watch?v=JVLmK8A5k1U',
    badgeLabel: '虐待防止',
    badgeIcon: 'ShieldAlert',
  }

  const slidesData = [
    { title: "高齢者虐待防止研修", order: 0, content: `<div class="flex flex-col items-center justify-center text-center space-y-6 w-full h-full"><div class="relative w-full max-w-4xl px-4"><div class="absolute inset-0 bg-blue-400 blur-3xl opacity-20 scale-150 animate-pulse"></div><div class="relative bg-transparent lg:bg-white p-0 lg:p-16 rounded-none lg:rounded-[3.5rem] shadow-none lg:shadow-2xl border-none lg:border lg:border-slate-200 w-full mx-auto"><div class="bg-blue-700 text-white px-4 lg:px-6 py-1 lg:py-1.5 rounded-full text-[8px] lg:text-[10px] font-black tracking-[0.3em] uppercase inline-block mb-6 lg:mb-8 shadow-sm">Legal Training 2024</div><h2 class="text-3xl lg:text-6xl font-black text-slate-900 leading-tight mb-4 text-balance">高齢者虐待防止研修</h2><p class="text-blue-700 text-sm lg:text-3xl font-black mt-2 whitespace-nowrap">〜尊厳を守るプロフェッショナルとして〜</p></div></div><div class="flex items-center justify-center gap-4 text-slate-500 font-black text-[8px] lg:text-[10px] tracking-widest pt-4"><span class="h-px w-6 lg:w-8 bg-slate-300"></span>CARE LEARNING SYSTEM<span class="h-px w-6 lg:w-8 bg-slate-300"></span></div></div>` },
    { title: "はじめに：『虐待』は身近にある", order: 1, content: `<div class="space-y-6 lg:space-y-8 text-center px-4 h-full flex flex-col justify-center"><div class="inline-flex items-center gap-3 px-4 py-2 bg-blue-100 text-blue-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-blue-200 mb-2 uppercase tracking-widest mx-auto">Introduction</div><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight">「自分だけは絶対にしない」<br/>そう言い切れますか？</h4><div class="p-0 lg:p-10 bg-transparent lg:bg-slate-50 border-none lg:border-2 lg:border-blue-100 shadow-none lg:shadow-xl rounded-none lg:rounded-[3rem] text-center lg:text-left text-sm lg:text-xl font-bold text-blue-800 space-y-4 lg:space-y-6 leading-relaxed max-w-4xl mx-auto"><p class="font-black">虐待は、特別な人が起こす事件とは限りません。誰にでもある「心の余裕のなさ」が、ふとした瞬間に不適切なケアへと繋がってしまうのです。</p><p class="font-black">この研修は、あなた自身と利用者様の笑顔を守るための「盾」を手に入れる時間です。</p></div></div>` },
    { title: "2024年度 義務化の背景", order: 2, content: `<div class="space-y-6 lg:space-y-8 text-center px-4 h-full flex flex-col justify-center"><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight mb-2">なぜ今、対策が強化されたのか</h4><div class="grid grid-cols-1 lg:grid-cols-2 gap-4 lg:gap-6 max-w-4xl mx-auto w-full"><div class="p-6 lg:p-8 bg-white border-2 border-slate-200 rounded-[2rem] lg:rounded-[2.5rem] shadow-xl flex flex-col items-center gap-2 lg:gap-4"><p class="font-black text-lg lg:text-xl text-blue-800">相談件数の増加</p><p class="text-xs lg:text-sm font-bold text-slate-700 leading-relaxed text-balance">施設従事者による虐待の通報件数は、過去最高を更新し続けています。</p></div><div class="p-6 lg:p-8 bg-white border-2 border-slate-200 rounded-[2rem] lg:rounded-[2.5rem] shadow-xl flex flex-col items-center gap-2 lg:gap-4"><p class="font-black text-lg lg:text-xl text-blue-800">深刻な人権侵害</p><p class="text-xs lg:text-sm font-bold text-slate-700 leading-relaxed text-balance">尊厳を傷つける行為は、利用者の生きる意欲を奪う重大な侵害です。</p></div></div></div>` },
    { title: "義務化された4つの措置", order: 3, content: `<div class="space-y-6 lg:space-y-8 text-center h-full flex flex-col justify-center px-4"><div class="inline-flex items-center gap-3 px-4 py-2 bg-red-100 text-red-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-red-200 mb-2 shadow-sm mx-auto"><span class="w-2 h-2 bg-red-700 rounded-full animate-ping"></span>MUST CHECK</div><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight">全ての事業所が実施すべき<br/>4つの必須事項</h4><div class="grid grid-cols-1 lg:grid-cols-2 gap-3 lg:gap-4 max-w-4xl mx-auto w-full"><div class="p-4 lg:p-6 bg-slate-50 border-2 border-slate-200 rounded-2xl lg:rounded-3xl text-center font-black text-sm lg:text-base text-slate-900 shadow-sm hover:border-blue-400 transition-all">1. 虐待防止委員会の開催</div><div class="p-4 lg:p-6 bg-slate-50 border-2 border-slate-200 rounded-2xl lg:rounded-3xl text-center font-black text-sm lg:text-base text-slate-900 shadow-sm hover:border-blue-400 transition-all">2. 指針の整備</div><div class="p-4 lg:p-6 bg-slate-50 border-2 border-slate-200 rounded-2xl lg:rounded-3xl text-center font-black text-sm lg:text-base text-slate-900 shadow-sm hover:border-blue-400 transition-all">3. 定期的な研修の実施</div><div class="p-4 lg:p-6 bg-slate-50 border-2 border-slate-200 rounded-2xl lg:rounded-3xl text-center font-black text-sm lg:text-base text-slate-900 shadow-sm hover:border-blue-400 transition-all">4. 担当者の配置</div></div><p class="text-red-700 font-black text-[10px] lg:text-base mt-4 underline underline-offset-4 decoration-2 text-balance">※未実施の場合、基本報酬が1%減算されます。</p></div>` },
    { title: "高齢者虐待の「5つの定義」", order: 4, content: `<div class="flex flex-col items-center text-center space-y-4 lg:space-y-6 px-4 h-full justify-center"><div class="p-4 lg:p-6 bg-white rounded-[2rem] lg:rounded-[3.5rem] w-full max-w-2xl shadow-xl border-2 border-slate-200 shrink-0"><h4 class="text-xl lg:text-2xl font-black mb-2 text-slate-900">法的に定義された5つのカテゴリー</h4><p class="text-[10px] lg:text-sm text-slate-900 font-black">プロとして正確な線引きを理解しましょう</p></div><div class="grid grid-cols-1 lg:grid-cols-2 gap-3 lg:gap-x-12 lg:gap-y-3 font-black text-sm lg:text-base w-full max-w-4xl"><div class="flex flex-col gap-3"><span class="px-6 py-2 lg:py-2.5 bg-blue-50 border-2 border-blue-200 rounded-2xl text-blue-900 shadow-sm text-center">身体的な虐待</span><span class="px-6 py-2 lg:py-2.5 bg-rose-50 border-2 border-rose-200 rounded-2xl text-rose-900 shadow-sm text-center">心理的な虐待</span><span class="px-6 py-2 lg:py-2.5 bg-amber-50 border-2 border-amber-200 rounded-2xl text-amber-900 shadow-sm text-center text-balance">介護等放棄（ネグレクト）</span></div><div class="flex flex-col gap-3"><span class="px-6 py-2 lg:py-2.5 bg-purple-50 border-2 border-purple-200 rounded-2xl text-purple-900 shadow-sm text-center">性的な虐待</span><span class="px-6 py-2 lg:py-2.5 bg-emerald-50 border-2 border-emerald-200 rounded-2xl text-emerald-900 shadow-sm text-center text-balance">経済的な虐待</span></div></div></div>` },
    { title: "1. 身体的な虐待：直接的な暴力", order: 5, content: `<div class="flex flex-col justify-center h-full space-y-8 lg:space-y-12 px-4 lg:px-12 text-left"><div class="space-y-4 lg:space-y-6"><h4 class="text-2xl lg:text-5xl font-black text-blue-900 flex items-center gap-4 lg:gap-6"><span class="w-2 h-10 lg:w-3 lg:h-16 bg-blue-700 rounded-full"></span>身体的虐待（暴行）</h4></div><ul class="space-y-4 lg:space-y-8 text-lg lg:text-4xl font-black text-slate-800 pl-0 leading-tight"><li class="whitespace-nowrap">・殴る、蹴る、つねる、叩く</li><li class="whitespace-nowrap">・無理やり食事を口に押し込む</li><li class="whitespace-nowrap">・無理に立ち上がらせる、座らせる</li></ul></div>` },
    { title: "1. 身体的な虐待：不適切な拘束", order: 6, content: `<div class="flex flex-col justify-center h-full space-y-8 lg:space-y-12 px-4 lg:px-12 text-left"><div class="space-y-4 lg:space-y-6"><h4 class="text-2xl lg:text-5xl font-black text-blue-900 flex items-center gap-4 lg:gap-6"><span class="w-2 h-10 lg:w-3 lg:h-16 bg-blue-700 rounded-full"></span>身体拘束</h4></div><ul class="space-y-4 lg:space-y-8 text-lg lg:text-4xl font-black text-slate-800 pl-0 leading-tight"><li class="whitespace-nowrap">・ベッド柵で四方を囲む</li><li class="whitespace-nowrap">・車椅子に紐やベルトで縛る</li><li class="whitespace-nowrap">・向精神薬を過剰に投与する</li><li class="whitespace-nowrap">・部屋に鍵をかけて閉じ込める</li></ul></div>` },
    { title: "2. 心理的な虐待：言葉の暴力", order: 7, content: `<div class="flex flex-col justify-center h-full space-y-8 lg:space-y-12 px-4 lg:px-12 text-left"><div class="space-y-4 lg:space-y-6"><h4 class="text-2xl lg:text-5xl font-black text-rose-800 flex items-center gap-4 lg:gap-6"><span class="w-2 h-10 lg:w-3 lg:h-16 bg-rose-600 rounded-full"></span>心理制虐待</h4></div><ul class="space-y-4 lg:space-y-8 text-lg lg:text-4xl font-black text-slate-800 pl-0 leading-tight"><li class="whitespace-nowrap">・怒鳴る、ののしる、脅す</li><li class="whitespace-nowrap">・意図的な無視、排斥、仲間外れ</li><li class="whitespace-nowrap text-balance">・子供扱い、尊厳を傷つける言動</li></ul></div>` },
    { title: "3. 介護等放棄（ネグレクト）", order: 8, content: `<div class="flex flex-col justify-center h-full space-y-8 lg:space-y-12 px-4 lg:px-12 text-left"><div class="space-y-4 lg:space-y-6"><h4 class="text-2xl lg:text-5xl font-black text-amber-700 flex items-center gap-4 lg:gap-6"><span class="w-2 h-10 lg:w-3 lg:h-16 bg-amber-600 rounded-full"></span>介護等放棄</h4></div><ul class="space-y-4 lg:space-y-8 text-lg lg:text-4xl font-black text-slate-800 pl-0 leading-tight"><li class="whitespace-nowrap">・排泄放置、入浴させない</li><li class="whitespace-nowrap">・食事や水分を十分に与えない</li><li class="whitespace-nowrap">・必要な医療・介護をさせない</li><li class="whitespace-nowrap">・ナースコールを意図的に無視する</li></ul></div>` },
    { title: "4. 性的な虐待：尊厳の侵害", order: 9, content: `<div class="flex flex-col justify-center h-full space-y-8 lg:space-y-12 px-4 lg:px-12 text-left"><div class="space-y-4 lg:space-y-6"><h4 class="text-2xl lg:text-5xl font-black text-purple-900 flex items-center gap-4 lg:gap-6"><span class="w-2 h-10 lg:w-3 lg:h-16 bg-purple-700 rounded-full"></span>性的虐待</h4></div><ul class="space-y-4 lg:space-y-8 text-lg lg:text-4xl font-black text-slate-800 pl-0 leading-tight"><li class="whitespace-nowrap">・不必要に身体を露出させる</li><li class="whitespace-nowrap">・わいせつな言葉を投げかける</li><li class="whitespace-nowrap">・嫌がる接触、性交の強制</li></ul></div>` },
    { title: "5. 経済的な虐待：財産の侵害", order: 10, content: `<div class="flex flex-col justify-center h-full space-y-8 lg:space-y-12 px-4 lg:px-12 text-left"><div class="space-y-4 lg:space-y-6"><h4 class="text-2xl lg:text-5xl font-black text-emerald-900 flex items-center gap-4 lg:gap-6"><span class="w-2 h-10 lg:w-3 lg:h-16 bg-emerald-700 rounded-full"></span>経済的虐待</h4></div><ul class="space-y-4 lg:space-y-8 text-lg lg:text-4xl font-black text-slate-800 pl-0 leading-tight"><li class="whitespace-nowrap">・年金や預貯金を勝手に使う</li><li class="whitespace-nowrap">・通帳を隠す、不当に処分する</li><li class="whitespace-nowrap">・必要な金銭を与えない</li></ul></div>` },
    { title: "身体拘束の禁止と3つの例外要件", order: 11, content: `<div class="p-6 lg:p-4 relative overflow-hidden text-left max-w-4xl mx-auto flex flex-col items-center h-full justify-center"><div class="absolute -top-10 -right-10 w-64 h-64 bg-blue-50 rounded-full blur-3xl opacity-50"></div><h4 class="text-[10px] lg:text-[8px] font-black tracking-[0.4em] uppercase text-blue-800 mb-6 lg:mb-2 text-center py-2 px-6 bg-blue-50 rounded-full border border-blue-100 shadow-sm">身体拘束の3原則</h4><div class="space-y-4 lg:space-y-3 w-full lg:max-w-3xl text-slate-900"><div><p class="text-blue-800 text-[10px] lg:text-[8px] mb-1 lg:mb-0 uppercase tracking-widest font-black">01. 緊急性・差し迫った状態</p><div class="lg:flex lg:items-baseline lg:gap-6"><p class="text-2xl lg:text-3xl font-black whitespace-nowrap mb-1 lg:mb-0">切迫性</p><p class="text-sm lg:text-xl font-bold text-slate-600">命や身体に重大な危険がある</p></div></div><div class="h-px bg-slate-100 lg:my-1"></div><div><p class="text-blue-800 text-[10px] lg:text-[8px] mb-1 lg:mb-0 uppercase tracking-widest font-black">02. 他に手段がない</p><div class="lg:flex lg:items-baseline lg:gap-6"><p class="text-2xl lg:text-3xl font-black whitespace-nowrap mb-1 lg:mb-0">非代替性</p><p class="text-sm lg:text-xl font-bold text-slate-600">他に手段が全くない</p></div></div><div class="h-px bg-slate-100 lg:my-1"></div><div><p class="text-blue-800 text-[10px] lg:text-[8px] mb-1 lg:mb-0 uppercase tracking-widest font-black">03. 短時間であること</p><div class="lg:flex lg:items-baseline lg:gap-6"><p class="text-2xl lg:text-3xl font-black whitespace-nowrap mb-1 lg:mb-0">一時性</p><p class="text-sm lg:text-xl font-bold text-slate-600">必要最小限の時間である</p></div></div></div></div>` },
    { title: "身体拘束の手続きと記録", order: 12, content: `<div class="space-y-6 lg:space-y-8 text-center flex flex-col items-center justify-center h-full px-4 w-full"><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight mb-4">組織の判断と詳細な記録が義務</h4><div class="space-y-4 lg:space-y-6 font-black text-slate-800 max-w-4xl text-base lg:text-2xl leading-relaxed text-left"><div>1. 担当者だけでなく、チームで慎重に検討する</div><div>2. 利用者本人・家族に説明し、必ず同意を得る</div><div>3. 拘束の態様、解除への取り組みを毎回記録する</div><div>4. 毎日、解除できないかを評価し続ける</div></div></div>` },
    { title: "スピーチロック（言葉の拘束）", order: 13, content: `<div class="p-8 lg:p-12 bg-amber-50 rounded-[2.5rem] lg:rounded-[4rem] border-4 border-amber-300 border-dashed text-center shadow-inner max-w-4xl mx-auto flex flex-col items-center justify-center h-full px-4"><div class="bg-amber-700 text-white px-6 lg:px-8 py-1.5 lg:py-2 rounded-full text-[8px] lg:text-[10px] font-black inline-block mb-6 lg:mb-8 uppercase tracking-widest shadow-lg">Crucial Point</div><h4 class="text-xl lg:text-3xl font-black text-amber-950 mb-6 lg:mb-8 italic text-balance">「ちょっと待って」は<br/>心の自由を奪う拘束です</h4><p class="text-lg lg:text-xl font-black text-amber-900 leading-relaxed py-4 lg:py-6 px-4">何気ない一言が、身体拘束と同じ罪深さを<br/>持つことを自覚しましょう。</p></div>` },
    { title: "なぜ虐待は起きるのか：要因分析", order: 14, content: `<div class="space-y-6 lg:space-y-10 text-center flex flex-col items-center justify-center h-full px-4 w-full"><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-relaxed mb-4 lg:mb-8">虐待は「環境のゆがみ」から生まれる</h4><div class="grid grid-cols-1 gap-4 lg:gap-6 max-w-2xl mx-auto w-full"><div class="p-6 lg:p-8 bg-white border-2 border-slate-200 rounded-3xl shadow-xl text-left flex items-center gap-4 lg:gap-6"><div class="w-10 h-10 lg:w-12 lg:h-12 bg-blue-700 text-white rounded-full flex items-center justify-center shrink-0 font-black text-xs lg:text-base">1</div><div><p class="font-black text-base lg:text-xl text-blue-800 mb-1">教育・知識の不足</p><p class="text-[10px] lg:text-sm font-bold text-slate-700 leading-relaxed text-balance">認知症の行動理解ができず、「わがまま」と捉えてしまう。</p></div></div><div class="p-6 lg:p-8 bg-white border-2 border-slate-200 rounded-3xl shadow-xl text-left flex items-center gap-4 lg:gap-6"><div class="w-10 h-10 lg:w-12 lg:h-12 bg-blue-700 text-white rounded-full flex items-center justify-center shrink-0 font-black text-xs lg:text-base">2</div><div><p class="font-black text-base lg:text-xl text-blue-800 mb-1">職員のストレス</p><p class="text-[10px] lg:text-sm font-bold text-slate-700 leading-relaxed text-balance">過重労働、人手不足、プライベートの悩みによる余裕のなさ。</p></div></div></div></div>` },
    { title: "未然防止：自己チェックリスト", order: 15, content: `<div class="space-y-6 lg:space-y-8 text-center flex flex-col items-center justify-center h-full w-full px-4"><h4 class="text-xl lg:text-3xl font-black text-slate-900 mb-4 lg:mb-6">「ケアの質」を客観的に見る</h4><div class="space-y-3 lg:space-y-4 font-black text-slate-900 text-sm lg:text-2xl max-w-4xl text-left"><div>□ 利用者を「ちゃん・くん」付けで呼んでいないか？</div><div>□ 同意を得ずに、無言で車椅子を押していないか？</div><div>□ 食事を急かしたり、無理やり口に入れていないか？</div><div>□ 仲間の不適切な対応を、見て見ぬふりをしていないか？</div><div>□ 自分のストレスを、利用者にぶつけていないか？</div></div></div>` },
    { title: "ケーススタディ：現場の葛藤", order: 16, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-6 lg:space-y-8 px-4 w-full"><div class="inline-flex items-center gap-3 px-4 py-2 bg-amber-50 text-amber-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-amber-200 mb-2 mx-auto">CASE STUDY</div><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight px-4">場面：人手不足の夕食時</h4><div class="p-6 lg:p-8 bg-white border-2 border-slate-100 rounded-[2rem] lg:rounded-[3rem] shadow-xl max-w-4xl text-left space-y-4 lg:space-y-6 w-full"><p class="text-sm lg:text-xl font-bold text-slate-800 leading-relaxed text-balance text-center">認知症のA様が何度も立ち上がります。<br class="lg:hidden" />配膳に追われるB職員は、<br class="lg:hidden" />つい強い口調で<br/><span class="text-rose-600 font-black">「座ってて！転んだらどうするの！」</span><br/>と言いながら、<br class="lg:hidden" />A様の肩を強く押さえて座らせました。</p><div class="h-px bg-slate-100"></div><p class="text-xs lg:text-lg font-black text-blue-700 italic text-center px-4">この「B職員の焦り」の中に、<br class="lg:hidden" />何が隠れているでしょうか？</p></div></div>` },
    { title: "分析：虐待の芽が生まれる瞬間", order: 17, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-6 lg:space-y-8 px-4 w-full"><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight">分析：それは「愛の鞭」か、<br class="lg:hidden" />それとも？</h4><div class="grid grid-cols-1 lg:grid-cols-2 gap-4 lg:gap-6 max-w-5xl mx-auto w-full"><div class="p-6 lg:p-8 bg-rose-50 border-2 border-rose-100 rounded-[2rem] text-left space-y-3 lg:space-y-4 shadow-sm"><p class="font-black text-base lg:text-xl text-rose-700">不適切なケア（虐待の芽）</p><ul class="text-[10px] lg:text-sm font-bold text-slate-700 space-y-1 lg:space-y-2"><li>・行動を力で制限する</li><li>・強い言葉で自尊心を傷つける</li><li>・「忙しいから」という感覚の麻痺</li></ul></div><div class="p-6 lg:p-8 bg-blue-50 border-2 border-blue-100 rounded-[2rem] text-left space-y-3 lg:space-y-4 shadow-sm"><p class="font-black text-base lg:text-xl text-blue-700">背後にあるリスク</p><ul class="text-[10px] lg:text-sm font-bold text-slate-700 space-y-1 lg:space-y-2"><li>・過度なストレスによる感情爆発</li><li>・「これくらいなら皆やっている」という慣れ</li><li>・孤立した環境での客観性喪失</li></ul></div></div></div>` },
    { title: "解決：チームで連鎖を断ち切る", order: 18, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-6 lg:space-y-8 px-4 w-full"><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight">プロとして「チーム」で守る</h4><div class="p-6 lg:p-10 bg-emerald-50 border-2 border-emerald-100 rounded-[2.5rem] lg:rounded-[4rem] shadow-inner text-left max-w-4xl space-y-4 lg:space-y-6 mx-auto"><p class="text-base lg:text-xl font-black text-emerald-900">不適切なケアを止める具体策</p><div class="grid grid-cols-1 gap-3 lg:gap-4 text-sm lg:text-lg font-bold text-slate-800"><div class="flex items-center gap-3 lg:gap-4 bg-white p-3 lg:p-4 rounded-xl lg:rounded-2xl border border-emerald-100 shadow-sm"><span class="w-6 h-6 lg:w-8 lg:h-8 bg-emerald-600 text-white rounded-full flex items-center justify-center text-[10px] lg:text-sm shrink-0">1</span>焦りを感じたら「交代」を頼む</div><div class="flex items-center gap-3 lg:gap-4 bg-white p-3 lg:p-4 rounded-xl lg:rounded-2xl border border-emerald-100 shadow-sm"><span class="w-6 h-6 lg:w-8 lg:h-8 bg-emerald-600 text-white rounded-full flex items-center justify-center text-[10px] lg:text-sm shrink-0">2</span>同僚のきつい言動に割って入る</div><div class="flex items-center gap-3 lg:gap-4 bg-white p-3 lg:p-4 rounded-xl lg:rounded-2xl border border-emerald-100 shadow-sm"><span class="w-6 h-6 lg:w-8 lg:h-8 bg-emerald-600 text-white rounded-full flex items-center justify-center text-[10px] lg:text-sm shrink-0">3</span>「忙しさ」を理由に尊厳を後回しにしない</div></div></div></div>` },
    { title: "早期発見と通報義務", order: 19, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-6 lg:space-y-8 px-4 w-full"><h4 class="text-xl lg:text-3xl font-black italic text-red-900">「疑い」段階でも報告の義務</h4><div class="p-8 lg:p-10 bg-white border-4 border-red-100 rounded-[2rem] lg:rounded-[3rem] shadow-xl max-w-4xl mx-auto w-full"><p class="text-xl lg:text-3xl font-black leading-relaxed text-center text-slate-900">発見した者は、速やかに<br/><span class="text-red-700 underline underline-offset-8 decoration-4">市町村</span>へ通報する義務があります。</p></div><p class="text-[10px] lg:text-lg font-black text-red-800 px-4 text-balance">※確実な証拠がなくても、ためらわずに報告することが命を救います。</p></div>` },
    { title: "通報者の保護規定", order: 20, content: `<div class="flex flex-col items-center justify-center h-full text-left space-y-6 lg:space-y-10 px-6 lg:px-12 w-full"><h4 class="text-xl lg:text-3xl font-black text-blue-800 flex items-center gap-4 w-full"><svg class="w-6 h-6 lg:w-8 lg:h-8 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" /></svg>公益通報者保護法</h4><p class="text-sm lg:text-2xl font-black leading-relaxed text-slate-900 max-w-4xl bg-blue-50 p-6 lg:p-8 rounded-2xl lg:rounded-3xl border border-blue-100 w-full text-balance">虐待を通報したことを理由に、解雇や減給、嫌がらせなどの不利益な扱いをすることは法律で固く禁じられています。</p><p class="text-xs lg:text-xl font-black text-blue-800 text-center w-full">勇気ある行動が、利用者の命を守ります。</p></div>` },
    { title: "組織の役割：虐待防止委員会", order: 21, content: `<div class="flex flex-col items-center justify-center h-full text-left space-y-6 lg:space-y-8 px-6 lg:px-12 w-full"><h4 class="text-xl lg:text-3xl font-black text-emerald-900 text-center mb-4 uppercase tracking-widest w-full">個人の責任にしない仕組み</h4><div class="space-y-6 lg:space-y-10 font-black text-slate-900 max-w-4xl mx-auto w-full"><div><p class="text-lg lg:text-3xl text-emerald-700 mb-1 lg:mb-2 flex items-center gap-3"><span>●</span> 事例分析：</p><p class="text-sm lg:text-xl pl-8 lg:pl-12 text-slate-600 font-bold">原因を特定し、組織で改善する。</p></div><div><p class="text-lg lg:text-3xl text-emerald-700 mb-1 lg:mb-2 flex items-center gap-3"><span>●</span> 相談窓口：</p><p class="text-sm lg:text-xl pl-8 lg:pl-12 text-slate-600 font-bold">職員がすぐに話せる風土を作る。</p></div><div><p class="text-lg lg:text-3xl text-emerald-700 mb-1 lg:mb-2 flex items-center gap-3"><span>●</span> 再発防止：</p><p class="text-sm lg:text-xl pl-8 lg:pl-12 text-slate-600 font-bold">具体的な改善策を全員で徹底する。</p></div></div></div>` },
    { title: "家族だったら？（倫理の遵守）", order: 22, content: `<div class="space-y-6 lg:space-y-10 text-center flex flex-col items-center justify-center h-full px-4 w-full"><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight">プロとしての誇り</h4><div class="p-8 lg:p-12 bg-white border-[4px] lg:border-[6px] border-blue-600 rounded-[2rem] lg:rounded-[3rem] shadow-2xl max-w-3xl mx-auto w-full"><p class="text-xl lg:text-3xl font-black text-blue-900 leading-relaxed italic text-balance">もし、目の前の利用者が<br/>自分の大切な家族なら、<br/>同じことをしますか？</p></div><p class="font-black text-sm lg:text-xl text-slate-800 mt-4 text-balance">その問いに自信を持って<br class="lg:hidden" />「はい」と答えられるケアを。</p></div>` },
    { title: "まとめ：今日から変えられること", order: 23, content: `<div class="flex flex-col items-center text-center space-y-8 lg:space-y-12 w-full h-full justify-center text-slate-900 px-4"><div class="w-24 h-24 lg:w-32 h-32 bg-blue-700 rounded-[2.5rem] lg:rounded-[3.5rem] flex items-center justify-center shadow-2xl shadow-blue-200 rotate-3 transition-transform hover:rotate-0 duration-500"><svg class="w-12 h-12 lg:w-16 h-16 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14.828 14.828a4 4 0 01-5.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg></div><h3 class="text-2xl lg:text-5xl font-black leading-tight">笑顔のある職場を、<br/>全員で作りましょう。</h3><div class="pt-8 lg:pt-12 border-t-2 border-slate-200 w-full max-w-md text-center"><p class="text-slate-500 font-black text-[8px] lg:text-[10px] uppercase tracking-[0.5em]">End of Session</p></div></div>` },
    { title: "理解度テストのご案内", order: 24, content: `
        <div class="flex flex-col items-center text-center space-y-6 lg:space-y-8 w-full h-full justify-center px-4">
          <div class="bg-emerald-600 text-white px-6 py-1.5 rounded-full text-[8px] lg:text-[10px] font-black tracking-[0.3em] uppercase inline-block mb-4 lg:mb-6 shadow-lg">Course Completed</div>
          <h2 class="text-2xl lg:text-5xl font-black text-slate-900 leading-tight mb-2 lg:mb-4">講義セッション終了</h2>
          <p class="text-emerald-800 text-base lg:text-2xl font-black leading-relaxed">大変お疲れ様でした。<br/>最後に理解度テスト（全10問）を行います。</p>
          <div class="p-4 lg:p-6 bg-blue-50 rounded-2xl lg:rounded-3xl border-2 border-blue-100 max-w-lg mx-auto mt-6 lg:mt-8">
            <p class="text-blue-900 font-black text-sm lg:text-xl flex items-center justify-center gap-3">
              <span class="w-2 h-2 bg-blue-700 rounded-full"></span>
              全問正解を目指しましょう！
              <span class="w-2 h-2 bg-blue-700 rounded-full"></span>
            </p>
          </div>
        </div>
      ` }
  ]

  const questionsData = [
    { text: '日々のケアにおいて、自尊心を傷つける「不適切なケア（虐待の芽）」に該当する行為はどれか？', explanation: '無言で車椅子を動かす行為は、利用者の主体性を無視し、不安や恐怖を与える「不適切なケア」の典型例です。', order: 1, choices: { create: [{ text: '無言で後ろから突然車椅子を押し始める', isCorrect: true }, { text: '次の動作に移る前に必ず声をかける', isCorrect: false }, { text: '自分のイライラを自覚した時に同僚に交代を頼む', isCorrect: false }, { text: '利用者の「できること」を奪わずに見守る', isCorrect: false }] } },
    { text: '高齢者虐待法で定義される「5つの虐待」に含まれない区分はどれか？', explanation: 'セルフ・ネグレクト（自己放任）は深刻な問題ですが、法的な「従事者による5つの虐待」には含まれません。', order: 2, choices: { create: [{ text: '自己放任（セルフ・ネグレクト）', isCorrect: true }, { text: '心理的虐待', isCorrect: false }, { text: '介護等放棄（ネグレクト）', isCorrect: false }, { text: '経済的虐待', isCorrect: false }] } },
    { text: '身体拘束が例外的に認められる「3つの要件」の正しい組み合わせは？', explanation: '切迫性（命の危険）、非代替性（他に手段がない）、一時性（短時間）の3つが必須です。', order: 3, choices: { create: [{ text: '切迫性・非代替性・一時性', isCorrect: true }, { text: '切迫性・安全性・継続性', isCorrect: false }, { text: '緊急性・非代替性・同意性', isCorrect: false }, { text: '有効性・安全性・一時性', isCorrect: false }] } },
    { text: '身体的虐待に該当する「不適切な拘束」の事例として、正しいものはどれか？', explanation: 'ベッド柵で四方を囲むことは、本人の行動を完全に制限するため身体拘束に該当します。', order: 4, choices: { create: [{ text: 'ベッド柵（サイドレール）で四方を囲む', isCorrect: true }, { text: '転倒防止のために離床センサーを使用する', isCorrect: false }, { text: '食事の際に誤嚥防止の姿勢を整える', isCorrect: false }, { text: '車椅子のブレーキを確実にかける', isCorrect: false }] } },
    { text: '「ちょっと待ってて」等の言葉で行動を制限する「スピーチロック」は、どの虐待に繋がりやすいとされるか？', explanation: '言葉による行動制限は、心理的虐待や身体的虐待（身体拘束）の入り口となります。', order: 5, choices: { create: [{ text: '心理的虐待・身体的虐待', isCorrect: true }, { text: '経済的虐待', isCorrect: false }, { text: '性的虐待', isCorrect: false }, { text: 'いずれの虐待にも該当しない', isCorrect: false }] } },
    { text: '介護等放棄（ネグレクト）の具体的な説明として正しいものはどれか？', explanation: 'ナースコールの意図的な無視や、排泄放置による不衛生な状態の継続が該当します。', order: 6, choices: { create: [{ text: '意図的にナースコールを無視し続ける', isCorrect: true }, { text: '本人の体調に合わせて食事量を調整する', isCorrect: false }, { text: 'リハビリの拒否に対して無理に実施しない', isCorrect: false }, { text: '安全のために夜間の見守り回数を増やす', isCorrect: false }] } },
    { text: '経済的虐待に該当する「不適切な財産の取り扱い」はどれか？', explanation: '本人の同意なく、年金や預貯金を家族や職員が管理・流用することが該当します。', order: 7, choices: { create: [{ text: '本人の同意なく預貯金を勝手に使う', isCorrect: true }, { text: '支払い能力のない利用者へ督促を行う', isCorrect: false }, { text: '法に基づき成年後見人が財産を管理する', isCorrect: false }, { text: '施設利用料の改定を通知する', isCorrect: false }] } },
    { text: '虐待の「疑い」を発見した際の対応として、最も適切なものはどれか？', explanation: '確実な証拠がなくても、疑いがある段階で市町村等へ報告する義務があります。', order: 8, choices: { create: [{ text: '証拠がなくても「疑い」があれば報告する', isCorrect: true }, { text: '本人の確実な訴えがあるまで様子を見る', isCorrect: false }, { text: 'まずは当事者の職員と話し合って解決する', isCorrect: false }, { text: '家族に報告し、判断を仰ぐ', isCorrect: false }] } },
    { text: '虐待を発見した際の法律上の「義務的な通報先」はどこか？', explanation: '法律（高齢者虐待防止法）では「市町村」への通報が義務付けられています。', order: 9, choices: { create: [{ text: '市町村（自治体）', isCorrect: true }, { text: '警察署のみ', isCorrect: false }, { text: '保健所', isCorrect: false }, { text: '法人の顧問弁護士', isCorrect: false }] } },
    { text: '身体拘束を行う際、詳細な記録が義務付けられている項目に含まれないものはどれか？', explanation: '拘束の態様、時間、理由、解除に向けた取り組みを記録する義務がありますが、感想文は不要です。', order: 10, choices: { create: [{ text: '担当職員の個人的な反省文', isCorrect: true }, { text: '身体拘束の態様（具体的な方法）', isCorrect: false }, { text: '身体拘束をせざるを得ない理由', isCorrect: false }, { text: '解除に向けた具体的な取り組み', isCorrect: false }] } }
  ]

  let course = await prisma.course.findUnique({ where: { slug } })

  if (course) {
    await prisma.choice.deleteMany({ where: { question: { courseId: course.id } } })
    await prisma.question.deleteMany({ where: { courseId: course.id } })
    await prisma.slide.deleteMany({ where: { courseId: course.id } })
    
    course = await prisma.course.update({
      where: { id: course.id },
      data: {
        ...courseData,
        slides: { create: slidesData },
        questions: { create: questionsData }
      }
    })
  } else {
    course = await prisma.course.create({
      data: {
        ...courseData,
        slides: { create: slidesData },
        questions: { create: questionsData }
      }
    })
  }

  return course
}
