import { PrismaClient } from '@prisma/client'

export async function seedDementia(prisma: PrismaClient) {
  return await prisma.course.create({
    data: {
      title: '認知症を正しく知ろう ～安心を届けるケアのヒント～',
      description: '2024年施行の認知症基本法に基づき、最新の認知症ケアと意思決定支援を100%網羅した決定版。',
      introduction: `
        <div class="space-y-8">
          <div class="flex items-center gap-4"><span class="h-1 w-12 bg-emerald-600 rounded-full"></span><p class="text-emerald-600 font-black tracking-widest text-sm uppercase">Curriculum Hook</p></div>
          <h2 class="text-4xl font-black text-slate-900 leading-tight">「なぜ、私の言葉が<br/>届かないんだろう？」</h2>
          <div class="space-y-6 text-slate-600 text-lg leading-relaxed font-medium">
            <p>良かれと思ってやった介助なのに、拒否されたり怒鳴られたり。そんな経験はありませんか？</p>
            <div class="p-8 bg-emerald-50/50 rounded-[2rem] border border-emerald-100 shadow-inner relative overflow-hidden">
              <div class="absolute top-0 right-0 w-24 h-24 bg-emerald-100/30 rounded-bl-full"></div>
              <p class="relative z-10 font-medium italic">あなたが悪いのではありません。そこには、認知症という「真っ暗な霧」の中を歩く人の、切実な理由があるのです。</p>
            </div>
            <p>この研修は、そんな「届かない言葉」を「安心の絆」に変えるためのヒントを探る時間です。国が定める共生社会の指針に基づき、共に生きるケアを学びましょう。</p>
          </div>
        </div>
      `,
      learningObjectives: `
        <div class="grid grid-cols-1 gap-6">
          <div class="group p-6 bg-white border border-slate-100 rounded-3xl shadow-sm hover:shadow-emerald-50 transition-all duration-500 flex items-start gap-6">
            <div class="w-14 h-14 bg-emerald-600 text-white rounded-2xl flex items-center justify-center text-xl font-black shrink-0 shadow-lg group-hover:scale-110 transition-transform">1</div>
            <div><h4 class="text-xl font-black text-slate-900 mb-2">本人の「意思」を尊重できる</h4><p class="text-slate-500 leading-relaxed font-medium">厚生労働省の「意思決定支援」の考え方を理解し、本人の思いを汲み取れるようになる。</p></div>
          </div>
          <div class="group p-6 bg-white border border-slate-100 rounded-3xl shadow-sm hover:shadow-emerald-50 transition-all duration-500 flex items-start gap-6">
            <div class="w-14 h-14 bg-emerald-600 text-white rounded-2xl flex items-center justify-center text-xl font-black shrink-0 shadow-lg group-hover:scale-110 transition-transform">2</div>
            <div><h4 class="text-xl font-black text-slate-900 mb-2">生活場面ごとの工夫ができる</h4><p class="text-slate-500 leading-relaxed font-medium">食事・排泄・入浴など、認知症の特性に応じた具体的な介助と環境設定を習得する。</p></div>
          </div>
        </div>
      `,
      slides: {
        create: [
          { title: '認知症を正しく知ろう', order: 0, content: `<div class="flex flex-col items-center justify-center min-h-[300px] text-center space-y-12"><div class="relative"><div class="absolute inset-0 bg-emerald-400 blur-3xl opacity-20 scale-150 animate-pulse"></div><div class="relative bg-white p-10 rounded-[3rem] shadow-2xl border border-slate-100 max-w-sm"><div class="bg-emerald-600 text-white px-6 py-1.5 rounded-full text-[10px] font-black tracking-[0.3em] uppercase inline-block mb-6">Dementia Care</div><h2 class="text-3xl font-black text-slate-900 leading-tight mb-4">認知症を正しく知ろう<br/>〜安心を届けるケアのヒント〜</h2></div></div><div class="flex items-center gap-4 text-slate-400 font-black text-[10px] tracking-widest"><span class="h-px w-8 bg-slate-200"></span>CARE LEARNING SYSTEM<span class="h-px w-8 bg-slate-200"></span></div></div>` },
          { title: '社会的背景：認知症基本法（2024）', order: 1, content: `<div class="space-y-8"><div class="inline-flex items-center gap-3 px-4 py-2 bg-emerald-50 text-emerald-600 rounded-full text-xs font-black ring-1 ring-emerald-100"><span class="w-2 h-2 bg-emerald-600 rounded-full animate-ping"></span>LEGAL CONTEXT</div><h4 class="text-2xl font-black text-slate-900 leading-tight">認知症は「特別なこと」ではなく<br/><span class="text-emerald-600 decoration-4 underline underline-offset-8">共に生きる隣人</span>の姿です</h4><div class="grid grid-cols-1 sm:grid-cols-2 gap-4"><div class="p-6 bg-white border-2 border-slate-50 rounded-[2rem] shadow-sm"><div class="w-10 h-10 bg-slate-900 text-white rounded-xl flex items-center justify-center mb-4"><svg class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" /></svg></div><p class="text-sm font-black text-slate-900 mb-2">共生社会の実現</p><p class="text-[11px] text-slate-500 leading-relaxed">認知症基本法に基づき、尊厳を保持しつつ希望を持って暮らせる社会を目指します。</p></div><div class="p-6 bg-white border-2 border-slate-50 rounded-[2rem] shadow-sm"><div class="w-10 h-10 bg-emerald-600 text-white rounded-xl flex items-center justify-center mb-4"><svg class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path d="M9 12l2 2 4-4m6 2a9 9 0 11-12 0 9 9 0 0112 0z" /></svg></div><p class="text-sm font-black text-slate-900 mb-2">意思決定支援</p><p class="text-[11px] text-slate-500 leading-relaxed">「何もできない」と決めつけず、本人の意向を最大限に尊重する支援が義務です。</p></div></div></div>` },
          { title: '医学的基礎：3つの原因疾患', order: 2, content: `<div class="grid grid-cols-1 gap-3"><div class="group p-4 bg-slate-50/50 rounded-2xl border border-slate-100 flex items-center gap-5 hover:bg-white transition-all"><div class="w-12 h-12 bg-slate-900 text-white rounded-xl flex items-center justify-center text-lg font-black shrink-0">1</div><div class="flex-1"><p class="text-sm font-black text-slate-900">アルツハイマー型（最多）</p><p class="text-[10px] text-slate-500">脳全体が萎縮し、物忘れや判断力の低下が緩やかに進行します。</p></div></div><div class="group p-4 bg-slate-50/50 rounded-2xl border border-slate-100 flex items-center gap-5 hover:bg-white transition-all"><div class="w-12 h-12 bg-slate-900 text-white rounded-xl flex items-center justify-center text-lg font-black shrink-0">2</div><div class="flex-1"><p class="text-sm font-black text-slate-900">レビー小体型</p><p class="text-[10px] text-slate-500">幻視（ないものが見える）や、歩行の不安定さが特徴です。</p></div></div><div class="group p-4 bg-slate-50/50 rounded-2xl border border-slate-100 flex items-center gap-5 hover:bg-white transition-all"><div class="w-12 h-12 bg-slate-900 text-white rounded-xl flex items-center justify-center text-lg font-black shrink-0">3</div><div class="flex-1"><p class="text-sm font-black text-slate-900">血管性認知症</p><p class="text-[10px] text-slate-500">脳梗塞等により、できることとできないことが混在（まだら症状）します。</p></div></div></div>` },
          { title: '中核症状：脳の故障', order: 3, content: `<div class="space-y-8"><div class="p-8 bg-blue-50 rounded-[2.5rem] border-2 border-blue-100 border-dashed relative text-center"><h4 class="text-2xl font-black text-blue-900 mb-4">本人の「努力」では解決できません</h4><p class="text-[11px] text-blue-800 italic font-medium">これは脳という「器械」の故障です。叱ったり励ましたりしても解決しません。</p></div><div class="grid grid-cols-2 gap-4"><div class="p-4 bg-white border border-slate-100 rounded-2xl"><p class="text-[10px] font-black text-slate-900 mb-1">記憶障害</p><p class="text-[9px] text-slate-500 font-medium">直前の出来事を完全に忘れる</p></div><div class="p-4 bg-white border border-slate-100 rounded-2xl"><p class="text-[10px] font-black text-slate-900 mb-1">見当識障害</p><p class="text-[9px] text-slate-500 font-medium">時間、場所、人がわからない</p></div><div class="p-4 bg-white border border-slate-100 rounded-2xl"><p class="text-[10px] font-black text-slate-900 mb-1">実行機能障害</p><p class="text-[9px] text-slate-500 font-medium">料理などの手順がわからない</p></div><div class="p-4 bg-white border border-slate-100 rounded-2xl"><p class="text-[10px] font-black text-slate-900 mb-1">失認・失行</p><p class="text-[9px] text-slate-500 font-medium">物の使い方がわからない</p></div></div></div>` },
          { title: 'BPSD（行動・心理症状）の真実', order: 4, content: `<div class="space-y-8"><div class="flex flex-col items-center"><div class="bg-slate-100 px-4 py-1 rounded-full text-[10px] font-black text-slate-500 tracking-widest uppercase mb-4">Behavioral Analysis</div><h4 class="text-xl font-black text-slate-900 text-center leading-relaxed">BPSDは「SOSのメッセージ」</h4></div><div class="relative grid grid-cols-2 gap-px bg-slate-200 p-px rounded-[2rem] overflow-hidden border border-slate-200 shadow-2xl"><div class="p-6 bg-white flex flex-col items-center text-center space-y-3"><div class="w-10 h-10 bg-emerald-50 text-emerald-600 rounded-full flex items-center justify-center font-black">A</div><p class="text-xs font-black text-slate-900">身体的要因</p><p class="text-[9px] text-slate-400 leading-tight">便秘、脱水、痛み、痒みが「イライラ」や「徘徊」に繋がります</p></div><div class="p-6 bg-white flex flex-col items-center text-center space-y-3"><div class="w-10 h-10 bg-emerald-50 text-emerald-600 rounded-full flex items-center justify-center font-black">B</div><p class="text-xs font-black text-slate-900">環境的要因</p><p class="text-[9px] text-slate-400 leading-tight">眩しい光、騒音、暑さ。環境を整えるだけで症状は落ち着きます</p></div><div class="p-6 bg-white flex flex-col items-center text-center space-y-3"><div class="w-10 h-10 bg-emerald-50 text-emerald-600 rounded-full flex items-center justify-center font-black">C</div><p class="text-xs font-black text-slate-900">心理的要因</p><p class="text-[9px] text-slate-400 leading-tight">疎外感、役に立たないという絶望感。安心できる居場所が必要です</p></div><div class="p-6 bg-white flex flex-col items-center text-center space-y-3"><div class="w-10 h-10 bg-emerald-50 text-emerald-600 rounded-full flex items-center justify-center font-black">D</div><p class="text-xs font-black text-slate-900">関わり要因</p><p class="text-[9px] text-slate-400 leading-tight">強制や否定。私たちの不用意な一言が、BPSDを引き起こします</p></div></div></div>` },
          { title: '意思決定支援のあり方', order: 5, content: `<div class="space-y-6"><div class="bg-slate-900 text-white p-10 rounded-[2.5rem] shadow-2xl relative overflow-hidden text-center text-white"><h4 class="text-xs font-black tracking-[0.3em] uppercase opacity-50 mb-6">MHLW Policy</h4><p class="text-lg font-bold mb-6 italic">本人の意向を最後まで探し続けること</p><div class="space-y-4 text-sm text-slate-300 text-left"><div class="flex items-center gap-4"><span class="w-8 h-8 bg-emerald-500 rounded-lg flex items-center justify-center font-black text-xs">01</span><p>意向の把握：言葉だけでなく表情や過去の嗜好から推察する</p></div><div class="flex items-center gap-4"><span class="w-8 h-8 bg-emerald-500 rounded-lg flex items-center justify-center font-black text-xs">02</span><p>環境の調整：本人が選択しやすい選択肢を提示する</p></div><div class="flex items-center gap-4"><span class="w-8 h-8 bg-emerald-500 rounded-lg flex items-center justify-center font-black text-xs">03</span><p>チーム検討：ひとりの判断ではなく多職種で最善を議論する</p></div></div></div></div>` },
          { title: '生活場面の工夫：食事', order: 6, content: `<div class="space-y-8"><div class="p-10 bg-emerald-50 rounded-[3rem] border border-emerald-100 flex flex-col items-center text-center space-y-6"><h4 class="text-2xl font-black text-emerald-900">「できる」を支える環境設定</h4><div class="space-y-4 w-full text-left"><div class="bg-white/80 px-6 py-4 rounded-2xl shadow-sm"><p class="text-sm font-bold text-slate-700">白い皿に白い飯は認識しづらい。食器の色のコントラストを上げ、集中できる環境を作ります。</p></div><div class="bg-white/80 px-6 py-4 rounded-2xl shadow-sm"><p class="text-sm font-bold text-slate-700">「食べさせてもらう」のではなく、本人が使いやすいスプーンや自助具を選定します。</p></div></div></div></div>` },
          { title: '入浴介助の工夫：恐怖心の解消', order: 7, content: `<div class="space-y-8"><div class="relative p-10 bg-slate-900 rounded-[3rem] shadow-2xl overflow-hidden text-center text-white"><h4 class="text-2xl font-black mb-8 italic">拒否の裏には「水の恐怖」がある</h4><div class="p-6 bg-white/5 rounded-2xl border border-white/10 space-y-4 text-left"><p class="text-slate-300 text-sm leading-relaxed font-medium">・シャワーの音や湯気に驚いている可能性がある。<br/>・足元を隠して安心感を与える（バスタオルを巻く等）。<br/>・「お風呂」と言わず「足湯に行きませんか？」等、本人が好む言葉を使う。</p></div></div></div>` },
          { title: '3つのケアの心：パーソン・センタード', order: 8, content: `<div class="space-y-8"><div class="flex flex-col items-center text-center"><h4 class="text-xl font-black text-slate-900 leading-relaxed">「否定しない・驚かせない・急がせない」</h4></div><div class="relative grid grid-cols-3 gap-px bg-slate-200 p-px rounded-[2rem] overflow-hidden border border-slate-200 shadow-2xl"><div class="p-6 bg-white text-center space-y-3"><div class="w-10 h-10 bg-emerald-50 text-emerald-600 rounded-full flex items-center justify-center font-black mx-auto">1</div><p class="text-xs font-black text-slate-900">否定しない</p><p class="text-[9px] text-slate-400 leading-tight">本人の正解を尊重する</p></div><div class="p-6 bg-white text-center space-y-3"><div class="w-10 h-10 bg-emerald-50 text-emerald-600 rounded-full flex items-center justify-center font-black mx-auto">2</div><p class="text-xs font-black text-slate-900">驚かせない</p><p class="text-[9px] text-slate-400 leading-tight">視界に入ってから話す</p></div><div class="p-6 bg-white text-center space-y-3"><div class="w-10 h-10 bg-emerald-50 text-emerald-600 rounded-full flex items-center justify-center font-black mx-auto">3</div><p class="text-xs font-black text-slate-900">急がせない</p><p class="text-[9px] text-slate-400 leading-tight">「待つ」ことも介助です</p></div></div></div>` },
          { title: '不適切なケアの回避', order: 9, content: `<div class="space-y-8"><div class="p-8 bg-red-50 rounded-[2.5rem] border-2 border-red-100 border-dashed relative text-center"><h4 class="text-2xl font-black text-red-900 mb-4">スピーチロックは虐待の芽</h4><p class="text-[11px] text-red-800 italic font-medium">「認知症だからわからないだろう」という油断が、身体拘束や心理的虐待を生みます。</p></div><div class="bg-white p-8 rounded-[2rem] border border-slate-100 shadow-xl"><p class="text-sm font-black text-slate-900">私たちの言葉掛け一つで、本人の「不穏」は防げます。</p></div></div>` },
          { title: '魔法のコミュニケーション技術', order: 10, content: `<div class="space-y-8"><div class="relative p-10 bg-slate-900 rounded-[3rem] shadow-2xl overflow-hidden text-center text-white"><h4 class="text-2xl font-black mb-8 italic">言葉以外の「メッセージ」を伝える</h4><div class="p-6 bg-white/5 rounded-2xl border border-white/10 space-y-4 text-left"><p class="text-xs font-black text-emerald-400 tracking-widest uppercase">Communication ABC</p><p class="text-slate-300 text-sm leading-relaxed font-medium">A: 目線を合わせる（座って話す）<br/>B: 言葉は短く、一度にひとつだけ<br/>C: 「はい/いいえ」で答えられる質問を</p></div></div></div>` },
          { title: 'ケーススタディ', order: 11, content: `<div class="space-y-6"><div class="p-8 bg-orange-50 border-2 border-orange-100 rounded-[2.5rem]"><p class="text-orange-900 text-lg font-black leading-relaxed">夕方、「家に帰ります！」と荷物をまとめ始めたB様。あなたならどうしますか？</p></div><div class="grid grid-cols-1 gap-4"><div class="p-6 bg-white border border-slate-100 rounded-2xl shadow-sm flex items-center gap-4 opacity-60"><span class="w-10 h-10 bg-slate-100 text-slate-400 rounded-xl flex items-center justify-center font-black">×</span><p class="text-xs font-bold text-slate-500 italic">「もう夜ですよ、帰れません！」と正論で説得する</p></div><div class="p-6 bg-white border border-emerald-100 rounded-2xl shadow-xl ring-2 ring-emerald-50 flex items-center gap-4"><span class="w-10 h-10 bg-emerald-600 text-white rounded-xl flex items-center justify-center font-black shadow-lg">○</span><p class="text-xs font-black text-slate-900">「お家が気になるんですね。少しお茶を飲んでから、一緒に帰り支度をしませんか？」と意向に寄り添う</p></div></div></div>` },
          { title: 'チームケアと情報共有', order: 12, content: `<div class="space-y-8"><div class="p-10 bg-emerald-50 rounded-[3rem] border border-emerald-100 flex flex-col items-center text-center space-y-6"><div class="w-20 h-20 bg-white rounded-[2rem] shadow-xl flex items-center justify-center font-black text-2xl text-emerald-600">Team</div><h4 class="text-2xl font-black text-emerald-900">ひとりで抱え込まない</h4><p class="text-slate-600 font-medium">BPSDの兆候や、ケアの成功体験をチームで共有することが、最善の意思決定支援に繋がります。</p></div></div>` },
          { title: 'アセスメントの重要性', order: 13, content: `<div class="space-y-6"><div class="bg-slate-900 text-white p-10 rounded-[2.5rem] shadow-2xl relative text-center"><h4 class="text-2xl font-black mb-4 italic">本人の「強み」に目を向ける</h4><p class="text-sm text-slate-400 leading-relaxed font-medium">「何ができないか」ではなく「何ができるか」をアセスメントし、日常生活の中に役割を見出しましょう。</p></div></div>` },
          { title: 'まとめ：あなたの笑顔が最高のケア', order: 14, content: `<div class="flex flex-col items-center justify-center min-h-[400px] text-center space-y-10"><div class="w-24 h-24 bg-emerald-600 rounded-[2.5rem] flex items-center justify-center shadow-2xl shadow-emerald-200 rotate-3"><svg class="w-12 h-12 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M14.828 14.828a4 4 0 01-5.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg></div><h3 class="text-3xl font-black text-slate-900 leading-tight">認知症ケアに正解はありません。<br/>でも、「寄り添う心」は共通です。</h3><p class="text-slate-500 font-medium text-lg max-w-sm mx-auto leading-relaxed">今日から笑顔のケアを始めましょう。</p><div class="pt-10 border-t border-slate-100 w-full"><p class="text-slate-400 font-black text-xs uppercase tracking-[0.3em]">End of Session</p></div></div>` }
        ]
      },
      questions: {
        create: [
          { text: '認知症基本法（2024）で定められたケアの目的はどれか。', explanation: '本人の尊厳を保持し、共生を目指すことが目的です。', order: 1, choices: { create: [{ text: '本人の尊厳を保持し、共生を目指す', isCorrect: true }, { text: '施設内での一律の安全管理', isCorrect: false }] } },
          { text: 'BPSD（行動・心理症状）が発生する大きな要因のひとつは何か。', explanation: '便秘や痛みなどの身体的苦痛が原因となることが多いです。', order: 2, choices: { create: [{ text: '便秘や痛みなどの身体的苦痛', isCorrect: true }, { text: '本人の性格の問題', isCorrect: false }] } },
          { text: '本人の意向を最大限に尊重する支援方法を何というか。', explanation: '意思決定支援と呼ばれます。', order: 3, choices: { create: [{ text: '意思決定支援', isCorrect: true }, { text: '管理型ケア', isCorrect: false }] } },
          { text: '食事において本人が認識しやすくするための環境設定はどれか。', explanation: '食器のコントラストを上げることが有効です。', order: 4, choices: { create: [{ text: '食器の色のコントラストを上げる', isCorrect: true }, { text: 'テレビをつけたままで食事する', isCorrect: false }] } },
          { text: '2024年度から義務化された「認知症介護基礎研修」の対象は誰か？', explanation: '介護サービス事業所に勤務する、無資格の全介護職員が受講義務の対象です。', order: 5, choices: { create: [{ text: '無資格の全介護職員', isCorrect: true }, { text: 'ケアマネジャーのみ', isCorrect: false }] } }
        ]
      }
    }
  })
}
