import { PrismaClient } from '@prisma/client'

export async function seedDementia(prisma: PrismaClient) {
  const slug = 'dementia'
  const courseData = {
    slug,
    title: '認知症ケア研修（2024年度）',
    description: '〜安心を届ける意思決定支援と共生〜',
    introduction: `
        <div class="flex flex-col items-center justify-center text-center space-y-3 pt-4 px-4">
          <div class="flex items-center gap-4">
            <span class="h-px w-8 lg:w-12 bg-emerald-700 rounded-full"></span>
            <p class="text-emerald-800 font-black tracking-widest text-lg lg:text-2xl uppercase">認知症ケア研修</p>
            <span class="h-px w-8 lg:w-12 bg-emerald-700 rounded-full"></span>
          </div>
          <h2 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight text-balance">「なぜ、私の言葉が<br/>届かないんだろう？」</h2>
          <div class="max-w-2xl space-y-2 text-slate-800 text-sm lg:text-base leading-relaxed font-bold px-4 text-center">
            <p>良かれと思ってやった介助なのに、拒絶されたり怒鳴られたり。<br class="lg:hidden" />そんな経験はありませんか？</p>
            <div class="p-4 lg:p-5 bg-emerald-50 rounded-[1.5rem] lg:rounded-[2rem] border-2 border-emerald-200 shadow-inner relative overflow-hidden text-[10px] lg:text-xs text-left mt-4">
              <div class="absolute top-0 right-0 w-16 h-16 lg:w-24 lg:h-24 bg-emerald-100/50 rounded-bl-full"></div>
              <p class="relative z-10 italic text-emerald-900 font-black text-xs lg:text-sm leading-relaxed">あなたが悪いのではありません。そこには、認知症という「真っ暗な霧」の中を歩く人の、切実な理由があるのです。</p>
            </div>
            <p class="text-[10px] lg:text-sm text-slate-900 font-black text-center mt-4 text-balance">この研修は、そんな「届かない言葉」を「安心の絆」に変えるためのヒントを探る時間です。</p>
          </div>
        </div>
      `,
    learningObjectives: `
        <div class="flex flex-col items-center justify-center text-center space-y-4 pt-4 px-4 w-full">
          <div class="bg-emerald-700 text-white px-6 py-2 rounded-full text-[10px] font-black tracking-[0.3em] uppercase mb-2 shadow-lg shadow-emerald-200">学習目標</div>
          <div class="grid grid-cols-1 gap-3 w-full max-w-2xl">
            <div class="group p-4 bg-white border-2 border-slate-200 rounded-[1.5rem] lg:rounded-[2rem] shadow-sm flex items-center gap-4 lg:gap-6 hover:shadow-xl hover:border-emerald-400 transition-all duration-500">
              <div class="w-10 h-10 lg:w-12 lg:h-12 bg-emerald-700 text-white rounded-xl flex items-center justify-center text-base lg:text-lg font-black shrink-0 shadow-lg shadow-emerald-200">1</div>
              <div class="text-left">
                <h4 class="text-sm lg:text-lg font-black text-slate-900">本人の「意思」を尊重できる</h4>
                <p class="text-slate-800 text-[10px] lg:text-xs font-bold leading-relaxed">最新の「意思決定支援」の考え方を理解し、本人の思いを汲み取れるようになる。</p>
              </div>
            </div>
            <div class="group p-4 bg-white border-2 border-slate-200 rounded-[1.5rem] lg:rounded-[2rem] shadow-sm flex items-center gap-4 lg:gap-6 hover:shadow-xl hover:border-emerald-400 transition-all duration-500">
              <div class="w-10 h-10 lg:w-12 lg:h-12 bg-emerald-700 text-white rounded-xl flex items-center justify-center text-base lg:text-lg font-black shrink-0 shadow-lg shadow-emerald-200">2</div>
              <div class="text-left">
                <h4 class="text-sm lg:text-lg font-black text-slate-900">生活場面ごとの工夫ができる</h4>
                <p class="text-slate-800 text-[10px] lg:text-xs font-bold leading-relaxed">食事・排泄・入浴など、認知症の特性に応じた具体的な介助技術を習得する。</p>
              </div>
            </div>
            <div class="group p-4 bg-white border-2 border-slate-200 rounded-[1.5rem] lg:rounded-[2rem] shadow-sm flex items-center gap-4 lg:gap-6 hover:shadow-xl hover:border-emerald-400 transition-all duration-500">
              <div class="w-10 h-10 lg:w-12 lg:h-12 bg-emerald-700 text-white rounded-xl flex items-center justify-center text-base lg:text-lg font-black shrink-0 shadow-lg shadow-emerald-200">3</div>
              <div class="text-left">
                <h4 class="text-sm lg:text-lg font-black text-slate-900">BPSDを「SOS」と捉えられる</h4>
                <p class="text-slate-800 text-[10px] lg:text-xs font-bold leading-relaxed">周辺症状（BPSD）の裏にある身体的・環境的要因を分析できるようになる。</p>
              </div>
            </div>
          </div>
        </div>
      `,
    badgeLabel: '認知症',
    badgeIcon: 'Zap',
  }

  const slidesData = [
    { title: "認知症ケア研修", order: 0, content: `<div class="flex flex-col items-center justify-center text-center space-y-6 w-full h-full"><div class="relative w-full max-w-4xl px-4"><div class="absolute inset-0 bg-emerald-400 blur-3xl opacity-20 scale-150 animate-pulse"></div><div class="relative bg-transparent lg:bg-white p-0 lg:p-16 rounded-none lg:rounded-[3.5rem] shadow-none lg:shadow-2xl border-none lg:border lg:border-slate-200 w-full mx-auto"><div class="bg-emerald-700 text-white px-4 lg:px-6 py-1 lg:py-1.5 rounded-full text-[8px] lg:text-[10px] font-black tracking-[0.3em] uppercase inline-block mb-6 lg:mb-8 shadow-sm">法定研修 2024</div><h2 class="text-3xl lg:text-6xl font-black text-slate-900 leading-tight mb-4 text-balance px-4 text-center">認知症ケア研修</h2><p class="text-emerald-700 text-sm lg:text-3xl font-black mt-2 whitespace-nowrap text-center w-full">〜安心を届ける意思決定支援と共生〜</p></div></div><div class="flex items-center justify-center gap-4 text-slate-500 font-black text-[8px] lg:text-[10px] tracking-widest pt-4"><span class="h-px w-6 lg:w-8 bg-slate-300"></span>ケア・ラーニング・システム<span class="h-px w-6 lg:w-8 bg-slate-300"></span></div></div>` },
    { title: "はじめに：なぜ届かないのか", order: 1, content: `<div class="space-y-6 lg:space-y-8 text-center px-4 h-full flex flex-col justify-center"><div class="inline-flex items-center gap-3 px-4 py-2 bg-emerald-100 text-emerald-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-emerald-200 mb-2 uppercase tracking-widest mx-auto">はじめに</div><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight px-4 text-center w-full">「真っ暗な霧」の中を<br class="lg:hidden" />歩く人の不安</h4><div class="p-0 lg:p-10 bg-transparent lg:bg-emerald-50 border-none lg:border-2 lg:border-emerald-100 shadow-none lg:shadow-xl rounded-none lg:rounded-[3rem] text-center lg:text-left text-sm lg:text-xl font-bold text-emerald-800 space-y-4 lg:space-y-6 leading-relaxed max-w-4xl mx-auto px-4"><p class="font-black text-center lg:text-left text-balance">認知症の方は、記憶や時間が抜け落ちる「得体の知れない不安」の中にいます。</p><p class="font-black text-center lg:text-left text-balance">私たちの言葉が届かないのは、拒絶ではなく、ただ「状況が把握できず怖い」だけなのかもしれません。</p></div></div>` },
    { title: "認知症基本法（2024）の施行", order: 2, content: `<div class="space-y-6 lg:space-y-8 text-center px-4 h-full flex flex-col justify-center"><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight mb-2 px-4 text-balance text-center w-full">共生社会への大きな転換</h4><div class="grid grid-cols-1 lg:grid-cols-2 gap-4 lg:gap-6 max-w-4xl mx-auto w-full"><div class="p-0 lg:p-8 bg-transparent lg:bg-white border-none lg:border-2 lg:border-slate-200 rounded-none lg:rounded-[2.5rem] shadow-none lg:shadow-xl flex flex-col items-center gap-2 lg:gap-4"><p class="font-black text-lg lg:text-xl text-emerald-800 text-balance text-center">「何もできない人」ではない</p><p class="text-sm lg:text-sm font-bold text-slate-700 leading-relaxed text-balance text-center">人生の主体者として尊厳を保持し、希望を持って暮らせる社会を目指します。</p></div><div class="p-0 lg:p-8 bg-transparent lg:bg-white border-none lg:border-2 lg:border-slate-200 rounded-none lg:rounded-[2.5rem] shadow-none lg:shadow-xl flex flex-col items-center gap-2 lg:gap-4"><p class="font-black text-lg lg:text-xl text-emerald-800 text-balance text-center">意思決定支援の重視</p><p class="text-sm lg:text-sm font-bold text-slate-700 leading-relaxed text-balance text-center">本人が自分らしく選択できるよう、周囲がサポートすることが基本となります。</p></div></div></div>` },
    { title: "認知症ケアの3原則", order: 3, content: `<div class="space-y-6 lg:space-y-8 text-center h-full flex flex-col justify-center px-4"><div class="inline-flex items-center gap-3 px-4 py-2 bg-emerald-100 text-emerald-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-emerald-200 mb-2 shadow-sm mx-auto uppercase tracking-widest">基本原則</div><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight">心に届くケアの3原則</h4><div class="grid grid-cols-1 lg:grid-cols-3 gap-3 lg:gap-4 max-w-5xl mx-auto w-full px-4"><div class="p-4 lg:p-6 bg-emerald-50 border-2 border-emerald-200 rounded-2xl lg:rounded-3xl text-center font-black text-sm lg:text-base text-emerald-900 shadow-sm">1. 驚かせない</div><div class="p-4 lg:p-6 bg-emerald-50 border-2 border-emerald-200 rounded-2xl lg:rounded-3xl text-center font-black text-sm lg:text-base text-emerald-900 shadow-sm">2. 急かさない</div><div class="p-4 lg:p-6 bg-emerald-50 border-2 border-emerald-200 rounded-2xl lg:rounded-3xl text-center font-black text-sm lg:text-base text-emerald-900 shadow-sm">3. 否定しない</div></div><p class="text-slate-500 font-black text-[10px] lg:text-base mt-4 text-balance text-center w-full">※この3つを徹底するだけで、利用者の不安は劇的に軽減されます。</p></div>` },
    { title: "3つの主要な原因疾患", order: 4, content: `<div class="flex flex-col items-center text-center space-y-4 lg:space-y-6 px-4 h-full justify-center"><div class="p-4 lg:p-6 bg-white rounded-[2rem] lg:rounded-[3.5rem] w-full max-w-2xl shadow-xl border-2 border-slate-200 shrink-0"><h4 class="text-xl lg:text-2xl font-black mb-2 text-slate-900 text-balance text-center">代表的な原因疾患を知る</h4><p class="text-[10px] lg:text-sm text-slate-900 font-black">原因によって「見え方」が違います</p></div><div class="grid grid-cols-1 lg:grid-cols-3 gap-3 lg:gap-x-4 lg:gap-y-3 font-black text-sm lg:text-base w-full max-w-5xl"><div class="p-4 bg-blue-50 border-2 border-blue-200 rounded-2xl text-left"><p class="text-blue-900 mb-1 text-center lg:text-left">アルツハイマー型</p><p class="text-[10px] lg:text-xs text-slate-600 text-center lg:text-left">脳全体が萎縮。物忘れから始まり、緩やかに進行します。</p></div><div class="p-4 bg-rose-50 border-2 border-rose-200 rounded-2xl text-left"><p class="text-rose-900 mb-1 text-center lg:text-left">レビー小体型</p><p class="text-[10px] lg:text-xs text-slate-600 text-center lg:text-left">幻視（ないものが見える）や歩行不安定が特徴的です。</p></div><div class="p-4 bg-emerald-50 border-2 border-emerald-200 rounded-2xl text-left"><p class="text-emerald-900 mb-1 text-center lg:text-left">血管性認知症</p><p class="text-[10px] lg:text-xs text-slate-600 text-center lg:text-left">脳梗塞等による「まだら認知症」。意欲低下が目立ちます。</p></div></div></div>` },
    { title: "中核症状1：記憶障害", order: 5, content: `<div class="flex flex-col justify-center h-full space-y-8 lg:space-y-12 px-4 lg:px-12 text-left"><div class="space-y-4 lg:space-y-6"><h4 class="text-2xl lg:text-5xl font-black text-emerald-900 flex items-center gap-4 lg:gap-6"><span class="w-2 h-10 lg:w-3 lg:h-16 bg-emerald-700 rounded-full"></span>記憶障害</h4></div><ul class="space-y-4 lg:space-y-8 text-lg lg:text-4xl font-black text-slate-800 pl-0 leading-tight"><li class="whitespace-nowrap">・直前の出来事を完全に忘れる</li><li class="whitespace-nowrap">・「忘れたこと」自体も忘れる</li><li class="whitespace-nowrap text-balance">・ヒントがあっても思い出せない</li></ul><p class="text-red-700 font-black text-sm lg:text-2xl mt-4 text-center w-full">叱ったり励ましたりしても治りません</p></div>` },
    { title: "中核症状2：見当識障害", order: 6, content: `<div class="flex flex-col justify-center h-full space-y-8 lg:space-y-12 px-4 lg:px-12 text-left"><div class="space-y-4 lg:space-y-6"><h4 class="text-2xl lg:text-5xl font-black text-emerald-900 flex items-center gap-4 lg:gap-6"><span class="w-2 h-10 lg:w-3 lg:h-16 bg-emerald-700 rounded-full"></span>見当識障害</h4></div><ul class="space-y-4 lg:space-y-8 text-lg lg:text-4xl font-black text-slate-800 pl-0 leading-tight"><li class="whitespace-nowrap">・時間・季節がわからなくなる</li><li class="whitespace-nowrap">・場所（今どこか）がわからなくなる</li><li class="whitespace-nowrap text-balance">・人（家族や自分）がわからなくなる</li></ul><p class="text-blue-800 font-black text-sm lg:text-2xl mt-4 text-balance text-center w-full">「自分がいま誰で、どこにいるか」不明な恐怖</p></div>` },
    { title: "中核症状3：理解・判断力の低下", order: 7, content: `<div class="flex flex-col justify-center h-full space-y-8 lg:space-y-12 px-4 lg:px-12 text-left"><div class="space-y-4 lg:space-y-6"><h4 class="text-2xl lg:text-5xl font-black text-emerald-900 flex items-center gap-4 lg:gap-6"><span class="w-2 h-10 lg:w-3 lg:h-16 bg-emerald-700 rounded-full"></span>理解・判断力の低下</h4></div><ul class="space-y-4 lg:space-y-8 text-lg lg:text-4xl font-black text-slate-800 pl-0 leading-tight"><li class="whitespace-nowrap">・二つ以上のことが同時にできない</li><li class="whitespace-nowrap">・情報が多いとパニックになる</li><li class="whitespace-nowrap text-balance">・抽象的な言葉が理解しづらい</li></ul></div>` },
    { title: "BPSD（行動・心理症状）とは？", order: 8, content: `<div class="flex flex-col items-center text-center space-y-6 lg:space-y-10 px-4 h-full justify-center"><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight text-balance text-center w-full">BPSDは「SOSメッセージ」</h4><div class="grid grid-cols-1 lg:grid-cols-2 gap-3 lg:gap-x-12 lg:gap-y-3 font-black text-sm lg:text-base w-full max-w-4xl text-left"><div class="flex flex-col gap-3"><span class="px-6 py-2.5 lg:py-3 bg-emerald-50 border-2 border-emerald-200 rounded-2xl text-emerald-900 shadow-sm text-center">徘徊・帰宅願望</span><span class="px-6 py-2.5 lg:py-3 bg-emerald-50 border-2 border-emerald-200 rounded-2xl text-emerald-900 shadow-sm text-center">暴言・暴力</span><span class="px-6 py-2.5 lg:py-3 bg-emerald-50 border-2 border-emerald-200 rounded-2xl text-emerald-900 shadow-sm text-center">収集癖・弄便</span></div><div class="flex flex-col gap-3"><span class="px-6 py-2.5 lg:py-3 bg-emerald-50 border-2 border-emerald-200 rounded-2xl text-emerald-900 shadow-sm text-center">抑うつ・不安</span><span class="px-6 py-2.5 lg:py-3 bg-emerald-50 border-2 border-emerald-200 rounded-2xl text-emerald-900 shadow-sm text-center">睡眠障害・幻覚</span></div></div><p class="text-emerald-700 font-black text-sm lg:text-xl px-4 text-balance text-center w-full">困った行動には、必ず「理由（苦痛）」があります。</p></div>` },
    { title: "BPSDの要因：身体的・環境的", order: 9, content: `<div class="flex flex-col justify-center h-full space-y-8 lg:space-y-12 px-4 lg:px-12 text-left"><h4 class="text-xl lg:text-3xl font-black text-emerald-900 text-center w-full">なぜ「不穏」になるのか？</h4><ul class="space-y-4 lg:space-y-6 text-sm lg:text-2xl font-black text-slate-800 pl-0 leading-tight text-center w-full"><li>・身体的：便秘、痛み、脱水、発熱</li><li>・環境的：騒音、照明、温度、知らない人</li><li>・心理的：孤独、叱られた悲しみ、役割の喪失</li></ul><p class="text-rose-700 font-black text-center w-full mt-4 text-balance px-4 text-center">薬の前に「環境と身体」を見直しましょう</p></div>` },
    { title: "介助の工夫：食事", order: 10, content: `<div class="flex flex-col items-center justify-center h-full space-y-6 lg:space-y-8 px-4 w-full"><h4 class="text-xl lg:text-3xl font-black text-slate-900 text-center w-full mb-4 px-4 text-center">食事を楽しめる環境設定</h4><div class="grid grid-cols-1 gap-3 lg:gap-4 w-full max-w-2xl"><div class="flex items-center gap-4 bg-white p-4 rounded-2xl border-2 border-slate-100 shadow-sm font-black"><span class="w-10 h-10 bg-emerald-700 text-white rounded-full flex items-center justify-center shrink-0">1</span>食器のコントラスト（白飯に黒い茶碗等）</div><div class="flex items-center gap-4 bg-white p-4 rounded-2xl border-2 border-slate-100 shadow-sm font-black"><span class="w-10 h-10 bg-emerald-700 text-white rounded-full flex items-center justify-center shrink-0">2</span>テレビを消して集中できる環境を作る</div><div class="flex items-center gap-4 bg-white p-4 rounded-2xl border-2 border-slate-100 shadow-sm font-black"><span class="w-10 h-10 bg-emerald-700 text-white rounded-full flex items-center justify-center shrink-0">3</span>「美味しいですね」と共感的声掛け</div></div></div>` },
    { title: "介助の工夫：入浴", order: 11, content: `<div class="flex flex-col items-center justify-center h-full space-y-6 lg:space-y-8 px-4 w-full"><h4 class="text-xl lg:text-3xl font-black text-slate-900 text-center w-full mb-4 text-balance px-4 text-center">「羞恥心」への最大限の配慮</h4><div class="grid grid-cols-1 gap-3 lg:gap-4 w-full max-w-2xl"><div class="flex items-center gap-4 bg-white p-4 rounded-2xl border-2 border-slate-100 shadow-sm font-black"><span class="w-10 h-10 bg-emerald-700 text-white rounded-full flex items-center justify-center shrink-0">1</span>全裸になる時間を最小限にする</div><div class="flex items-center gap-4 bg-white p-4 rounded-2xl border-2 border-slate-100 shadow-sm font-black"><span class="w-10 h-10 bg-emerald-700 text-white rounded-full flex items-center justify-center shrink-0">2</span>「お風呂」と言わず「さっぱりしませんか」</div><div class="flex items-center gap-4 bg-white p-4 rounded-2xl border-2 border-slate-100 shadow-sm font-black"><span class="w-10 h-10 bg-emerald-700 text-white rounded-full flex items-center justify-center shrink-0">3</span>湯温の確認を必ず一緒に行う</div></div></div>` },
    { title: "介助の工夫：排泄", order: 12, content: `<div class="flex flex-col items-center justify-center h-full text-left space-y-6 lg:space-y-8 px-6 lg:px-12 w-full"><h4 class="text-xl lg:text-3xl font-black text-emerald-700 text-center mb-4 uppercase tracking-widest w-full px-4 text-center">自尊心を傷つけない排泄介助</h4><div class="space-y-6 lg:space-y-10 font-black text-slate-900 max-w-4xl mx-auto w-full"><div><p class="text-lg lg:text-3xl text-emerald-600 mb-1 flex items-center gap-3"><span>●</span> タイミングの把握：</p><p class="text-sm lg:text-xl pl-8 lg:pl-12 text-slate-600 font-bold text-balance">本人のサイン（落ち着きがなくなる等）を逃さない。</p></div><div><p class="text-lg lg:text-3xl text-emerald-600 mb-1 flex items-center gap-3"><span>●</span> プライバシー確保：</p><p class="text-sm lg:text-xl pl-8 lg:pl-12 text-slate-600 font-bold text-balance">扉を閉める。手早く、かつ丁寧に行う。</p></div><div><p class="text-lg lg:text-3xl text-emerald-600 mb-1 flex items-center gap-3"><span>●</span> 失敗を否定しない：</p><p class="text-sm lg:text-xl pl-8 lg:pl-12 text-slate-600 font-bold text-balance">「大丈夫ですよ、すぐ着替えましょう」と明るく対応。</p></div></div></div>` },
    { title: "コミュニケーション：驚かせない", order: 13, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-6 lg:space-y-8 px-4 w-full"><div class="inline-flex items-center gap-3 px-4 py-2 bg-emerald-100 text-emerald-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-emerald-200 mb-2 mx-auto uppercase tracking-widest">重要事項</div><h4 class="text-xl lg:text-3xl font-black text-emerald-900 leading-tight px-4 text-balance text-center w-full">「背後」から声をかけない</h4><div class="p-6 lg:p-10 bg-white border-[4px] lg:border-[6px] border-emerald-600 rounded-[2rem] lg:rounded-[3rem] shadow-2xl max-w-3xl mx-auto w-full"><p class="text-lg lg:text-3xl font-black text-emerald-900 leading-relaxed italic text-balance text-center">必ず「正面」に回り、視線を合わせてから。<br/>低い位置からゆっくりと、笑顔で話しかけましょう。</p></div></div>` },
    { title: "意思決定支援：意向を推察する", order: 14, content: `<div class="flex flex-col items-center justify-center h-full text-left space-y-6 lg:space-y-8 px-6 lg:px-12 w-full"><h4 class="text-xl lg:text-3xl font-black text-emerald-900 text-center mb-4 uppercase tracking-widest w-full px-4 text-center">心の声を聴く技術</h4><div class="space-y-6 lg:space-y-10 font-black text-slate-900 max-w-4xl mx-auto w-full"><div><p class="text-lg lg:text-3xl text-emerald-700 mb-1 flex items-center gap-3"><span>●</span> 表情を観察する：</p><p class="text-sm lg:text-xl pl-8 lg:pl-12 text-slate-600 font-bold text-balance">言葉以外の「快・不快」のサインを見極める。</p></div><div><p class="text-lg lg:text-3xl text-emerald-700 mb-1 flex items-center gap-3"><span>●</span> 過去を知る：</p><p class="text-sm lg:text-xl pl-8 lg:pl-12 text-slate-600 font-bold text-balance">本人の経歴や大切にしていた価値観を尊重する。</p></div><div><p class="text-lg lg:text-3xl text-emerald-700 mb-1 flex items-center gap-3"><span>●</span> 選択肢を示す：</p><p class="text-sm lg:text-xl pl-8 lg:pl-12 text-slate-600 font-bold text-balance">「どうしますか？」ではなく「AとB、どちらがいいですか？」</p></div></div></div>` },
    { title: "家族支援：介護者の心に寄り添う", order: 15, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-6 lg:space-y-8 px-4 w-full"><div class="inline-flex items-center gap-3 px-4 py-2 bg-blue-50 text-blue-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-blue-200 mb-2 mx-auto uppercase tracking-widest">家族支援</div><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight px-4 text-balance text-center w-full">家族もまた「ケアの対象」</h4><div class="p-6 lg:p-8 bg-white border-2 border-blue-100 rounded-3xl text-left max-w-4xl space-y-4 shadow-sm mx-auto"><p class="text-sm lg:text-lg font-bold text-slate-700 leading-relaxed text-balance text-center">愛する家族が変わっていく姿を見るのは、耐え難い苦痛です。私たちは、ご家族の悩みや孤独にも耳を傾ける「伴走者」でありたいと考えます。</p></div><p class="text-blue-800 font-black text-xs lg:text-xl text-center w-full">※一人で抱え込まないよう、地域の相談窓口や資源を紹介することも重要です。</p></div>` },
    { title: "1. 事例：帰宅願望がある方へ", order: 16, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-6 lg:space-y-8 px-4 w-full"><div class="inline-flex items-center gap-3 px-4 py-2 bg-emerald-50 text-emerald-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-emerald-200 mb-2 mx-auto uppercase text-center">事例 1</div><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight px-4 text-balance text-center w-full">場面：「家に帰ります」</h4><div class="p-0 lg:p-8 bg-transparent lg:bg-white border-none lg:border-2 lg:border-slate-100 rounded-none lg:rounded-[2rem] shadow-none lg:shadow-xl max-w-4xl text-left space-y-4 lg:space-y-6 w-full text-center"><p class="text-sm lg:text-xl font-bold text-slate-800 leading-relaxed text-balance px-4 text-center">夕暮れ時、出口に向かう利用者様。<br class="lg:hidden" />「ここにはいられません。帰ります」<br class="lg:hidden" />と強く訴えています。</p><div class="h-px bg-slate-100"></div><p class="text-xs lg:text-lg font-black text-emerald-700 italic text-center px-4 text-balance text-center w-full">「ダメですよ」と扉を閉めますか？<br class="lg:hidden" />その方が「今、帰りたい場所」は<br class="lg:hidden" />今の自宅でしょうか？</p></div></div>` },
    { title: "2. 事例：入浴拒否がある方へ", order: 17, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-6 lg:space-y-8 px-4 w-full"><div class="inline-flex items-center gap-3 px-4 py-2 bg-emerald-50 text-emerald-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-emerald-200 mb-2 mx-auto uppercase">事例 2</div><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight px-4 text-balance text-center w-full">場面：「お風呂は嫌だ」</h4><div class="p-0 lg:p-8 bg-transparent lg:bg-white border-none lg:border-2 lg:border-slate-100 rounded-none lg:rounded-[2rem] shadow-none lg:shadow-xl max-w-4xl text-left space-y-4 lg:space-y-6 w-full text-center"><p class="text-sm lg:text-xl font-bold text-slate-800 leading-relaxed text-balance px-4 text-center">入浴時間ですが、「入りません！」<br class="lg:hidden" />と頑なに拒否されています。<br class="lg:hidden" />衛生上、今日中に入ってほしい場面です。</p><div class="h-px bg-slate-100"></div><p class="text-xs lg:text-lg font-black text-emerald-700 italic text-center px-4 text-balance text-center w-full">「清潔のために必要です」と説得しますか？<br class="lg:hidden" />それとも別の「心地よい言葉」を探しますか？</p></div></div>` },
    { title: "解決：理由を見つければケアは変わる", order: 18, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-6 lg:space-y-8 px-4 w-full"><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight px-4 text-balance text-center w-full">「理由」を見つければ、ケアは変わる</h4><div class="p-6 lg:p-10 bg-emerald-50 border-2 border-emerald-100 rounded-[2.5rem] lg:rounded-[4rem] shadow-inner text-left max-w-4xl space-y-4 lg:space-y-6 mx-auto text-center"><p class="text-base lg:text-xl font-black text-emerald-900 text-center w-full">安心を届けるための具体策</p><div class="grid grid-cols-1 gap-3 lg:gap-4 text-sm lg:text-lg font-bold text-slate-800"><div class="flex items-center gap-3 lg:gap-4 bg-white p-3 lg:p-4 rounded-xl lg:rounded-2xl border border-emerald-100 shadow-sm"><span class="w-6 h-6 lg:w-8 lg:h-8 bg-emerald-600 text-white rounded-full flex items-center justify-center text-[10px] lg:text-sm shrink-0">1</span>帰宅願望には「否定」せず、思いに共感する</div><div class="flex items-center gap-3 lg:gap-4 bg-white p-3 lg:p-4 rounded-xl lg:rounded-2xl border border-emerald-100 shadow-sm"><span class="w-6 h-6 lg:w-8 lg:h-8 bg-emerald-600 text-white rounded-full flex items-center justify-center text-[10px] lg:text-sm shrink-0">2</span>拒否には「別の目的（足湯、蒸しタオル等）」を提案</div><div class="flex items-center gap-3 lg:gap-4 bg-white p-3 lg:p-4 rounded-xl lg:rounded-2xl border border-emerald-100 shadow-sm"><span class="w-6 h-6 lg:w-8 lg:h-8 bg-emerald-600 text-white rounded-full flex items-center justify-center text-[10px] lg:text-sm shrink-0">3</span>一人で解決せず、成功事例をチームで共有する</div></div></div></div>` },
    { title: "中核症状への正しい対応", order: 19, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-6 lg:space-y-8 px-4 w-full text-center"><h4 class="text-xl lg:text-3xl font-black italic text-emerald-900 px-4 text-balance text-center w-full">「本人の努力」では無理</h4><div class="p-8 lg:p-10 bg-white border-4 border-emerald-100 rounded-[2rem] lg:rounded-[3rem] shadow-xl max-w-4xl mx-auto w-full"><p class="text-xl lg:text-3xl font-black leading-relaxed text-center text-slate-900">忘れること、理解できないことは<br/><span class="text-emerald-700 underline underline-offset-8 decoration-4">脳の故障</span>による不随意なものです。</p></div><p class="text-[10px] lg:text-lg font-black text-emerald-800 px-4 text-balance text-center w-full">本人の尊厳を守るために、私たちは「寄り添う技術」を磨き続けます。</p></div>` },
    { title: "認知症の方との「距離感」", order: 20, content: `<div class="flex flex-col items-center justify-center h-full text-left space-y-6 lg:space-y-10 px-6 lg:px-12 w-full text-center"><h4 class="text-xl lg:text-3xl font-black text-emerald-800 flex items-center gap-4 w-full px-4 justify-center text-balance text-center w-full">視線の高さを合わせる</h4><p class="text-sm lg:text-2xl font-black leading-relaxed text-slate-900 max-w-4xl bg-emerald-50 p-6 lg:p-8 rounded-2xl lg:rounded-3xl border border-emerald-100 w-full text-balance text-center">見下ろされると、それだけで威圧感を感じ、不安を煽ります。しゃがんで目線を合わせ、対等な関係を築きましょう。</p><p class="text-xs lg:text-xl font-black text-emerald-800 text-center w-full text-balance px-4 text-center">あなたの笑顔が、最も効果的な「認知症ケア」です。</p></div>` },
    { title: "満足感：あなたの理解", order: 21, content: `<div class="space-y-6 lg:space-y-10 text-center flex flex-col items-center justify-center h-full px-4 w-full text-center"><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight px-4 text-center w-full">プロとしての共感</h4><div class="p-8 lg:p-12 bg-white border-[4px] lg:border-[6px] border-emerald-600 rounded-[2rem] lg:rounded-[3rem] shadow-2xl max-w-3xl mx-auto w-full"><p class="text-xl lg:text-3xl font-black text-emerald-900 leading-relaxed italic text-balance text-center">あなたの「一言」が、<br/>混乱の中にいる人の<br/>確かな「安心」になります。</p></div><p class="font-black text-sm lg:text-xl text-slate-800 mt-4 text-balance text-center w-full px-4">今日からその安心を届けるケアを始めましょう。</p></div>` },
    { title: "まとめ：認知症ケアの誇り", order: 22, content: `<div class="flex flex-col items-center text-center space-y-8 lg:space-y-12 w-full h-full justify-center text-slate-900 px-4 text-center"><div class="w-24 h-24 lg:w-32 h-32 bg-emerald-700 rounded-[2.5rem] lg:rounded-[3.5rem] flex items-center justify-center shadow-2xl shadow-emerald-200 rotate-3 transition-transform hover:rotate-0 duration-500 mx-auto"><svg class="w-12 h-12 lg:w-16 h-16 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M13 10V3L4 14h7v7l9-11h-7z" /></svg></div><h3 class="text-2xl lg:text-5xl font-black leading-tight text-center w-full">心に寄り添うケアを、<br/>全員で実践しましょう。</h3><div class="pt-8 lg:pt-12 border-t-2 border-slate-200 w-full max-w-md text-center mx-auto"><p class="text-slate-500 font-black text-[8px] lg:text-[10px] uppercase tracking-[0.5em]">研修修了</p></div></div>` },
    { title: "実践チェックのご案内", order: 23, content: `
        <div class="flex flex-col items-center text-center space-y-6 lg:space-y-8 w-full h-full justify-center px-4 text-center">
          <div class="bg-emerald-600 text-white px-6 py-1.5 rounded-full text-[8px] lg:text-[10px] font-black tracking-[0.3em] uppercase inline-block mb-4 lg:mb-6 shadow-lg px-4">修了</div>
          <h2 class="text-2xl lg:text-5xl font-black text-slate-900 leading-tight mb-2 lg:mb-4 text-balance text-center w-full px-4 text-center">講義セッション終了</h2>
          <p class="text-emerald-800 text-base lg:text-2xl font-black leading-relaxed text-center w-full text-balance px-4 text-center">大変お疲れ様でした。<br/>最後に理解度テスト（全10問）を行います。</p>
          <div class="p-4 lg:p-6 bg-emerald-50 rounded-2xl lg:rounded-3xl border-2 border-emerald-100 max-w-lg mx-auto mt-6 lg:mt-8">
            <p class="text-emerald-900 font-black text-sm lg:text-xl flex items-center justify-center gap-3">
              <span class="w-2 h-2 bg-emerald-700 rounded-full"></span>    
              全問正解を目指しましょう！
              <span class="w-2 h-2 bg-emerald-700 rounded-full"></span>    
            </p>
          </div>
        </div>
      ` },
    { title: "意思決定支援のあり方", order: 24, content: `<div class="flex flex-col items-center justify-center h-full text-left space-y-6 lg:space-y-8 px-6 lg:px-12 w-full text-center"><h4 class="text-xl lg:text-3xl font-black text-emerald-900 text-center mb-4 uppercase tracking-widest w-full text-center">本人の意向を最後まで探す</h4><div class="p-6 bg-white border-2 border-emerald-100 rounded-3xl text-left max-w-3xl space-y-4 shadow-sm mx-auto text-center"><p class="text-sm lg:text-xl font-black text-slate-800 leading-relaxed text-balance text-center">「もう何もわからない」と決めつけず、表情やわずかな反応から本人の望む暮らしを推察し続けることが、プロとしての意思決定支援です。</p></div><div class="flex items-center justify-center gap-4 text-slate-500 font-black text-[8px] lg:text-[10px] tracking-widest pt-4 w-full text-center"><span class="h-px w-6 lg:w-8 bg-slate-300"></span>ケア・ラーニング・システム<span class="h-px w-6 lg:w-8 bg-slate-300"></span></div></div>` }
  ]

  const questionsData = [
    { text: '2024年に施行された「認知症基本法」において、最も重視されている考え方はどれか？', explanation: '「共生社会の実現」と、本人の「尊厳の保持」が法律の柱となっています。', order: 1, choices: { create: [{ text: '共生社会の実現と本人の尊厳保持', isCorrect: true }, { text: '施設内での一律の安全管理', isCorrect: false }, { text: '認知症の完治を目指す医療の提供', isCorrect: false }] } },
    { text: '記憶障害により直前の出来事を忘れてしまった利用者への対応として、適切なものはどれか？', explanation: '忘れることは脳の故障による症状であり、叱っても解決しません。安心感を与える対応が求められます。', order: 2, choices: { create: [{ text: '安心感を与え、否定せずに寄り添う', isCorrect: true }, { text: '「さっき言いましたよね」と注意する', isCorrect: false }, { text: '思い出すまで何度も繰り返し質問する', isCorrect: false }] } },
    { text: 'BPSD（周辺症状）が発生する大きな要因として、まず検討すべきことは何か？', explanation: '便秘や痛みなどの身体的苦痛、または環境の不快さがBPSDを引き起こす大きな要因です。', order: 3, choices: { create: [{ text: '身体적苦痛や環境の不快さの有無', isCorrect: true }, { text: '本人の性格やわがまま', isCorrect: false }, { text: '薬の服用を忘れたことのみ', isCorrect: false }] } },
    { text: '見当識障害がある方が、夕方に「家に帰ります」と訴える理由として考えにくいものは？', explanation: '「わがまま」ではなく、場所や時間がわからない不安や、過去の記憶に基づく「役割への責任感」が原因であることが多いです。', order: 4, choices: { create: [{ text: '職員を困らせようとするわがまま', isCorrect: true }, { text: '今いる場所がわからないことへの不安', isCorrect: false }, { text: '家族のために夕食を作らなければという責任感', isCorrect: false }] } },
    { text: '本人の意向を推察し、自分らしく選択できるよう支援することを何というか？', explanation: 'これを「意思決定支援」と呼び、認知症ケアの最も重要な基本となります。', order: 5, choices: { create: [{ text: '意思決定支援', isCorrect: true }, { text: '管理型ケア', isCorrect: false }, { text: '代理決定', isCorrect: false }] } },
    { text: '認知症の方とのコミュニケーションにおける「3つのない」に含まれないものはどれか？', explanation: '「驚かせない・急かさない・否定しない」が3原則です。', order: 6, choices: { create: [{ text: '何もさせない', isCorrect: true }, { text: '驚かせない', isCorrect: false }, { text: '急かさない', isCorrect: false }, { text: '否定しない', isCorrect: false }] } },
    { text: '食事介助において、本人が食べ物を認識しやすくするための工夫はどれか？', explanation: '視覚的な情報を整理するため、食器の色のコントラストを上げることが有効です。', order: 7, choices: { create: [{ text: '食器の色のコントラストを上げる', isCorrect: true }, { text: 'テレビをつけたまま食事をする', isCorrect: false }, { text: 'おかずをすべて混ぜて提供する', isCorrect: false }] } },
    { text: '入浴拒否がある方への声掛けとして、プロとしてより適切なものはどれか？', explanation: '「入浴」という言葉に抵抗がある場合、「さっぱりしましょう」など本人が快感を感じる言葉を選びます。', order: 8, choices: { create: [{ text: '「さっぱりしませんか」と心地よさを提案', isCorrect: true }, { text: '「決まりですから入ってください」と説得', isCorrect: false }, { text: '「不潔になりますよ」と不安を煽る', isCorrect: false }] } },
    { text: '認知症の方がパニックになっている際、最初にとるべき態度はどれか？', explanation: 'まずは視線の高さを合わせ、落ち着いた笑顔で安心感を伝えることが先決です。', order: 9, choices: { create: [{ text: '視線の高さを合わせ、笑顔で接する', isCorrect: true }, { text: '上から見下ろすようにして制止する', isCorrect: false }, { text: '大声を出して周囲に危険を知らせる', isCorrect: false }] } },
    { text: '意思決定支援において、過去の経歴や大切にしていた価値観を尊重するのはなぜか？', explanation: '本人の「自分らしさ（アイデンティティ）」を保ち、尊厳を守るために不可欠だからです。', order: 10, choices: { create: [{ text: '本人の尊厳と自分らしさを守るため', isCorrect: true }, { text: '施設側の管理を楽にするため', isCorrect: false }, { text: '単なるマニュアルの手順だから', isCorrect: false }] } }
  ]

  let course = await prisma.course.findUnique({ where: { slug } })

  if (course) {
    await prisma.choice.deleteMany({ where: { question: { courseId: course.id } } })
    await prisma.question.deleteMany({ where: { courseId: course.id } })
    await prisma.slide.deleteMany({ where: { courseId: course.id } })
    
    course = await prisma.course.update({
      where: { id: course.id },
      data: {
        ...courseData,
        slides: { create: slidesData },
        questions: { create: questionsData }
      }
    })
  } else {
    course = await prisma.course.create({
      data: {
        ...courseData,
        slides: { create: slidesData },
        questions: { create: questionsData }
      }
    })
  }

  return course
}
