import { PrismaClient } from '@prisma/client'

export async function seedInfection(prisma: PrismaClient) {
  return await prisma.course.create({
    data: {
      title: '感染症・食中毒の予防および蔓延防止に関する研修',
      description: '「持ち込まない・広げない」を徹底するための標準予防策と、2024年義務化のBCPまでを完全網羅。',
      introduction: `
        <div class="space-y-8">
          <div class="flex items-center gap-4"><span class="h-1 w-12 bg-sky-600 rounded-full"></span><p class="text-sky-600 font-black tracking-widest text-sm uppercase">Curriculum Hook</p></div>
          <h2 class="text-4xl font-black text-slate-900 leading-tight">あなたの手は、今、本当に<br/>「安全」だと言い切れますか？</h2>
          <div class="space-y-6 text-slate-600 text-lg leading-relaxed font-medium">
            <p>「自分は健康だから大丈夫」というその油断が、施設全体を巻き込むパンデミックの引き金になります。</p>
            <div class="p-8 bg-sky-50/50 rounded-[2rem] border border-sky-100 shadow-inner relative overflow-hidden">
              <div class="absolute top-0 right-0 w-24 h-24 bg-sky-100/30 rounded-bl-full"></div>
              <p class="relative z-10 font-medium italic">高齢者の命を奪うのは病気だけではありません。私たちが持ち込むウイルスや細菌こそが、最大の脅威なのです。</p>
            </div>
            <p>この研修は、プロフェッショナルとして利用者の命を守る「盾」になるための、最新の防衛技術を学ぶ時間です。</p>
          </div>
        </div>
      `,
      learningObjectives: `
        <div class="grid grid-cols-1 gap-6">
          <div class="group p-6 bg-white border border-slate-100 rounded-3xl shadow-sm hover:shadow-sky-50 transition-all duration-500 flex items-start gap-6">
            <div class="w-14 h-14 bg-sky-600 text-white rounded-2xl flex items-center justify-center text-xl font-black shrink-0 shadow-lg group-hover:scale-110 transition-transform">1</div>
            <div><h4 class="text-xl font-black text-slate-900 mb-2">標準予防策（PPE・手洗い）の完遂</h4><p class="text-slate-500 leading-relaxed font-medium">全ての利用者が感染している可能性を前提とした、正しい防護具の着脱と手指衛生の手順をマスターする。</p></div>
          </div>
          <div class="group p-6 bg-white border border-slate-100 rounded-3xl shadow-sm hover:shadow-sky-50 transition-all duration-500 flex items-start gap-6">
            <div class="w-14 h-14 bg-sky-600 text-white rounded-2xl flex items-center justify-center text-xl font-black shrink-0 shadow-lg group-hover:scale-110 transition-transform">2</div>
            <div><h4 class="text-xl font-black text-slate-900 mb-2">蔓延防止とBCPの実践</h4><p class="text-slate-500 leading-relaxed font-medium">ノロウイルス等の発生時の初動対応と、2024年度から義務化された「BCP（業務継続計画）」の役割を理解する。</p></div>
          </div>
        </div>
      `,
      slides: {
        create: [
          { title: '感染症対策：見えない敵との戦い', order: 0, content: `<div class="flex flex-col items-center justify-center min-h-[300px] text-center space-y-12"><div class="relative"><div class="absolute inset-0 bg-sky-400 blur-3xl opacity-20 scale-150 animate-pulse"></div><div class="relative bg-white p-10 rounded-[3rem] shadow-2xl border border-slate-100 max-w-sm"><div class="bg-sky-600 text-white px-6 py-1.5 rounded-full text-[10px] font-black tracking-[0.3em] uppercase inline-block mb-6">Infection Control</div><h2 class="text-3xl font-black text-slate-900 leading-tight mb-4">感染症・食中毒予防<br/>〜持ち込まない・広げない〜</h2></div></div><div class="flex items-center gap-4 text-slate-400 font-black text-[10px] tracking-widest"><span class="h-px w-8 bg-slate-200"></span>CARE LEARNING SYSTEM<span class="h-px w-8 bg-slate-200"></span></div></div>` },
          { title: '基本概念：スタンダード・プリコーション', order: 1, content: `<div class="space-y-8"><div class="inline-flex items-center gap-3 px-4 py-2 bg-sky-50 text-sky-600 rounded-full text-xs font-black ring-1 ring-sky-100"><span class="w-2 h-2 bg-sky-600 rounded-full animate-ping"></span>CORE CONCEPT</div><h4 class="text-2xl font-black text-slate-900 leading-tight">「全ての利用者が感染している」<br/>と<span class="text-sky-600 decoration-4 underline underline-offset-8">想定する</span>ことが基本です</h4><div class="p-8 bg-white border-2 border-slate-50 rounded-[2.5rem] shadow-sm font-bold text-slate-700 leading-relaxed italic">血液、体液、排泄物、傷のある皮膚。これらは全て感染源であるとみなし、誰に対しても平等に、常に同じ高いレベルの予防策を実施します。</div></div>` },
          { title: '3つの主要な感染経路', order: 2, content: `<div class="grid grid-cols-1 gap-3"><div class="group p-4 bg-slate-50/50 rounded-2xl border border-slate-100 flex items-center gap-5 hover:bg-white transition-all"><div class="w-12 h-12 bg-sky-600 text-white rounded-xl flex items-center justify-center text-lg font-black shrink-0">1</div><div class="flex-1"><p class="text-sm font-black text-slate-900">接触感染</p><p class="text-[10px] text-slate-500 font-medium">手やドアノブを介して広がる。ノロウイルス、疥癬など。</p></div></div><div class="group p-4 bg-slate-50/50 rounded-2xl border border-slate-100 flex items-center gap-5 hover:bg-white transition-all"><div class="w-12 h-12 bg-sky-600 text-white rounded-xl flex items-center justify-center text-lg font-black shrink-0">2</div><div class="flex-1"><p class="text-sm font-black text-slate-900">飛沫感染</p><p class="text-[10px] text-slate-500 font-medium">咳やくしゃみのしぶき（2m以内）で広がる。インフルエンザなど。</p></div></div><div class="group p-4 bg-slate-50/50 rounded-2xl border border-slate-100 flex items-center gap-5 hover:bg-white transition-all"><div class="w-12 h-12 bg-sky-600 text-white rounded-xl flex items-center justify-center text-lg font-black shrink-0">3</div><div class="flex-1"><p class="text-sm font-black text-slate-900">空気感染</p><p class="text-[10px] text-slate-500 font-medium">空気中に漂う微粒子を吸い込んで広がる。結核、麻疹など。</p></div></div></div>` },
          { title: '【IDクイズ】アルコールが効かないのは？', order: 3, content: `<div class="p-10 bg-slate-900 text-white rounded-[3rem] shadow-2xl relative overflow-hidden text-center"><h4 class="text-xs font-black tracking-[0.3em] uppercase opacity-50 mb-8">Interactive Quiz</h4><p class="text-lg font-bold mb-10">次の中で、通常のアルコール消毒液が<br/>ほとんど効かないウイルスはどれ？</p><div class="grid grid-cols-2 gap-6"><div class="p-6 bg-white/10 rounded-3xl border border-white/20 hover:bg-white/20 transition-colors"><p class="font-black">インフルエンザ</p></div><div class="p-6 bg-red-600 rounded-3xl border border-red-500 shadow-xl animate-pulse"><p class="font-black mb-2">ノロウイルス</p><p class="text-[10px] opacity-80 font-medium">正解！次亜塩素酸Naが必要です</p></div></div></div>` },
          { title: '最強の武器：正しい手指衛生', order: 4, content: `<div class="space-y-8"><div class="flex flex-col items-center"><h4 class="text-xl font-black text-slate-900 text-center leading-relaxed">石鹸で「30秒」洗っていますか？</h4></div><div class="relative grid grid-cols-2 gap-px bg-slate-200 p-px rounded-[2rem] overflow-hidden border border-slate-200 shadow-2xl text-center"><div class="p-6 bg-white space-y-3"><div class="w-10 h-10 bg-sky-50 text-sky-600 rounded-full flex items-center justify-center font-black mx-auto">1</div><p class="text-xs font-black text-slate-900">タイミング</p><p class="text-[9px] text-slate-400">ケアの前後、汚染物に触れた後、手袋を脱いだ後も必須！</p></div><div class="p-6 bg-white space-y-3"><div class="w-10 h-10 bg-sky-50 text-sky-600 rounded-full flex items-center justify-center font-black mx-auto">2</div><p class="text-xs font-black text-slate-900">洗い残し注意</p><p class="text-[9px] text-slate-400">指先、親指の付け根、手首、指の間は特に汚れが残ります</p></div></div></div>` },
          { title: '重要：PPE（防護具）の「脱ぐ」順番', order: 5, content: `<div class="space-y-6"><div class="bg-slate-900 text-white p-10 rounded-[2.5rem] shadow-2xl relative overflow-hidden"><h4 class="text-xs font-black tracking-[0.3em] uppercase opacity-50 mb-6">Strict Rules</h4><p class="text-sm text-emerald-400 font-black mb-4">汚染面に触れないための「脱ぐ順番」が命を分けます</p><div class="space-y-4 text-lg font-black text-left"><div class="flex items-center gap-4"><span class="w-8 h-8 bg-white/10 rounded-lg flex items-center justify-center text-xs">01</span><p>手袋：外側を触らずに裏返して脱ぐ</p></div><div class="flex items-center gap-4"><span class="w-8 h-8 bg-white/10 rounded-lg flex items-center justify-center text-xs">02</span><p>ガウン：内側から丸めるように脱ぐ</p></div><div class="flex items-center gap-4"><span class="w-8 h-8 bg-white/10 rounded-lg flex items-center justify-center text-xs">03</span><p>マスク：表面に触れずゴム紐を持つ</p></div></div></div></div>` },
          { title: '食中毒予防の3原則', order: 6, content: `<div class="space-y-8"><div class="p-8 bg-amber-50 rounded-[2.5rem] border-2 border-amber-100 border-dashed relative text-center"><div class="absolute -top-4 left-1/2 -translate-x-1/2 bg-amber-600 text-white px-6 py-1 rounded-full text-[10px] font-black tracking-widest uppercase">Food Safety</div><h4 class="text-2xl font-black text-amber-900 mb-4">つけない・増やさない・やっつける</h4><div class="grid grid-cols-3 gap-4 mt-6"><div class="p-4 bg-white rounded-xl shadow-sm"><p class="text-[10px] font-black">1. 清潔</p><p class="text-[8px] text-slate-500">（つけない）</p></div><div class="p-4 bg-white rounded-xl shadow-sm"><p class="text-[10px] font-black">2. 迅速</p><p class="text-[8px] text-slate-500">（増やさない）</p></div><div class="p-4 bg-white rounded-xl shadow-sm"><p class="text-[10px] font-black">3. 加熱</p><p class="text-[8px] text-slate-500">（やっつける）</p></div></div></div></div>` },
          { title: 'ノロウイルス嘔吐物処理の鉄則', order: 7, content: `<div class="space-y-8"><div class="p-10 bg-red-50 rounded-[3rem] border border-red-100 flex flex-col items-center text-center space-y-6"><div class="w-20 h-20 bg-white rounded-[2rem] shadow-xl flex items-center justify-center"><svg class="w-10 h-10 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg></div><h4 class="text-2xl font-black text-red-900">乾燥は最大の敵</h4><p class="text-red-800 text-sm font-medium leading-relaxed">乾燥してウイルスが舞い上がると、吸い込んで感染します。次亜塩素酸ナトリウム（0.1%）で浸し、外側から内側へ静かに拭き取ります。</p></div></div>` },
          { title: '発生時の初動シミュレーション', order: 8, content: `<div class="space-y-6"><div class="p-8 bg-orange-50 border-2 border-orange-100 rounded-[2.5rem] text-center"><p class="text-orange-900 text-lg font-black leading-relaxed">利用者が突然の嘔吐。周囲には他の利用者もいます。あなたならどうしますか？</p></div><div class="grid grid-cols-1 gap-4"><div class="p-6 bg-white border border-slate-100 rounded-2xl shadow-sm flex items-center gap-4 opacity-60"><span class="w-10 h-10 bg-slate-100 text-slate-400 rounded-xl flex items-center justify-center font-black">×</span><p class="text-xs font-bold italic">すぐに素手で介助し、後で手洗いをする</p></div><div class="p-6 bg-white border border-emerald-100 rounded-2xl shadow-xl ring-2 ring-emerald-50 flex items-center gap-4"><span class="w-10 h-10 bg-emerald-600 text-white rounded-xl flex items-center justify-center font-black shadow-lg">○</span><p class="text-xs font-black text-slate-900 font-bold">周囲を遠ざけ、応援を呼び、PPEを装着してから処理を開始する</p></div></div></div>` },
          { title: '2024年度最新要件：感染症BCP', order: 9, content: `<div class="space-y-8"><div class="flex flex-col items-center text-center"><div class="bg-slate-100 px-4 py-1 rounded-full text-[10px] font-black text-slate-500 tracking-widest uppercase mb-4">Business Continuity</div><h4 class="text-xl font-black text-slate-900 leading-relaxed">職員の半数が欠勤しても、<br/>命を守り抜くために</h4></div><div class="relative grid grid-cols-2 gap-px bg-slate-200 p-px rounded-[2rem] overflow-hidden border border-slate-200 shadow-2xl"><div class="p-6 bg-white text-center space-y-3"><div class="w-10 h-10 bg-sky-50 text-sky-600 rounded-full flex items-center justify-center font-black mx-auto">1</div><p class="text-xs font-black text-slate-900 font-bold">優先業務の絞り込み</p><p class="text-[9px] text-slate-400">生命に関わるケア（食事・排泄・投薬）を最優先。レク等は休止する</p></div><div class="p-6 bg-white text-center space-y-3"><div class="w-10 h-10 bg-sky-50 text-sky-600 rounded-full flex items-center justify-center font-black mx-auto">2</div><p class="text-xs font-black text-slate-900 font-bold">情報共有ルート</p><p class="text-[9px] text-slate-400">誰が、誰に、いつ報告するか。BCP指針を事前に共有しておく</p></div></div></div>` },
          { title: '健康管理と「出勤しない勇気」', order: 10, content: `<div class="space-y-8"><div class="relative p-10 bg-slate-900 rounded-[3rem] shadow-2xl overflow-hidden text-center text-white"><h4 class="text-2xl font-black mb-8 italic">小さな「違和感」を隠さない</h4><div class="p-6 bg-white/5 rounded-2xl border border-white/10 text-left"><p class="text-slate-300 text-sm leading-relaxed font-medium">・自身に熱や下痢がある場合は必ず報告し、指示を仰ぐ。<br/>・自分の健康を守ることは、利用者を守ることそのものです。</p></div></div></div>` },
          { title: 'まとめ：利用者の命を守る盾として', order: 11, content: `<div class="flex flex-col items-center justify-center min-h-[450px] text-center space-y-10"><div class="w-24 h-24 bg-sky-600 rounded-[2.5rem] flex items-center justify-center shadow-2xl shadow-sky-200 rotate-3"><svg class="w-12 h-12 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" /></svg></div><h3 class="text-3xl font-black text-slate-900 leading-tight">手洗い一つが、誰かの未来を救う</h3><p class="text-slate-500 font-medium text-lg max-w-sm mx-auto leading-relaxed">プロフェッショナルとして、「持ち込まない・広げない」を今日から再徹底しましょう。</p><div class="pt-10 border-t border-slate-100 w-full"><p class="text-slate-400 font-black text-xs uppercase tracking-[0.3em]">End of Session</p></div></div>` }
        ]
      },
      questions: {
        create: [
          { text: 'ノロウイルスに最も効果的な消毒液はどれか。', explanation: 'アルコールはノロウイルスには効きにくいため、0.1%以上の次亜塩素酸ナトリウムを使用します。', order: 1, choices: { create: [{ text: '次亜塩素酸ナトリウム', isCorrect: true }, { text: 'アルコール', isCorrect: false }, { text: '消毒用ハンドソープ', isCorrect: false }] } },
          { text: 'PPE（個人防護具）を脱ぐ際、汚染面に触れないための最も適切な順番はどれか。', explanation: '汚染の激しいものから脱ぎます。一般的に「手袋 → ガウン → マスク」の順で、表面に触れないよう脱ぎます。', order: 2, choices: { create: [{ text: '手袋 → ガウン → マスク', isCorrect: true }, { text: 'マスク → 手袋 → ガウン', isCorrect: false }, { text: 'ガウン → マスク → 手袋', isCorrect: false }] } },
          { text: '食中毒予防の3原則に含まれないものはどれか。', explanation: '「つけない・増やさない・やっつける」が3原則です。', order: 3, choices: { create: [{ text: '冷まさない', isCorrect: true }, { text: 'つけない（清潔）', isCorrect: false }, { text: '増やさない（迅速）', isCorrect: false }, { text: 'やっつける（殺菌）', isCorrect: false }] } },
          { text: 'ノロウイルスの嘔吐物を処理する際、最も注意すべきことは何か。', explanation: '乾燥するとウイルスが空気中に舞い上がり、吸入感染を引き起こすため、乾燥させないことが最優先です。', order: 4, choices: { create: [{ text: '乾燥させないように素早く覆う', isCorrect: true }, { text: '掃除機で吸い取る', isCorrect: false }, { text: '水で薄めて広げる', isCorrect: false }] } },
          { text: '2024年度より義務化された「感染症BCP」において、人員不足時に優先すべき業務はどれか。', explanation: '生命維持に直結する食事・排泄・投薬などの身体ケアを最優先し、レクリエーションなどは休止します。', order: 5, choices: { create: [{ text: '食事・排泄・投薬の身体ケア', isCorrect: true }, { text: '季節の行事やレクリエーション', isCorrect: false }, { text: '居室のワックス掛け', isCorrect: false }] } }
        ]
      }
    }
  })
}
