import { PrismaClient } from '@prisma/client'

export async function seedDisaster(prisma: PrismaClient) {
  return await prisma.course.create({
    data: {
      title: '非常災害時の対応（BCP：業務継続計画を含む）に関する研修',
      description: '2024年4月からのBCP義務化に対応。地震・水害・火災時の優先判断と組織的対応を網羅した決定版。',
      introduction: `
        <div class="space-y-8">
          <div class="flex items-center gap-4">
            <span class="h-1 w-12 bg-orange-600 rounded-full"></span>
            <p class="text-orange-600 font-black tracking-widest text-sm uppercase">BCP Essential Hook</p>
          </div>
          <h2 class="text-4xl font-black text-slate-900 leading-tight">その時、あなたの指示を<br/>待つ命がある。</h2>
          <div class="space-y-6 text-slate-600 text-lg leading-relaxed font-medium">
            <p>地震、水害、そして深夜の火災。災害は、私たちが最も「準備ができていない時」に襲ってきます。パニックを抑え、命を救うのは、唯一「日頃の想定（BCP）」だけです。</p>
            <div class="p-8 bg-orange-50/50 rounded-[2rem] border border-orange-100 shadow-inner relative overflow-hidden">
              <div class="absolute top-0 right-0 w-24 h-24 bg-orange-100/30 rounded-bl-full"></div>
              <p class="relative z-10 font-medium italic">2024年度より、BCP（業務継続計画）の策定と職員への周知が「完全義務化」されました。未策定の場合は基本報酬が3%減算される、経営的にも極めて重要な項目です。</p>
            </div>
            <p>この研修では、災害発生時の「優先順位」と、組織としてケアを止めないための鉄則を学びます。</p>
          </div>
        </div>
      `,
      learningObjectives: `
        <div class="grid grid-cols-1 gap-6">
          <div class="group p-6 bg-white border border-slate-100 rounded-3xl shadow-sm hover:shadow-orange-50 transition-all duration-500 flex items-start gap-6">
            <div class="w-14 h-14 bg-orange-600 text-white rounded-2xl flex items-center justify-center text-xl font-black shrink-0 shadow-lg group-hover:scale-110 transition-transform">1</div>
            <div><h4 class="text-xl font-black text-slate-900 mb-2">BCPに基づく優先業務の判断</h4><p class="text-slate-500 leading-relaxed font-medium">ライフライン停止や人員不足の極限状態で、どのケアを優先し、何を休止すべきかの組織的判断基準を理解する。</p></div>
          </div>
          <div class="group p-6 bg-white border border-slate-100 rounded-3xl shadow-sm hover:shadow-orange-50 transition-all duration-500 flex items-start gap-6">
            <div class="w-14 h-14 bg-orange-600 text-white rounded-2xl flex items-center justify-center text-xl font-black shrink-0 shadow-lg group-hover:scale-110 transition-transform">2</div>
            <div><h4 class="text-xl font-black text-slate-900 mb-2">避難技術と安全確保の完遂</h4><p class="text-slate-500 leading-relaxed font-medium">地震（シェイクアウト）、水害（垂直・水平避難）、火災（初期消火・通報）の具体的行動手順をマスターする。</p></div>
          </div>
        </div>
      `,
      slides: {
        create: [
          { title: '非常災害対策：命と事業を止めない技術', order: 0, content: `<div class="flex flex-col items-center justify-center min-h-[300px] text-center space-y-12"><div class="relative"><div class="absolute inset-0 bg-orange-400 blur-3xl opacity-20 scale-150 animate-pulse"></div><div class="relative bg-white p-10 rounded-[3rem] shadow-2xl border border-slate-100 max-w-sm"><div class="bg-orange-600 text-white px-6 py-1.5 rounded-full text-[10px] font-black tracking-[0.3em] uppercase inline-block mb-6">Crisis Management</div><h2 class="text-3xl font-black text-slate-900 leading-tight mb-4">非常災害時の対応<br/>〜BCPの基本と実践〜</h2></div></div><div class="flex items-center gap-4 text-slate-400 font-black text-[10px] tracking-widest"><span class="h-px w-8 bg-slate-200"></span>CARE LEARNING SYSTEM<span class="h-px w-8 bg-slate-200"></span></div></div>` },
          { title: '2024年度 義務化の背景：なぜBCPか', order: 1, content: `<div class="space-y-8"><div class="inline-flex items-center gap-3 px-4 py-2 bg-orange-50 text-orange-600 rounded-full text-xs font-black ring-1 ring-orange-100"><span class="w-2 h-2 bg-orange-600 rounded-full animate-ping"></span>LEGAL MANDATE</div><h4 class="text-2xl font-black text-slate-900 leading-tight">「書類」ではなく<br/><span class="text-orange-600 decoration-4 underline underline-offset-8">「命を救う仕組み」</span>です</h4><div class="grid grid-cols-1 sm:grid-cols-2 gap-4"><div class="p-6 bg-white border-2 border-slate-50 rounded-[2rem] shadow-sm"><p class="text-sm font-black text-slate-900 mb-2">未策定時の減算リスク</p><p class="text-[11px] text-slate-500 font-medium">施設系サービスでは基本報酬の3%減算。組織的対応が欠かせません。</p></div><div class="p-6 bg-white border-2 border-slate-50 rounded-[2rem] shadow-sm"><p class="text-sm font-black text-slate-900 mb-2">研修と訓練の義務</p><p class="text-[11px] text-slate-500 font-medium">計画を作るだけでなく、全職員が「自分の役割」を知ることが要件です。</p></div></div></div>` },
          { title: '災害時の「3大ピンチ」を想定する', order: 2, content: `<div class="space-y-8"><div class="flex flex-col items-center text-center"><div class="bg-slate-100 px-4 py-1 rounded-full text-[10px] font-black text-slate-500 tracking-widest uppercase mb-4">Crisis Analysis</div><h4 class="text-xl font-black text-slate-900 text-center leading-relaxed">これらが「同時」に起きた時、どう動くか</h4></div><div class="relative grid grid-cols-3 gap-px bg-slate-200 p-px rounded-[2rem] overflow-hidden border border-slate-200 shadow-2xl"><div class="p-6 bg-white text-center space-y-3"><div class="w-10 h-10 bg-orange-50 text-orange-600 rounded-full flex items-center justify-center font-black mx-auto">A</div><p class="text-xs font-black text-slate-900">インフラ停止</p><p class="text-[9px] text-slate-400 leading-tight">停電・断水・通信断絶。情報が集まらない恐怖</p></div><div class="p-6 bg-white text-center space-y-3"><div class="w-10 h-10 bg-orange-50 text-orange-600 rounded-full flex items-center justify-center font-black mx-auto">B</div><p class="text-xs font-black text-slate-900">人員不足</p><p class="text-[9px] text-slate-400 leading-tight">スタッフ自身が被災。通常の半分以下の人数でのケア</p></div><div class="p-6 bg-white text-center space-y-3"><div class="w-10 h-10 bg-orange-50 text-orange-600 rounded-full flex items-center justify-center font-black mx-auto">C</div><p class="text-xs font-black text-slate-900">物品の枯渇</p><p class="text-[9px] text-slate-400 leading-tight">おむつ、食料、燃料の不足。物流が止まった状態</p></div></div></div>` },
          { title: '避難判断の基準：垂直か、水平か', order: 3, content: `<div class="space-y-8"><div class="p-8 bg-blue-50 rounded-[2.5rem] border-2 border-blue-100 border-dashed relative text-center"><h4 class="text-2xl font-black text-blue-900 mb-4">無理な移動が事故を招く</h4><p class="text-[11px] text-blue-800 italic font-medium">「外へ逃げる」だけが避難ではありません。状況に応じた最善を選択します。</p></div><div class="bg-white p-8 rounded-[2rem] border border-slate-100 shadow-xl"><div class="grid grid-cols-2 gap-4"><div class="p-4 bg-slate-50 rounded-2xl"><p class="text-[10px] font-black text-slate-900 mb-1">水平避難（屋外へ）</p><p class="text-[9px] text-slate-500 leading-tight">火災発生時、地滑りリスクがある時、建物の倒壊リスクがある時。安全な広場等へ。</p></div><div class="p-4 bg-slate-50 rounded-2xl"><p class="text-[10px] font-black text-slate-900 mb-1">垂直避難（上階へ）</p><p class="text-[9px] text-slate-500 leading-tight">水害発生時、津波の危険がある時。2階以上の浸水リスクのない安全な場所へ移動。</p></div></div></div></div>` },
          { title: '業務のトリアージ：ケアの優先順位', order: 4, content: `<div class="space-y-6"><div class="bg-slate-900 text-white p-10 rounded-[2.5rem] shadow-2xl relative overflow-hidden"><h4 class="text-xs font-black tracking-[0.3em] uppercase opacity-50 mb-6">Prioritization</h4><p class="text-sm text-orange-400 font-black mb-4">「全部やる」は不可能です。生命維持に特化します</p><div class="space-y-4 text-lg font-black text-left"><div class="flex items-center gap-4"><span class="w-8 h-8 bg-white/10 rounded-lg flex items-center justify-center text-xs">01</span><p>最優先：食事（水分補給）、排泄、投薬、安否確認</p></div><div class="flex items-center gap-4"><span class="w-8 h-8 bg-white/10 rounded-lg flex items-center justify-center text-xs">02</span><p>休止：レクリエーション、リハビリ、定期入浴、清掃</p></div></div><p class="text-[10px] text-slate-500 mt-6 leading-relaxed">何をやめるかをあらかじめ決めておくことが、現場のパニックを防ぎます。</p></div></div>` },
          { title: '地震発生！その瞬間の初動行動', order: 5, content: `<div class="space-y-8"><div class="flex flex-col items-center"><h4 class="text-xl font-black text-slate-900 text-center leading-relaxed">自分と利用者の身を守る「3ステップ」</h4></div><div class="p-8 bg-white border-2 border-slate-100 rounded-[2.5rem] shadow-sm"><div class="grid grid-cols-3 gap-2 text-center text-[10px] font-black uppercase text-orange-600"><p>1. DROP!</p><p>2. COVER!</p><p>3. HOLD ON!</p></div><div class="grid grid-cols-3 gap-2 mt-4 text-center text-xs text-slate-700 font-bold"><p>まず低く（転倒防止）</p><p>頭を守り（落下物から）</p><p>揺れが収まるまで待つ</p></div></div><div class="p-6 bg-orange-50 rounded-2xl text-[10px] font-medium leading-relaxed">※介護現場では、利用者の車椅子のブレーキをかけ、頭部をクッション等で保護する「介助者としてのシェイクアウト」も同時に行います。</div></div>` },
          { title: 'シミュレーション：深夜の緊急事態', order: 6, content: `<div class="space-y-6"><div class="p-8 bg-orange-50 border-2 border-orange-100 rounded-[2.5rem] text-center"><p class="text-orange-900 text-lg font-black leading-relaxed">深夜2時、大きな地震が発生。全館停電し、複数の利用者が悲鳴をあげています。スタッフはあなた一人です。どうしますか？</p></div><div class="grid grid-cols-1 gap-4"><div class="p-6 bg-white border border-slate-100 rounded-2xl shadow-sm flex items-center gap-4 opacity-60"><span class="w-10 h-10 bg-slate-100 text-slate-400 rounded-xl flex items-center justify-center font-black">×</span><p class="text-xs font-bold italic">真っ先に火元を確認しに厨房へ走り、その後安否確認をする</p></div><div class="p-6 bg-white border border-emerald-100 rounded-2xl shadow-xl ring-2 ring-emerald-50 flex items-center gap-4"><span class="w-10 h-10 bg-emerald-600 text-white rounded-xl flex items-center justify-center font-black shadow-lg">○</span><p class="text-xs font-black text-slate-900 font-bold">まず自身の安全を確保（ライト点灯）。大声で呼びかけ利用者を落ち着かせ、部屋を回って安否を確認する。BCPの連絡網に従い、法人の他拠点や管理者に即報告する。</p></div></div></div>` },
          { title: '災害後の生活維持：二次被害を防ぐ', order: 7, content: `<div class="space-y-8"><div class="p-10 bg-emerald-50 rounded-[3rem] border border-emerald-100 flex flex-col items-center text-center space-y-6"><div class="w-20 h-20 bg-white rounded-[2rem] shadow-xl flex items-center justify-center text-emerald-600 font-black text-2xl">Health</div><h4 class="text-2xl font-black text-emerald-900">「エコノミークラス症候群」に注意</h4><p class="text-slate-600 font-medium leading-relaxed">避難生活では、慣れない環境での運動不足や脱水により血栓ができやすくなります。定期的な水分補給の促しと、座ったままできる足の指の運動をチームで励行しましょう。</p></div></div>` },
          { title: 'まとめ：日頃の訓練が命を分ける', order: 8, content: `<div class="flex flex-col items-center justify-center min-h-[450px] text-center space-y-10"><div class="w-24 h-24 bg-orange-600 rounded-[2.5rem] flex items-center justify-center shadow-2xl shadow-orange-200 rotate-3"><svg class="w-12 h-12 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5" /></svg></div><h3 class="text-3xl font-black text-slate-900 leading-tight">BCPは、利用者の人生を<br/>守り抜くための約束です。</h3><p class="text-slate-500 font-medium text-lg max-w-sm mx-auto leading-relaxed">今日の知識を、明日の避難訓練に繋げましょう。備えだけが、パニックを「救命の技術」に変えます。</p><div class="pt-10 border-t border-slate-100 w-full"><p class="text-slate-400 font-black text-xs uppercase tracking-[0.3em]">End of Session</p></div></div>` }
        ]
      },
      questions: {
        create: [
          { text: '2024年度より、全ての介護施設において策定と職員への周知が「義務化」された計画はどれか。', explanation: 'BCP（業務継続計画）と呼ばれます。感染症や自然災害が発生しても、重要な業務を継続するための計画です。未策定の場合は基本報酬の減算対象となります。', order: 1, choices: { create: [{ text: 'BCP（業務継続計画）', isCorrect: true }, { text: '中期経営計画', isCorrect: false }, { text: '職員旅行計画', isCorrect: false }, { text: 'ボランティア活用計画', isCorrect: false }] } },
          { text: '地震発生時の身を守る基本行動「シェイクアウト」の正しい3つの手順はどれか。', explanation: '「まず低く(Drop)」「頭を守り(Cover)」「揺れが収まるまで待つ(Hold on)」が基本です。', order: 2, choices: { create: [{ text: 'まず低く・頭を守り・動かない', isCorrect: true }, { text: 'すぐに立ち上がり・窓を開け・外へ走る', isCorrect: false }, { text: '火元へ走り・消火器を持ち・叫ぶ', isCorrect: false }] } },
          { text: '災害等による人員不足時に、BCPに基づいて優先的に継続すべき業務はどれか。', explanation: '生命維持に不可欠な食事・水分補給、排泄介助、必要な投薬などを最優先し、レクリエーション等は一時休止します。', order: 3, choices: { create: [{ text: '生命維持に関わる食事・排泄・投薬', isCorrect: true }, { text: '定期的なレクリエーション', isCorrect: false }, { text: '居室のワックス掛けや大掃除', isCorrect: false }] } },
          { text: '水害や津波の危険がある際、建物の2階以上の安全な場所へ避難することを何というか。', explanation: '上階へ移動することを「垂直避難」、屋外の離れた安全な場所へ移動することを「水平避難」と呼びます。', order: 4, choices: { create: [{ text: '垂直避難', isCorrect: true }, { text: '水平避難', isCorrect: false }, { text: '平行避難', isCorrect: false }] } },
          { text: '避難後の生活において、脱水や運動不足から生じる「エコノミークラス症候群」を防ぐために重要なことは？', explanation: 'こまめな水分補給と、足首を回すなどの適度な運動が血栓の予防に不可欠です。', order: 5, choices: { create: [{ text: 'こまめな水分補給と足の運動', isCorrect: true }, { text: '食事を極限まで減らすこと', isCorrect: false }, { text: '一日中横になって動かないこと', isCorrect: false }] } }
        ]
      }
    }
  })
}
