import { PrismaClient } from '@prisma/client'

export async function seedRestraint(prisma: PrismaClient) {
  const slug = 'restraint'
  const courseData = {
    slug,
    title: '身体拘束廃止・防止研修（2024年度）',
    description: '〜身体を縛らず、心を縛らないケアを目指して〜',
    introduction: `
        <div class="flex flex-col items-center justify-center text-center space-y-2 pt-2 px-4 text-balance">
          <div class="flex items-center gap-4">
            <span class="h-px w-8 lg:w-12 bg-red-700 rounded-full"></span>
            <p class="text-red-800 font-black tracking-widest text-lg lg:text-xl uppercase">身体拘束廃止研修</p>
            <span class="h-px w-8 lg:w-12 bg-red-700 rounded-full"></span>
          </div>
          <h2 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight">「安全のため」という言葉が、<br/>誰かの自由を奪っていませんか？</h2>
          <div class="max-w-2xl space-y-2 text-slate-800 text-sm lg:text-base leading-relaxed font-bold px-4 text-center">
            <p>身体拘束は、単なる「動作の制限」ではありません。それは、その方の「尊厳」と「生きる意欲」を根底から壊す行為です。</p>
            <div class="p-3 lg:p-4 bg-red-50 rounded-[1.5rem] lg:rounded-[2rem] border-2 border-red-200 shadow-inner relative overflow-hidden text-[10px] lg:text-xs text-left">
              <div class="absolute top-0 right-0 w-16 h-16 lg:w-20 lg:h-20 bg-red-100/50 rounded-bl-full"></div>
              <p class="relative z-10 italic text-red-900 font-black text-xs lg:text-sm leading-relaxed">一度始めた拘束は、麻薬のように日常化します。2024年度の運営基準では、拘束廃止への取り組みがさらに厳格化されました。縛らないケアは、知識とチーム力で必ず実現できます。</p>
            </div>
            <p class="text-[10px] lg:text-sm text-slate-900 font-black text-center mt-2">この研修は、拘束の連鎖を断ち切り、本当の安心を創るためのものです。</p>
          </div>
        </div>
      `,
    learningObjectives: `
        <div class="flex flex-col items-center justify-center text-center space-y-3 pt-2 px-4 w-full text-balance">
          <div class="bg-red-700 text-white px-6 py-1.5 rounded-full text-[10px] font-black tracking-[0.3em] uppercase mb-1 shadow-lg shadow-red-200">Learning Objectives</div>
          <div class="grid grid-cols-1 gap-2 w-full max-w-2xl">
            <div class="group p-3 lg:p-4 bg-white border-2 border-slate-200 rounded-[1.5rem] lg:rounded-[2rem] shadow-sm flex items-center gap-4 lg:gap-6 hover:shadow-xl hover:border-red-400 transition-all duration-500 text-center lg:text-left">
              <div class="w-10 h-10 lg:w-12 lg:h-12 bg-red-700 text-white rounded-xl flex items-center justify-center text-base lg:text-lg font-black shrink-0 shadow-lg shadow-red-200">1</div>
              <div class="text-left">
                <h4 class="text-sm lg:text-base font-black text-slate-900">拘束の「弊害」を深く知る</h4>
                <p class="text-slate-800 text-[10px] lg:text-xs font-bold leading-tight">ADL低下、認知症の悪化、精神特屈辱感など、拘束が招く残酷な現実を理解する。</p>
              </div>
            </div>
            <div class="group p-3 lg:p-4 bg-white border-2 border-slate-200 rounded-[1.5rem] lg:rounded-[2rem] shadow-sm flex items-center gap-4 lg:gap-6 hover:shadow-xl hover:border-red-400 transition-all duration-500 text-center lg:text-left">
              <div class="w-10 h-10 lg:w-12 lg:h-12 bg-red-700 text-white rounded-xl flex items-center justify-center text-base lg:text-lg font-black shrink-0 shadow-lg shadow-red-200">2</div>
              <div class="text-left">
                <h4 class="text-sm lg:text-base font-black text-slate-900">「やむを得ない3要件」の厳格化</h4>
                <p class="text-slate-800 text-[10px] lg:text-xs font-bold leading-tight">例外的に行う場合の3要件と、記録・手続きの法的義務を正確に習得する。</p>
              </div>
            </div>
            <div class="group p-3 lg:p-4 bg-white border-2 border-slate-200 rounded-[1.5rem] lg:rounded-[2rem] shadow-sm flex items-center gap-4 lg:gap-6 hover:shadow-xl hover:border-red-400 transition-all duration-500 text-center lg:text-left">
              <div class="w-10 h-10 lg:w-12 lg:h-12 bg-red-700 text-white rounded-xl flex items-center justify-center text-base lg:text-lg font-black shrink-0 shadow-lg shadow-red-200">3</div>
              <div class="text-left">
                <h4 class="text-sm lg:text-base font-black text-slate-900">代替案を導き出すチーム力</h4>
                <p class="text-slate-800 text-[10px] lg:text-xs font-bold leading-tight">環境整備や個別性の理解を通じ、拘束に頼らない具体的なケアを提案できる。</p>
              </div>
            </div>
          </div>
        </div>
      `,
    videoUrl: null,
    badgeLabel: '拘束廃止',
    badgeIcon: 'UserMinus',
  }

  const slidesData = [
    { title: "身体拘束廃止研修", order: 0, content: `<div class="flex flex-col items-center justify-center text-center space-y-4 w-full h-full text-balance"><div class="relative w-full max-w-4xl px-4"><div class="absolute inset-0 bg-red-400 blur-3xl opacity-20 scale-150 animate-pulse text-center"></div><div class="relative bg-transparent lg:bg-white p-0 lg:p-12 rounded-none lg:rounded-[3.5rem] shadow-none lg:shadow-2xl border-none lg:border lg:border-slate-200 w-full mx-auto text-center"><div class="bg-red-700 text-white px-4 lg:px-6 py-1 lg:py-1.5 rounded-full text-[8px] lg:text-[10px] font-black tracking-[0.3em] uppercase inline-block mb-6 lg:mb-8 shadow-sm">法定研修 2024</div><h2 class="text-3xl lg:text-5xl font-black text-slate-900 leading-tight mb-4 text-center text-balance px-4">身体拘束廃止・防止研修</h2><p class="text-red-700 text-sm lg:text-2xl font-black mt-2 whitespace-nowrap text-center">〜尊厳を守り、自由を支える〜</p></div></div><div class="flex items-center justify-center gap-4 text-slate-500 font-black text-[8px] lg:text-[10px] tracking-widest pt-4 text-center w-full"><span class="h-px w-6 lg:w-8 bg-slate-300"></span>CARE LEARNING SYSTEM<span class="h-px w-6 lg:w-8 bg-slate-300"></span></div></div>` },
    { title: "身体拘束とは何か？", order: 1, content: `<div class="space-y-4 lg:space-y-6 text-center px-4 h-full flex flex-col justify-center text-balance text-center"><div class="inline-flex items-center gap-3 px-4 py-1.5 bg-red-100 text-red-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-red-200 mb-2 uppercase tracking-widest mx-auto text-center">定義の再確認</div><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4 text-center w-full">自由を奪う全ての行為</h4><div class="p-0 lg:p-8 bg-transparent lg:bg-red-50 border-none lg:border-2 lg:border-red-100 shadow-none lg:shadow-xl rounded-none lg:rounded-[3rem] text-center lg:text-left text-sm lg:text-lg font-bold text-red-800 space-y-4 max-w-4xl mx-auto px-4 text-center"><p class="font-black text-center">身体拘束とは、衣類または綿入り帯等を用いて、一時的に当該入所者の身体を拘束し、またはその運動を抑制する行動制限のこと。単なる「紐で縛る」だけではありません。</p></div></div>` },
    { title: "2024年度 運営基準の厳格化", order: 2, content: `<div class="space-y-4 lg:space-y-6 text-center px-4 h-full flex flex-col justify-center text-balance"><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight mb-2 px-4 text-center w-full text-balance">組織的な取り組みが「義務」に</h4><div class="grid grid-cols-1 lg:grid-cols-2 gap-4 max-w-4xl mx-auto w-full"><div class="p-6 lg:p-8 bg-white border-2 border-slate-200 rounded-2xl shadow-xl flex flex-col items-center gap-2 lg:gap-4 text-center"><p class="font-black text-lg lg:text-xl text-red-800">指針の策定と研修</p><p class="text-xs lg:text-sm font-bold text-slate-700 leading-relaxed text-center">身体拘束廃止の指針を定め、全職員への年2回以上の研修実施が完全義務化されました。</p></div><div class="p-6 lg:p-8 bg-white border-2 border-slate-200 rounded-2xl shadow-xl flex flex-col items-center gap-2 lg:gap-4 text-center"><p class="font-black text-lg lg:text-xl text-red-800">委員会と記録</p><p class="text-xs lg:text-sm font-bold text-slate-700 leading-relaxed text-center">「身体拘束適正化委員会」の設置と、やむを得ず行う場合の詳細な記録が厳格に求められます。</p></div></div></div>` },
    { title: "拘束の具体例1：ベッド・車椅子", order: 3, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left text-balance text-center"><div class="space-y-4"><h4 class="text-2xl lg:text-4xl font-black text-red-900 flex items-center gap-4 lg:gap-6 justify-center"><span class="w-2 h-8 lg:w-3 lg:h-12 bg-red-700 rounded-full"></span>物理的な制限</h4></div><ul class="space-y-4 lg:space-y-6 text-lg lg:text-3xl font-black text-slate-800 pl-0 leading-tight text-center"><li>・ベッドを4枚の柵で囲う</li><li>・車椅子にY字ベルトや腰ベルトを使用</li><li>・車椅子のテーブルをロックして立てないようにする</li></ul></div>` },
    { title: "拘束の具体例2：衣類・手指", order: 4, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left text-balance text-center"><div class="space-y-4"><h4 class="text-2xl lg:text-4xl font-black text-red-900 flex items-center gap-4 lg:gap-6 justify-center"><span class="w-2 h-8 lg:w-3 lg:h-12 bg-red-700 rounded-full"></span>尊厳を損なう制限</h4></div><ul class="space-y-4 lg:space-y-6 text-lg lg:text-3xl font-black text-slate-800 pl-0 leading-tight text-center"><li>・つなぎ服（拘束服）を着せる</li><li>・手指の動きを制限する「ミトン」の使用</li><li>・点滴やチューブを抜かないよう手を縛る</li></ul></div>` },
    { title: "拘束の具体例3：環境・薬物", order: 5, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left text-balance text-center"><div class="space-y-4"><h4 class="text-2xl lg:text-4xl font-black text-red-900 flex items-center gap-4 lg:gap-6 justify-center"><span class="w-2 h-8 lg:w-3 lg:h-12 bg-red-700 rounded-full"></span>見えない拘束</h4></div><ul class="space-y-4 lg:space-y-6 text-lg lg:text-3xl font-black text-slate-800 pl-0 leading-tight text-center"><li>・居室の扉に鍵をかけ、閉じ込める</li><li>・立ち上がれない低い椅子に座らせる</li><li>・抗精神病薬を過剰に投与し、活動を抑える</li></ul></div>` },
    { title: "拘束の弊害1：身体的悪影響", order: 6, content: `<div class="flex flex-col items-center text-center space-y-4 lg:space-y-6 px-4 h-full justify-center text-balance text-center text-center"><h4 class="text-xl lg:text-2xl font-black text-red-900 leading-tight text-center w-full">寝かせきりが寝たきりを作る</h4><div class="grid grid-cols-1 lg:grid-cols-2 gap-3 font-black text-sm lg:text-base w-full max-w-4xl text-center"><div class="flex flex-col gap-3"><span class="px-6 py-2.5 bg-red-50 border-2 border-red-200 rounded-2xl text-red-900 shadow-sm text-center font-black">筋力・骨密度の急激な低下</span><span class="px-6 py-2.5 bg-red-50 border-2 border-red-200 rounded-2xl text-red-900 shadow-sm text-center text-balance font-black">圧迫による褥瘡（床ずれ）</span></div><div class="flex flex-col gap-3"><span class="px-6 py-2.5 bg-red-50 border-2 border-red-200 rounded-2xl text-red-900 shadow-sm text-center font-black">関節の拘縮（固まる）</span><span class="px-6 py-2.5 bg-red-50 border-2 border-red-200 rounded-2xl text-red-900 shadow-sm text-center text-balance font-black">心肺機能の低下・食欲不振</span></div></div></div>` },
    { title: "拘束の弊害2：精神的悪影響", order: 7, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-6 lg:space-y-8 px-4 w-full text-balance"><div class="inline-flex items-center gap-3 px-4 py-1.5 bg-red-100 text-red-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-red-200 mb-2 mx-auto text-center uppercase tracking-widest text-center">心の傷</div><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4 text-center w-full text-center">生きる意欲を奪う</h4><div class="p-6 lg:p-10 bg-white border-[4px] lg:border-[6px] border-red-600 rounded-[2rem] lg:rounded-[3rem] shadow-2xl max-w-3xl mx-auto w-full text-center text-center text-center"><p class="text-lg lg:text-2xl font-black text-red-900 leading-relaxed italic text-balance text-center text-center">「縛られる」ことの屈辱感。それは怒り、悲しみ、絶望へと変わり、認知症の症状をさらに悪化させます。人間としての尊厳が壊される瞬間です。</p></div></div>` },
    { title: "拘束の弊害3：社会的悪影響", order: 8, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-4 lg:space-y-6 px-4 w-full text-balance"><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight">施設全体の質の低下</h4><div class="p-6 bg-red-50 border-2 border-red-100 rounded-3xl text-left max-w-3xl space-y-4 shadow-sm mx-auto text-center text-center text-center text-balance"><p class="text-sm lg:text-lg font-black text-slate-800 leading-relaxed text-center text-balance text-center">拘束が当たり前になると、職員の思考が停止し、観察力が低下します。「事故＝拘束」という安易な解決策は、ケアの専門性を失わせ、家族や地域からの信頼を根底から壊します。</p></div></div>` },
    { title: "やむを得ない3要件1：切迫性", order: 9, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left text-balance text-center"><h4 class="text-xl lg:text-2xl font-black text-red-900 text-center w-full font-black">命の危険が「目前」にあるか</h4><ul class="space-y-4 lg:space-y-6 text-sm lg:text-xl font-black text-slate-800 pl-0 leading-tight text-center w-full"><li>・今、この瞬間に自傷・他害の恐れがある</li><li>・生命維持に必要な医療処置を抜く危険が極めて高い</li><li>・「将来転ぶかもしれない」という予測は含まない</li></ul><p class="text-red-700 font-black text-center w-full mt-4 text-sm lg:text-lg text-center">時間的・客観的な緊急性が求められます</p></div>` },
    { title: "やむを得ない3要件2：非代替性", order: 10, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left text-balance text-center"><h4 class="text-xl lg:text-2xl font-black text-red-900 text-center w-full font-black">他に手段はないか</h4><ul class="space-y-4 lg:space-y-6 text-sm lg:text-xl font-black text-slate-800 pl-0 leading-tight text-center w-full text-center text-center"><li>・センサーや見守りの強化を試みたか</li><li>・居室のレイアウトや用具の変更を検討したか</li><li>・他の職員による付き添いや関わりの工夫をしたか</li></ul><p class="text-red-700 font-black text-center w-full mt-4 text-sm lg:text-lg text-center text-center">「手間がかかるから」は理由になりません</p></div>` },
    { title: "やむを得ない3要け3：一時性", order: 11, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left text-balance text-center"><h4 class="text-xl lg:text-2xl font-black text-red-900 text-center w-full font-black text-center text-center">最短時間で解除する</h4><ul class="space-y-4 lg:space-y-6 text-sm lg:text-xl font-black text-slate-800 pl-0 leading-tight text-center w-full text-center text-center"><li>・目的の状態が解消されたら即座に解除する</li><li>・「夜間だけ」であっても、漫然と継続しない</li><li>・常に解除に向けた具体的な計画を持っているか</li></ul><p class="text-red-700 font-black text-center w-full mt-4 text-sm lg:text-lg text-center text-center">一時的な処置であることを忘れてはいけません</p></div>` },
    { title: "3要件を満たした際の手続き義務", order: 12, content: `<div class="flex flex-col items-center justify-center h-full space-y-6 lg:space-y-8 px-4 w-full text-balance text-center"><h4 class="text-xl lg:text-2xl font-black text-red-900 text-center w-full mb-2 px-4 animate-pulse">「記録」がなければ不正です</h4><div class="grid grid-cols-1 gap-3 lg:gap-4 w-full max-w-2xl text-center"><div class="flex items-center gap-4 bg-white p-3 rounded-2xl border-2 border-red-100 shadow-sm font-black justify-center lg:justify-start text-sm lg:text-base text-center"><span class="w-10 h-10 bg-red-600 text-white rounded-full flex items-center justify-center shrink-0 font-black">1</span>理由、時間、態様、心身の状況を詳細に記録</div><div class="flex items-center gap-4 bg-white p-3 rounded-2xl border-2 border-red-100 shadow-sm font-black justify-center lg:justify-start text-sm lg:text-base text-center"><span class="w-10 h-10 bg-red-600 text-white rounded-full flex items-center justify-center shrink-0 font-black">2</span>本人・家族へ十分な説明と同意（書面）</div><div class="flex items-center gap-4 bg-white p-3 rounded-2xl border-2 border-red-100 shadow-sm font-black justify-center lg:justify-start text-sm lg:text-base text-center"><span class="w-10 h-10 bg-red-600 text-white rounded-full flex items-center justify-center shrink-0 font-black">3</span>施設内委員会で、継続の必要性を常に検討</div></div></div>` },
    { title: "拘束をしないための代替案：環境", order: 13, content: `<div class="flex flex-col items-center text-center space-y-4 lg:space-y-6 px-4 h-full justify-center text-balance text-center text-center"><div class="p-4 lg:p-6 bg-white rounded-[2rem] lg:rounded-[3.5rem] w-full max-w-2xl shadow-xl border-2 border-slate-200 shrink-0 text-center"><h4 class="text-xl lg:text-2xl font-black mb-2 text-slate-900 text-center">縛る前に「環境」を変える</h4></div><div class="grid grid-cols-1 lg:grid-cols-2 gap-3 font-black text-[10px] lg:text-sm w-full max-w-5xl"><div class="p-3 bg-red-50 border-2 border-red-200 rounded-2xl text-left"><p class="text-red-900 mb-1 font-black">低床ベッド・マット</p><p class="text-slate-600 text-[10px]">転落の衝撃を最小限にし、柵による拘束を外す。</p></div><div class="p-3 bg-red-50 border-2 border-red-200 rounded-2xl text-left"><p class="text-red-900 mb-1 font-black">離床センサーの活用</p><p class="text-slate-600 text-[10px]">動き出しをいち早く察知し、間に合う見守りを行う。</p></div><div class="p-3 bg-red-50 border-2 border-red-200 rounded-2xl text-left"><p class="text-red-900 mb-1 font-black">椅子の見直し</p><p class="text-slate-600 text-[10px]">立ち上がりやすく、かつ安定感のある椅子を選ぶ。</p></div><div class="p-3 bg-red-50 border-2 border-red-200 rounded-2xl text-left"><p class="text-red-900 mb-1 font-black">手すりの適切な配置</p><p class="text-slate-600 text-[10px]">自力移動をサポートし、ふらつきを防止する動線作り。</p></div></div></div>` },
    { title: "拘束をしないための代替案：ケア", order: 14, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left text-balance text-center"><div class="space-y-4"><h4 class="text-2xl lg:text-4xl font-black text-red-900 flex items-center gap-4 lg:gap-6 justify-center"><span class="w-2 h-8 lg:w-3 lg:h-12 bg-red-700 rounded-full"></span>心にアプローチする</h4></div><ul class="space-y-4 lg:space-y-6 text-lg lg:text-3xl font-black text-slate-800 pl-0 leading-tight text-center"><li>・「なぜ動きたいか」の背景を探る（排泄、空腹など）</li><li>・こまめな声かけと、安心感を与える関わり</li><li>・日中の活動量を増やし、夜間の良眠を促す</li></ul></div>` },
    { title: "身体拘束適正化検討委員会の役割", order: 15, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-4 lg:space-y-6 px-4 w-full text-balance text-center text-balance text-center text-center"><h4 class="text-xl lg:text-2xl font-black text-red-900 text-center w-full px-4 text-center text-center">現場を孤立させない仕組み</h4><div class="p-6 bg-white border-2 border-red-100 rounded-3xl text-left max-w-3xl space-y-4 shadow-sm mx-auto text-center text-center text-center text-center text-balance text-center text-center text-center"><p class="text-sm lg:text-lg font-black text-slate-800 leading-relaxed text-center text-balance text-center text-center">委員会は「現場のミスを責める場」ではありません。個別の困難事例に対し、多職種の視点で知恵を出し合い、拘束を外すための「具体的なケアプラン」を立案・サポートする場です。</p></div></div>` },
    { title: "「ドラッグロック」：薬による拘束", order: 16, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-6 lg:space-y-8 px-4 w-full text-balance text-center text-center text-center"><div class="inline-flex items-center gap-3 px-4 py-1.5 bg-red-100 text-red-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-red-200 mb-2 mx-auto text-center uppercase tracking-widest text-center text-center">薬物拘束</div><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4 text-center w-full text-center text-center">静かにさせるための投薬</h4><div class="p-6 lg:p-10 bg-white border-[4px] lg:border-[6px] border-red-600 rounded-[2rem] lg:rounded-[3rem] shadow-2xl max-w-3xl mx-auto w-full text-center text-center text-center text-center"><p class="text-lg lg:text-2xl font-black text-red-900 leading-relaxed italic text-balance text-center text-center text-center">本来の治療目的を超え、職員の管理のしやすさのために抗精神病薬等を用いて、活動を抑制することも重大な身体拘束の一つです。</p></div></div>` },
    { title: "認知症ケアと身体拘束の関係", order: 17, content: `<div class="flex flex-col items-center justify-center h-full text-left space-y-4 lg:space-y-6 px-6 lg:px-12 w-full text-balance text-center text-center text-center text-center text-center"><h4 class="text-xl lg:text-2xl font-black text-red-700 text-center mb-2 uppercase tracking-widest w-full px-4 text-center text-center text-center text-center text-center">不安が行動を突き動かす</h4><div class="space-y-6 lg:space-y-8 font-black text-slate-900 max-w-4xl mx-auto w-full text-center text-center text-center"><div><p class="text-lg lg:text-2xl text-red-600 mb-1 flex items-center gap-3 justify-center text-center font-black"><span>●</span> 理解：</p><p class="text-sm lg:text-lg text-slate-600 font-bold text-center">「歩き回る」のは「何かを探している」サイン。</p></div><div><p class="text-lg lg:text-2xl text-red-600 mb-1 flex items-center gap-3 justify-center text-center font-black"><span>●</span> 共感：</p><p class="text-sm lg:text-lg text-slate-600 font-bold text-center text-balance">縛ることで生じる恐怖が、さらなる混乱を招く。</p></div><div><p class="text-lg lg:text-2xl text-red-600 mb-1 flex items-center gap-3 justify-center text-center font-black"><span>●</span> 尊重：</p><p class="text-sm lg:text-lg text-slate-600 font-bold text-center text-balance">自由な動きを尊重した上での、安全策を模索する。</p></div></div></div>` },
    { title: "CASE STUDY 1：転倒リスクと4枚柵", order: 18, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-4 lg:space-y-6 px-4 w-full text-balance text-center text-center text-center text-center text-center"><div class="inline-flex items-center gap-3 px-4 py-1.5 bg-rose-50 text-rose-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-rose-200 mb-2 mx-auto text-center uppercase tracking-widest text-center text-center">事例 1</div><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4 text-center w-full text-center text-center">夜間のベッド転落が不安</h4><div class="p-6 lg:p-8 bg-white border-2 border-slate-100 rounded-[2rem] lg:rounded-[3rem] shadow-xl max-w-4xl text-left space-y-4 w-full text-center text-center text-center"><p class="text-sm lg:text-lg font-bold text-slate-800 leading-relaxed text-balance px-4 text-center text-center text-center">H様は夜間に起き出して転倒し、骨折した経験があります。再発を防ぐため、ベッドを4枚の柵で完全に囲ってもいいでしょうか？</p><div class="h-px bg-slate-100 text-center text-center"></div><p class="text-xs lg:text-base font-black text-red-700 italic text-center px-4 text-balance text-center w-full text-center text-center">柵を乗り越えようとした際の、<br class="lg:hidden" />さらなる重大事故のリスクを考えましょう。</p></div></div>` },
    { title: "CASE STUDY 2：ミトン使用の是非", order: 19, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-4 lg:space-y-6 px-4 w-full text-balance text-center text-center text-center text-center text-center text-center"><div class="inline-flex items-center gap-3 px-4 py-1.5 bg-rose-50 text-rose-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-rose-200 mb-2 mx-auto text-center uppercase tracking-widest text-center text-center text-center">事例 2</div><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4 text-center w-full text-center text-center text-center">胃瘻チューブを抜いてしまう</h4><div class="p-6 lg:p-8 bg-white border-2 border-slate-100 rounded-[2rem] lg:rounded-[3rem] shadow-xl max-w-4xl text-left space-y-4 w-full text-center text-center text-center text-center"><p class="text-sm lg:text-lg font-bold text-slate-800 leading-relaxed text-balance px-4 text-center text-center text-center text-center text-balance">認知症のI様は、お腹の胃瘻チューブが気になり、何度も抜こうとします。再手術は本人の負担。ミトンをつけて手を制限しますか？</p><div class="h-px bg-slate-100 text-center text-center text-center"></div><p class="text-xs lg:text-base font-black text-red-700 italic text-center px-4 text-balance text-center w-full text-center text-center text-center text-center">「抜く」という行為の奥にある<br class="lg:hidden" />「不快感」や「違和感」を解消できませんか？</p></div></div>` },
    { title: "解決：身体拘束をしない具体策", order: 20, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-4 lg:space-y-6 px-4 w-full text-balance text-center text-center text-center text-center text-center text-center text-center"><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4 text-center w-full text-center text-center text-center text-center text-center text-center">プロとしての挑戦</h4><div class="p-6 lg:p-10 bg-red-50 border-2 border-red-100 rounded-[2.5rem] lg:rounded-[4rem] shadow-inner text-left max-w-4xl space-y-4 mx-auto text-center text-center text-center text-center text-center text-center text-center"><div class="grid grid-cols-1 gap-3 text-sm lg:text-base font-bold text-slate-800 text-center text-center text-center text-center text-center text-center text-center text-center"><div class="flex items-center gap-3 lg:gap-4 bg-white p-3 rounded-xl lg:rounded-2xl border border-red-100 shadow-sm text-center justify-center lg:justify-start text-center text-center text-center text-center text-center text-center text-center"><span class="w-6 h-6 lg:w-8 lg:h-8 bg-red-600 text-white rounded-full flex items-center justify-center text-[10px] lg:text-sm shrink-0 font-black">1</span>柵を減らし、ベッド横に衝撃吸収マットを敷く</div><div class="flex items-center gap-3 lg:gap-4 bg-white p-3 rounded-xl lg:rounded-2xl border border-red-100 shadow-sm text-center justify-center lg:justify-start text-center text-center text-center text-center text-center text-center text-center"><span class="w-6 h-6 lg:w-8 lg:h-8 bg-red-600 text-white rounded-full flex items-center justify-center text-[10px] lg:text-sm shrink-0 font-black">2</span>チューブが見えないよう衣類を工夫し、関心を逸らす</div><div class="flex items-center gap-3 lg:gap-4 bg-white p-3 rounded-xl lg:rounded-2xl border border-red-100 shadow-sm text-center justify-center lg:justify-start text-center text-center text-center text-center text-center text-center text-center"><span class="w-6 h-6 lg:w-8 lg:h-8 bg-red-600 text-white rounded-full flex items-center justify-center text-[10px] lg:text-sm shrink-0 font-black">3</span>「見守り」を「作業」ではなく「交流」へ変える</div></div></div></div>` },
    { title: "満足感：自由を支えるケアの喜び", order: 21, content: `<div class="space-y-6 lg:space-y-8 text-center flex flex-col items-center justify-center h-full px-4 w-full text-balance text-center text-balance text-center text-center text-center text-center text-center text-center"><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4 text-center w-full text-center text-center text-center text-center text-center text-center">プロフェッショナルの証</h4><div class="p-8 lg:p-10 bg-white border-[4px] lg:border-[6px] border-red-600 rounded-[2rem] lg:rounded-[3rem] shadow-2xl max-w-3xl mx-auto w-full text-center text-center text-center text-center text-center text-center text-center text-center"><p class="text-xl lg:text-2xl font-black text-red-900 leading-relaxed italic text-balance text-center text-center text-center text-center text-center text-center text-center text-center">拘束を外したことで、<br/>その方に笑顔が戻り、歩き出した。<br/>その瞬間に立ち会えることが、介護の醍醐味です。</p></div><p class="font-black text-sm lg:text-lg text-slate-800 mt-2 text-center w-full px-4 text-center text-center text-center text-center text-center text-center text-center">縛らない勇気が、最善のケアを創ります。</p></div>` },
    { title: "拘束廃止のプロセス：PDCA", order: 22, content: `<div class="flex flex-col items-center justify-center h-full text-left space-y-4 lg:space-y-6 px-6 lg:px-12 w-full text-balance text-center text-center text-center text-center text-center"><h4 class="text-xl lg:text-2xl font-black text-red-700 text-center mb-2 uppercase tracking-widest w-full px-4 text-center text-center text-center text-center text-center">止まらない改善</h4><div class="space-y-6 lg:space-y-8 font-black text-slate-900 max-w-4xl mx-auto w-full text-center text-center text-center"><div><p class="text-lg lg:text-2xl text-red-600 mb-1 flex items-center gap-3 justify-center text-center font-black"><span>●</span> Plan：</p><p class="text-sm lg:text-lg text-slate-600 font-bold text-center">全職種で拘束解除の目標を立てる。</p></div><div><p class="text-lg lg:text-2xl text-red-600 mb-1 flex items-center gap-3 justify-center text-center font-black"><span>●</span> Do：</p><p class="text-sm lg:text-lg text-slate-600 font-bold text-center text-balance">代替案を1週間試行し、状況を細かく観察。</p></div><div><p class="text-lg lg:text-2xl text-red-600 mb-1 flex items-center gap-3 justify-center text-center font-black"><span>●</span> Check：</p><p class="text-sm lg:text-lg text-slate-600 font-bold text-center text-balance">うまくいかない理由を「責めずに」共有。</p></div></div></div>` },
    { title: "まとめ：今日から変えられること", order: 23, content: `<div class="flex flex-col items-center text-center space-y-6 lg:space-y-10 w-full h-full justify-center text-slate-900 px-4 text-center text-balance text-center text-center text-center text-center text-center text-center text-center text-center"><div class="w-24 h-24 lg:w-28 h-28 bg-red-700 rounded-[2.5rem] lg:rounded-[3rem] flex items-center justify-center shadow-2xl rotate-3 transition-transform hover:rotate-0 duration-500 mx-auto text-center text-center text-center text-center text-center text-center text-center text-center"><svg class="w-12 h-12 lg:w-16 h-16 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" /></svg></div><h3 class="text-2xl lg:text-4xl font-black leading-tight text-center w-full text-balance text-center text-center text-center text-center text-center text-center text-center">身体を縛らず、心を縛らず。<br/>誇りあるケアを、今日から。</h3><div class="pt-8 lg:pt-10 border-t-2 border-slate-200 w-full max-w-md text-center mx-auto text-center text-center text-center text-center text-center text-center text-center text-center"><p class="text-slate-500 font-black text-[8px] lg:text-[10px] uppercase tracking-[0.5em]">研修修了</p></div></div>` },
    { title: "理解度テストのご案内", order: 24, content: `
        <div class="flex flex-col items-center text-center space-y-4 lg:space-y-6 w-full h-full justify-center px-4 text-center text-balance text-center text-center text-center text-center text-center text-center text-center text-center">
          <div class="bg-emerald-600 text-white px-6 py-1.5 rounded-full text-[8px] lg:text-[10px] font-black tracking-[0.3em] uppercase inline-block mb-4 lg:mb-2 shadow-lg px-4 text-center text-center text-center text-center text-center text-center">修了</div>
          <h2 class="text-2xl lg:text-4xl font-black text-slate-900 leading-tight mb-2 text-center w-full text-balance text-center text-center text-center text-center text-center text-center">講義セッション終了</h2>
          <p class="text-emerald-800 text-base lg:text-xl font-black leading-relaxed text-center w-full text-balance px-4 text-center text-center text-center text-center text-center text-center">大変お疲れ様でした。<br/>最後に理解度テスト（全10問）を行います。</p>
          <div class="p-4 lg:p-6 bg-red-50 rounded-2xl lg:rounded-3xl border-2 border-red-100 max-w-lg mx-auto mt-6 text-center text-center text-center text-center text-center text-center text-center">
            <p class="text-red-900 font-black text-sm lg:text-lg flex items-center justify-center gap-3 text-center text-center text-center text-center text-center text-center text-center">
              <span class="w-2 h-2 bg-red-700 rounded-full text-center"></span>    
              全問正解を目指しましょう！
              <span class="w-2 h-2 bg-red-700 rounded-full text-center"></span>    
            </p>
          </div>
        </div>
      ` }
  ]

  const questionsData = [
    { text: '身体拘束がもたらす弊害のうち、身体的な悪影響として正しいものはどれか？', explanation: '拘束により動かないことで筋力や骨密度が低下し、さらに寝たきりの状態を悪化させます。', order: 1, choices: { create: [{ text: '筋力低下や関節の拘縮（固まる）', isCorrect: true }, { text: '食欲が増進する', isCorrect: false }, { text: '認知機能が改善する', isCorrect: false }] } },
    { text: '身体拘束の具体例として、厚生労働省が定める「11項目」に含まれるものはどれか？', explanation: 'ベッドを4枚の柵で囲い、自力で降りられないようにすることは代表的な身体拘束です。', order: 2, choices: { create: [{ text: 'ベッドを4枚の柵で囲う', isCorrect: true }, { text: '本人の希望でナースコールを置く', isCorrect: false }, { text: '歩行時に付き添いをする', isCorrect: false }] } },
    { text: '身体拘束を例外的に行う場合に満たすべき「3要件」に含まれないものはどれか？', explanation: '「切迫性・非代替性・一時性」が3要件であり、「人手不足」は正当な理由になりません。', order: 3, choices: { create: [{ text: '人手不足による管理の都合', isCorrect: true }, { text: '命の危険がある「切迫性」', isCorrect: false }, { text: '他に方法がない「非代替性」', isCorrect: false }, { text: '短期間の「一時性」', isCorrect: false }] } },
    { text: '車椅子のテーブルをロックし、立ち上がれないようにすることへの評価は？', explanation: '物理的に行動を制限する行為であり、明白な身体拘束に該当します。', order: 4, choices: { create: [{ text: '身体拘束に該当する', isCorrect: true }, { text: '姿勢保持のためなら拘束ではない', isCorrect: false }, { text: '食後30分なら認められる', isCorrect: false }] } },
    { text: '身体拘束を「一時的」に行った際、施設が必ず行うべき法的義務はどれか？', explanation: '理由や時間、態様などを詳細に「記録」し、保存する義務があります。', order: 5, choices: { create: [{ text: '具体的な態様や時間の記録', isCorrect: true }, { text: '事後報告のみで良い', isCorrect: false }, { text: '記録は不要である', isCorrect: false }] } },
    { text: '本来の治療目的を超え、薬物によって活動を抑制することを何というか？', explanation: '「ドラッグロック（薬物による拘束）」と呼ばれ、重大な身体拘束の一つとみなされます。', order: 6, choices: { create: [{ text: 'ドラッグロック', isCorrect: true }, { text: 'メディカルケア', isCorrect: false }, { text: 'ケミカルサポート', isCorrect: false }] } },
    { text: '拘束をしないための代替案として、環境面での工夫に該当するものはどれか？', explanation: '低床ベッドを使用し、転落時の衝撃を和らげることで柵を外すなどの工夫が有効です。', order: 7, choices: { create: [{ text: '低床ベッドや衝撃吸収マットの使用', isCorrect: true }, { text: '居室のドアに外から鍵をかける', isCorrect: false }, { text: '高い柵を増設する', isCorrect: false }] } },
    { text: '身体拘束廃止に向けて、施設内に設置が義務付けられている組織は何か？', explanation: '身体拘束適正化検討委員会（または廃止委員会）の設置が義務化されています。', order: 8, choices: { create: [{ text: '身体拘束適正化検討委員会', isCorrect: true }, { text: '効率的運営委員会', isCorrect: false }, { text: '事故報告受付係', isCorrect: false }] } },
    { text: '身体拘束がもたらす「精神的」な悪影響として、最も適切なものはどれか？', explanation: '縛られることによる屈辱感や絶望感は、認知症の症状（BPSD）を悪化させる原因となります。', order: 9, choices: { create: [{ text: '屈辱感や絶望感による意欲の低下', isCorrect: true }, { text: '安心感が増して穏やかになる', isCorrect: false }, { text: '職員への感謝の気持ちが芽生える', isCorrect: false }] } },
    { text: '身体拘束を「行わない」ケアを実現するために、最も重要とされる考え方はどれか？', explanation: '「なぜ動きたいのか」という本人の意向や背景にある理由を多職種で考え、代替案を見出すことが重要です。', order: 10, choices: { create: [{ text: 'なぜ動きたいのか、理由や背景を探る', isCorrect: true }, { text: '事故が起きたら自己責任だと割り切る', isCorrect: false }, { text: '家族に「拘束しないと危ない」と説得する', isCorrect: false }] } }
  ]

  let course = await prisma.course.findUnique({ where: { slug: 'restraint' } })

  if (course) {
    await prisma.choice.deleteMany({ where: { question: { courseId: course.id } } })
    await prisma.question.deleteMany({ where: { courseId: course.id } })
    await prisma.slide.deleteMany({ where: { courseId: course.id } })
    
    course = await prisma.course.update({
      where: { id: course.id },
      data: {
        ...courseData,
        slides: { create: slidesData },
        questions: { create: questionsData }
      }
    })
  } else {
    course = await prisma.course.create({
      data: {
        ...courseData,
        slides: { create: slidesData },
        questions: { create: questionsData }
      }
    })
  }

  return course
}
