import { PrismaClient } from '@prisma/client'

export async function seedMedical(prisma: PrismaClient) {
  const slug = 'medical'
  const courseData = {
    slug,
    title: '医療的ケア研修（2024年度）',
    description: '〜命を繋ぐ観察眼と異常の早期発見〜',
    introduction: `
        <div class="flex flex-col items-center justify-center text-center space-y-2 pt-2 px-4 text-balance">
          <div class="flex items-center gap-4">
            <span class="h-px w-8 lg:w-12 bg-blue-700 rounded-full"></span>
            <p class="text-blue-800 font-black tracking-widest text-lg lg:text-xl uppercase">医療的ケア研修</p>
            <span class="h-px w-8 lg:w-12 bg-blue-700 rounded-full"></span>
          </div>
          <h2 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight">利用者の「静かな変化」を<br/>見逃していませんか？</h2>
          <div class="max-w-2xl space-y-2 text-slate-800 text-sm lg:text-base leading-relaxed font-bold px-4 text-center">
            <p>バイタル数値には現れない、ほんの少しの「活気のなさ」や「呼吸の浅さ」。<br class="lg:hidden" />それは身体が発している切実なSOSかもしれません。</p>
            <div class="p-3 lg:p-4 bg-blue-50 rounded-[1.5rem] lg:rounded-[2rem] border-2 border-blue-200 shadow-inner relative overflow-hidden text-[10px] lg:text-xs text-left">
              <div class="absolute top-0 right-0 w-16 h-16 lg:w-20 lg:h-20 bg-blue-100/50 rounded-bl-full"></div>
              <p class="relative z-10 italic text-blue-900 font-black text-xs lg:text-sm leading-relaxed">私たちは医師ではありません。しかし、24時間その方に寄り添う私たちにしか気づけない「変化」があります。医療職へ確実なバトンを繋ぐ、観察のプロを目指しましょう。</p>
            </div>
            <p class="text-[10px] lg:text-sm text-slate-900 font-black text-center mt-2">この研修は、命を救うための「根拠ある観察眼」を養うためのものです。</p>
          </div>
        </div>
      `,
    learningObjectives: `
        <div class="flex flex-col items-center justify-center text-center space-y-3 pt-2 px-4 w-full text-balance">
          <div class="bg-blue-700 text-white px-6 py-1.5 rounded-full text-[10px] font-black tracking-[0.3em] uppercase mb-1 shadow-lg shadow-blue-200">Learning Objectives</div>
          <div class="grid grid-cols-1 gap-2 w-full max-w-2xl">
            <div class="group p-3 lg:p-4 bg-white border-2 border-slate-200 rounded-[1.5rem] lg:rounded-[2rem] shadow-sm flex items-center gap-4 lg:gap-6 hover:shadow-xl hover:border-blue-400 transition-all duration-500 text-center lg:text-left">
              <div class="w-10 h-10 lg:w-12 lg:h-12 bg-blue-700 text-white rounded-xl flex items-center justify-center text-base lg:text-lg font-black shrink-0 shadow-lg shadow-blue-200">1</div>
              <div class="text-left">
                <h4 class="text-sm lg:text-base font-black text-slate-900">バイタルの「意味」を理解する</h4>
                <p class="text-slate-800 text-[10px] lg:text-xs font-bold leading-tight">単なる測定で終わらず、数値の変動から身体の異変を推察できるようになる。</p>
              </div>
            </div>
            <div class="group p-3 lg:p-4 bg-white border-2 border-slate-200 rounded-[1.5rem] lg:rounded-[2rem] shadow-sm flex items-center gap-4 lg:gap-6 hover:shadow-xl hover:border-blue-400 transition-all duration-500 text-center lg:text-left">
              <div class="w-10 h-10 lg:w-12 lg:h-12 bg-blue-700 text-white rounded-xl flex items-center justify-center text-base lg:text-lg font-black shrink-0 shadow-lg shadow-blue-200">2</div>
              <div class="text-left">
                <h4 class="text-sm lg:text-base font-black text-slate-900">医療的ケアの手順を完遂できる</h4>
                <p class="text-slate-800 text-[10px] lg:text-xs font-bold leading-tight">喀痰吸引、経管栄養の法的根拠と、事故を防ぐ安全な手順を習得する。</p>
              </div>
            </div>
            <div class="group p-3 lg:p-4 bg-white border-2 border-slate-200 rounded-[1.5rem] lg:rounded-[2rem] shadow-sm flex items-center gap-4 lg:gap-6 hover:shadow-xl hover:border-blue-400 transition-all duration-500 text-center lg:text-left">
              <div class="w-10 h-10 lg:w-12 lg:h-12 bg-blue-700 text-white rounded-xl flex items-center justify-center text-base lg:text-lg font-black shrink-0 shadow-lg shadow-blue-200">3</div>
              <div class="text-left">
                <h4 class="text-sm lg:text-base font-black text-slate-900">急変時の報告能力を高める</h4>
                <p class="text-slate-800 text-[10px] lg:text-xs font-bold leading-tight">SBARなどの伝達手法を用い、医療職へ客観的事実を的確に伝えられる。</p>
              </div>
            </div>
          </div>
        </div>
      `,
    videoUrl: null,
    badgeLabel: '医療連携',
    badgeIcon: 'Activity',
  }

  const slidesData = [
    { title: "医療的ケア研修", order: 0, content: `<div class="flex flex-col items-center justify-center text-center space-y-4 w-full h-full text-balance"><div class="relative w-full max-w-4xl px-4"><div class="absolute inset-0 bg-blue-400 blur-3xl opacity-20 scale-150 animate-pulse text-center"></div><div class="relative bg-transparent lg:bg-white p-0 lg:p-12 rounded-none lg:rounded-[3.5rem] shadow-none lg:shadow-2xl border-none lg:border lg:border-slate-200 w-full mx-auto text-center"><div class="bg-blue-700 text-white px-4 lg:px-6 py-1 lg:py-1.5 rounded-full text-[8px] lg:text-[10px] font-black tracking-[0.3em] uppercase inline-block mb-6 lg:mb-8 shadow-sm">法定研修 2024</div><h2 class="text-3xl lg:text-5xl font-black text-slate-900 leading-tight mb-4 text-center">医療的ケア・異常発見</h2><p class="text-blue-700 text-sm lg:text-2xl font-black mt-2 whitespace-nowrap text-center">〜命を繋ぐプロの観察眼〜</p></div></div><div class="flex items-center justify-center gap-4 text-slate-500 font-black text-[8px] lg:text-[10px] tracking-widest pt-4 text-center w-full"><span class="h-px w-6 lg:w-8 bg-slate-300"></span>CARE LEARNING SYSTEM<span class="h-px w-6 lg:w-8 bg-slate-300"></span></div></div>` },
    { title: "救命の第一走者として", order: 1, content: `<div class="space-y-4 lg:space-y-6 text-center px-4 h-full flex flex-col justify-center text-balance text-center"><div class="inline-flex items-center gap-3 px-4 py-1.5 bg-blue-100 text-blue-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-blue-200 mb-2 uppercase tracking-widest mx-auto text-center">救命のバトン</div><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4 text-center w-full">医療職へ繋ぐための「観察」</h4><div class="p-0 lg:p-8 bg-transparent lg:bg-blue-50 border-none lg:border-2 lg:border-blue-100 shadow-none lg:shadow-xl rounded-none lg:rounded-[3rem] text-center lg:text-left text-sm lg:text-lg font-bold text-blue-800 space-y-4 max-w-4xl mx-auto px-4 text-center"><p class="font-black text-center">バイタル測定は「測ること」が目的ではありません。「前日と何が違うか」「この数値が何を意味するか」を考えることが、本当の医療的ケアの始まりです。</p></div></div>` },
    { title: "バイタルサイン1：体温の盲点", order: 2, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left text-balance"><div class="space-y-4"><h4 class="text-2xl lg:text-4xl font-black text-blue-900 flex items-center gap-4 lg:gap-6 justify-center"><span class="w-2 h-8 lg:w-3 lg:h-12 bg-blue-700 rounded-full"></span>高齢者の体温変化</h4></div><ul class="space-y-4 lg:space-y-6 text-lg lg:text-3xl font-black text-slate-800 pl-0 leading-tight text-center"><li>・35度台（低体温）は重症化の予兆</li><li>・熱が出にくい肺炎や感染症に注意</li><li>・「平熱」を時間帯別に把握しておく</li></ul></div>` },
    { title: "バイタルサイン2：血圧の変動", order: 3, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left text-balance text-center"><div class="space-y-4"><h4 class="text-2xl lg:text-4xl font-black text-blue-900 flex items-center gap-4 lg:gap-6 justify-center"><span class="w-2 h-8 lg:w-3 lg:h-12 bg-blue-700 rounded-full"></span>変動の理由を考える</h4></div><ul class="space-y-4 lg:space-y-6 text-lg lg:text-3xl font-black text-slate-800 pl-0 leading-tight text-center"><li>・入浴後・食後の急降下による失神</li><li>・痛みや不安による血圧の急上昇</li><li>・麻痺側の測定は原則避ける</li></ul></div>` },
    { title: "バイタルサイン3：脈拍・呼吸・SpO2", order: 4, content: `<div class="space-y-6 lg:space-y-8 text-center h-full flex flex-col justify-center px-4 text-balance text-center"><div class="inline-flex items-center gap-3 px-4 py-2 bg-red-100 text-red-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-red-200 mb-2 shadow-sm mx-auto uppercase tracking-widest"><span class="w-2 h-2 bg-red-700 rounded-full animate-ping"></span>MUST CHECK</div><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight text-center w-full">「いつもと違う」リズム</h4><div class="grid grid-cols-1 lg:grid-cols-3 gap-3 lg:gap-4 max-w-5xl mx-auto w-full px-4 text-center"><div class="p-4 bg-white border-2 border-slate-200 rounded-2xl shadow-sm">不整脈（脈の欠落）</div><div class="p-4 bg-white border-2 border-slate-200 rounded-2xl shadow-sm">肩呼吸・あえぎ呼吸</div><div class="p-4 bg-white border-2 border-slate-200 rounded-2xl shadow-sm">SpO2 90%以下の低下</div></div><p class="text-red-700 font-black text-[10px] lg:text-sm mt-4 text-center w-full">※これらは即座に医療職へ報告すべき警告サインです。</p></div>` },
    { title: "意識レベルの評価：JCS", order: 5, content: `<div class="flex flex-col items-center text-center space-y-4 lg:space-y-6 px-4 h-full justify-center text-balance text-center"><div class="p-4 lg:p-6 bg-white rounded-[2rem] lg:rounded-[3.5rem] w-full max-w-2xl shadow-xl border-2 border-slate-200 shrink-0 text-center"><h4 class="text-xl lg:text-2xl font-black mb-2 text-slate-900 text-center text-balance px-4">ジャパン・コーマ・スケール</h4></div><div class="grid grid-cols-1 lg:grid-cols-3 gap-3 font-black text-[10px] lg:text-sm w-full max-w-5xl"><div class="p-3 bg-blue-50 border-2 border-blue-200 rounded-2xl text-left"><p class="text-blue-900 mb-1">1桁：起きている</p><p class="text-slate-600">見当識障害があるが、目は開いている状態。</p></div><div class="p-3 bg-blue-50 border-2 border-blue-200 rounded-2xl text-left"><p class="text-blue-900 mb-1">2桁：呼びかけで開眼</p><p class="text-slate-600">刺激を与えると目を開ける状態。</p></div><div class="p-3 bg-blue-50 border-2 border-blue-200 rounded-2xl text-left"><p class="text-blue-900 mb-1">3桁：痛みで開眼せず</p><p class="text-slate-600">強い刺激でも反応がない重篤な状態。</p></div></div></div>` },
    { title: "喀痰吸引：安全な実践手順", order: 6, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left text-balance text-center"><div class="space-y-4"><h4 class="text-2xl lg:text-4xl font-black text-blue-900 flex items-center gap-4 lg:gap-6 justify-center"><span class="w-2 h-8 lg:w-3 lg:h-12 bg-blue-700 rounded-full"></span>15秒以内の原則</h4></div><ul class="space-y-4 lg:space-y-6 text-lg lg:text-3xl font-black text-slate-800 pl-0 leading-tight text-center"><li>・吸引圧をかけすぎない（20kPa以下）</li><li>・カテーテルの挿入時は圧をかけない</li><li>・粘膜を傷つけないよう回転させながら</li></ul><p class="text-red-700 font-black text-sm lg:text-xl mt-4 text-center w-full">低酸素状態を防ぐため、迅速に！</p></div>` },
    { title: "経管栄養：注入前の徹底確認", order: 7, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left text-balance text-center"><div class="space-y-4"><h4 class="text-2xl lg:text-4xl font-black text-blue-900 flex items-center gap-4 lg:gap-6 justify-center"><span class="w-2 h-8 lg:w-3 lg:h-12 bg-blue-700 rounded-full"></span>確認が命を救う</h4></div><ul class="space-y-4 lg:space-y-6 text-lg lg:text-3xl font-black text-slate-800 pl-0 leading-tight text-center"><li>・チューブの固定位置（抜けの確認）</li><li>・胃残（内容物）の有無と色の確認</li><li>・注入物の種類・温度・速度の再照合</li></ul></div>` },
    { title: "経管栄養：誤嚥・逆流を防ぐ姿勢", order: 8, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left text-balance text-center"><div class="space-y-4"><h4 class="text-2xl lg:text-4xl font-black text-blue-900 flex items-center gap-4 lg:gap-6 justify-center"><span class="w-2 h-8 lg:w-3 lg:h-12 bg-blue-700 rounded-full"></span>30〜60度の挙上</h4></div><ul class="space-y-4 lg:space-y-6 text-lg lg:text-3xl font-black text-slate-800 pl-0 leading-tight text-center"><li>・注入中、注入後30分〜1時間は座位保持</li><li>・左側臥位は逆流しやすいため注意</li><li>・腹部膨満や嘔気の有無を常に観察</li></ul></div>` },
    { title: "脱水症：高齢者の「乾き」を見抜く", order: 9, content: `<div class="flex flex-col items-center text-center space-y-4 lg:space-y-6 px-4 h-full justify-center text-balance text-center"><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight text-center w-full">脇の下が乾いていたら危険</h4><div class="grid grid-cols-1 lg:grid-cols-2 gap-3 font-black text-sm lg:text-base w-full max-w-4xl text-center"><div class="flex flex-col gap-3"><span class="px-6 py-2.5 bg-blue-50 border-2 border-blue-200 rounded-2xl text-blue-900 shadow-sm text-center">口腔粘膜の乾燥</span><span class="px-6 py-2.5 bg-blue-50 border-2 border-blue-200 rounded-2xl text-blue-900 shadow-sm text-center text-balance">皮膚のツルゴール（弾力）低下</span></div><div class="flex flex-col gap-3"><span class="px-6 py-2.5 bg-blue-50 border-2 border-blue-200 rounded-2xl text-blue-900 shadow-sm text-center">尿量の減少と濃縮（色が濃い）</span><span class="px-6 py-2.5 bg-blue-50 border-2 border-blue-200 rounded-2xl text-blue-900 shadow-sm text-center text-balance">意識の混濁（せん妄）</span></div></div></div>` },
    { title: "浮腫（むくみ）：心・腎機能の鏡", order: 10, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left text-balance text-center"><h4 class="text-xl lg:text-2xl font-black text-blue-900 text-center w-full">どこが、いつから、どれくらい？</h4><ul class="space-y-4 lg:space-y-6 text-sm lg:text-xl font-black text-slate-800 pl-0 leading-tight text-center"><li>・靴下の跡がずっと消えない</li><li>・指で押すと戻ってこない（陥凹性）</li><li>・急激な体重増加（1週間に数キロ）</li></ul><p class="text-blue-700 font-black text-center w-full mt-4 text-sm lg:text-lg text-balance">心不全や腎不全の悪化を疑うべきサインです</p></div>` },
    { title: "排泄物の異常：緊急信号", order: 11, content: `<div class="flex flex-col items-center justify-center h-full space-y-6 lg:space-y-8 px-4 w-full text-balance text-center"><h4 class="text-xl lg:text-2xl font-black text-red-900 text-center w-full mb-2 px-4 animate-pulse">「色」と「形」の変化を逃さない</h4><div class="grid grid-cols-1 gap-3 lg:gap-4 w-full max-w-2xl text-center"><div class="flex items-center gap-4 bg-white p-3 rounded-2xl border-2 border-red-100 shadow-sm font-black text-sm lg:text-base justify-center lg:justify-start"><span class="w-10 h-10 bg-red-600 text-white rounded-full flex items-center justify-center shrink-0">1</span>黒色便・タール便（上部消化管出血）</div><div class="flex items-center gap-4 bg-white p-3 rounded-2xl border-2 border-red-100 shadow-sm font-black text-sm lg:text-base justify-center lg:justify-start"><span class="w-10 h-10 bg-red-600 text-white rounded-full flex items-center justify-center shrink-0">2</span>鮮血便（下部消化管出血・痔）</div><div class="flex items-center gap-4 bg-white p-3 rounded-2xl border-2 border-red-100 shadow-sm font-black text-sm lg:text-base justify-center lg:justify-start"><span class="w-10 h-10 bg-red-600 text-white rounded-full flex items-center justify-center shrink-0">3</span>血尿・混濁尿・尿量減少</div></div></div>` },
    { title: "高齢者の肺炎：熱が出ない怖さ", order: 12, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-6 lg:space-y-8 px-4 w-full text-balance text-center text-center"><div class="inline-flex items-center gap-3 px-4 py-1.5 bg-red-100 text-red-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-red-200 mb-2 mx-auto text-center">非典型症状</div><h4 class="text-xl lg:text-2xl font-black text-red-900 leading-tight px-4 text-center w-full">「なんとなく変」こそが真実</h4><div class="p-6 lg:p-10 bg-white border-[4px] lg:border-[6px] border-red-600 rounded-[2rem] lg:rounded-[3rem] shadow-2xl max-w-3xl mx-auto w-full text-center"><p class="text-lg lg:text-2xl font-black text-red-900 leading-relaxed italic text-balance text-center text-center">熱がない、咳も出ない。<br/>でも、「食欲がない」「ボーッとしている」。<br/>その直感が、肺炎の早期発見に繋がります。</p></div></div>` },
    { title: "低血糖の恐怖：インスリン利用者", order: 13, content: `<div class="flex flex-col items-center justify-center h-full space-y-6 lg:space-y-8 px-4 w-full text-balance text-center"><h4 class="text-xl lg:text-2xl font-black text-red-900 text-center w-full mb-2 px-4 animate-pulse">冷や汗と震えは緊急事態</h4><div class="grid grid-cols-1 gap-3 lg:gap-4 w-full max-w-2xl text-center"><div class="flex items-center gap-4 bg-white p-3 rounded-2xl border-2 border-red-100 shadow-sm font-black text-sm lg:text-base justify-center lg:justify-start"><span class="w-10 h-10 bg-red-600 text-white rounded-full flex items-center justify-center shrink-0">1</span>症状：空腹感、あくび、冷や汗、手の震え</div><div class="flex items-center gap-4 bg-white p-3 rounded-2xl border-2 border-red-100 shadow-sm font-black text-sm lg:text-base justify-center lg:justify-start"><span class="w-10 h-10 bg-red-600 text-white rounded-full flex items-center justify-center shrink-0">2</span>対応：糖分（ブドウ糖やジュース）を即座に摂取</div><div class="flex items-center gap-4 bg-white p-3 rounded-2xl border-2 border-red-100 shadow-sm font-black text-sm lg:text-base justify-center lg:justify-start"><span class="w-10 h-10 bg-red-600 text-white rounded-full flex items-center justify-center shrink-0">3</span>注意：意識がない場合は口に物を入れない</div></div></div>` },
    { title: "報告の標準化：SBAR法", order: 14, content: `<div class="flex flex-col items-center justify-center h-full text-left space-y-4 lg:space-y-6 px-6 lg:px-12 w-full text-balance text-center"><h4 class="text-xl lg:text-2xl font-black text-blue-700 text-center mb-2 uppercase tracking-widest w-full px-4">医療職へ確実に伝える</h4><div class="space-y-6 lg:space-y-8 font-black text-slate-900 max-w-4xl mx-auto w-full text-center"><div><p class="text-lg lg:text-2xl text-blue-600 mb-1 flex items-center gap-3 justify-center text-center"><span>●</span> Situation（状況）：</p><p class="text-sm lg:text-lg text-slate-600 font-bold text-center">何が起きているか（一言で結論）。</p></div><div><p class="text-lg lg:text-2xl text-blue-600 mb-1 flex items-center gap-3 justify-center text-center"><span>●</span> Background（背景）：</p><p class="text-sm lg:text-lg text-slate-600 font-bold text-center">経過や既往歴（なぜそうなったか）。</p></div><div><p class="text-lg lg:text-2xl text-blue-600 mb-1 flex items-center gap-3 justify-center text-center"><span>●</span> Assessment（評価）：</p><p class="text-sm lg:text-lg text-slate-600 font-bold text-center text-balance">現在の状態（数値や変化）への自分の見解。</p></div></div></div>` },
    { title: "経過記録：客観性の追求", order: 15, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-4 lg:space-y-6 px-4 w-full text-balance text-center text-balance"><h4 class="text-xl lg:text-2xl font-black text-blue-900 text-center w-full px-4">「辛そう」を言葉に直す</h4><div class="p-6 bg-white border-2 border-blue-100 rounded-3xl text-left max-w-3xl space-y-4 shadow-sm mx-auto text-center"><p class="text-sm lg:text-lg font-black text-slate-800 leading-relaxed text-center text-balance">主観的な「様子」を、客観的な「事実」に変換します。「ぐったりしている」ではなく「呼びかけへの反応が遅く、視線が合わない」。「息が苦しそう」ではなく「呼吸数30回/分、肩呼吸がある」。</p></div></div>` },
    { title: "1. 事例：バイタル数値は正常だが…", order: 16, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-4 lg:space-y-6 px-4 w-full text-balance text-center"><div class="inline-flex items-center gap-3 px-4 py-1.5 bg-blue-50 text-blue-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-blue-200 mb-2 mx-auto text-center">事例 1</div><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4 text-center w-full">場面：なんとなく活気がない</h4><div class="p-6 lg:p-8 bg-white border-2 border-slate-100 rounded-[2rem] lg:rounded-[3rem] shadow-xl max-w-4xl text-left space-y-4 w-full text-center"><p class="text-sm lg:text-lg font-bold text-slate-800 leading-relaxed text-balance px-4 text-center text-center">熱も血圧も正常範囲内。しかし、昼食を半分残し、いつもより返事が弱々しい。あなたは看護師に報告しますか？</p><div class="h-px bg-slate-100"></div><p class="text-xs lg:text-base font-black text-blue-700 italic text-center px-4 text-balance text-center w-full">報告する場合、看護師が判断しやすいために、あなたは何を確認してから伝えますか？</p></div></div>` },
    { title: "2. 事例：痰詰まりの吸引中", order: 17, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-4 lg:space-y-6 px-4 w-full text-balance text-center"><div class="inline-flex items-center gap-3 px-4 py-1.5 bg-blue-50 text-blue-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-blue-200 mb-2 mx-auto text-center">事例 2</div><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4 text-center w-full text-balance text-center">場面：吸引時の急変</h4><div class="p-6 lg:p-8 bg-white border-2 border-slate-100 rounded-[2rem] lg:rounded-[3rem] shadow-xl max-w-4xl text-left space-y-4 w-full text-center"><p class="text-sm lg:text-lg font-bold text-slate-800 leading-relaxed text-balance px-4 text-center text-balance text-center">吸引中、急に顔色が紫色（チアノーゼ）になり、呼吸が激しくなりました。あなたはそのまま吸引を続けますか？</p><div class="h-px bg-slate-100"></div><p class="text-xs lg:text-base font-black text-red-700 italic text-center px-4 text-balance text-center w-full">この瞬間の「最優先行動」は何ですか？誰を呼びますか？</p></div></div>` },
    { title: "解決：医療連携を強固にする関わり", order: 18, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-4 lg:space-y-6 px-4 w-full text-balance text-center text-center"><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4 text-center w-full text-center">「気づき」を救命へ繋ぐ</h4><div class="p-6 lg:p-10 bg-blue-50 border-2 border-blue-100 rounded-[2.5rem] lg:rounded-[4rem] shadow-inner text-left max-w-4xl space-y-4 mx-auto text-center"><p class="text-base lg:text-lg font-black text-blue-900 text-center w-full text-balance">観察のプロの具体策</p><div class="grid grid-cols-1 gap-3 text-sm lg:text-base font-bold text-slate-800 text-center"><div class="flex items-center gap-3 lg:gap-4 bg-white p-3 rounded-xl lg:rounded-2xl border border-blue-100 shadow-sm text-center justify-center lg:justify-start"><span class="w-6 h-6 lg:w-8 lg:h-8 bg-blue-600 text-white rounded-full flex items-center justify-center text-[10px] lg:text-sm shrink-0 text-center">1</span>迷ったら「数値」を取り、報告の根拠を作る</div><div class="flex items-center gap-3 lg:gap-4 bg-white p-3 rounded-xl lg:rounded-2xl border border-blue-100 shadow-sm text-center justify-center lg:justify-start"><span class="w-6 h-6 lg:w-8 lg:h-8 bg-blue-600 text-white rounded-full flex items-center justify-center text-[10px] lg:text-sm shrink-0 text-center">2</span>吸引中の異変は即中止。酸素投与や救命を優先</div><div class="flex items-center gap-3 lg:gap-4 bg-white p-3 rounded-xl lg:rounded-2xl border border-blue-100 shadow-sm text-center justify-center lg:justify-start"><span class="w-6 h-6 lg:w-8 lg:h-8 bg-blue-600 text-white rounded-full flex items-center justify-center text-[10px] lg:text-sm shrink-0 text-center">3</span>「いつもと違う」という直感を医療職に信じてもらう</div></div></div></div>` },
    { title: "満足感：あなたの眼が命を守る", order: 19, content: `<div class="space-y-6 lg:space-y-8 text-center flex flex-col items-center justify-center h-full px-4 w-full text-balance text-center text-balance"><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4 text-center w-full">プロとしての貢献</h4><div class="p-8 lg:p-10 bg-white border-[4px] lg:border-[6px] border-blue-600 rounded-[2rem] lg:rounded-[3rem] shadow-2xl max-w-3xl mx-auto w-full text-center"><p class="text-xl lg:text-2xl font-black text-blue-900 leading-relaxed italic text-balance text-center text-center">医療職ではないあなたの気づきが、<br/>一人の利用者の命を救い、<br/>穏やかな日常を繋ぎ止めます。</p></div><p class="font-black text-sm lg:text-lg text-slate-800 mt-2 text-center w-full px-4 text-center">その観察眼こそが、プロの介護職の誇りです。</p></div>` },
    { title: "まとめ：今日から変えられる「観察」", order: 20, content: `<div class="flex flex-col items-center text-center space-y-6 lg:space-y-10 w-full h-full justify-center text-slate-900 px-4 text-center text-balance"><div class="w-24 h-24 lg:w-28 h-28 bg-blue-700 rounded-[2.5rem] lg:rounded-[3rem] flex items-center justify-center shadow-2xl rotate-3 transition-transform hover:rotate-0 duration-500 mx-auto text-center"><svg class="w-12 h-12 lg:w-16 h-16 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z" /></svg></div><h3 class="text-2xl lg:text-4xl font-black leading-tight text-center w-full text-balance">あなたの気づきが、<br/>命の最後の砦になります。</h3><div class="pt-8 lg:pt-10 border-t-2 border-slate-200 w-full max-w-md text-center mx-auto"><p class="text-slate-500 font-black text-[8px] lg:text-[10px] uppercase tracking-[0.5em]">End of Session</p></div></div>` },
    { title: "理解度テストのご案内", order: 21, content: `
        <div class="flex flex-col items-center text-center space-y-4 lg:space-y-6 w-full h-full justify-center px-4 text-center text-balance">
          <div class="bg-emerald-600 text-white px-6 py-1.5 rounded-full text-[8px] lg:text-[10px] font-black tracking-[0.3em] uppercase inline-block mb-4 lg:mb-2 shadow-lg px-4 text-center">修了</div>
          <h2 class="text-2xl lg:text-4xl font-black text-slate-900 leading-tight mb-2 text-center w-full text-balance">講義セッション終了</h2>
          <p class="text-emerald-800 text-base lg:text-xl font-black leading-relaxed text-center w-full text-balance px-4">大変お疲れ様でした。<br/>最後に理解度テスト（全10問）を行います。</p>
          <div class="p-4 lg:p-6 bg-blue-50 rounded-2xl lg:rounded-3xl border-2 border-blue-100 max-w-lg mx-auto mt-6">
            <p class="text-blue-900 font-black text-sm lg:text-lg flex items-center justify-center gap-3 text-center">
              <span class="w-2 h-2 bg-blue-700 rounded-full"></span>    
              全問正解を目指しましょう！
              <span class="w-2 h-2 bg-blue-700 rounded-full"></span>    
            </p>
          </div>
        </div>
      ` }
  ]

  const questionsData = [
    { text: '高齢者のバイタルサインにおいて、重症化のサインとされる体温はどれか？', explanation: '35度台の低体温は、感染症の重症化や免疫力の著しい低下を示す危険なサインです。', order: 1, choices: { create: [{ text: '35度台（低体温）', isCorrect: true }, { text: '36.5度', isCorrect: false }, { text: '37.0度', isCorrect: false }] } },
    { text: '喀痰吸引を行う際、1回の吸引時間の限度として適切なものはどれか？', explanation: '低酸素状態を防ぐため、1回の吸引は15秒以内で行うのが原則です。', order: 2, choices: { create: [{ text: '15秒以内', isCorrect: true }, { text: '1分以内', isCorrect: false }, { text: '出なくなるまで', isCorrect: false }] } },
    { text: '経管栄養の注入を行う際、誤嚥や逆流を防ぐための適切な体位はどれか？', explanation: '上半身を30度〜60度程度起こした状態（ファウラー位）で注入します。', order: 3, choices: { create: [{ text: '上半身を30〜60度挙上する', isCorrect: true }, { text: '完全に仰向けにする', isCorrect: false }, { text: 'うつ伏せにする', isCorrect: false }] } },
    { text: '高齢者の脱水のサインとして、最も気づきやすい身体的変化はどれか？', explanation: '脇の下の乾燥や、口腔内の粘膜の乾きは脱水の重要なサインです。', order: 4, choices: { create: [{ text: '脇の下の乾燥', isCorrect: true }, { text: '顔のむくみ', isCorrect: false }, { text: '多汗', isCorrect: false }] } },
    { text: '医療職へ状況を報告する際に用いられる、情報の標準的な伝達手法（SBAR）の意味は？', explanation: 'Situation（状況）、Background（背景）、Assessment（評価）、Recommendation（提案）の頭文字です。', order: 5, choices: { create: [{ text: '状況・背景・評価・提案', isCorrect: true }, { text: '氏名・年齢・性別・住所', isCorrect: false }, { text: '食事・排泄・睡眠・入浴', isCorrect: false }] } },
    { text: 'インスリン投与中の利用者が、冷や汗や手の震えを訴えた場合に疑うべき状態は？', explanation: '低血糖の典型的な初期症状であり、放置すると意識障害を招く恐れがあります。', order: 6, choices: { create: [{ text: '低血糖', isCorrect: true }, { text: '高血圧', isCorrect: false }, { text: '脱水症', isCorrect: false }] } },
    { text: 'ジャパン・コーマ・スケール（JCS）において、「呼びかけで目を覚ます」状態は何桁か？', explanation: 'JCSの2桁（10、20、30）は、刺激（呼びかけや痛み）で目を覚ます状態を指します。', order: 7, choices: { create: [{ text: '2桁（10〜30）', isCorrect: true }, { text: '1桁（1〜3）', isCorrect: false }, { text: '3桁（100〜300）', isCorrect: false }] } },
    { text: '介護職が経過記録を書く際、最も重要とされる姿勢はどれか？', explanation: '「辛そう」などの主観を避け、数値や具体的な動作などの客観的事実を記すことが重要です。', order: 8, choices: { create: [{ text: '客観的事実を正確に記す', isCorrect: true }, { text: '自分の感想を中心に書く', isCorrect: false }, { text: 'きれいな文章で書く', isCorrect: false }] } },
    { text: '口腔ケアが全身疾患の予防に繋がる最大の理由は何か？', explanation: '口腔内の細菌を減らすことで、誤嚥性肺炎の発生リスクを大幅に下げることができます。', order: 9, choices: { create: [{ text: '誤嚥性肺炎を防ぐため', isCorrect: true }, { text: '虫歯を治すため', isCorrect: false }, { text: '味覚を鋭くするため', isCorrect: false }] } },
    { text: '利用者の浮腫（むくみ）を発見した際、観察すべきポイントとして正しいものは？', explanation: '靴下の跡が消えない、指で押して跡が戻らないなどの強さを確認し、医療職へ伝えます。', order: 10, choices: { create: [{ text: '指で押して跡が戻るかどうか', isCorrect: true }, { text: '皮膚の色が明るいかどうか', isCorrect: false }, { text: '筋肉がついているかどうか', isCorrect: false }] } }
  ]

  let course = await prisma.course.findUnique({ where: { slug } })

  if (course) {
    await prisma.choice.deleteMany({ where: { question: { courseId: course.id } } })
    await prisma.question.deleteMany({ where: { courseId: course.id } })
    await prisma.slide.deleteMany({ where: { courseId: course.id } })
    
    course = await prisma.course.update({
      where: { id: course.id },
      data: {
        ...courseData,
        slides: { create: slidesData },
        questions: { create: questionsData }
      }
    })
  } else {
    course = await prisma.course.create({
      data: {
        ...courseData,
        slides: { create: slidesData },
        questions: { create: questionsData }
      }
    })
  }

  return course
}
