import { PrismaClient } from '@prisma/client'

export async function seedMedical(prisma: PrismaClient) {
  const slug = 'medical'
  const courseData = {
    slug,
    title: '医療的ケア研修（2024年度）',
    description: '〜命を繋ぐ観察眼と異常の早期発見〜',
    introduction: `
        <div class="flex flex-col items-center justify-center text-center space-y-3 pt-4 px-4 text-balance">
          <div class="flex items-center gap-4">
            <span class="h-px w-8 lg:w-12 bg-blue-700 rounded-full"></span>
            <p class="text-blue-800 font-black tracking-widest text-lg lg:text-2xl uppercase">医療制定ケア・喀痰吸引</p>
            <span class="h-px w-8 lg:w-12 bg-blue-700 rounded-full"></span>
          </div>
          <h2 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight">利用者の「静かなSOS」を<br/>見逃していませんか？</h2>
          <div class="max-w-2xl space-y-2 text-slate-800 text-sm lg:text-base leading-relaxed font-bold px-4 text-center">
            <p>バイタル数値には現れない、ほんの少しの「活気のなさ」や「呼吸の浅さ」。<br class="lg:hidden" />それは身体が発している切実な異変のサインかもしれません。</p>
            <div class="p-4 lg:p-5 bg-blue-50 rounded-[1.5rem] lg:rounded-[2rem] border-2 border-blue-200 shadow-inner relative overflow-hidden text-[10px] lg:text-xs text-left mt-4">
              <div class="absolute top-0 right-0 w-16 h-16 lg:w-24 lg:h-24 bg-blue-100/50 rounded-bl-full"></div>
              <p class="relative z-10 italic text-blue-900 font-black text-xs lg:text-sm text-balance leading-relaxed">私たちは医師ではありません。しかし、24時間その方に寄り添う私たちにしか気づけない「変化」があります。医療職へ確実なバトンを繋ぐ、観察のプロを目指しましょう。</p>
            </div>
            <p class="text-[10px] lg:text-sm text-slate-900 font-black text-center mt-4 text-balance">2024年度、医療的ケアの安全確保は全ての事業所に求められる必須スキルです。</p>
          </div>
        </div>
      `,
    learningObjectives: `
        <div class="flex flex-col items-center justify-center text-center space-y-4 pt-4 px-4 w-full text-balance">
          <div class="bg-blue-700 text-white px-6 py-2 rounded-full text-[10px] font-black tracking-[0.3em] uppercase mb-2 shadow-lg shadow-blue-200">Learning Objectives</div>
          <div class="grid grid-cols-1 gap-3 w-full max-w-2xl">
            <div class="group p-4 bg-white border-2 border-slate-200 rounded-[1.5rem] lg:rounded-[2rem] shadow-sm flex items-center gap-4 lg:gap-6 hover:shadow-xl hover:border-blue-400 transition-all duration-500">
              <div class="w-10 h-10 lg:w-12 lg:h-12 bg-blue-700 text-white rounded-xl flex items-center justify-center text-base lg:text-lg font-black shrink-0 shadow-lg shadow-blue-200">1</div>
              <div class="text-left">
                <h4 class="text-sm lg:text-lg font-black text-slate-900">法的境界線と責任を理解する</h4>
                <p class="text-slate-800 text-[10px] lg:text-xs font-bold leading-relaxed text-balance">認定特定行為としての喀痰吸引・経管栄養の範囲と、安全確保の法的義務を学ぶ。</p>
              </div>
            </div>
            <div class="group p-4 bg-white border-2 border-slate-200 rounded-[1.5rem] lg:rounded-[2rem] shadow-sm flex items-center gap-4 lg:gap-6 hover:shadow-xl hover:border-blue-400 transition-all duration-500">
              <div class="w-10 h-10 lg:w-12 lg:h-12 bg-blue-700 text-white rounded-xl flex items-center justify-center text-base lg:text-lg font-black shrink-0 shadow-lg shadow-blue-200">2</div>
              <div class="text-left">
                <h4 class="text-sm lg:text-lg font-black text-slate-900">根拠ある観察技術を習得する</h4>
                <p class="text-slate-800 text-[10px] lg:text-xs font-bold leading-relaxed text-balance">バイタルの「数値」の裏にある「病態」を推測し、リスクを予見する観察眼を養う。</p>
              </div>
            </div>
            <div class="group p-4 bg-white border-2 border-slate-200 rounded-[1.5rem] lg:rounded-[2rem] shadow-sm flex items-center gap-4 lg:gap-6 hover:shadow-xl hover:border-blue-400 transition-all duration-500">
              <div class="w-10 h-10 lg:w-12 lg:h-12 bg-blue-700 text-white rounded-xl flex items-center justify-center text-base lg:text-lg font-black shrink-0 shadow-lg shadow-blue-200">3</div>
              <div class="text-left">
                <h4 class="text-sm lg:text-lg font-black text-slate-900">多職種連携の質を高める</h4>
                <p class="text-slate-800 text-[10px] lg:text-xs font-bold text-balance leading-relaxed">SBAR等の標準化された伝達手法を用い、看護師や医師と迅速かつ的確に連携する。</p>
              </div>
            </div>
          </div>
        </div>
      `,
    badgeLabel: '医療連携',
    badgeIcon: 'Activity',
  }

  const slidesData = [
    { title: "医療的ケア研修", order: 0, content: `<div class="flex flex-col items-center justify-center text-center space-y-6 w-full h-full text-balance"><div class="relative w-full max-w-4xl px-4"><div class="absolute inset-0 bg-blue-400 blur-3xl opacity-20 scale-150 animate-pulse text-center"></div><div class="relative bg-transparent lg:bg-white p-0 lg:p-16 rounded-none lg:rounded-[3.5rem] shadow-none lg:shadow-2xl border-none lg:border lg:border-slate-200 w-full mx-auto text-center"><div class="bg-blue-700 text-white px-4 lg:px-6 py-1 lg:py-1.5 rounded-full text-[8px] lg:text-[10px] font-black tracking-[0.3em] uppercase inline-block mb-6 lg:mb-8 shadow-sm">Legal Training 2024</div><h2 class="text-3xl lg:text-5xl font-black text-slate-900 leading-tight mb-4 px-4 text-center">医療的ケア・喀痰吸引</h2><p class="text-blue-700 text-sm lg:text-3xl font-black mt-2 whitespace-nowrap text-center">〜命を繋ぐプロの観察眼〜</p></div></div><div class="flex items-center justify-center gap-4 text-slate-500 font-black text-[8px] lg:text-[10px] tracking-widest pt-4 text-center w-full"><span class="h-px w-6 lg:w-8 bg-slate-300"></span>CARE LEARNING SYSTEM<span class="h-px w-6 lg:w-8 bg-slate-300"></span></div></div>` },
    
    { title: "救命の第一走者として：観察の本質", order: 1, content: `<div class="space-y-6 lg:space-y-8 text-center px-4 h-full flex flex-col justify-center text-balance"><div class="inline-flex items-center gap-3 px-4 py-2 bg-blue-100 text-blue-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-blue-200 mb-2 uppercase tracking-widest mx-auto text-center">救命のバトン</div><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight px-4 text-center w-full">医療職へ繋ぐための「観察」</h4><div class="p-0 lg:p-10 bg-transparent lg:bg-blue-50 border-none lg:border-2 lg:border-blue-100 shadow-none lg:shadow-xl rounded-none lg:rounded-[3rem] text-center lg:text-left text-sm lg:text-xl font-bold text-blue-800 space-y-4 lg:space-y-6 leading-relaxed max-w-4xl mx-auto px-4 text-center"><p class="font-black text-center">バイタル測定は「測ること」が目的ではありません。「前日と何が違うか」「この数値が身体のどの不調を示しているか」を考えることが、本当の医療的ケアの始まりです。</p></div></div>` },

    { title: "法的境界線：認定特定行為の責任", order: 2, content: `<div class="space-y-6 lg:space-y-8 text-center px-4 h-full flex flex-col justify-center text-balance text-center"><div class="inline-flex items-center gap-3 px-4 py-2 bg-red-100 text-red-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-red-200 mb-2 shadow-sm mx-auto uppercase tracking-widest text-center"><span class="w-2 h-2 bg-red-700 rounded-full animate-ping"></span>LEGAL BOUNDARY</div><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight mb-2 px-4 text-center w-full">「医行為」の一部を担う重み</h4><div class="grid grid-cols-1 lg:grid-cols-2 gap-4 max-w-4xl mx-auto w-full text-center"><div class="p-6 lg:p-8 bg-white border-2 border-slate-200 rounded-[2rem] lg:rounded-[2.5rem] shadow-xl flex flex-col items-center gap-2 lg:gap-4"><p class="font-black text-lg lg:text-xl text-blue-800 text-center">介護職ができる範囲</p><p class="text-sm lg:text-base font-bold text-slate-700 leading-relaxed text-center">口腔内、鼻腔内、気管カニューレ内の吸引。胃瘻、腸瘻、経鼻経管栄養の注入。</p></div><div class="p-6 lg:p-8 bg-white border-2 border-slate-200 rounded-[2rem] lg:rounded-[2.5rem] shadow-xl flex flex-col items-center gap-2 lg:gap-4"><p class="font-black text-lg lg:text-xl text-blue-800 text-center">遵守すべき条件</p><p class="text-sm lg:text-base font-bold text-slate-700 leading-relaxed text-center">医師の指示、看護師との連携、本人の同意、そして事業所の登録が不可欠です。</p></div></div></div>` },

    { title: "バイタルサイン1：体温（高齢者の盲点）", order: 3, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left text-balance text-center"><div class="space-y-4 lg:space-y-6 text-center w-full"><h4 class="text-2xl lg:text-5xl font-black text-blue-900 flex items-center gap-4 lg:gap-6 justify-center"><span class="w-2 h-10 lg:w-3 lg:h-16 bg-blue-700 rounded-full"></span>高齢者の体温変化</h4></div><ul class="space-y-4 lg:space-y-6 text-lg lg:text-3xl font-black text-slate-800 pl-0 leading-tight text-center"><li>・35度台（低体温）は重症化の予兆</li><li>・熱が出にくい肺炎や感染症に注意</li><li>・「平熱」を時間帯別に把握しておく</li><li>・測定部位（腋窩）の乾燥を必ず確認</li></ul></div>` },

    { title: "バイタルサイン2：血圧（変動の理由を聴く）", order: 4, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left text-balance text-center"><div class="space-y-4 lg:space-y-6 text-center w-full"><h4 class="text-2xl lg:text-5xl font-black text-blue-900 flex items-center gap-4 lg:gap-6 justify-center"><span class="w-2 h-10 lg:w-3 lg:h-16 bg-blue-700 rounded-full"></span>変動の背後にある病態</h4></div><ul class="space-y-4 lg:space-y-6 text-lg lg:text-3xl font-black text-slate-800 pl-0 leading-tight text-center"><li>・食後・入浴後の急降下（失神リスク）</li><li>・痛み、不安、尿閉による急上昇</li><li>・左右差がある場合は脳血管障害を疑う</li><li>・麻痺側の測定は「不正確」かつ「苦痛」</li></ul></div>` },

    { title: "バイタルサイン3：脈拍・呼吸・SpO2", order: 5, content: `<div class="space-y-6 lg:space-y-8 text-center h-full flex flex-col justify-center px-4 text-balance text-center"><div class="inline-flex items-center gap-3 px-4 py-2 bg-red-100 text-red-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-red-200 mb-2 shadow-sm mx-auto uppercase tracking-widest text-center"><span class="w-2 h-2 bg-red-700 rounded-full animate-ping"></span>CRITICAL SIGN</div><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight text-center w-full">「いつもと違う」リズム</h4><div class="grid grid-cols-1 lg:grid-cols-3 gap-3 lg:gap-4 max-w-5xl mx-auto w-full px-4 text-center text-center"><div class="p-4 bg-white border-2 border-slate-200 rounded-2xl shadow-sm font-black">不整脈（結滞）</div><div class="p-4 bg-white border-2 border-slate-200 rounded-2xl shadow-sm font-black">肩呼吸・あえぎ呼吸</div><div class="p-4 bg-white border-2 border-slate-200 rounded-2xl shadow-sm font-black">SpO2 90%以下の低下</div></div><p class="text-red-700 font-black text-[10px] lg:text-base mt-4 text-center w-full text-balance px-4 text-center">※SpO2低下は「酸素が足りない」結果。その原因（痰・心不全等）を特定する眼が重要です。</p></div>` },

    { title: "意識レベル評価：JCSの正確な伝達", order: 6, content: `<div class="flex flex-col items-center text-center space-y-4 lg:space-y-6 px-4 h-full justify-center text-balance text-center"><div class="p-4 lg:p-6 bg-white rounded-[2rem] lg:rounded-[3.5rem] w-full max-w-2xl shadow-xl border-2 border-slate-200 shrink-0 text-center"><h4 class="text-xl lg:text-2xl font-black mb-2 text-slate-900 text-center text-balance px-4 text-center">ジャパン・コーマ・スケール</h4><p class="text-[10px] lg:text-sm text-slate-900 font-black text-center text-center">「目が開いているか」が最初の基準</p></div><div class="grid grid-cols-1 lg:grid-cols-3 gap-3 font-black text-[10px] lg:text-sm w-full max-w-5xl text-center"><div class="p-3 bg-blue-50 border-2 border-blue-200 rounded-2xl text-left"><p class="text-blue-900 mb-1 font-black text-center">1桁：起きている</p><p class="text-slate-600 font-bold text-center">見当識障害。自分の名前や場所が言えない。</p></div><div class="p-3 bg-blue-50 border-2 border-blue-200 rounded-2xl text-left"><p class="text-blue-900 mb-1 font-black text-center">2桁：呼びかけで開眼</p><p class="text-slate-600 font-bold text-center">刺激を与えると目を開けるが、すぐ眠る。</p></div><div class="p-3 bg-blue-50 border-2 border-blue-200 rounded-2xl text-left"><p class="text-blue-900 mb-1 font-black text-center">3桁：痛みで開眼せず</p><p class="text-slate-600 font-bold text-center">強い刺激でも反応がない重篤な状態。</p></div></div></div>` },

    { title: "喀痰吸引：なぜ「吸引」が必要か", order: 7, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left text-balance text-center"><h4 class="text-xl lg:text-3xl font-black text-blue-900 text-center w-full">窒息と感染から命を守る</h4><div class="p-8 lg:p-10 bg-white border-4 border-blue-100 rounded-[2rem] lg:rounded-[3rem] shadow-xl max-w-4xl mx-auto w-full text-center"><p class="text-xl lg:text-3xl font-black leading-relaxed text-center text-slate-900 text-balance text-center">自力で出せない痰は、空気の通り道を塞ぎ、<br/><span class="text-blue-700 underline underline-offset-8 decoration-4">細菌の温床（肺炎の原因）</span>となります。</p></div><p class="text-blue-700 font-black text-center w-full mt-4 text-sm lg:text-lg text-center">吸引は「苦痛を与える」ものではなく「呼吸を助ける」ケアです。</p></div>` },

    { title: "喀痰吸引：安全な実践と「15秒」の原則", order: 8, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left text-balance text-center"><div class="space-y-4 lg:space-y-6 text-center w-full"><h4 class="text-2xl lg:text-5xl font-black text-blue-900 flex items-center gap-4 lg:gap-6 justify-center"><span class="w-2 h-10 lg:w-3 lg:h-16 bg-blue-700 rounded-full"></span>粘膜を傷つけない技術</h4></div><ul class="space-y-4 lg:space-y-6 text-lg lg:text-3xl font-black text-slate-800 pl-0 leading-tight text-center"><li>・吸引圧は20kPa（150mmHg）以下を厳守</li><li>・挿入時は圧をかけず、抜く時に回転させる</li><li>・1回15秒以内。痰が取れなくても一旦抜く</li><li>・口腔・鼻腔・カニューレの順序と清潔操作</li></ul><p class="text-red-700 font-black text-sm lg:text-xl mt-4 italic text-center text-center">※酸素欠乏（低酸素血症）を招かないための迅速さが必要です。</p></div>` },

    { title: "経管栄養：注入前の「3重」チェック", order: 9, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left text-balance text-center"><div class="space-y-4 lg:space-y-6 text-center w-full"><h4 class="text-2xl lg:text-5xl font-black text-blue-900 flex items-center gap-4 lg:gap-6 justify-center"><span class="w-2 h-10 lg:w-3 lg:h-16 bg-blue-700 rounded-full"></span>確認漏れは「死」に直結する</h4></div><ul class="space-y-4 lg:space-y-6 text-lg lg:text-3xl font-black text-slate-800 pl-0 leading-tight text-center"><li>・指示書の照合（栄養剤の種類・濃度・量）</li><li>・チューブの固定位置（マジック印のズレ確認）</li><li>・胃残（逆流物）の量・色の確認（100ml以上は報告）</li><li>・栄養剤の温度（人肌程度）と注入速度</li></ul></div>` },

    { title: "経管栄養：誤嚥・逆流を防ぐ重力の力", order: 10, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left text-balance text-center"><div class="space-y-4 lg:space-y-6 text-center w-full"><h4 class="text-2xl lg:text-5xl font-black text-blue-900 flex items-center gap-4 lg:gap-6 justify-center"><span class="w-2 h-10 lg:w-3 lg:h-16 bg-blue-700 rounded-full"></span>30〜60度の角度保持</h4></div><ul class="space-y-4 lg:space-y-6 text-lg lg:text-3xl font-black text-slate-800 pl-0 leading-tight text-center"><li>・注入中〜終了後1時間は座位または半坐位</li><li>・左側臥位は胃の出口を塞ぎ逆流しやすい</li><li>・腹部膨満、嘔気、冷や汗があれば即中止</li><li>・注入後の白湯（フラッシュ）で清潔を保つ</li></ul><p class="text-blue-700 font-black text-sm lg:text-xl mt-4 italic text-center text-center">※「入れたら終わり」ではありません。吸収までが医療的ケアです。</p></div>` },

    { title: "清潔操作の執念：感染経路を断つ", order: 11, content: `<div class="space-y-6 lg:space-y-8 text-center h-full flex flex-col justify-center px-4 text-balance text-center"><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight text-center w-full">未滅菌と滅菌の使い分け</h4><div class="grid grid-cols-1 lg:grid-cols-2 gap-4 lg:gap-6 max-w-4xl mx-auto w-full text-center text-center"><div class="p-6 lg:p-8 bg-blue-50 border-2 border-blue-100 rounded-[2rem] shadow-xl text-center"><p class="font-black text-lg lg:text-xl text-blue-800 text-center">無菌操作の徹底</p><p class="text-sm lg:text-base font-bold text-slate-700 leading-relaxed text-center">カテーテルの先端には絶対に素手で触れない。一回ごとにアルコール消毒または滅菌水で洗浄。</p></div><div class="p-6 lg:p-8 bg-blue-50 border-2 border-blue-100 rounded-[2rem] shadow-xl text-center"><p class="font-black text-lg lg:text-xl text-blue-800 text-center">保管環境の整備</p><p class="text-sm lg:text-base font-bold text-slate-700 leading-relaxed text-center">消毒液の有効期限、容器の清潔。カテーテルを乾燥状態で保管する理由を理解する。</p></div></div></div>` },

    { title: "脱水症：高齢者の「乾き」は静かに進む", order: 12, content: `<div class="flex flex-col items-center text-center space-y-4 lg:space-y-6 px-4 h-full justify-center text-balance text-center"><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight text-center w-full text-center">脇の下が乾いていたらSOS</h4><div class="grid grid-cols-1 lg:grid-cols-2 gap-3 font-black text-sm lg:text-base w-full max-w-4xl text-center text-center"><div class="flex flex-col gap-3 text-center"><span class="px-6 py-3 bg-blue-50 border-2 border-blue-200 rounded-2xl text-blue-900 shadow-sm text-center">口腔粘膜・舌の乾燥</span><span class="px-6 py-3 bg-blue-50 border-2 border-blue-200 rounded-2xl text-blue-900 shadow-sm text-center text-balance">皮膚の弾力低下（ハンカチーフサイン）</span></div><div class="flex flex-col gap-3 text-center"><span class="px-6 py-3 bg-blue-50 border-2 border-blue-200 rounded-2xl text-blue-900 shadow-sm text-center">尿量の減少と色の濃縮</span><span class="px-6 py-3 bg-blue-50 border-2 border-blue-200 rounded-2xl text-blue-900 shadow-sm text-center text-balance">意識の混濁（いつもよりウトウトする）</span></div></div><p class="text-rose-700 font-black text-sm lg:text-xl px-4 mt-4 italic text-center">※喉の渇きを訴えないからこそ、プロの「眼」が必要です。</p></div>` },

    { title: "浮腫（むくみ）：心臓と腎臓のSOS", order: 13, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left text-balance text-center"><h4 class="text-xl lg:text-3xl font-black text-blue-900 text-center w-full">どこが、いつから、どれくらい？</h4><ul class="space-y-4 lg:space-y-6 text-sm lg:text-xl font-black text-slate-800 pl-0 leading-tight text-center w-full"><li>・靴下の跡がずっと消えない（初期サイン）</li><li>・指で押すと戻ってこない（陥凹性浮腫）</li><li>・急激な体重増加（1週間に2キロ以上は心不全を疑う）</li><li>・仰向けで苦しがる（起座呼吸の予兆）</li></ul><p class="text-blue-700 font-black text-center w-full mt-4 text-sm lg:text-lg italic text-center">※浮腫は「単なるむくみ」ではなく「循環不全」の警告です。</p></div>` },

    { title: "排泄物の異常：一刻を争う「色」の変化", order: 14, content: `<div class="flex flex-col items-center justify-center h-full space-y-6 lg:space-y-8 px-4 w-full text-balance text-center"><h4 class="text-xl lg:text-2xl font-black text-red-900 text-center w-full mb-2 px-4 animate-pulse">「形」よりも「色」を見る</h4><div class="grid grid-cols-1 gap-3 lg:gap-4 w-full max-w-2xl text-center"><div class="flex items-center gap-4 bg-white p-4 rounded-2xl border-2 border-red-100 shadow-sm font-black text-sm lg:text-base justify-center lg:justify-start"><span class="w-10 h-10 bg-red-600 text-white rounded-full flex items-center justify-center shrink-0">1</span>黒色便・タール便：胃・十二指腸出血の疑い</div><div class="flex items-center gap-4 bg-white p-4 rounded-2xl border-2 border-red-100 shadow-sm font-black text-sm lg:text-base justify-center lg:justify-start"><span class="w-10 h-10 bg-red-600 text-white rounded-full flex items-center justify-center shrink-0">2</span>鮮血便：直腸出血や激しい痔の疑い</div><div class="p-4 bg-white border-2 border-red-100 rounded-2xl shadow-sm flex items-center gap-4 font-black justify-center lg:justify-start"><span class="w-10 h-10 bg-red-600 text-white rounded-full flex items-center justify-center shrink-0">3</span>血尿・コーヒー残渣様の尿：腎・膀胱の深刻な異変</div></div></div>` },

    { title: "高齢者の肺炎：熱が出ない「静かな殺し屋」", order: 15, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-6 lg:space-y-8 px-4 w-full text-balance text-center text-center"><div class="inline-flex items-center gap-3 px-4 py-1.5 bg-red-100 text-red-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-red-200 mb-2 mx-auto text-center">Atypical Symptoms</div><h4 class="text-xl lg:text-3xl font-black text-red-900 leading-tight px-4 text-center w-full text-center">「なんとなく変」こそが真実</h4><div class="p-8 lg:p-12 bg-white border-[4px] lg:border-[6px] border-red-600 rounded-[2rem] lg:rounded-[3rem] shadow-2xl max-w-3xl mx-auto w-full text-center text-center"><p class="text-lg lg:text-3xl font-black text-red-900 leading-relaxed italic text-balance text-center text-center">熱がない、咳も出ない。<br/>でも、「食欲がない」「ボーッとしている」。<br/>その直感（アセスメント）が、肺炎の早期発見に繋がります。</p></div></div>` },

    { title: "低血糖の恐怖：インスリン利用者への対応", order: 16, content: `<div class="flex flex-col items-center justify-center h-full space-y-6 lg:space-y-8 px-4 w-full text-balance text-center"><h4 class="text-xl lg:text-2xl font-black text-red-900 text-center w-full mb-2 px-4 animate-pulse">冷や汗と震えは「脳」の悲鳴</h4><div class="grid grid-cols-1 gap-3 lg:gap-4 w-full max-w-2xl text-center"><div class="flex items-center gap-4 bg-white p-4 rounded-2xl border-2 border-red-100 shadow-sm font-black text-sm lg:text-base justify-center lg:justify-start"><span class="w-10 h-10 bg-red-600 text-white rounded-full flex items-center justify-center shrink-0">1</span>初期：強い空腹感、あくび、冷や汗、生あくび</div><div class="flex items-center gap-4 bg-white p-4 rounded-2xl border-2 border-red-100 shadow-sm font-black text-sm lg:text-base justify-center lg:justify-start"><span class="w-10 h-10 bg-red-600 text-white rounded-full flex items-center justify-center shrink-0">2</span>対応：意識があれば糖分摂取。なければ即救急要請</div><div class="flex items-center gap-4 bg-white p-4 rounded-2xl border-2 border-red-100 shadow-sm font-black text-sm lg:text-base justify-center lg:justify-start"><span class="w-10 h-10 bg-red-600 text-white rounded-full flex items-center justify-center shrink-0 text-center">3</span>注意：勝手な自己判断で様子を見ない</div></div></div>` },

    { title: "報告の標準化：SBAR法で「迷い」を断つ", order: 17, content: `<div class="flex flex-col items-center justify-center h-full text-left space-y-4 lg:space-y-6 px-6 lg:px-12 w-full text-balance text-center"><h4 class="text-xl lg:text-3xl font-black text-blue-700 text-center mb-4 uppercase tracking-widest w-full px-4 text-center">医療職が「即決」できる報告を</h4><div class="space-y-6 lg:space-y-10 font-black text-slate-900 max-w-4xl mx-auto w-full text-center"><div><p class="text-lg lg:text-2xl text-blue-600 mb-1 flex items-center gap-3 justify-center text-center text-center"><span>●</span> Situation（状況）：</p><p class="text-sm lg:text-xl text-slate-600 font-bold text-center text-center">「A様が嘔吐し、意識が朦朧としています」</p></div><div><p class="text-lg lg:text-2xl text-blue-600 mb-1 flex items-center gap-3 justify-center text-center text-center"><span>●</span> Background（背景）：</p><p class="text-sm lg:text-xl text-slate-600 font-bold text-center text-center">「1時間前に胃瘻から200ml注入を終えたばかりです」</p></div><div><p class="text-lg lg:text-2xl text-blue-600 mb-1 flex items-center gap-3 justify-center text-center text-center"><span>●</span> Assessment（評価）：</p><p class="text-sm lg:text-xl text-slate-600 font-bold text-center text-center">「誤嚥の可能性が高く、呼吸が30回と速いです」</p></div></div></div>` },

    { title: "経過記録：主観から「客観」への変換", order: 18, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-4 lg:space-y-6 px-4 w-full text-balance text-center text-balance text-center text-center text-center"><h4 class="text-xl lg:text-2xl font-black text-blue-900 text-center w-full px-4 text-center">「辛そう」を言葉に直す執念</h4><div class="p-8 lg:p-10 bg-blue-50 border-2 border-blue-200 rounded-[2.5rem] lg:rounded-[4rem] shadow-inner text-left max-w-4xl space-y-4 lg:space-y-6 mx-auto text-left text-left text-left"><div class="grid grid-cols-1 lg:grid-cols-2 gap-4 lg:gap-8 text-left text-left"><div class="bg-white p-6 rounded-3xl shadow-sm border border-blue-100 text-left text-left"><p class="text-blue-800 font-black mb-2 text-lg text-left text-left text-left">● 感情ではなく「事実」</p><p class="text-sm font-bold text-slate-600 leading-relaxed text-left text-left text-left">「ぐったりしている」× → 「呼びかけに対し、一度開眼するがすぐに閉じる。発語なし」○</p></div><div class="bg-white p-6 rounded-3xl shadow-sm border border-blue-100 text-left text-left text-left"><p class="text-blue-800 font-black mb-2 text-lg text-left text-left text-left">● 数値で「変動」を示す</p><p class="text-sm font-bold text-slate-600 leading-relaxed text-left text-left text-left">「熱がある」× → 「平熱36.2℃に対し、現在37.8℃。30分で上昇傾向」○</p></div></div></div></div>` },

    { title: "多職種連携：看護師を支える「情報」の質", order: 19, content: `<div class="flex flex-col items-center justify-center h-full text-left space-y-6 lg:space-y-8 px-6 lg:px-12 w-full text-balance text-center text-center"><h4 class="text-xl lg:text-3xl font-black text-blue-800 flex items-center gap-4 w-full justify-center text-center text-center">指示待ちからの脱却</h4><p class="text-sm lg:text-xl font-black leading-relaxed text-slate-900 max-w-4xl bg-blue-50 p-6 lg:p-10 rounded-2xl lg:rounded-3xl border border-blue-100 w-full text-center text-center">「どうすればいいですか？」と聞く前に、「今の状態はこうです。私は〇〇が必要だと思います」と言える介護職が、チームの質を底上げし、利用者の安全を守ります。</p><p class="text-xs lg:text-lg font-black text-blue-800 text-center w-full px-4 text-center text-center">現場の第一発見者こそが、アセスメントの主役です。</p></div>` },

    { title: "ケーススタディ1：数値は正常だが「変」な時", order: 20, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-4 lg:space-y-6 px-4 w-full text-balance text-center text-center"><div class="inline-flex items-center gap-3 px-4 py-1.5 bg-blue-50 text-blue-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-blue-200 mb-2 mx-auto text-center text-center">CASE STUDY 01</div><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4 text-center w-full text-center">場面：食事を残し始めたA様</h4><div class="p-6 lg:p-10 bg-white border-2 border-slate-100 rounded-[2rem] lg:rounded-[3rem] shadow-xl max-w-4xl text-left space-y-4 w-full text-center text-center text-center"><p class="text-sm lg:text-xl font-bold text-slate-800 leading-relaxed text-balance px-4 text-center text-center text-center">バイタルは正常。しかし、いつも完食するA様が一口も食べず、視線が合いません。「様子を見ますか？」それとも「報告しますか？」</p><div class="h-px bg-slate-100 text-center"></div><p class="text-xs lg:text-lg font-black text-blue-700 italic text-center px-4 text-balance text-center w-full text-center">あなたが報告すると決めた「根拠」を、看護師にどう伝えますか？</p></div></div>` },

    { title: "ケーススタディ2：吸引時のチアノーゼ", order: 21, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-4 lg:space-y-6 px-4 w-full text-balance text-center text-center"><div class="inline-flex items-center gap-3 px-4 py-1.5 bg-blue-50 text-blue-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-blue-200 mb-2 mx-auto text-center text-center">CASE STUDY 02</div><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4 text-center w-full text-balance text-center text-center">場面：吸引中の急変</h4><div class="p-6 lg:p-10 bg-white border-2 border-slate-100 rounded-[2rem] lg:rounded-[3rem] shadow-xl max-w-4xl text-left space-y-4 w-full text-center text-center text-center text-center"><p class="text-sm lg:text-xl font-bold text-slate-800 leading-relaxed text-balance px-4 text-center text-balance text-center text-center">吸引中、急に顔色が紫色になり、SpO2が85%に低下しました。痰はまだ取り切れていません。あなたは吸引を続けますか？</p><div class="h-px bg-slate-100 text-center"></div><p class="text-xs lg:text-lg font-black text-red-700 italic text-center px-4 text-balance text-center w-full text-center text-center">この瞬間の「優先順位」は何ですか？救命のために何を捨て、何を救いますか？</p></div></div>` },

    { title: "プロフェッショナルとしての誇り：満足感", order: 22, content: `<div class="space-y-6 lg:space-y-10 text-center flex flex-col items-center justify-center h-full px-4 w-full text-balance text-center text-balance text-center text-center"><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight px-4 text-center w-full text-center">あなたの眼が、命の最後の砦</h4><div class="p-8 lg:p-12 bg-white border-[4px] lg:border-[6px] border-blue-600 rounded-[2rem] lg:rounded-[3rem] shadow-2xl max-w-3xl mx-auto w-full text-center text-center text-center text-center"><p class="text-xl lg:text-3xl font-black text-blue-900 leading-relaxed italic text-balance text-center text-center text-center text-center text-center">「いつもと違う」という直感を、<br/>理論と数値で武装した「確信」へ。<br/>あなたの気づきが、穏やかな日常を守ります。</p></div><p class="font-black text-sm lg:text-xl text-slate-800 mt-4 text-center w-full px-4 text-center text-center">その誇りを持って、明日のケアに向かいましょう。</p></div>` },

    { title: "全15科目、完遂おめでとうございます", order: 23, content: `<div class="flex flex-col items-center text-center space-y-8 lg:space-y-12 w-full h-full justify-center text-slate-900 px-4 text-center text-balance text-center text-center"><div class="w-24 h-24 lg:w-32 h-32 bg-blue-700 rounded-[2.5rem] lg:rounded-[3.5rem] flex items-center justify-center shadow-2xl shadow-blue-200 rotate-3 transition-transform hover:rotate-0 duration-500 mx-auto text-center text-center text-center text-center"><svg class="w-12 h-12 lg:w-16 h-16 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg></div><h3 class="text-2xl lg:text-5xl font-black leading-tight text-center w-full text-balance text-center text-center">全課程の修了、心より敬意を表します。<br/>現場を変える力が、今あなたに宿っています。</h3><div class="pt-8 lg:pt-12 border-t-2 border-slate-200 w-full max-w-md text-center mx-auto text-center text-center text-center"><p class="text-slate-500 font-black text-[8px] lg:text-[10px] uppercase tracking-[0.5em] text-center text-center text-center text-center">Mastery of All Sessions Accomplished</p></div></div>` },

    { title: "理解度テストのご案内", order: 24, content: `
        <div class="flex flex-col items-center text-center space-y-6 lg:space-y-8 w-full h-full justify-center px-4 text-center text-balance text-center text-center text-center">
          <div class="bg-emerald-600 text-white px-6 py-1.5 rounded-full text-[8px] lg:text-[10px] font-black tracking-[0.3em] uppercase inline-block mb-4 lg:mb-6 shadow-lg px-4 text-center text-center">Course Completed</div>
          <h2 class="text-2xl lg:text-5xl font-black text-slate-900 leading-tight mb-2 lg:mb-4 text-center w-full text-balance text-center text-center">最終関門：理解度テスト</h2>
          <p class="text-emerald-800 text-base lg:text-2xl font-black leading-relaxed text-center w-full text-balance px-4 text-center text-center">大変お疲れ様でした。<br/>最後に理解度テスト（全10問）を行います。</p>
          <div class="p-4 lg:p-6 bg-blue-50 rounded-2xl lg:rounded-3xl border-2 border-blue-100 max-w-lg mx-auto mt-6 lg:mt-8 text-center text-center text-center">
            <p class="text-blue-900 font-black text-sm lg:text-xl flex items-center justify-center gap-3 text-center text-center text-center">
              <span class="w-2 h-2 bg-blue-700 rounded-full text-center text-center text-center"></span>
              全問正解で、真のリーダーへ
              <span class="w-2 h-2 bg-blue-700 rounded-full text-center text-center text-center"></span>
            </p>
          </div>
        </div>
      ` }
  ]

  const questionsData = [
    { text: '高齢者のバイタルサインにおいて、重症化のサインとされる体温はどれか？', explanation: '35度台の低体温は、感染症の重症化や免疫力の著しい低下を示す危険なサインです。', order: 1, choices: { create: [{ text: '35度台（低体温）', isCorrect: true }, { text: '36.5度', isCorrect: false }, { text: '37.0度', isCorrect: false }] } },
    { text: '喀痰吸引を行う際、1回の吸引時間の限度として適切なものはどれか？', explanation: '低酸素状態を防ぐため、1回の吸引は15秒以内で行うのが原則です。', order: 2, choices: { create: [{ text: '15秒以内', isCorrect: true }, { text: '1分以内', isCorrect: false }, { text: '出なくなるまで', isCorrect: false }] } },
    { text: '経管栄養の注入を行う際、誤嚥や逆流を防ぐための適切な体位はどれか？', explanation: '上半身を30度〜60度程度起こした状態（ファウラー位）で注入します。', order: 3, choices: { create: [{ text: '上半身を30〜60度挙上する', isCorrect: true }, { text: '完全に仰向けにする', isCorrect: false }, { text: 'うつ伏せにする', isCorrect: false }] } },
    { text: '高齢者の脱水のサインとして、最も気づきやすい身体的変化はどれか？', explanation: '脇の下の乾燥や、口腔内の粘膜の乾きは脱水の重要なサインです。', order: 4, choices: { create: [{ text: '脇の下の乾燥', isCorrect: true }, { text: '顔のむくみ', isCorrect: false }, { text: '多汗', isCorrect: false }] } },
    { text: '医療職へ状況を報告する際に用いられる、情報の標準的な伝達手法（SBAR）の意味は？', explanation: 'Situation（状況）、Background（背景）、Assessment（評価）、Recommendation（提案）の頭文字です。', order: 5, choices: { create: [{ text: '状況・背景・評価・提案', isCorrect: true }, { text: '氏名・年齢・性別・住所', isCorrect: false }, { text: '食事・排泄・睡眠・入浴', isCorrect: false }] } },
    { text: 'インスリン投与中の利用者が、冷や汗や手の震えを訴えた場合に疑うべき状態は？', explanation: '低血糖の典型的な初期症状であり、放置すると意識障害を招く恐れがあります。', order: 6, choices: { create: [{ text: '低血糖', isCorrect: true }, { text: '高血圧', isCorrect: false }, { text: '脱水症', isCorrect: false }] } },
    { text: 'ジャパン・コーマ・スケール（JCS）において、「呼びかけで目を覚ます」状態は何桁か？', explanation: 'JCSの2桁（10、20、30）は、刺激（呼びかけや痛み）で目を覚ます状態を指します。', order: 7, choices: { create: [{ text: '2桁（10〜30）', isCorrect: true }, { text: '1桁（1〜3）', isCorrect: false }, { text: '3桁（100〜300）', isCorrect: false }] } },
    { text: '介護職が経過記録を書く際、最も重要とされる姿勢はどれか？', explanation: '「辛そう」などの主観を避け、数値や具体的な動作などの客観的事実を記すことが重要です。', order: 8, choices: { create: [{ text: '客観的事実を正確に記す', isCorrect: true }, { text: '自分の感想を中心に書く', isCorrect: false }, { text: 'きれいな文章で書く', isCorrect: false }] } },
    { text: '口腔ケアが全身疾患の予防に繋がる最大の理由は何か？', explanation: '口腔内の細菌を減らすことで、誤嚥性肺炎の発生リスクを大幅に下げることができます。', order: 9, choices: { create: [{ text: '誤嚥性肺炎を防ぐため', isCorrect: true }, { text: '虫歯を治すため', isCorrect: false }, { text: '味覚を鋭くするため', isCorrect: false }] } },
    { text: '利用者の浮腫（むくみ）を発見した際、観察すべきポイントとして正しいものは？', explanation: '靴下の跡が消えない、指で押して跡が戻らないなどの強さを確認し、医療職へ伝えます。', order: 10, choices: { create: [{ text: '指で押して跡が戻るかどうか', isCorrect: true }, { text: '皮膚の色が明るいかどうか', isCorrect: false }, { text: '筋肉がついているかどうか', isCorrect: false }] } }
  ]

  let course = await prisma.course.findUnique({ where: { slug } })

  if (course) {
    await prisma.choice.deleteMany({ where: { question: { courseId: course.id } } })
    await prisma.question.deleteMany({ where: { courseId: course.id } })
    await prisma.slide.deleteMany({ where: { courseId: course.id } })
    
    course = await prisma.course.update({
      where: { id: course.id },
      data: {
        ...courseData,
        slides: { create: slidesData },
        questions: { create: questionsData }
      }
    })
  } else {
    course = await prisma.course.create({
      data: {
        ...courseData,
        slides: { create: slidesData },
        questions: { create: questionsData }
      }
    })
  }

  return course
}
