import { PrismaClient } from '@prisma/client'

export async function seedMedical(prisma: PrismaClient) {
  return await prisma.course.create({
    data: {
      title: '医療に関する研修（連携・観察・医療的ケア）',
      description: 'バイタル観察の極意から医行為の範囲、専門職への正確な報告術（ISBAR）までを網羅した医療連携の決定版。',
      introduction: `
        <div class="space-y-8">
          <div class="flex items-center gap-4">
            <span class="h-1 w-12 bg-rose-600 rounded-full"></span>
            <p class="text-rose-600 font-black tracking-widest text-sm uppercase">Medical Bridge Hook</p>
          </div>
          <h2 class="text-4xl font-black text-slate-900 leading-tight">「いつもと何かが違う...」<br/>その直感を、自信を持って医療職に伝えられていますか？</h2>
          <div class="space-y-6 text-slate-600 text-lg leading-relaxed font-medium">
            <p>毎日接しているあなただからこそ気づける、「なんとなく元気がない」「いつもより食いつきが悪い」という小さな変化。それは、医師も気づけない重大な急変のサインかもしれません。</p>
            <div class="p-8 bg-rose-50/50 rounded-[2rem] border border-rose-100 shadow-inner relative overflow-hidden">
              <div class="absolute top-0 right-0 w-24 h-24 bg-rose-100/30 rounded-bl-full"></div>
              <p class="relative z-10 font-medium italic">介護と医療は、敵対するものでも、上下があるものでもありません。利用者の命を守るための「同じチーム」です。自信を持って医療職と繋がるための『技術』を学びましょう。</p>
            </div>
            <p>この研修では、バイタルの数値の裏側にある事実を見抜く観察力と、2024年度改正で求められる「正確な報告術（ISBAR）」を網羅します。</p>
          </div>
        </div>
      `,
      learningObjectives: `
        <div class="grid grid-cols-1 gap-6">
          <div class="group p-6 bg-white border border-slate-100 rounded-3xl shadow-sm hover:shadow-rose-50 transition-all duration-500 flex items-start gap-6">
            <div class="w-14 h-14 bg-rose-600 text-white rounded-2xl flex items-center justify-center text-xl font-black shrink-0 shadow-lg group-hover:scale-110 transition-transform">1</div>
            <div><h4 class="text-xl font-black text-slate-900 mb-2">疾病の早期発見と観察術</h4><p class="text-slate-500 leading-relaxed font-medium">高齢者に多い疾患（誤嚥性肺炎・脳血管障害等）の兆候を理解し、バイタル数値と「見た目」を統合したアセスメントができる。</p></div>
          </div>
          <div class="group p-6 bg-white border border-slate-100 rounded-3xl shadow-sm hover:shadow-rose-50 transition-all duration-500 flex items-start gap-6">
            <div class="w-14 h-14 bg-rose-600 text-white rounded-2xl flex items-center justify-center text-xl font-black shrink-0 shadow-lg group-hover:scale-110 transition-transform">2</div>
            <div><h4 class="text-xl font-black text-slate-900 mb-2">正確な報告スキル（ISBAR）</h4><p class="text-slate-500 leading-relaxed font-medium">介護職が行える医行為の法的範囲を正しく理解し、医師や看護師へ正確に情報を伝える国際標準の報告術をマスターする。</p></div>
          </div>
        </div>
      `,
      slides: {
        create: [
          { title: '医療連携：命をつなぐ観察と報告', order: 0, content: `<div class="flex flex-col items-center justify-center min-h-[300px] text-center space-y-12"><div class="relative"><div class="absolute inset-0 bg-rose-400 blur-3xl opacity-20 scale-150 animate-pulse"></div><div class="relative bg-white p-10 rounded-[3rem] shadow-2xl border border-slate-100 max-w-sm"><div class="bg-rose-600 text-white px-6 py-1.5 rounded-full text-[10px] font-black tracking-[0.3em] uppercase inline-block mb-6">Medical Collaboration</div><h2 class="text-3xl font-black text-slate-900 leading-tight mb-4">医療に関する研修<br/>〜介護職にこそ必要な医学知識〜</h2></div></div><div class="flex items-center gap-4 text-slate-400 font-black text-[10px] tracking-widest"><span class="h-px w-8 bg-slate-200"></span>CARE LEARNING SYSTEM<span class="h-px w-8 bg-slate-200"></span></div></div>` },
          { title: 'バイタルサイン：数値の「裏」を読み解く', order: 1, content: `<div class="space-y-8"><div class="inline-flex items-center gap-3 px-4 py-2 bg-rose-50 text-rose-600 rounded-full text-xs font-black ring-1 ring-rose-100"><span class="w-2 h-2 bg-rose-600 rounded-full animate-ping"></span>VITAL SIGNS</div><h4 class="text-2xl font-black text-slate-900 leading-tight">数値が「正常」でも、<br/><span class="text-rose-600 decoration-4 underline underline-offset-8">重症の場合があります</span></h4><div class="grid grid-cols-1 sm:grid-cols-2 gap-4"><div class="p-6 bg-white border-2 border-slate-50 rounded-[2rem] shadow-sm"><p class="text-sm font-black text-slate-900 mb-2">体温の落とし穴</p><p class="text-[11px] text-slate-500 font-medium leading-relaxed">高齢者は平熱が低いため、37.0度でも発熱（重い感染症）の初期兆候であることがあります。数値だけでなく、顔の赤らみや「熱さ」を重視してください。</p></div><div class="p-6 bg-white border-2 border-slate-50 rounded-[2rem] shadow-sm"><p class="text-sm font-black text-slate-900 mb-2">SpO2の重要性</p><p class="text-[11px] text-slate-500 font-medium leading-relaxed">酸素飽和度は呼吸の質を示します。90%以下は緊急。また、いつもより「2〜3%低い」だけでも、肺炎や脱水の可能性があります。</p></div></div></div>` },
          { title: '「いつもと違う」を見抜く4つの視点', order: 2, content: `<div class="space-y-8"><div class="flex flex-col items-center text-center"><div class="bg-slate-100 px-4 py-1 rounded-full text-[10px] font-black text-slate-500 tracking-widest uppercase mb-4">Observation Analysis</div><h4 class="text-xl font-black text-slate-900 leading-relaxed">数値に表れない「異変の正体」</h4></div><div class="relative grid grid-cols-2 gap-px bg-slate-200 p-px rounded-[2rem] overflow-hidden border border-slate-200 shadow-2xl"><div class="p-6 bg-white text-center space-y-3"><div class="w-10 h-10 bg-rose-50 text-rose-600 rounded-full flex items-center justify-center font-black mx-auto">A</div><p class="text-xs font-black text-slate-900">顔色・表情</p><p class="text-[9px] text-slate-400 leading-tight">青白い、赤ら顔、目が合わない、表情が硬い、呼びかけへの反応が鈍い</p></div><div class="p-6 bg-white text-center space-y-3"><div class="w-10 h-10 bg-rose-50 text-rose-600 rounded-full flex items-center justify-center font-black mx-auto">B</div><p class="text-xs font-black text-slate-900">食事・水分</p><p class="text-[9px] text-slate-400 leading-tight">急に食欲が落ちた、飲み込みが悪い、口の中に食べ物を溜めている</p></div><div class="p-6 bg-white text-center space-y-3"><div class="w-10 h-10 bg-rose-50 text-rose-600 rounded-full flex items-center justify-center font-black mx-auto">C</div><p class="text-xs font-black text-slate-900">排泄・尿</p><p class="text-[9px] text-slate-400 leading-tight">尿の色が濃い、回数が極端に少ない（脱水の兆候）、便秘が続いている</p></div><div class="p-6 bg-white text-center space-y-3"><div class="w-10 h-10 bg-rose-50 text-rose-600 rounded-full flex items-center justify-center font-black mx-auto">D</div><p class="text-xs font-black text-slate-900">動作・意識</p><p class="text-[9px] text-slate-400 leading-tight">歩き方がふらつく、ろれつが回らない、急に怒りっぽくなった（脳への影響）</p></div></div></div>` },
          { title: '介護職ができる「医行為」の境界線', order: 3, content: `<div class="space-y-8"><div class="p-8 bg-rose-50 rounded-[2.5rem] border-2 border-rose-100 border-dashed relative text-center"><div class="absolute -top-4 left-1/2 -translate-x-1/2 bg-rose-600 text-white px-6 py-1 rounded-full text-[10px] font-black tracking-widest uppercase">Legal Scope</div><h4 class="text-2xl font-black text-rose-900 mb-4">法的範囲を正しく守る</h4><p class="text-[11px] text-rose-800 italic font-medium">「親切心」での処置が、重大な法的トラブルを招くことがあります。</p></div><div class="bg-white p-8 rounded-[2rem] border border-slate-100 shadow-xl"><div class="grid grid-cols-2 gap-4 text-left"><div class="p-4 bg-slate-50 rounded-2xl"><p class="text-[10px] font-black text-slate-900">○ 医行為ではない（実施可能）</p><p class="text-[9px] text-slate-500 leading-relaxed">・爪切り（周囲に異常なし）<br/>・耳垢清掃（耳垢栓塞以外）<br/>・皮膚への軟膏塗布<br/>・市販の目薬点眼</p></div><div class="p-4 bg-slate-50 rounded-2xl"><p class="text-[10px] font-black text-slate-900">× 医行為（原則禁止）</p><p class="text-[9px] text-slate-500 leading-relaxed">・インスリン注射（自己注射支援以外）<br/>・褥瘡の処置<br/>・摘便<br/>・特定研修を受けていない喀痰吸引</p></div></div></div></div>` },
          { title: '誤嚥性肺炎を防ぐ「口腔ケア」の力', order: 4, content: `<div class="p-10 bg-rose-50 rounded-[3rem] border border-rose-100 flex flex-col items-center text-center space-y-6"><div class="w-20 h-20 bg-white rounded-[2rem] shadow-xl flex items-center justify-center"><svg class="w-10 h-10 text-rose-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M14.828 14.828a4 4 0 01-5.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg></div><h4 class="text-2xl font-black text-rose-900">口腔ケアは「命のケア」</h4><p class="text-slate-600 text-sm font-medium leading-relaxed">高齢者の死亡原因の上位である「誤嚥性肺炎」。口の中の細菌を減らすだけで、発症リスクを激減させることができます。食後の丁寧な清掃と、パタカラ体操などの嚥下機能訓練をチームで徹底しましょう。</p></div>` },
          { title: '魔法の報告術：ISBAR（アイズバー）', order: 5, content: `<div class="space-y-6"><div class="bg-slate-900 text-white p-10 rounded-[2.5rem] shadow-2xl relative overflow-hidden"><h4 class="text-xs font-black tracking-[0.3em] uppercase opacity-50 mb-6">Professional Handover</h4><p class="text-sm text-emerald-400 font-black mb-4">医師や看護師へ、根拠（エビデンス）を伝える構成</p><div class="space-y-3 text-sm font-black text-left"><p><span class="text-rose-400 mr-2">I (Identity):</span> 私はコスモス苑の〇〇です。△△様について報告します</p><p><span class="text-rose-400 mr-2">S (Situation):</span> 今、発熱が38度あり、呼吸が荒いです</p><p><span class="text-rose-400 mr-2">B (Background):</span> 既往に心疾患があり、今朝から食欲がありませんでした</p><p><span class="text-rose-400 mr-2">A (Assessment):</span> 脱水と肺炎の疑いがあると感じます</p><p><span class="text-rose-400 mr-2">R (Recommendation):</span> 受診すべきか、指示をいただけますか？</p></div></div></div>` },
          { title: '内服管理：5つの「正しい」の徹底', order: 6, content: `<div class="space-y-8"><div class="p-8 bg-white border-2 border-rose-100 rounded-[2.5rem] shadow-sm text-center"><h4 class="text-xl font-black text-rose-900 mb-4">与薬ミスは「組織の事故」</h4><div class="grid grid-cols-5 gap-2 text-[9px] font-black text-rose-600 uppercase mb-4"><p>1. 正しい人</p><p>2. 正しい薬</p><p>3. 正しい量</p><p>4. 方法</p><p>5. 時間</p></div><p class="text-xs text-slate-500 leading-relaxed font-medium">特に「他者の薬」を飲ませてしまう事故は、命に直結します。手渡し前の指差し呼称と、ダブルチェックを絶対に怠らないでください。</p></div></div>` },
          { title: 'シミュレーション：数値に出ない異変', order: 7, content: `<div class="space-y-6"><div class="p-8 bg-orange-50 border-2 border-orange-100 rounded-[2.5rem] text-center"><p class="text-orange-900 text-lg font-black leading-relaxed">夕食時、A様が珍しく半分以上食べ残し、ぼんやりしています。熱は36.5度、血圧も正常です。あなたならどうしますか？</p></div><div class="grid grid-cols-1 gap-4"><div class="p-6 bg-white border border-slate-100 rounded-2xl shadow-sm flex items-center gap-4 opacity-60"><span class="w-10 h-10 bg-slate-100 text-slate-400 rounded-xl flex items-center justify-center font-black">×</span><p class="text-xs font-bold italic">バイタルが正常なので、「眠いだけかな」と自己判断してそのまま就寝介助する</p></div><div class="p-6 bg-white border border-emerald-100 rounded-2xl shadow-xl ring-2 ring-emerald-50 flex items-center gap-4"><span class="w-10 h-10 bg-emerald-600 text-white rounded-xl flex items-center justify-center font-black shadow-lg">○</span><p class="text-xs font-black text-slate-900 font-bold">「いつもと違う」ことを看護師にISBARで即報告する。食べ残しの様子や、視線の合いにくさ等の観察事実を併せて伝える。</p></div></div></div>` },
          { title: 'まとめ：チーム医療の架け橋として', order: 8, content: `<div class="flex flex-col items-center justify-center min-h-[450px] text-center space-y-10"><div class="w-24 h-24 bg-rose-600 rounded-[2.5rem] flex items-center justify-center shadow-2xl shadow-rose-200 rotate-3"><svg class="w-12 h-12 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" /></svg></div><h3 class="text-3xl font-black text-slate-900 leading-tight">医療連携は、<br/>信頼のバトンパスです。</h3><p class="text-slate-500 font-medium text-lg max-w-sm mx-auto leading-relaxed">一番近くにいるあなたの「気づき」が、利用者の命をつないでいます。自信を持って、その声を届けてください。</p><div class="pt-10 border-t border-slate-100 w-full"><p class="text-slate-400 font-black text-xs uppercase tracking-[0.3em]">End of Session</p></div></div>` }
        ]
      },
      questions: {
        create: [
          { text: '高齢者のバイタルサイン観察において、正しい知識はどれか。', explanation: '高齢者は平熱が低く、重症でも熱が上がりにくい場合があるため、37度台であっても数値だけでなく全身状態の観察が重要です。', order: 1, choices: { create: [{ text: '平熱が低いため37度台でも発熱のサインである可能性がある', isCorrect: true }, { text: '38度を超えなければ異常なしと判断してよい', isCorrect: false }, { text: '数値さえ正常なら、顔色が悪くても報告の必要はない', isCorrect: false }] } },
          { text: '医療職や看護師への正確な情報伝達のために用いられる、報告の標準的な構成手法を何というか。', explanation: 'ISBAR（状況・背景・評価・提案）と呼ばれる世界標準の手法です。2024年度の改定でも医療連携の要として重視されています。', order: 2, choices: { create: [{ text: 'ISBAR（アイズバー）', isCorrect: true }, { text: 'PDCAサイクル', isCorrect: false }, { text: 'SWOT分析', isCorrect: false }] } },
          { text: '介護職員が原則として「医行為ではない」として実施できる処置はどれか。', explanation: '爪切り（周囲に異常なし）、耳垢清掃、軟膏塗布、目薬の点眼などは医行為に該当しません。', order: 3, choices: { create: [{ text: '爪切り、耳垢清掃、皮膚への軟膏塗布', isCorrect: true }, { text: 'インスリン注射の実施', isCorrect: false }, { text: '褥瘡（床ずれ）の処置', isCorrect: false }] } },
          { text: '誤嚥性肺炎を予防するために、介護現場で最も効果的とされる日常ケアはどれか。', explanation: '口腔ケアにより口内の細菌数を抑制することが、肺への細菌侵入を防ぎ、肺炎発症のリスクを劇減させます。', order: 4, choices: { create: [{ text: '食後の丁寧な口腔ケア', isCorrect: true }, { text: '居室の掃除', isCorrect: false }, { text: '入浴の回数を増やすこと', isCorrect: false }] } },
          { text: '喀痰吸引や経管栄養を介護職員が実施するために不可欠な法的手続きはどれか。', explanation: '所定の研修を修了し、都道府県に「認定特定行為業務従事者」として登録されている必要があります。', order: 5, choices: { create: [{ text: '都道府県への認定特定行為業務従事者登録', isCorrect: true }, { text: '現場リーダーの口頭での許可', isCorrect: false }, { text: '本人の家族からの承諾のみ', isCorrect: false }] } }
        ]
      }
    }
  })
}
