import { PrismaClient } from '@prisma/client'

export async function seedTerminal(prisma: PrismaClient) {
  const slug = 'terminal'
  const courseData = {
    slug,
    title: '看取り・ターミナルケア研修（2024年度）',
    description: '〜尊厳ある人生の最終段階を支えるために〜',
    introduction: `
        <div class="flex flex-col items-center justify-center text-center space-y-2 pt-2 px-4 text-balance">
          <div class="flex items-center gap-4">
            <span class="h-px w-8 lg:w-12 bg-rose-700 rounded-full"></span>
            <p class="text-rose-800 font-black tracking-widest text-lg lg:text-xl uppercase">看取り・ターミナルケア</p>
            <span class="h-px w-8 lg:w-12 bg-rose-700 rounded-full"></span>
          </div>
          <h2 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight">「最期まで自分らしく」を支える、<br/>人生のフィナーレに伴走する。</h2>
          <div class="max-w-2xl space-y-2 text-slate-800 text-sm lg:text-base leading-relaxed font-bold px-4 text-center">
            <p>看取りは、死を待つ時間ではありません。最期までその人らしく「今を生きる」時間を支える、究極のケアです。</p>
            <div class="p-3 lg:p-4 bg-rose-50 rounded-[1.5rem] lg:rounded-[2rem] border-2 border-rose-200 shadow-inner relative overflow-hidden text-[10px] lg:text-xs text-left">
              <div class="absolute top-0 right-0 w-16 h-16 lg:w-20 lg:h-20 bg-rose-100/50 rounded-bl-full"></div>
              <p class="relative z-10 italic text-rose-900 font-black text-xs lg:text-sm leading-relaxed">ご本人の意向、ご家族の葛藤。そのすべてを包み込み、迷いながらも共に進む。介護職にしかできない「温かな看取り」のカタチを学びましょう。</p>
            </div>
            <p class="text-[10px] lg:text-sm text-slate-900 font-black text-center mt-2">この研修は、尊厳ある旅立ちを支えるための「心の地図」を描くためのものです。</p>
          </div>
        </div>
      `,
    learningObjectives: `
        <div class="flex flex-col items-center justify-center text-center space-y-3 pt-2 px-4 w-full text-balance">
          <div class="bg-rose-700 text-white px-6 py-1.5 rounded-full text-[10px] font-black tracking-[0.3em] uppercase mb-1 shadow-lg shadow-rose-200">Learning Objectives</div>
          <div class="grid grid-cols-1 gap-2 w-full max-w-2xl">
            <div class="group p-3 lg:p-4 bg-white border-2 border-slate-200 rounded-[1.5rem] lg:rounded-[2rem] shadow-sm flex items-center gap-4 lg:gap-6 hover:shadow-xl hover:border-rose-400 transition-all duration-500 text-center lg:text-left">
              <div class="w-10 h-10 lg:w-12 lg:h-12 bg-rose-700 text-white rounded-xl flex items-center justify-center text-base lg:text-lg font-black shrink-0 shadow-lg shadow-rose-200">1</div>
              <div class="text-left">
                <h4 class="text-sm lg:text-base font-black text-slate-900">ACP（人生会議）を実践できる</h4>
                <p class="text-slate-800 text-[10px] lg:text-xs font-bold leading-tight">本人の意向を繰り返し確認し、多職種・家族と共有するプロセスを習得する。</p>
              </div>
            </div>
            <div class="group p-3 lg:p-4 bg-white border-2 border-slate-200 rounded-[1.5rem] lg:rounded-[2rem] shadow-sm flex items-center gap-4 lg:gap-6 hover:shadow-xl hover:border-rose-400 transition-all duration-500 text-center lg:text-left">
              <div class="w-10 h-10 lg:w-12 lg:h-12 bg-rose-700 text-white rounded-xl flex items-center justify-center text-base lg:text-lg font-black shrink-0 shadow-lg shadow-rose-200">2</div>
              <div class="text-left">
                <h4 class="text-sm lg:text-base font-black text-slate-900">苦痛の緩和と変化の察知</h4>
                <p class="text-slate-800 text-[10px] lg:text-xs font-bold leading-tight">ターミナル期の身体的・精神的変化を理解し、非薬物的な緩和ケアを行う。</p>
              </div>
            </div>
            <div class="group p-3 lg:p-4 bg-white border-2 border-slate-200 rounded-[1.5rem] lg:rounded-[2rem] shadow-sm flex items-center gap-4 lg:gap-6 hover:shadow-xl hover:border-rose-400 transition-all duration-500 text-center lg:text-left">
              <div class="w-10 h-10 lg:w-12 lg:h-12 bg-rose-700 text-white rounded-xl flex items-center justify-center text-base lg:text-lg font-black shrink-0 shadow-lg shadow-rose-200">3</div>
              <div class="text-left">
                <h4 class="text-sm lg:text-base font-black text-slate-900">ご家族へのグリーフケア</h4>
                <p class="text-slate-800 text-[10px] lg:text-xs font-bold leading-tight">死別前後の悲しみに寄り添い、これまでの介護を肯定する支援技術を学ぶ。</p>
              </div>
            </div>
          </div>
        </div>
      `,
    videoUrl: null,
    badgeLabel: '看取り',
    badgeIcon: 'Heart',
  }

  const slidesData = [
    { title: "看取り・ターミナルケア研修", order: 0, content: `<div class="flex flex-col items-center justify-center text-center space-y-4 w-full h-full text-balance"><div class="relative w-full max-w-4xl px-4"><div class="absolute inset-0 bg-rose-400 blur-3xl opacity-20 scale-150 animate-pulse text-center"></div><div class="relative bg-transparent lg:bg-white p-0 lg:p-12 rounded-none lg:rounded-[3.5rem] shadow-none lg:shadow-2xl border-none lg:border lg:border-slate-200 w-full mx-auto text-center"><div class="bg-rose-700 text-white px-4 lg:px-6 py-1 lg:py-1.5 rounded-full text-[8px] lg:text-[10px] font-black tracking-[0.3em] uppercase inline-block mb-6 lg:mb-8 shadow-sm">法定研修 2024</div><h2 class="text-3xl lg:text-5xl font-black text-slate-900 leading-tight mb-4 text-center">看取り・ターミナルケア</h2><p class="text-rose-700 text-sm lg:text-2xl font-black mt-2 whitespace-nowrap text-center">〜尊厳ある人生の終焉を支える〜</p></div></div><div class="flex items-center justify-center gap-4 text-slate-500 font-black text-[8px] lg:text-[10px] tracking-widest pt-4 text-center w-full"><span class="h-px w-6 lg:w-8 bg-slate-300"></span>CARE LEARNING SYSTEM<span class="h-px w-6 lg:w-8 bg-slate-300"></span></div></div>` },
    { title: "看取りの定義：今を生きる支援", order: 1, content: `<div class="space-y-4 lg:space-y-6 text-center px-4 h-full flex flex-col justify-center text-balance text-center"><div class="inline-flex items-center gap-3 px-4 py-1.5 bg-rose-100 text-rose-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-rose-200 mb-2 uppercase tracking-widest mx-auto text-center">基本理念</div><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4 text-center w-full">死を待つ時間ではない</h4><div class="p-0 lg:p-8 bg-transparent lg:bg-rose-50 border-none lg:border-2 lg:border-rose-100 shadow-none lg:shadow-xl rounded-none lg:rounded-[3rem] text-center lg:text-left text-sm lg:text-lg font-bold text-rose-800 space-y-4 max-w-4xl mx-auto px-4 text-center"><p class="font-black text-center">看取り介護とは、近い将来死に至ることが避けられない方に対し、その人らしい尊厳を保ち、苦痛を最小限にして、安らかな最期を迎えられるよう援助することです。</p></div></div>` },
    { title: "2024年度 改正ガイドライン", order: 2, content: `<div class="space-y-4 lg:space-y-6 text-center px-4 h-full flex flex-col justify-center text-balance"><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight mb-2 px-4 text-center w-full">意思決定支援の強化</h4><div class="grid grid-cols-1 lg:grid-cols-2 gap-4 max-w-4xl mx-auto w-full"><div class="p-6 lg:p-8 bg-white border-2 border-slate-200 rounded-[2rem] lg:rounded-[2.5rem] shadow-xl flex flex-col items-center gap-2 lg:gap-4"><p class="font-black text-lg lg:text-xl text-rose-800 text-center">人生会議（ACP）</p><p class="text-xs lg:text-sm font-bold text-slate-700 leading-relaxed text-center">元気な時から、最期の医療やケアについて話し合い、共有し続けるプロセスを重視します。</p></div><div class="p-6 lg:p-8 bg-white border-2 border-slate-200 rounded-[2rem] lg:rounded-[2.5rem] shadow-xl flex flex-col items-center gap-2 lg:gap-4"><p class="font-black text-lg lg:text-xl text-rose-800 text-center">多職種チームの合意</p><p class="text-xs lg:text-sm font-bold text-slate-700 leading-relaxed text-center">医師、看護師、介護職、家族が方針を一致させ、一貫したケアを提供します。</p></div></div></div>` },
    { title: "看取りの3原則：尊厳・共感・連携", order: 3, content: `<div class="space-y-6 lg:space-y-8 text-center h-full flex flex-col justify-center px-4 text-balance text-center"><div class="inline-flex items-center gap-3 px-4 py-2 bg-rose-100 text-rose-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-rose-200 mb-2 shadow-sm mx-auto uppercase tracking-widest text-center"><span class="w-2 h-2 bg-rose-700 rounded-full animate-ping"></span>MUST CHECK</div><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight text-center w-full">支え抜くための3つの柱</h4><div class="grid grid-cols-1 lg:grid-cols-3 gap-3 lg:gap-4 max-w-5xl mx-auto w-full px-4 text-center"><div class="p-4 bg-white border-2 border-slate-200 rounded-2xl shadow-sm font-black">苦痛を除去する</div><div class="p-4 bg-white border-2 border-slate-200 rounded-2xl shadow-sm font-black">孤独にさせない</div><div class="p-4 bg-white border-2 border-slate-200 rounded-2xl shadow-sm font-black">意向を尊重する</div></div></div>` },
    { title: "ターミナル期の身体的変化", order: 4, content: `<div class="flex flex-col items-center text-center space-y-4 lg:space-y-6 px-4 h-full justify-center text-balance text-center"><div class="p-4 lg:p-6 bg-white rounded-[2rem] lg:rounded-[3.5rem] w-full max-w-2xl shadow-xl border-2 border-slate-200 shrink-0 text-center"><h4 class="text-xl lg:text-2xl font-black mb-2 text-slate-900 text-center text-balance px-4">自然な終わりのプロセス</h4></div><div class="grid grid-cols-1 lg:grid-cols-2 gap-3 font-black text-[10px] lg:text-sm w-full max-w-5xl"><div class="p-3 bg-rose-50 border-2 border-rose-200 rounded-2xl text-left"><p class="text-rose-900 mb-1">睡眠時間の増大</p><p class="text-slate-600">ウトウトする時間が増え、外界への反応が弱まります。</p></div><div class="p-3 bg-rose-50 border-2 border-rose-200 rounded-2xl text-left"><p class="text-rose-900 mb-1">食事・飲水の低下</p><p class="text-slate-600">栄養を必要としなくなり、内臓を休める準備に入ります。</p></div><div class="p-3 bg-rose-50 border-2 border-rose-200 rounded-2xl text-left"><p class="text-rose-900 mb-1">末梢の冷感・皮膚色</p><p class="text-slate-600">血流が中心部に集まり、手足が冷たく、斑紋が出ます。</p></div><div class="p-3 bg-rose-50 border-2 border-rose-200 rounded-2xl text-left"><p class="text-rose-900 mb-1">呼吸のリズム変化</p><p class="text-slate-600">下顎呼吸や無呼吸、死の喘鳴（ゴロゴロ）が見られます。</p></div></div></div>` },
    { title: "苦痛の緩和：介護職にできること", order: 5, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left text-balance text-center"><div class="space-y-4"><h4 class="text-2xl lg:text-4xl font-black text-rose-900 flex items-center gap-4 lg:gap-6 justify-center"><span class="w-2 h-8 lg:w-3 lg:h-12 bg-rose-700 rounded-full"></span>非薬物的なケア</h4></div><ul class="space-y-4 lg:space-y-6 text-lg lg:text-3xl font-black text-slate-800 pl-0 leading-tight text-center"><li>・口渇への口腔ケア（湿潤保持）</li><li>・呼吸を楽にする体位（半坐位等）</li><li>・不快な寝衣やシーツのシワ除去</li></ul><p class="text-rose-700 font-black text-sm lg:text-xl mt-4 text-center w-full">「触れる」「さする」タッチケアの力</p></div>` },
    { title: "精神的苦痛とスピリチュアルケア", order: 6, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left text-balance text-center"><div class="space-y-4"><h4 class="text-2xl lg:text-4xl font-black text-rose-900 flex items-center gap-4 lg:gap-6 justify-center"><span class="w-2 h-8 lg:w-3 lg:h-12 bg-rose-700 rounded-full"></span>人生の意味を肯定する</h4></div><ul class="space-y-4 lg:space-y-6 text-lg lg:text-3xl font-black text-slate-800 pl-0 leading-tight text-center"><li>・過去の思い出や功績を共に語る</li><li>・「ありがとう」を言葉で伝える</li><li>・孤独を感じさせない「そばにいる」時間</li></ul></div>` },
    { title: "意思決定支援：迷いを受け止める", order: 7, content: `<div class="flex flex-col items-center text-center space-y-4 lg:space-y-6 px-4 h-full justify-center text-balance text-center"><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight text-center w-full">揺れる思いこそが真実</h4><div class="grid grid-cols-1 lg:grid-cols-2 gap-3 font-black text-sm lg:text-base w-full max-w-4xl text-center"><div class="flex flex-col gap-3"><span class="px-6 py-2.5 bg-rose-50 border-2 border-rose-200 rounded-2xl text-rose-900 shadow-sm text-center text-balance">「延命はしない」と言ったのに…</span><span class="px-6 py-2.5 bg-rose-50 border-2 border-rose-200 rounded-2xl text-rose-900 shadow-sm text-center text-balance">家族間での意見の相違</span></div><div class="flex flex-col gap-3"><span class="px-6 py-2.5 bg-rose-50 border-2 border-rose-200 rounded-2xl text-rose-900 shadow-sm text-center text-balance">本人の沈黙の意味を考える</span><span class="px-6 py-2.5 bg-rose-50 border-2 border-rose-200 rounded-2xl text-rose-900 shadow-sm text-center text-balance">何度でも話し合いを重ねる</span></div></div><p class="text-rose-700 font-black text-sm lg:text-xl px-4 text-center w-full">結論を急がず、プロセスに寄り添います。</p></div>` },
    { title: "食事と水分の考え方", order: 8, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left text-balance text-center"><h4 class="text-xl lg:text-2xl font-black text-rose-900 text-center w-full">無理強いしない優しさ</h4><ul class="space-y-4 lg:space-y-6 text-sm lg:text-xl font-black text-slate-800 pl-0 leading-tight text-center w-full"><li>・飲めない・食べられないのは自然な準備</li><li>・過度な点滴は浮腫や喘鳴を招く恐れ</li><li>・「一口の楽しみ」を大切にする</li></ul><p class="text-blue-700 font-black text-center w-full mt-4 text-sm lg:text-lg">「食べさせない」のではなく「身体に合わせる」</p></div>` },
    { title: "ご家族への支援：心の準備", order: 9, content: `<div class="flex flex-col items-center justify-center h-full space-y-6 lg:space-y-8 px-4 w-full text-balance text-center"><h4 class="text-xl lg:text-2xl font-black text-slate-900 text-center w-full mb-2 px-4">「看取って良かった」のために</h4><div class="grid grid-cols-1 gap-3 lg:gap-4 w-full max-w-2xl text-center"><div class="flex items-center gap-4 bg-white p-3 rounded-2xl border-2 border-slate-100 shadow-sm font-black justify-center lg:justify-start text-sm lg:text-base"><span class="w-10 h-10 bg-rose-700 text-white rounded-full flex items-center justify-center shrink-0">1</span>経過を丁寧に、具体的に伝える</div><div class="flex items-center gap-4 bg-white p-3 rounded-2xl border-2 border-slate-100 shadow-sm font-black justify-center lg:justify-start text-sm lg:text-base"><span class="w-10 h-10 bg-rose-700 text-white rounded-full flex items-center justify-center shrink-0">2</span>最期の瞬間に立ち会えるよう配慮する</div><div class="flex items-center gap-4 bg-white p-3 rounded-2xl border-2 border-slate-100 shadow-sm font-black justify-center lg:justify-start text-sm lg:text-base"><span class="w-10 h-10 bg-rose-700 text-white rounded-full flex items-center justify-center shrink-0">3</span>これまでの介護への労いを言葉にする</div></div></div>` },
    { title: "臨終の前兆と看取りの瞬間", order: 10, content: `<div class="flex flex-col items-center justify-center h-full space-y-6 lg:space-y-8 px-4 w-full text-balance text-center"><h4 class="text-xl lg:text-2xl font-black text-red-900 text-center w-full mb-2 px-4 animate-pulse">その時、慌てないために</h4><div class="grid grid-cols-1 gap-3 lg:gap-4 w-full max-w-2xl text-center"><div class="flex items-center gap-4 bg-white p-3 rounded-2xl border-2 border-red-100 shadow-sm font-black justify-center lg:justify-start text-sm lg:text-base"><span class="w-10 h-10 bg-red-600 text-white rounded-full flex items-center justify-center shrink-0">1</span>呼吸の停止、脈拍の消失を確認</div><div class="flex items-center gap-4 bg-white p-3 rounded-2xl border-2 border-red-100 shadow-sm font-black justify-center lg:justify-start text-sm lg:text-base"><span class="w-10 h-10 bg-red-600 text-white rounded-full flex items-center justify-center shrink-0">2</span>速やかに看護師・医師へ連絡</div><div class="flex items-center gap-4 bg-white p-3 rounded-2xl border-2 border-red-100 shadow-sm font-black justify-center lg:justify-start text-sm lg:text-base"><span class="w-10 h-10 bg-red-600 text-white rounded-full flex items-center justify-center shrink-0">3</span>家族が到着するまで、一人にしない</div></div></div>` },
    { title: "死後の処置：エンゼルケア", order: 11, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-6 lg:space-y-8 px-4 w-full text-balance text-center"><div class="inline-flex items-center gap-3 px-4 py-1.5 bg-rose-100 text-rose-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-rose-200 mb-2 mx-auto text-center">最後のおめかし</div><h4 class="text-xl lg:text-2xl font-black text-rose-900 leading-tight px-4 text-center w-full">尊厳ある旅立ちの準備</h4><div class="p-6 lg:p-10 bg-white border-[4px] lg:border-[6px] border-rose-600 rounded-[2rem] lg:rounded-[3rem] shadow-2xl max-w-3xl mx-auto w-full text-center"><p class="text-lg lg:text-2xl font-black text-rose-900 leading-relaxed italic text-balance text-center">その人らしい装いを整え、ご家族と共に感謝を込めて行います。これは、ご家族が死を受け入れるための大切な儀式でもあります。</p></div></div>` },
    { title: "グリーフケア：悲しみに伴走する", order: 12, content: `<div class="flex flex-col items-center justify-center h-full text-left space-y-4 lg:space-y-6 px-6 lg:px-12 w-full text-balance text-center"><h4 class="text-xl lg:text-2xl font-black text-rose-700 text-center mb-2 uppercase tracking-widest w-full px-4">死別後の支援</h4><div class="space-y-6 lg:space-y-8 font-black text-slate-900 max-w-4xl mx-auto w-full text-center"><div><p class="text-lg lg:text-2xl text-rose-600 mb-1 flex items-center gap-3 justify-center text-center"><span>●</span> 感情の受容</p><p class="text-sm lg:text-lg text-slate-600 font-bold text-center">無理に励まさず、悲しみを出し切るのを待つ。</p></div><div><p class="text-lg lg:text-2xl text-rose-600 mb-1 flex items-center gap-3 justify-center text-center"><span>●</span> 意味づけの支援</p><p class="text-sm lg:text-lg text-slate-600 font-bold text-center">「最期に立ち会えてよかったですね」等の声かけ。</p></div><div><p class="text-lg lg:text-2xl text-rose-600 mb-1 flex items-center gap-3 justify-center text-center"><span>●</span> 後悔の緩和</p><p class="text-sm lg:text-lg text-slate-600 font-bold text-center">「十分すぎるほど尽くされましたよ」と伝える。</p></div></div></div>` },
    { title: "介護職自身の心のセルフケア", order: 13, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-4 lg:space-y-6 px-4 w-full text-balance text-center text-balance"><h4 class="text-xl lg:text-2xl font-black text-rose-900 text-center w-full px-4">燃え尽きを防ぐために</h4><div class="p-6 bg-white border-2 border-rose-100 rounded-3xl text-left max-w-3xl space-y-4 shadow-sm mx-auto text-center"><p class="text-sm lg:text-lg font-black text-slate-800 leading-relaxed text-center text-balance">看取りは職員にも大きな心理的影響を与えます。一人の死を全員で共有し、感情を吐き出せるデブリーフィング（振り返り）の場を大切にしましょう。悲しむことは、プロとして恥ずべきことではありません。</p></div></div>` },
    { title: "1. 事例：意思が揺れるご家族", order: 14, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-4 lg:space-y-6 px-4 w-full text-balance text-center"><div class="inline-flex items-center gap-3 px-4 py-1.5 bg-rose-50 text-rose-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-rose-200 mb-2 mx-auto text-center">事例 1</div><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4 text-center w-full">場面：救急搬送を巡る迷い</h4><div class="p-6 lg:p-8 bg-white border-2 border-slate-100 rounded-[2rem] lg:rounded-[3rem] shadow-xl max-w-4xl text-left space-y-4 w-full text-center"><p class="text-sm lg:text-lg font-bold text-slate-800 leading-relaxed text-balance px-4 text-center text-center">「自然に逝かせてあげたい」と言っていた長男様が、いざ呼吸が苦しくなった母を前にして「やっぱり病院へ連れて行って！」と叫ばれました。あなたはどう動きますか？</p><div class="h-px bg-slate-100"></div><p class="text-xs lg:text-base font-black text-rose-700 italic text-center px-4 text-balance text-center w-full">この瞬間のご家族の「心」に、どう寄り添いますか？</p></div></div>` },
    { title: "2. 事例：夜間の静かな旅立ち", order: 15, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-4 lg:space-y-6 px-4 w-full text-balance text-center"><div class="inline-flex items-center gap-3 px-4 py-1.5 bg-rose-50 text-rose-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-rose-200 mb-2 mx-auto text-center">事例 2</div><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4 text-center w-full text-balance text-center">場面：一人にさせない体制</h4><div class="p-6 lg:p-8 bg-white border-2 border-slate-100 rounded-[2rem] lg:rounded-[3rem] shadow-xl max-w-4xl text-left space-y-4 w-full text-center"><p class="text-sm lg:text-lg font-bold text-slate-800 leading-relaxed text-balance px-4 text-center text-balance text-center">深夜、巡回時にE様の呼吸が止まっているのを発見しました。家族への連絡、主治医への連絡。少人数の夜勤帯で、あなたが優先すべき初動は何ですか？</p><div class="h-px bg-slate-100"></div><p class="text-xs lg:text-base font-black text-rose-700 italic text-center px-4 text-balance text-center w-full">「死後の処置」を始める前に、すべきことは何ですか？</p></div></div>` },
    { title: "解決：尊厳あるフィナーレを支える", order: 16, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-4 lg:space-y-6 px-4 w-full text-balance text-center text-center"><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4 text-center w-full text-center">プロとしての回答</h4><div class="p-6 lg:p-10 bg-rose-50 border-2 border-rose-100 rounded-[2.5rem] lg:rounded-[4rem] shadow-inner text-left max-w-4xl space-y-4 mx-auto text-center"><p class="text-base lg:text-lg font-black text-rose-900 text-center w-full text-balance">看取りのプロの具体策</p><div class="grid grid-cols-1 gap-3 text-sm lg:text-base font-bold text-slate-800 text-center"><div class="flex items-center gap-3 lg:gap-4 bg-white p-3 rounded-xl lg:rounded-2xl border border-rose-100 shadow-sm text-center justify-center lg:justify-start"><span class="w-6 h-6 lg:w-8 lg:h-8 bg-rose-600 text-white rounded-full flex items-center justify-center text-[10px] lg:text-sm shrink-0 text-center">1</span>家族の揺れは愛情。否定せず、今の思いを医師へ繋ぐ</div><div class="flex items-center gap-3 lg:gap-4 bg-white p-3 rounded-xl lg:rounded-2xl border border-rose-100 shadow-sm text-center justify-center lg:justify-start"><span class="w-6 h-6 lg:w-8 lg:h-8 bg-rose-600 text-white rounded-full flex items-center justify-center text-[10px] lg:text-sm shrink-0 text-center">2</span>発見時はまず安らかな死を確認し、主治医へ即刻連絡</div><div class="flex items-center gap-3 lg:gap-4 bg-white p-3 rounded-xl lg:rounded-2xl border border-rose-100 shadow-sm text-center justify-center lg:justify-start"><span class="w-6 h-6 lg:w-8 lg:h-8 bg-rose-600 text-white rounded-full flex items-center justify-center text-[10px] lg:text-sm shrink-0 text-center">3</span>「そばに寄り添う時間」を何より優先し、孤独を避ける</div></div></div></div>` },
    { title: "満足感：看取って良かったと言えるケア", order: 17, content: `<div class="space-y-6 lg:space-y-8 text-center flex flex-col items-center justify-center h-full px-4 w-full text-balance text-center text-balance"><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4 text-center w-full">プロとしての貢献</h4><div class="p-8 lg:p-10 bg-white border-[4px] lg:border-[6px] border-rose-600 rounded-[2rem] lg:rounded-[3rem] shadow-2xl max-w-3xl mx-auto w-full text-center"><p class="text-xl lg:text-2xl font-black text-rose-900 leading-relaxed italic text-balance text-center text-center">「ここで最期を迎えられて良かった」<br/>その一言が、ご家族の明日を支え、<br/>あなたの専門性を証明します。</p></div><p class="font-black text-sm lg:text-lg text-slate-800 mt-2 text-center w-full px-4 text-center">その誇りを持って、日々のケアにあたりましょう。</p></div>` },
    { title: "まとめ：今日から変えられる「寄り添い」", order: 18, content: `<div class="flex flex-col items-center text-center space-y-6 lg:space-y-10 w-full h-full justify-center text-slate-900 px-4 text-center text-balance"><div class="w-24 h-24 lg:w-28 h-28 bg-rose-700 rounded-[2.5rem] lg:rounded-[3rem] flex items-center justify-center shadow-2xl rotate-3 transition-transform hover:rotate-0 duration-500 mx-auto text-center"><svg class="w-12 h-12 lg:w-16 h-16 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" /></svg></div><h3 class="text-2xl lg:text-4xl font-black leading-tight text-center w-full text-balance">最期まで、その人らしく。<br/>あなたが、その尊厳を守る盾になります。</h3><div class="pt-8 lg:pt-10 border-t-2 border-slate-200 w-full max-w-md text-center mx-auto"><p class="text-slate-500 font-black text-[8px] lg:text-[10px] uppercase tracking-[0.5em]">End of Session</p></div></div>` },
    { title: "理解度テストのご案内", order: 19, content: `
        <div class="flex flex-col items-center text-center space-y-4 lg:space-y-6 w-full h-full justify-center px-4 text-center text-balance">
          <div class="bg-emerald-600 text-white px-6 py-1.5 rounded-full text-[8px] lg:text-[10px] font-black tracking-[0.3em] uppercase inline-block mb-4 lg:mb-2 shadow-lg px-4 text-center">修了</div>
          <h2 class="text-2xl lg:text-4xl font-black text-slate-900 leading-tight mb-2 text-center w-full text-balance">講義セッション終了</h2>
          <p class="text-emerald-800 text-base lg:text-xl font-black leading-relaxed text-center w-full text-balance px-4">大変お疲れ様でした。<br/>最後に理解度テスト（全10問）を行います。</p>
          <div class="p-4 lg:p-6 bg-rose-50 rounded-2xl lg:rounded-3xl border-2 border-rose-100 max-w-lg mx-auto mt-6">
            <p class="text-rose-900 font-black text-sm lg:text-lg flex items-center justify-center gap-3 text-center">
              <span class="w-2 h-2 bg-rose-700 rounded-full"></span>    
              全問正解を目指しましょう！
              <span class="w-2 h-2 bg-rose-700 rounded-full"></span>    
            </p>
          </div>
        </div>
      ` }
  ]

  const questionsData = [
    { text: '本人が望む医療やケアについて、前もって話し合い共有するプロセスを何というか？', explanation: 'ACP（アドバンス・ケア・プランニング）と呼ばれ、日本語では「人生会議」と愛称されています。', order: 1, choices: { create: [{ text: 'ACP（人生会議）', isCorrect: true }, { text: 'BCP（業務継続計画）', isCorrect: false }, { text: 'SBAR（状況報告）', isCorrect: false }] } },
    { text: '看取り期において、食欲や水分摂取量が低下することへの見解として適切なものは？', explanation: '身体が自然に終わりへ向かう準備であり、無理な摂取は逆に苦痛（むくみ、喘鳴等）を招くことがあります。', order: 2, choices: { create: [{ text: '身体の自然な準備であり、無理強いしない', isCorrect: true }, { text: '無理にでも食べさせないと衰弱する', isCorrect: false }, { text: '点滴で無理やり水分を補給すべきである', isCorrect: false }] } },
    { text: 'ターミナル期における身体的苦痛（痛み）への対応として、介護職がすべきことは？', explanation: '表情や動作から痛みをアセスメントし、速やかに医療職へ報告して緩和を図ることが重要です。', order: 3, choices: { create: [{ text: '医療職と連携し、痛みの緩和を最優先する', isCorrect: true }, { text: '「年齢のせいだから」と様子を見る', isCorrect: false }, { text: '本人が訴えるまで放置する', isCorrect: false }] } },
    { text: '死が近づいた際に見られる、不規則で顎を動かして呼吸する状態を何というか？', explanation: '「下顎呼吸（かがくこきゅう）」と呼ばれ、臨終が近い重要なサインの一つです。', order: 4, choices: { create: [{ text: '下顎呼吸', isCorrect: true }, { text: '深呼吸', isCorrect: false }, { text: '腹式呼吸', isCorrect: false }] } },
    { text: 'ご家族が死別の悲しみを乗り越えられるよう支援することを何というか？', explanation: '「グリーフケア（悲嘆のケア）」と呼ばれ、看取り後も続く大切な支援の一部です。', order: 5, choices: { create: [{ text: 'グリーフケア', isCorrect: true }, { text: 'スキンケア', isCorrect: false }, { text: 'フットケア', isCorrect: false }] } },
    { text: '延命治療を行わない（蘇生措置を拒否する）という事前の意思表示を何というか？', explanation: 'DNAR（Do Not Attempt Resuscitation）と呼ばれ、事前にチームで共有しておく必要があります。', order: 6, choices: { create: [{ text: 'DNAR', isCorrect: true }, { text: 'AED', isCorrect: false }, { text: 'CPR', isCorrect: false }] } },
    { text: '死後の処置（エンゼルケア）の目的として、最も適切なものはどれか？', explanation: '本人の尊厳を守るとともに、ご家族が死を受け入れる心の準備を支える大切な儀式です。', order: 7, choices: { create: [{ text: '本人の尊厳保持と家族の心の準備を支える', isCorrect: true }, { text: '単なる遺体の清掃作業である', isCorrect: false }, { text: '法的な義務を果たすためだけに行う', isCorrect: false }] } },
    { text: 'ターミナル期の口腔ケアについて、適切な考え方はどれか？', explanation: '感染予防だけでなく、口の中の渇き（口渇感）による不快感を和らげるために重要です。', order: 8, choices: { create: [{ text: '口渇感を和らげるために継続する', isCorrect: true }, { text: 'もう食べないので必要ない', isCorrect: false }, { text: '危ないので一切行ってはいけない', isCorrect: false }] } },
    { text: '利用者が亡くなった後の、介護職員自身のメンタルケアについて正しいものは？', explanation: '看取りは職員にも大きな心理的影響を与えるため、チームで感情を共有し支え合うことが必要です。', order: 9, choices: { create: [{ text: 'チームで感情を共有し、支え合うべきである', isCorrect: true }, { text: 'プロなら悲しんではいけない', isCorrect: false }, { text: 'すぐに忘れて次の仕事に集中すべきである', isCorrect: false }] } },
    { text: '看取り介護において、介護職が果たらすべき最も重要な「非言語」的ケアはどれか？', explanation: '言葉がなくても、そばにいて手を握る、温かい眼差しを向けることが、最大の安心感を与えます。', order: 10, choices: { create: [{ text: 'そばに寄り添い、手を握るなどの安心感', isCorrect: true }, { text: 'テキパキと事務的に作業を終わらせること', isCorrect: false }, { text: '離れた場所で見守り続けること', isCorrect: false }] } }
  ]

  let course = await prisma.course.findUnique({ where: { slug } })

  if (course) {
    await prisma.choice.deleteMany({ where: { question: { courseId: course.id } } })
    await prisma.question.deleteMany({ where: { courseId: course.id } })
    await prisma.slide.deleteMany({ where: { courseId: course.id } })
    
    course = await prisma.course.update({
      where: { id: course.id },
      data: {
        ...courseData,
        slides: { create: slidesData },
        questions: { create: questionsData }
      }
    })
  } else {
    course = await prisma.course.create({
      data: {
        ...courseData,
        slides: { create: slidesData },
        questions: { create: questionsData }
      }
    })
  }

  return course
}
