import { PrismaClient } from '@prisma/client'

export async function seedTerminal(prisma: PrismaClient) {
  const slug = 'terminal'
  const courseData = {
    slug,
    title: '看取り・ターミナルケア研修（2024年度）',
    description: '〜尊厳ある人生の最終段階を支えるために〜',
    introduction: `
        <div class="flex flex-col items-center justify-center text-center space-y-3 pt-4 px-4 text-balance">
          <div class="flex items-center gap-4">
            <span class="h-px w-8 lg:w-12 bg-rose-700 rounded-full"></span>
            <p class="text-rose-800 font-black tracking-widest text-lg lg:text-2xl uppercase">看取り・ターミナルケア</p>
            <span class="h-px w-8 lg:w-12 bg-rose-700 rounded-full"></span>
          </div>
          <h2 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight">「最期まで自分らしく」を支える、<br/>人生のフィナーレに伴走する。</h2>
          <div class="max-w-2xl space-y-2 text-slate-800 text-sm lg:text-base leading-relaxed font-bold px-4 text-center">
            <p>看取りは、死を待つ時間ではありません。最期までその人らしく「今を生きる」時間を支える、究極のケアです。</p>
            <div class="p-4 lg:p-5 bg-rose-50 rounded-[1.5rem] lg:rounded-[2rem] border-2 border-rose-200 shadow-inner relative overflow-hidden text-[10px] lg:text-xs text-left mt-4">
              <div class="absolute top-0 right-0 w-16 h-16 lg:w-24 lg:h-24 bg-rose-100/50 rounded-bl-full"></div>
              <p class="relative z-10 italic text-rose-900 font-black text-xs lg:text-sm text-balance leading-relaxed">ご本人の意向、ご家族の葛藤。そのすべてを包み込み、迷いながらも共に進む。介護職にしかできない「温かな看取り」のカタチを学びましょう。</p>
            </div>
            <p class="text-[10px] lg:text-sm text-slate-900 font-black text-center mt-4">この研修は、尊厳ある旅立ちを支えるための「心の地図」を描くためのものです。</p>
          </div>
        </div>
      `,
    learningObjectives: `
        <div class="flex flex-col items-center justify-center text-center space-y-4 pt-4 px-4 w-full text-balance">
          <div class="bg-rose-700 text-white px-6 py-2 rounded-full text-[10px] font-black tracking-[0.3em] uppercase mb-2 shadow-lg shadow-rose-200">Learning Objectives</div>
          <div class="grid grid-cols-1 gap-3 w-full max-w-2xl">
            <div class="group p-4 bg-white border-2 border-slate-200 rounded-[1.5rem] lg:rounded-[2rem] shadow-sm flex items-center gap-4 lg:gap-6 hover:shadow-xl hover:border-rose-400 transition-all duration-500">
              <div class="w-10 h-10 lg:w-12 lg:h-12 bg-rose-700 text-white rounded-xl flex items-center justify-center text-base lg:text-lg font-black shrink-0 shadow-lg shadow-rose-200">1</div>
              <div class="text-left">
                <h4 class="text-sm lg:text-lg font-black text-slate-900">ACP（人生会議）を深掘りする</h4>
                <p class="text-slate-800 text-[10px] lg:text-xs font-bold leading-relaxed text-balance">本人の意向が揺れ動くことを前提に、多職種・家族と対話を重ねるプロセスを理解する。</p>
              </div>
            </div>
            <div class="group p-4 bg-white border-2 border-slate-200 rounded-[1.5rem] lg:rounded-[2rem] shadow-sm flex items-center gap-4 lg:gap-6 hover:shadow-xl hover:border-rose-400 transition-all duration-500">
              <div class="w-10 h-10 lg:w-12 lg:h-12 bg-rose-700 text-white rounded-xl flex items-center justify-center text-base lg:text-lg font-black shrink-0 shadow-lg shadow-rose-200">2</div>
              <div class="text-left">
                <h4 class="text-sm lg:text-lg font-black text-slate-900">身体・精神的苦痛を緩和する</h4>
                <p class="text-slate-800 text-[10px] lg:text-xs font-bold leading-relaxed text-balance">終末期の生理的変化（喘鳴、浮腫、斑紋等）を正しく理解し、非薬物的な緩和ケアを行う。</p>
              </div>
            </div>
            <div class="group p-4 bg-white border-2 border-slate-200 rounded-[1.5rem] lg:rounded-[2rem] shadow-sm flex items-center gap-4 lg:gap-6 hover:shadow-xl hover:border-rose-400 transition-all duration-500">
              <div class="w-10 h-10 lg:w-12 lg:h-12 bg-rose-700 text-white rounded-xl flex items-center justify-center text-base lg:text-lg font-black shrink-0 shadow-lg shadow-rose-200">3</div>
              <div class="text-left">
                <h4 class="text-sm lg:text-lg font-black text-slate-900">グリーフケアと自己回復力</h4>
                <p class="text-slate-800 text-[10px] lg:text-xs font-bold text-balance leading-relaxed">ご家族の悲嘆への伴走と、看取りに関わる職員自身のメンタルケア（自己変容）を学ぶ。</p>
              </div>
            </div>
          </div>
        </div>
      `,
    badgeLabel: '看取り',
    badgeIcon: 'Heart',
    videoUrl: 'https://youtu.be/hVPEhl03xsU',
  }

  const slidesData = [
    { title: "看取り・ターミナルケア研修", order: 0, content: `<div class="flex flex-col items-center justify-center text-center space-y-6 w-full h-full text-balance"><div class="relative w-full max-w-4xl px-4"><div class="absolute inset-0 bg-rose-400 blur-3xl opacity-20 scale-150 animate-pulse"></div><div class="relative bg-transparent lg:bg-white p-0 lg:p-16 rounded-none lg:rounded-[3.5rem] shadow-none lg:shadow-2xl border-none lg:border lg:border-slate-200 w-full mx-auto text-center"><div class="bg-rose-700 text-white px-4 lg:px-6 py-1 lg:py-1.5 rounded-full text-[8px] lg:text-[10px] font-black tracking-[0.3em] uppercase inline-block mb-6 lg:mb-8 shadow-sm">Legal Training 2024</div><h2 class="text-3xl lg:text-5xl font-black text-slate-900 leading-tight mb-4 px-4 text-center">看取り・ターミナルケア</h2><p class="text-rose-700 text-sm lg:text-3xl font-black mt-2 whitespace-nowrap text-center">〜尊厳ある人生の終焉を支える〜</p></div></div><div class="flex items-center justify-center gap-4 text-slate-500 font-black text-[8px] lg:text-[10px] tracking-widest pt-4"><span class="h-px w-6 lg:w-8 bg-slate-300"></span>CARE LEARNING SYSTEM<span class="h-px w-6 lg:w-8 bg-slate-300"></span></div></div>` },
    
    { title: "看取りの定義：『今』を輝かせる支援", order: 1, content: `<div class="space-y-6 lg:space-y-8 text-center px-4 h-full flex flex-col justify-center text-balance"><div class="inline-flex items-center gap-3 px-4 py-2 bg-rose-100 text-rose-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-rose-200 mb-2 uppercase tracking-widest mx-auto">Concept</div><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight px-4 text-center w-full">死を待つ時間ではなく<br/>「最期まで生き抜く」時間</h4><div class="p-0 lg:p-10 bg-transparent lg:bg-rose-50 border-none lg:border-2 lg:border-rose-100 shadow-none lg:shadow-xl rounded-none lg:rounded-[3rem] text-center lg:text-left text-sm lg:text-xl font-bold text-rose-800 space-y-4 lg:space-y-6 leading-relaxed max-w-4xl mx-auto px-4 text-center"><p class="font-black text-center">看取りとは、単なる身体的な世話の終焉ではありません。本人が歩んできた人生を肯定し、苦痛を最小限にし、安心感の中で旅立てるよう「環境」と「心」を整える究極のケアです。</p></div></div>` },

    { title: "2024年度 改正：ACPの完全義務化へ", order: 2, content: `<div class="space-y-6 lg:space-y-8 text-center px-4 h-full flex flex-col justify-center text-balance"><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight mb-2 px-4 text-center w-full">意思決定支援の「継続性」</h4><div class="grid grid-cols-1 lg:grid-cols-2 gap-4 lg:gap-6 max-w-4xl mx-auto w-full text-center"><div class="p-6 lg:p-8 bg-white border-2 border-slate-200 rounded-[2rem] lg:rounded-[2.5rem] shadow-xl flex flex-col items-center gap-2 lg:gap-4"><p class="font-black text-lg lg:text-xl text-rose-800 text-center">一度決めたら終わりではない</p><p class="text-sm lg:text-base font-bold text-slate-700 leading-relaxed text-center">状態の変化に合わせて、本人の意向は揺れ動くのが当然です。何度でも話し合い（ACP）を重ねることが義務付けられています。</p></div><div class="p-6 lg:p-8 bg-white border-2 border-slate-200 rounded-[2rem] lg:rounded-[2.5rem] shadow-xl flex flex-col items-center gap-2 lg:gap-4"><p class="font-black text-lg lg:text-xl text-rose-800 text-center">多職種チームでの合意形成</p><p class="text-sm lg:text-base font-bold text-slate-700 leading-relaxed text-center">医師、看護師、介護職、そして家族。全員が「本人の望み」を一点の曇りなく共有している状態を目指します。</p></div></div></div>` },

    { title: "看取りケアの3本柱：支え抜く覚悟", order: 3, content: `<div class="space-y-6 lg:space-y-8 text-center h-full flex flex-col justify-center px-4 text-balance"><div class="inline-flex items-center gap-3 px-4 py-2 bg-red-100 text-red-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-red-200 mb-2 shadow-sm mx-auto uppercase tracking-widest"><span class="w-2 h-2 bg-red-700 rounded-full animate-ping"></span>MUST CHECK</div><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight text-center w-full">絶対に譲れない3つの視点</h4><div class="grid grid-cols-1 lg:grid-cols-3 gap-3 lg:gap-4 max-w-5xl mx-auto w-full px-4 text-center"><div class="p-4 lg:p-6 bg-rose-50 border-2 border-rose-200 rounded-2xl lg:rounded-3xl text-center font-black text-sm lg:text-base text-rose-900 shadow-sm">1. 苦痛の徹底除去</div><div class="p-4 lg:p-6 bg-rose-50 border-2 border-rose-200 rounded-2xl lg:rounded-3xl text-center font-black text-sm lg:text-base text-rose-900 shadow-sm">2. 孤独の完全払拭</div><div class="p-4 lg:p-6 bg-rose-50 border-2 border-rose-200 rounded-2xl lg:rounded-3xl text-center font-black text-sm lg:text-base text-rose-900 shadow-sm">3. 意向の絶対尊重</div></div><p class="text-slate-500 font-black text-[10px] lg:text-base mt-4 text-center w-full">※これらの一つでも欠ければ、それは「尊厳ある看取り」とは呼べません。</p></div>` },

    { title: "自然な終わりのプロセス：生理的変化", order: 4, content: `<div class="flex flex-col items-center text-center space-y-4 lg:space-y-6 px-4 h-full justify-center text-balance"><div class="p-4 lg:p-6 bg-white rounded-[2rem] lg:rounded-[3.5rem] w-full max-w-2xl shadow-xl border-2 border-slate-200 shrink-0 text-center"><h4 class="text-xl lg:text-2xl font-black mb-2 text-slate-900 text-center">身体が「旅立ち」を準備する時</h4><p class="text-[10px] lg:text-sm text-slate-900 font-black text-center">これらは病気ではなく、自然な移行です</p></div><div class="grid grid-cols-1 lg:grid-cols-2 gap-3 font-black text-[10px] lg:text-sm w-full max-w-5xl text-center"><div class="p-3 bg-rose-50 border-2 border-rose-200 rounded-2xl text-left"><p class="text-rose-900 mb-1 font-black">● 嗜眠（しみん）の増大</p><p class="text-slate-600 font-bold">1日の大半を眠って過ごします。呼びかけへの反応が徐々に緩やかになります。</p></div><div class="p-3 bg-rose-50 border-2 border-rose-200 rounded-2xl text-left"><p class="text-rose-900 mb-1 font-black">● 代謝の低下と飲食拒否</p><p class="text-slate-600 font-bold">消化機能が停止し、水分や栄養を必要としなくなります。無理な摂取は苦痛を招きます。</p></div><div class="p-3 bg-rose-50 border-2 border-rose-200 rounded-2xl text-left"><p class="text-rose-900 mb-1 font-black">● 循環の不全（末梢の冷感）</p><p class="text-slate-600 font-bold">血液が中心部に集まり、手足が冷たくなり、膝や背中に「斑紋（死斑）」が出始めます。</p></div><div class="p-3 bg-rose-50 border-2 border-rose-200 rounded-2xl text-left"><p class="text-rose-900 mb-1 font-black">● 呼吸の変調（喘鳴など）</p><p class="text-slate-600 font-bold">喉に痰が絡んだような「ゴロゴロ」という音（死の喘鳴）や、不規則な呼吸が見られます。</p></div></div></div>` },

    { title: "身体的苦痛の緩和：非薬物的な知恵", order: 5, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left text-balance"><div class="space-y-4 lg:space-y-6"><h4 class="text-2xl lg:text-5xl font-black text-rose-900 flex items-center gap-4 lg:gap-6"><span class="w-2 h-10 lg:w-3 lg:h-16 bg-rose-700 rounded-full"></span>「触れる」ケアの魔法</h4></div><ul class="space-y-4 lg:space-y-6 text-lg lg:text-3xl font-black text-slate-800 pl-0 leading-tight"><li>・口渇への保湿（水を含ませたガーゼでの潤い）</li><li>・呼吸を楽にするポジショニング（30度程度の挙上）</li><li>・「さする」「握る」といったタクティールケア</li><li>・好きな音楽、アロマ、清潔なリネンでの環境調整</li></ul><p class="text-rose-700 font-black text-sm lg:text-xl mt-4 italic">※薬で消せない苦痛を、あなたの「手」が和らげます。</p></div>` },

    { title: "スピリチュアルケア：人生の統合", order: 6, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left text-balance"><div class="space-y-4 lg:space-y-6"><h4 class="text-2xl lg:text-5xl font-black text-rose-900 flex items-center gap-4 lg:gap-6"><span class="w-2 h-10 lg:w-3 lg:h-16 bg-rose-700 rounded-full"></span>「生きてきて良かった」を支える</h4></div><ul class="space-y-4 lg:space-y-6 text-lg lg:text-3xl font-black text-slate-800 pl-0 leading-tight"><li>・過去の輝かしい記憶を共に振り返る</li><li>・未完了の思い（会いたい人等）への橋渡し</li><li>・ただ「そばにいる」という、孤独からの解放</li><li>・「ありがとう」を交換できる場を演出する</li></ul></div>` },

    { title: "ACP：揺れる思いを受け止める覚悟", order: 7, content: `<div class="flex flex-col items-center text-center space-y-4 lg:space-y-6 px-4 h-full justify-center text-balance"><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight text-center w-full">結論ではなく「プロセス」に価値がある</h4><div class="grid grid-cols-1 lg:grid-cols-2 gap-3 lg:gap-x-12 lg:gap-y-3 font-black text-sm lg:text-base w-full max-w-4xl text-center"><div class="flex flex-col gap-3"><span class="px-6 py-3 bg-rose-50 border-2 border-rose-200 rounded-2xl text-rose-900 shadow-sm text-center">「最期まで家で」という言葉の裏側</span><span class="px-6 py-3 bg-rose-50 border-2 border-rose-200 rounded-2xl text-rose-900 shadow-sm text-center">苦しくなってからの「やっぱり助けて」</span></div><div class="flex flex-col gap-3"><span class="px-6 py-3 bg-rose-50 border-2 border-rose-200 rounded-2xl text-rose-900 shadow-sm text-center">家族の罪悪感からくる意見の豹変</span><span class="px-6 py-3 bg-rose-50 border-2 border-rose-200 rounded-2xl text-rose-900 shadow-sm text-center">沈黙の中に隠された「本音」を探る</span></div></div><p class="text-rose-700 font-black text-sm lg:text-xl px-4 mt-4 italic">※揺れるのは、懸命に生きている証拠。プロはそのすべてを肯定します。</p></div>` },

    { title: "水分・栄養：身体の準備を邪魔しない", order: 8, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left text-balance text-center"><h4 class="text-xl lg:text-3xl font-black text-rose-900 text-center w-full">無理な点滴・経管栄養の倫理</h4><div class="p-8 lg:p-10 bg-white border-4 border-rose-100 rounded-[2rem] lg:rounded-[3rem] shadow-xl max-w-4xl mx-auto w-full text-center"><p class="text-xl lg:text-3xl font-black leading-relaxed text-center text-slate-900 text-balance">身体が水分を拒むのは、喘鳴やむくみを防ぎ、<br/><span class="text-rose-700 underline underline-offset-8 decoration-4">穏やかな眠り</span>に入るための自然な反応です。</p></div><p class="text-blue-700 font-black text-center w-full mt-4 text-sm lg:text-lg">「食べさせない」のではなく「本人の楽な状態を優先する」</p></div>` },

    { title: "多職種連携：一貫した「安心」を届ける", order: 9, content: `<div class="flex flex-col items-center justify-center h-full text-left space-y-6 lg:space-y-8 px-6 lg:px-12 w-full text-balance text-center"><h4 class="text-xl lg:text-3xl font-black text-blue-800 text-center mb-4 uppercase tracking-widest w-full">チームの「和」が本人の「安」</h4><div class="space-y-6 lg:space-y-10 font-black text-slate-900 max-w-4xl mx-auto w-full text-center"><div><p class="text-lg lg:text-2xl text-blue-700 mb-1 flex items-center gap-3 justify-center"><span>●</span> 24時間の生活を知る介護職の役割：</p><p class="text-sm lg:text-xl text-slate-600 font-bold">わずかな表情の変化や、言葉にならない呟きを医師・看護師に繋ぐ。</p></div><div><p class="text-lg lg:text-2xl text-blue-700 mb-1 flex items-center gap-3 justify-center"><span>●</span> 医療と介護の「看取り基準」の統一：</p><p class="text-sm lg:text-xl text-slate-600 font-bold">どこからを「終末期」とし、どこまで「医療介入」するかを事前に合意する。</p></div></div></div>` },

    { title: "DNAR：法的・倫理的な境界線", order: 10, content: `<div class="p-8 lg:p-12 bg-amber-50 rounded-[2.5rem] lg:rounded-[4rem] border-4 border-amber-300 border-dashed text-center shadow-inner max-w-4xl mx-auto flex flex-col items-center justify-center h-full px-4 text-center"><div class="bg-amber-700 text-white px-6 lg:px-8 py-1.5 lg:py-2 rounded-full text-[8px] lg:text-[10px] font-black inline-block mb-6 lg:mb-8 uppercase tracking-widest shadow-lg">Legal & Ethical</div><h4 class="text-xl lg:text-3xl font-black text-amber-950 mb-6 lg:mb-8 italic text-balance">DNARは「不作為」ではありません</h4><p class="text-lg lg:text-xl font-black text-amber-900 leading-relaxed py-4 lg:py-6 px-4">蘇生措置をしないことは、ケアをしないことではない。<br/>「救命」よりも「苦痛緩和」を優先するという積極的な選択です。</p><p class="text-[10px] lg:text-sm font-bold text-amber-800 mt-4 underline">※不慮の事故（喉詰まり等）での対応は、事前合意に基づき冷静に判断します。</p></div>` },

    { title: "環境設定：静寂とプライバシーの確保", order: 11, content: `<div class="space-y-6 lg:space-y-8 text-center px-4 h-full flex flex-col justify-center text-balance text-center"><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight mb-2 px-4 text-center w-full">聖なる空間を作る</h4><div class="grid grid-cols-1 lg:grid-cols-2 gap-4 lg:gap-6 max-w-4xl mx-auto w-full text-center text-center"><div class="p-6 lg:p-8 bg-rose-50 border-2 border-rose-200 rounded-[2rem] lg:rounded-[2.5rem] shadow-xl flex flex-col items-center gap-2 lg:gap-4 text-center"><p class="font-black text-lg lg:text-xl text-rose-800">音と光の調整</p><p class="text-sm lg:text-sm font-bold text-slate-700 leading-relaxed">バタバタという足音や笑い声を避け、落ち着いた照明で穏やかな空気を作ります。</p></div><div class="p-6 lg:p-8 bg-rose-50 border-2 border-rose-200 rounded-[2rem] lg:rounded-[2.5rem] shadow-xl flex flex-col items-center gap-2 lg:gap-4 text-center"><p class="font-black text-lg lg:text-xl text-rose-800">家族への「居場所」</p><p class="text-sm lg:text-sm font-bold text-slate-700 leading-relaxed">家族が泊まり込める、あるいは長時間付き添える物理的・心理的配慮を尽くします。</p></div></div></div>` },

    { title: "臨終の前兆：最後のサインを見逃さない", order: 12, content: `<div class="flex flex-col items-center justify-center h-full space-y-6 lg:space-y-8 px-4 w-full text-balance text-center"><h4 class="text-xl lg:text-2xl font-black text-red-900 text-center w-full mb-2 px-4 animate-pulse">カウントダウンの始まり</h4><div class="grid grid-cols-1 gap-3 lg:gap-4 w-full max-w-2xl text-center"><div class="flex items-center gap-4 bg-white p-4 rounded-2xl border-2 border-red-100 shadow-sm font-black text-sm lg:text-base justify-center lg:justify-start"><span class="w-10 h-10 bg-red-600 text-white rounded-full flex items-center justify-center shrink-0">1</span>下顎呼吸（顎を動かす、不規則な呼吸）の出現</div><div class="flex items-center gap-4 bg-white p-4 rounded-2xl border-2 border-red-100 shadow-sm font-black text-sm lg:text-base justify-center lg:justify-start"><span class="w-10 h-10 bg-red-600 text-white rounded-full flex items-center justify-center shrink-0">2</span>橈骨動脈（手首の脈）の消失、血圧の低下</div><div class="flex items-center gap-4 bg-white p-4 rounded-2xl border-2 border-red-100 shadow-sm font-black text-sm lg:text-base justify-center lg:justify-start"><span class="w-10 h-10 bg-red-600 text-white rounded-full flex items-center justify-center shrink-0">3</span>尿量の減少、意識の完全な消失（昏睡）</div></div></div>` },

    { title: "臨終の瞬間：その時、プロはどう動くか", order: 13, content: `<div class="flex flex-col items-center justify-center h-full space-y-6 lg:space-y-8 px-4 w-full text-balance text-center"><h4 class="text-xl lg:text-3xl font-black text-slate-900 text-center w-full mb-4 px-4">「最後の一秒」を大切にする</h4><div class="grid grid-cols-1 gap-3 lg:gap-4 w-full max-w-2xl text-center"><div class="flex items-center gap-4 bg-white p-4 rounded-2xl border-2 border-slate-100 shadow-sm font-black justify-center lg:justify-start text-sm lg:text-base"><span class="w-10 h-10 bg-rose-700 text-white rounded-full flex items-center justify-center shrink-0 text-center">1</span>呼吸停止を確認後、静かに時刻を記録する</div><div class="flex items-center gap-4 bg-white p-4 rounded-2xl border-2 border-slate-100 shadow-sm font-black justify-center lg:justify-start text-sm lg:text-base"><span class="w-10 h-10 bg-rose-700 text-white rounded-full flex items-center justify-center shrink-0 text-center">2</span>ご家族に「ご臨終です」と静かに告げ、一礼する</div><div class="flex items-center gap-4 bg-white p-4 rounded-2xl border-2 border-slate-100 shadow-sm font-black justify-center lg:justify-start text-sm lg:text-base"><span class="w-10 h-10 bg-rose-700 text-white rounded-full flex items-center justify-center shrink-0 text-center">3</span>医師による死亡確認まで、ご家族の時間を守る</div></div></div>` },

    { title: "エンゼルケア：感謝を込めた最後のおめかし", order: 14, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-6 lg:space-y-8 px-4 w-full text-balance text-center"><div class="inline-flex items-center gap-3 px-4 py-1.5 bg-rose-100 text-rose-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-rose-200 mb-2 mx-auto text-center">Angel Care</div><h4 class="text-xl lg:text-2xl font-black text-rose-900 leading-tight px-4 text-center w-full">旅立ちの装いを整える</h4><div class="p-6 lg:p-10 bg-white border-[4px] lg:border-[6px] border-rose-600 rounded-[2rem] lg:rounded-[3rem] shadow-2xl max-w-3xl mx-auto w-full text-center"><p class="text-lg lg:text-2xl font-black text-rose-900 leading-relaxed italic text-balance text-center">お体を入念に清め、愛用していた服を着せ、生前のような柔らかな表情を整えます。ご家族と一緒に進めることで、悲しみを「感謝」へ昇華させるプロセスを支えます。</p></div></div>` },

    { title: "ご家族への支援：心の準備と後悔の緩和", order: 15, content: `<div class="flex flex-col items-center justify-center h-full text-left space-y-4 lg:space-y-6 px-6 lg:px-12 w-full text-balance text-center"><h4 class="text-xl lg:text-3xl font-black text-rose-700 text-center mb-2 uppercase tracking-widest w-full px-4">「これで良かった」を創る</h4><div class="space-y-6 lg:space-y-8 font-black text-slate-900 max-w-4xl mx-auto w-full text-center"><div><p class="text-lg lg:text-2xl text-rose-600 mb-1 flex items-center gap-3 justify-center text-center"><span>●</span> 経過の共有：</p><p class="text-sm lg:text-lg text-slate-600 font-bold text-center text-balance">「今朝は穏やかなお顔でしたよ」など、日常の断片を伝える。</p></div><div><p class="text-lg lg:text-2xl text-rose-600 mb-1 flex items-center gap-3 justify-center text-center"><span>●</span> 介護の肯定：</p><p class="text-sm lg:text-lg text-slate-600 font-bold text-center text-balance">「ご家族の献身的な支えがあったからこそ、ここまで頑張れましたね」</p></div></div></div>` },

    { title: "グリーフケア：死別後の「伴走」", order: 16, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-4 lg:space-y-6 px-4 w-full text-balance text-center"><h4 class="text-xl lg:text-2xl font-black text-rose-900 text-center w-full px-4">悲しみを「力」に変えるために</h4><div class="p-6 bg-rose-50 border-2 border-rose-100 rounded-3xl text-left max-w-3xl space-y-4 shadow-sm mx-auto text-center"><p class="text-sm lg:text-lg font-bold text-slate-800 leading-relaxed text-center text-balance">葬儀後の空虚感、突然の涙、自分を責める気持ち。ご家族の悲嘆（グリーフ）は長く続きます。施設を去られた後も、私たちは「あの時共に過ごした仲間」として心に寄り添い続けます。</p></div></div>` },

    { title: "職員の心のセルフケア：燃え尽きを防ぐ", order: 17, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-4 lg:space-y-6 px-4 w-full text-balance text-center"><h4 class="text-xl lg:text-2xl font-black text-rose-900 text-center w-full px-4 text-balance">看取る側も「人」である</h4><div class="p-6 bg-white border-2 border-rose-100 rounded-3xl text-left max-w-3xl space-y-4 shadow-sm mx-auto text-center"><p class="text-sm lg:text-lg font-black text-slate-800 leading-relaxed text-center text-balance">懸命にケアした利用者の死は、職員にも深い喪失感を与えます。悲しみを押し殺さず、チームで語り合い、互いの労をねぎらう時間（デブリーフィング）を必ず持ちましょう。あなたの心を守ることも、プロの仕事です。</p></div></div>` },

    { title: "ケーススタディ1：病院搬送を望む家族", order: 18, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-4 lg:space-y-6 px-4 w-full text-balance text-center"><div class="inline-flex items-center gap-3 px-4 py-1.5 bg-rose-50 text-rose-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-rose-200 mb-2 mx-auto text-center">CASE STUDY 01</div><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4 text-center w-full">場面：急変直前の動揺</h4><div class="p-6 lg:p-8 bg-white border-2 border-slate-100 rounded-[2rem] lg:rounded-[3rem] shadow-xl max-w-4xl text-left space-y-4 w-full text-center"><p class="text-sm lg:text-lg font-bold text-slate-800 leading-relaxed text-balance px-4 text-center">「最期は施設で」と合意していた長男様が、呼吸が荒くなった母を見て「やっぱり病院へ連れて行って、何とかして！」と叫ばれました。</p><div class="h-px bg-slate-100"></div><p class="text-xs lg:text-base font-black text-rose-700 italic text-center px-4 text-balance text-center w-full">指示通りに救急車を呼びますか？<br/>それとも、この叫びの「奥にある願い」を聴きますか？</p></div></div>` },

    { title: "分析1：動揺は「愛情」の現れ", order: 19, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-6 lg:space-y-8 px-4 w-full text-balance text-center text-center"><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight px-4 text-center w-full text-center">分析：一瞬の感情に振り回されない</h4><div class="grid grid-cols-1 lg:grid-cols-2 gap-4 lg:gap-6 max-w-5xl mx-auto w-full text-center text-left text-center"><div class="p-6 lg:p-8 bg-rose-50 border-2 border-rose-100 rounded-[2rem] text-left space-y-3 shadow-sm text-left"><p class="font-black text-base lg:text-xl text-rose-700 text-left text-left text-left">【NG：そのまま受け止める】</p><ul class="text-[10px] lg:text-xs font-bold text-slate-700 space-y-1 text-left text-left"><li>・何も言わずに119番する（本人の意向を無視）</li><li>・「決めたことですから」と冷たく断る</li><li>・動揺する家族を別室へ追い出す</li></ul></div><div class="p-6 lg:p-8 bg-blue-50 border-2 border-blue-100 rounded-[2rem] text-left space-y-3 shadow-sm text-left"><p class="font-black text-base lg:text-xl text-blue-700 text-left text-left text-left text-left">【プロ：意向を再確認する】</p><ul class="text-[10px] lg:text-xs font-bold text-slate-700 space-y-1 text-left text-left"><li>・「お辛いですね」と共感し、一旦深呼吸を促す</li><li>・「何が一番心配ですか？」と問い直す</li><li>・本人の「穏やかさ」を優先する方針を再共有する</li></ul></div></div></div>` },

    { title: "ケーススタディ2：孤独死という恐怖への対応", order: 20, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-4 lg:space-y-6 px-4 w-full text-balance text-center"><div class="inline-flex items-center gap-3 px-4 py-1.5 bg-rose-50 text-rose-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-rose-200 mb-2 mx-auto text-center">CASE STUDY 02</div><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4 text-center w-full text-balance text-center">場面：夜間の静かな最期</h4><div class="p-6 lg:p-8 bg-white border-2 border-slate-100 rounded-[2rem] lg:rounded-[3rem] shadow-xl max-w-4xl text-left space-y-4 w-full text-center"><p class="text-sm lg:text-lg font-bold text-slate-800 leading-relaxed text-balance px-4 text-center text-balance text-center">深夜2時、巡回時に利用者が息を引き取っているのを発見しました。家族は遠方で、到着まで数時間かかります。夜勤者はあなた一人。まず、何をしますか？</p><div class="h-px bg-slate-100"></div><p class="text-xs lg:text-base font-black text-rose-700 italic text-center px-4 text-balance text-center w-full text-center">「孤独な死」にさせないために、<br/>死後でもできることは何ですか？</p></div></div>` },

    { title: "分析2：死後のケアも「看取り」の一部", order: 21, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-6 lg:space-y-8 px-4 w-full text-balance text-center text-center"><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight px-4 text-center w-full text-center text-center">分析：立ち会いよりも「存在」の肯定</h4><div class="grid grid-cols-1 lg:grid-cols-2 gap-4 lg:gap-6 max-w-5xl mx-auto w-full text-center text-left text-center"><div class="p-6 lg:p-8 bg-white border-2 border-slate-200 rounded-[2rem] shadow-sm text-left space-y-3 text-left"><p class="font-black text-base lg:text-xl text-rose-800 text-left text-left text-left text-left">【物理的な初動】</p><ul class="text-[10px] lg:text-xs font-bold text-slate-700 space-y-1 text-left text-left"><li>・主治医、管理者、看護師への迅速な連絡</li><li>・正確な発見時刻と状態のメモ</li><li>・他利用者への影響を最小限にする</li></ul></div><div class="p-6 lg:p-8 bg-rose-50 border-2 border-rose-100 rounded-[2rem] text-left space-y-3 shadow-sm text-left"><p class="font-black text-base lg:text-xl text-rose-700 text-left text-left text-left text-left">【心の初動】</p><ul class="text-[10px] lg:text-xs font-bold text-slate-700 space-y-1 text-left text-left"><li>・「お疲れ様でした」と声をかけ、お体を整える</li><li>・家族が来るまで、手を握ったり寄り添う時間を作る</li><li>・「眠っているような穏やかさ」をご家族に伝える</li></ul></div></div></div>` },

    { title: "プロフェッショナルとしての誇り：満足感", order: 22, content: `<div class="space-y-6 lg:space-y-8 text-center flex flex-col items-center justify-center h-full px-4 w-full text-balance text-center text-balance"><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4 text-center w-full">看取って良かったと言えるケア</h4><div class="p-8 lg:p-10 bg-white border-[4px] lg:border-[6px] border-rose-600 rounded-[2rem] lg:rounded-[3rem] shadow-2xl max-w-3xl mx-auto w-full text-center"><p class="text-xl lg:text-2xl font-black text-rose-900 leading-relaxed italic text-balance text-center text-center">看取りは「敗北」ではありません。<br/>一人の人生を、最高敬意を持って<br/>完結させるお手伝いをする、崇高な仕事です。</p></div><p class="font-black text-sm lg:text-xl text-slate-800 mt-2 text-center w-full px-4 text-center">その誇りを持って、日々の「今」を大切にしましょう。</p></div>` },

    { title: "全15科目、完遂おめでとうございます", order: 23, content: `<div class="flex flex-col items-center text-center space-y-8 lg:space-y-12 w-full h-full justify-center text-slate-900 px-4 text-center text-balance"><div class="w-24 h-24 lg:w-32 h-32 bg-rose-700 rounded-[2.5rem] lg:rounded-[3.5rem] flex items-center justify-center shadow-2xl shadow-rose-200 rotate-3 transition-transform hover:rotate-0 duration-500 mx-auto text-center"><svg class="w-12 h-12 lg:w-16 h-16 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg></div><h3 class="text-2xl lg:text-5xl font-black leading-tight text-center w-full text-balance">全課程の修了、心より敬意を表します。<br/>現場を変える力が、今あなたに宿っています。</h3><div class="pt-8 lg:pt-12 border-t-2 border-slate-200 w-full max-w-md text-center mx-auto text-center"><p class="text-slate-500 font-black text-[8px] lg:text-[10px] uppercase tracking-[0.5em] text-center">Mastery of All Sessions Accomplished</p></div></div>` },

    { title: "理解度テストのご案内", order: 24, content: `
        <div class="flex flex-col items-center text-center space-y-6 lg:space-y-8 w-full h-full justify-center px-4 text-center text-balance">
          <div class="bg-emerald-600 text-white px-6 py-1.5 rounded-full text-[8px] lg:text-[10px] font-black tracking-[0.3em] uppercase inline-block mb-4 lg:mb-6 shadow-lg px-4 text-center">Course Completed</div>
          <h2 class="text-2xl lg:text-5xl font-black text-slate-900 leading-tight mb-2 lg:mb-4 text-center w-full text-balance">最終関門：理解度テスト</h2>
          <p class="text-emerald-800 text-base lg:text-2xl font-black leading-relaxed text-center w-full text-balance px-4">大変お疲れ様でした。<br/>最後に理解度テスト（全10問）を行います。</p>
          <div class="p-4 lg:p-6 bg-rose-50 rounded-2xl lg:rounded-3xl border-2 border-rose-100 max-w-lg mx-auto mt-6 lg:mt-8 text-center">
            <p class="text-rose-900 font-black text-sm lg:text-xl flex items-center justify-center gap-3 text-center">
              <span class="w-2 h-2 bg-rose-700 rounded-full text-center"></span>
              全問正解で、真のプロフェッショナルへ
              <span class="w-2 h-2 bg-rose-700 rounded-full text-center"></span>
            </p>
          </div>
        </div>
      ` }
  ]

  const questionsData = [
    { text: '本人が望む医療やケアについて、前もって話し合い共有するプロセスを何というか？', explanation: 'ACP（アドバンス・ケア・プランニング）と呼ばれ、日本語では「人生会議」と愛称されています。', order: 1, choices: { create: [{ text: 'ACP（人生会議）', isCorrect: true }, { text: 'BCP（業務継続計画）', isCorrect: false }, { text: 'SBAR（状況報告）', isCorrect: false }] } },
    { text: '看取り期において、食欲や水分摂取量が低下することへの見解として適切なものは？', explanation: '身体が自然に終わりへ向かう準備であり、無理な摂取は逆に苦痛（むくみ、喘鳴等）を招くことがあります。', order: 2, choices: { create: [{ text: '身体の自然な準備であり、無理強いしない', isCorrect: true }, { text: '無理にでも食べさせないと衰弱する', isCorrect: false }, { text: '点滴で無理やり水分を補給すべきである', isCorrect: false }] } },
    { text: 'ターミナル期における身体的苦痛（痛み）への対応として、介護職がすべきことは？', explanation: '表情や動作から痛みをアセスメントし、速やかに医療職へ報告して緩和を図ることが重要です。', order: 3, choices: { create: [{ text: '医療職と連携し、痛みの緩和を最優先する', isCorrect: true }, { text: '「年齢のせいだから」と様子を見る', isCorrect: false }, { text: '本人が訴えるまで放置する', isCorrect: false }] } },
    { text: '死が近づいた際に見られる、不規則で顎を動かして呼吸する状態を何というか？', explanation: '「下顎呼吸（かがくこきゅう）」と呼ばれ、臨終が近い重要なサインの一つです。', order: 4, choices: { create: [{ text: '下顎呼吸', isCorrect: true }, { text: '深呼吸', isCorrect: false }, { text: '腹式呼吸', isCorrect: false }] } },
    { text: 'ご家族が死別の悲しみを乗り越えられるよう支援することを何というか？', explanation: '「グリーフケア（悲嘆のケア）」と呼ばれ、看取り後も続く大切な支援の一部です。', order: 5, choices: { create: [{ text: 'グリーフケア', isCorrect: true }, { text: 'スキンケア', isCorrect: false }, { text: 'フットケア', isCorrect: false }] } },
    { text: '延命治療を行わない（蘇生措置を拒否する）という事前の意思表示を何というか？', explanation: 'DNAR（Do Not Attempt Resuscitation）と呼ばれ、事前にチームで共有しておく必要があります。', order: 6, choices: { create: [{ text: 'DNAR', isCorrect: true }, { text: 'AED', isCorrect: false }, { text: 'CPR', isCorrect: false }] } },
    { text: '死後の処置（エンゼルケア）の目的として、最も適切なものはどれか？', explanation: '本人の尊厳を守るとともに、ご家族が死を受け入れる心の準備を支える大切な儀式です。', order: 7, choices: { create: [{ text: '本人の尊厳保持と家族の心の準備を支える', isCorrect: true }, { text: '単なる遺体の清掃作業である', isCorrect: false }, { text: '法的な義務を果たすためだけに行う', isCorrect: false }] } },
    { text: 'ターミナル期の口腔ケアについて、適切な考え方はどれか？', explanation: '感染予防だけでなく、口の中の渇き（口渇感）による不快感を和らげるために重要です。', order: 8, choices: { create: [{ text: '口渇感を和らげるために継続する', isCorrect: true }, { text: 'もう食べないので必要ない', isCorrect: false }, { text: '危ないので一切行ってはいけない', isCorrect: false }] } },
    { text: '利用者が亡くなった後の、介護職員自身のメンタルケアについて正しいものは？', explanation: '看取りは職員にも大きな心理的影響を与えるため、チームで感情を共有し支え合うことが必要です。', order: 9, choices: { create: [{ text: 'チームで感情を共有し、支え合うべきである', isCorrect: true }, { text: 'プロなら悲しんではいけない', isCorrect: false }, { text: 'すぐに忘れて次の仕事に集中すべきである', isCorrect: false }] } },
    { text: '看取り介護において、介護職が果たらすべき最も重要な「非言語」的ケアはどれか？', explanation: '言葉がなくても、そばにいて手を握る、温かい眼差しを向けることが、最大の安心感を与えます。', order: 10, choices: { create: [{ text: 'そばに寄り添い、手を握るなどの安心感', isCorrect: true }, { text: 'テキパキと事務的に作業を終わらせること', isCorrect: false }, { text: '離れた場所で見守り続けること', isCorrect: false }] } }
  ]

  let course = await prisma.course.findUnique({ where: { slug } })

  if (course) {
    await prisma.choice.deleteMany({ where: { question: { courseId: course.id } } })
    await prisma.question.deleteMany({ where: { courseId: course.id } })
    await prisma.slide.deleteMany({ where: { courseId: course.id } })
    
    course = await prisma.course.update({
      where: { id: course.id },
      data: {
        ...courseData,
        slides: { create: slidesData },
        questions: { create: questionsData }
      }
    })
  } else {
    course = await prisma.course.create({
      data: {
        ...courseData,
        slides: { create: slidesData },
        questions: { create: questionsData }
      }
    })
  }

  return course
}
