import { PrismaClient } from '@prisma/client'

export async function seedMental(prisma: PrismaClient) {
  const slug = 'mental'
  const courseData = {
    slug,
    title: '精神的ケアに関する研修（2024年度）',
    description: '〜利用者と自分の心を守る、感情のプロフェッショナルへ〜',
    introduction: `
        <div class="flex flex-col items-center justify-center text-center space-y-2 pt-2 px-4 text-balance">
          <div class="flex items-center gap-4">
            <span class="h-px w-8 lg:w-12 bg-indigo-700 rounded-full"></span>
            <p class="text-indigo-800 font-black tracking-widest text-lg lg:text-xl uppercase">精神的ケア研修</p>
            <span class="h-px w-8 lg:w-12 bg-indigo-700 rounded-full"></span>
          </div>
          <h2 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight">一生懸命なあなたほど、<br/>自分の「心の悲鳴」を無視していませんか？</h2>
          <div class="max-w-2xl space-y-2 text-slate-800 text-sm lg:text-base leading-relaxed font-bold px-4 text-center">
            <p>介護は心を削る「感情労働」です。あなたの心のコップが溢れそうなとき、良いケアは生まれません。</p>
            <div class="p-3 lg:p-4 bg-indigo-50 rounded-[1.5rem] lg:rounded-[2rem] border-2 border-indigo-200 shadow-inner relative overflow-hidden text-[10px] lg:text-xs text-left">
              <div class="absolute top-0 right-0 w-16 h-16 lg:w-20 lg:h-20 bg-indigo-100/50 rounded-bl-full"></div>
              <p class="relative z-10 italic text-indigo-900 font-black text-xs lg:text-sm leading-relaxed">精神的ケアとは、相手を変えることではなく、ありのままの感情を認め、安心の居場所を共に作ること。そして、自分自身をケアする「技術」を学ぶことです。</p>
            </div>
            <p class="text-[10px] lg:text-sm text-slate-900 font-black text-center mt-2">この研修は、利用者とあなたの心を「人格の尊重」で繋ぐためのものです。</p>
          </div>
        </div>
      `,
    learningObjectives: `
        <div class="flex flex-col items-center justify-center text-center space-y-3 pt-2 px-4 w-full text-balance">
          <div class="bg-indigo-700 text-white px-6 py-1.5 rounded-full text-[10px] font-black tracking-[0.3em] uppercase mb-1 shadow-lg shadow-indigo-200">Learning Objectives</div>
          <div class="grid grid-cols-1 gap-2 w-full max-w-2xl">
            <div class="group p-3 lg:p-4 bg-white border-2 border-slate-200 rounded-[1.5rem] lg:rounded-[2rem] shadow-sm flex items-center gap-4 lg:gap-6 hover:shadow-xl hover:border-indigo-400 transition-all duration-500 text-center lg:text-left">
              <div class="w-10 h-10 lg:w-12 lg:h-12 bg-indigo-700 text-white rounded-xl flex items-center justify-center text-base lg:text-lg font-black shrink-0 shadow-lg shadow-indigo-200">1</div>
              <div class="text-left">
                <h4 class="text-sm lg:text-base font-black text-slate-900">感情を「肯定」する技術</h4>
                <p class="text-slate-800 text-[10px] lg:text-xs font-bold leading-tight">バリデーション療法の基礎を習得し、利用者の不安を安心に変える関わりを学ぶ。</p>
              </div>
            </div>
            <div class="group p-3 lg:p-4 bg-white border-2 border-slate-200 rounded-[1.5rem] lg:rounded-[2rem] shadow-sm flex items-center gap-4 lg:gap-6 hover:shadow-xl hover:border-indigo-400 transition-all duration-500 text-center lg:text-left">
              <div class="w-10 h-10 lg:w-12 lg:h-12 bg-indigo-700 text-white rounded-xl flex items-center justify-center text-base lg:text-lg font-black shrink-0 shadow-lg shadow-indigo-200">2</div>
              <div class="text-left">
                <h4 class="text-sm lg:text-base font-black text-slate-900">人格尊重と個別ケアの実践</h4>
                <p class="text-slate-800 text-[10px] lg:text-xs font-bold leading-tight">2024年度改正に基づき、一律の管理を排した「その人らしさ」を支える視点を養う。</p>
              </div>
            </div>
            <div class="group p-3 lg:p-4 bg-white border-2 border-slate-200 rounded-[1.5rem] lg:rounded-[2rem] shadow-sm flex items-center gap-4 lg:gap-6 hover:shadow-xl hover:border-indigo-400 transition-all duration-500 text-center lg:text-left">
              <div class="w-10 h-10 lg:w-12 lg:h-12 bg-indigo-700 text-white rounded-xl flex items-center justify-center text-base lg:text-lg font-black shrink-0 shadow-lg shadow-indigo-200">3</div>
              <div class="text-left">
                <h4 class="text-sm lg:text-base font-black text-slate-900">感情労働のセルフケア</h4>
                <p class="text-slate-800 text-[10px] lg:text-xs font-bold leading-tight">自身のストレスサインに気づき、チームでの支え合いを通じて心の健康を維持する。</p>
              </div>
            </div>
          </div>
        </div>
      `,
    videoUrl: 'https://youtu.be/pfaZhLN0zk4',
    badgeLabel: '精神ケア',
    badgeIcon: 'Sparkles',
  }

  const slidesData = [
    { title: "精神的ケアに関する研修", order: 0, content: `<div class="flex flex-col items-center justify-center text-center space-y-4 w-full h-full text-balance"><div class="relative w-full max-w-4xl px-4"><div class="absolute inset-0 bg-indigo-400 blur-3xl opacity-20 scale-150 animate-pulse text-center"></div><div class="relative bg-transparent lg:bg-white p-0 lg:p-12 rounded-none lg:rounded-[3.5rem] shadow-none lg:shadow-2xl border-none lg:border lg:border-slate-200 w-full mx-auto text-center"><div class="bg-indigo-700 text-white px-4 lg:px-6 py-1 lg:py-1.5 rounded-full text-[8px] lg:text-[10px] font-black tracking-[0.3em] uppercase inline-block mb-6 lg:mb-8 shadow-sm">法定研修 2024</div><h2 class="text-3xl lg:text-5xl font-black text-slate-900 leading-tight mb-4 text-center">精神的ケア・人格の尊重</h2><p class="text-indigo-700 text-sm lg:text-2xl font-black mt-2 whitespace-nowrap text-center">〜心を通わせ、自分も大切にする〜</p></div></div><div class="flex items-center justify-center gap-4 text-slate-500 font-black text-[8px] lg:text-[10px] tracking-widest pt-4 text-center w-full"><span class="h-px w-6 lg:w-8 bg-slate-300"></span>CARE LEARNING SYSTEM<span class="h-px w-6 lg:w-8 bg-slate-300"></span></div></div>` },
    { title: "人格の尊重：2024年度改正の核心", order: 1, content: `<div class="space-y-4 lg:space-y-6 text-center px-4 h-full flex flex-col justify-center text-balance text-center"><div class="inline-flex items-center gap-3 px-4 py-1.5 bg-indigo-100 text-indigo-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-indigo-200 mb-2 uppercase tracking-widest mx-auto text-center">基本理念</div><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4 text-center w-full">「個人」としての尊厳を守る</h4><div class="p-0 lg:p-8 bg-transparent lg:bg-indigo-50 border-none lg:border-2 lg:border-indigo-100 shadow-none lg:shadow-xl rounded-none lg:rounded-[3rem] text-center lg:text-left text-sm lg:text-lg font-bold text-indigo-800 space-y-4 max-w-4xl mx-auto px-4 text-center"><p class="font-black text-center">利用者は「管理の対象」ではありません。豊かな人生を歩んできた一人の先輩です。本人の意向、嗜好、生活歴を重視し、一律の管理を排したケアが法的に義務付けられました。</p></div></div>` },
    { title: "精神的自立への支援とは？", order: 2, content: `<div class="space-y-4 lg:space-y-6 text-center px-4 h-full flex flex-col justify-center text-balance"><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight mb-2 px-4 text-center w-full text-balance">身体だけでなく「心」を支える</h4><div class="grid grid-cols-1 lg:grid-cols-2 gap-4 max-w-4xl mx-auto w-full"><div class="p-6 lg:p-8 bg-white border-2 border-slate-200 rounded-2xl shadow-xl flex flex-col items-center gap-2 lg:gap-4 text-center"><p class="font-black text-lg lg:text-xl text-indigo-800">役割の再構築</p><p class="text-xs lg:text-sm font-bold text-slate-700 leading-relaxed">「何かを手伝ってもらう」など、施設内での役割を見出し、自尊心を回復させます。</p></div><div class="p-6 lg:p-8 bg-white border-2 border-slate-200 rounded-2xl shadow-xl flex flex-col items-center gap-2 lg:gap-4 text-center"><p class="font-black text-lg lg:text-xl text-indigo-800">意欲の尊重</p><p class="text-xs lg:text-sm font-bold text-slate-700 leading-relaxed">効率よりも「やってみたい」という本人の意欲を最優先し、見守る時間を持ちます。</p></div></div></div>` },
    { title: "魔法の技法：バリデーションの哲学", order: 3, content: `<div class="space-y-6 lg:space-y-8 text-center h-full flex flex-col justify-center px-4 text-balance text-center"><div class="inline-flex items-center gap-3 px-4 py-2 bg-indigo-100 text-indigo-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-indigo-200 mb-2 shadow-sm mx-auto uppercase tracking-widest text-center"><span class="w-2 h-2 bg-indigo-700 rounded-full animate-ping text-center"></span>VALIDATION</div><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight text-center w-full">感情を「肯定」する</h4><div class="p-6 lg:p-10 bg-white border-[4px] lg:border-[6px] border-indigo-600 rounded-[2rem] lg:rounded-[3rem] shadow-2xl max-w-3xl mx-auto w-full text-center"><p class="text-lg lg:text-2xl font-black text-indigo-900 leading-relaxed italic text-balance text-center text-center">正しいか間違いかではない。<br/>「その時どう感じたか」を聴き、<br/>ありのままを受容することです。</p></div></div>` },
    { title: "バリデーションの第1歩：よく見る", order: 4, content: `<div class="flex flex-col items-center text-center space-y-4 lg:space-y-6 px-4 h-full justify-center text-balance text-center text-center"><div class="p-4 lg:p-6 bg-white rounded-[2rem] lg:rounded-[3.5rem] w-full max-w-2xl shadow-xl border-2 border-slate-200 shrink-0 text-center"><h4 class="text-xl lg:text-2xl font-black mb-2 text-slate-900 text-center">非言語情報をキャッチする</h4></div><div class="p-6 bg-indigo-50 border-2 border-indigo-100 rounded-3xl text-left max-w-3xl space-y-4 shadow-inner text-center"><p class="text-sm lg:text-lg font-black text-indigo-900 leading-relaxed text-balance text-center">言葉になる前の不安は、表情、視線、手の動きに現れます。まずは作業の手を止め、10秒間、相手を「観察」することからケアが始まります。</p></div></div>` },
    { title: "バリデーションの第2歩：聴く", order: 5, content: `<div class="flex flex-col items-center text-center space-y-4 lg:space-y-6 px-4 h-full justify-center text-balance text-center text-center"><div class="p-4 lg:p-6 bg-white rounded-[2rem] lg:rounded-[3.5rem] w-full max-w-2xl shadow-xl border-2 border-slate-200 shrink-0 text-center"><h4 class="text-xl lg:text-2xl font-black mb-2 text-slate-900 text-center">「心の声」に耳を傾ける</h4></div><div class="p-6 bg-indigo-50 border-2 border-indigo-100 rounded-3xl text-left max-w-3xl space-y-4 shadow-inner text-center"><p class="text-sm lg:text-lg font-black text-indigo-900 leading-relaxed text-balance text-center">「家に帰らなきゃ」という言葉の裏には、今の場所への「不安」や「寂しさ」があります。事実は重要ではありません。その「感情」を聴き取ります。</p></div></div>` },
    { title: "バリデーションの第3歩：共鳴する", order: 6, content: `<div class="flex flex-col items-center text-center space-y-4 lg:space-y-6 px-4 h-full justify-center text-balance text-center text-center"><div class="p-4 lg:p-6 bg-white rounded-[2rem] lg:rounded-[3.5rem] w-full max-w-2xl shadow-xl border-2 border-slate-200 shrink-0 text-center"><h4 class="text-xl lg:text-2xl font-black mb-2 text-slate-900 text-center">感情を映し出す鏡になる</h4></div><div class="p-6 bg-indigo-50 border-2 border-indigo-100 rounded-3xl text-left max-w-3xl space-y-4 shadow-inner text-center"><p class="text-sm lg:text-lg font-black text-indigo-900 leading-relaxed text-balance text-center">相手の言葉を繰り返し（リフレージング）、「それは不安でしたね」と感情を言葉にして返すことで、「わかってもらえた」という深い安心感を生みます。</p></div></div>` },
    { title: "バリデーションの第4歩：受容する", order: 7, content: `<div class="flex flex-col items-center text-center space-y-4 lg:space-y-6 px-4 h-full justify-center text-balance text-center text-center"><div class="p-4 lg:p-6 bg-white rounded-[2rem] lg:rounded-[3.5rem] w-full max-w-2xl shadow-xl border-2 border-slate-200 shrink-0 text-center"><h4 class="text-xl lg:text-2xl font-black mb-2 text-slate-900 text-center">存在そのものを肯定する</h4></div><div class="p-6 bg-indigo-50 border-2 border-indigo-100 rounded-3xl text-left max-w-3xl space-y-4 shadow-inner text-center"><p class="text-sm lg:text-lg font-black text-indigo-900 leading-relaxed text-balance text-center">どのような感情も、その方にとっては真実です。否定せず受け入れることで、攻撃的な言動（BPSD）は劇的に穏やかになります。</p></div></div>` },
    { title: "ユマニチュード：見る・話す・触れる", order: 8, content: `<div class="flex flex-col items-center text-center space-y-4 lg:space-y-6 px-4 h-full justify-center text-balance text-center text-center"><div class="p-4 lg:p-6 bg-white rounded-[2rem] lg:rounded-[3.5rem] w-full max-w-2xl shadow-xl border-2 border-slate-200 shrink-0 text-center"><h4 class="text-xl lg:text-2xl font-black mb-2 text-slate-900 text-center">人間らしさを伝える技術</h4></div><div class="grid grid-cols-1 lg:grid-cols-3 gap-3 font-black text-[10px] lg:text-sm w-full max-w-5xl"><div class="p-3 bg-indigo-50 border-2 border-indigo-200 rounded-2xl text-left"><p class="text-indigo-900 mb-1 font-black">見る</p><p class="text-slate-600">正面から、同じ高さで、長く見つめる。</p></div><div class="p-3 bg-indigo-50 border-2 border-indigo-200 rounded-2xl text-left"><p class="text-indigo-900 mb-1 font-black">話す</p><p class="text-slate-600">穏やかな声で、ケアを実況中継する。</p></div><div class="p-3 bg-indigo-50 border-2 border-indigo-200 rounded-2xl text-left"><p class="text-indigo-900 mb-1 font-black">触れる</p><p class="text-slate-600">広い面積で、優しくゆっくりと触れる。</p></div></div></div>` },
    { title: "介護は「感情労働」である", order: 9, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left text-balance text-center"><div class="space-y-4"><h4 class="text-2xl lg:text-4xl font-black text-indigo-900 flex items-center gap-4 lg:gap-6 justify-center"><span class="w-2 h-8 lg:w-3 lg:h-12 bg-indigo-700 rounded-full"></span>心の管理という仕事</h4></div><ul class="space-y-4 lg:space-y-6 text-lg lg:text-3xl font-black text-slate-800 pl-0 leading-tight text-center"><li>・自分の感情を抑え、相手に合わせる</li><li>・精神的なエネルギー消費が激しい仕事</li><li>・セルフケアは「義務」である</li></ul><p class="text-rose-700 font-black text-sm lg:text-xl mt-4 text-center w-full">心のコップを溢れさせないために</p></div>` },
    { title: "自分への観察眼：ストレスサイン", order: 10, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left text-balance text-center"><h4 class="text-xl lg:text-2xl font-black text-indigo-900 text-center w-full">自分自身の変化に気づく</h4><ul class="space-y-4 lg:space-y-6 text-sm lg:text-xl font-black text-slate-800 pl-0 leading-tight text-center w-full"><li>・利用者へのイライラが止まらない</li><li>・仕事の後、極度に疲れ果てて動けない</li><li>・眠れない、食欲が極端に変わった</li></ul><p class="text-blue-700 font-black text-center w-full mt-4 text-sm lg:text-lg">「助けて」と言うのもプロのスキルです</p></div>` },
    { title: "デブリーフィング：感情を「出す」場", order: 11, content: `<div class="flex flex-col items-center justify-center h-full space-y-6 lg:space-y-8 px-4 w-full text-balance text-center"><h4 class="text-xl lg:text-2xl font-black text-indigo-900 text-center w-full mb-2 px-4">一人で抱え込まない</h4><div class="grid grid-cols-1 gap-3 lg:gap-4 w-full max-w-2xl text-center"><div class="flex items-center gap-4 bg-white p-3 rounded-2xl border-2 border-slate-100 shadow-sm font-black justify-center lg:justify-start text-sm lg:text-base"><span class="w-10 h-10 bg-indigo-700 text-white rounded-full flex items-center justify-center shrink-0">1</span>看取りや事故の後に、気持ちを話し合う</div><div class="flex items-center gap-4 bg-white p-3 rounded-2xl border-2 border-slate-100 shadow-sm font-black justify-center lg:justify-start text-sm lg:text-base"><span class="w-10 h-10 bg-indigo-700 text-white rounded-full flex items-center justify-center shrink-0">2</span>「辛かったね」と互いの感情を労い合う</div><div class="flex items-center gap-4 bg-white p-3 rounded-2xl border-2 border-slate-100 shadow-sm font-black justify-center lg:justify-start text-sm lg:text-base"><span class="w-10 h-10 bg-indigo-700 text-white rounded-full flex items-center justify-center shrink-0">3</span>批判せず聴くことで、チームの結束を強める</div></div></div>` },
    { title: "オンとオフの境界線（リセット術）", order: 12, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-6 lg:space-y-8 px-4 w-full text-balance"><div class="inline-flex items-center gap-3 px-4 py-1.5 bg-indigo-50 text-indigo-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-indigo-200 mb-2 mx-auto text-center">Self-Reset</div><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4 text-center w-full">施設を出たら「別の自分」へ</h4><div class="p-6 lg:p-10 bg-white border-[4px] lg:border-[6px] border-indigo-600 rounded-[2rem] lg:rounded-[3rem] shadow-2xl max-w-3xl mx-auto w-full text-center"><p class="text-lg lg:text-2xl font-black text-indigo-900 leading-relaxed italic text-balance text-center">着替える、手を洗う、深呼吸する。物理的な動作をトリガーにして、仕事の感情を持ち越さない工夫をしましょう。</p></div></div>` },
    { title: "認知症の心理：なぜ「怒る」のか", order: 13, content: `<div class="flex flex-col items-center justify-center h-full text-left space-y-4 lg:space-y-6 px-6 lg:px-12 w-full text-balance text-center"><h4 class="text-xl lg:text-2xl font-black text-indigo-700 text-center mb-2 uppercase tracking-widest w-full px-4">行動は「SOS」のメッセージ</h4><div class="space-y-6 lg:space-y-8 font-black text-slate-900 max-w-4xl mx-auto w-full text-center"><div><p class="text-lg lg:text-2xl text-indigo-600 mb-1 flex items-center gap-3 justify-center text-center font-black"><span>●</span> 世界の喪失</p><p class="text-sm lg:text-lg text-slate-600 font-bold text-center">意味がわからなくなる恐怖が怒りに変わる。</p></div><div><p class="text-lg lg:text-2xl text-indigo-600 mb-1 flex items-center gap-3 justify-center text-center font-black"><span>●</span> 自尊心の痛み</p><p class="text-sm lg:text-lg text-slate-600 font-bold text-center">「できない自分」を指摘される苦しみ。</p></div><div><p class="text-lg lg:text-2xl text-indigo-600 mb-1 flex items-center gap-3 justify-center text-center font-black"><span>●</span> 伝わらないもどかしさ</p><p class="text-sm lg:text-lg text-slate-600 font-bold text-center text-balance">身体の痛みを言葉にできない混乱。</p></div></div></div>` },
    { title: "アサーション：爽やかな自己主張", order: 14, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-4 lg:space-y-6 px-4 w-full text-balance text-center text-balance"><h4 class="text-xl lg:text-2xl font-black text-indigo-900 text-center w-full px-4">相手も自分も大切に</h4><div class="p-6 bg-white border-2 border-indigo-100 rounded-3xl text-left max-w-3xl space-y-4 shadow-sm mx-auto text-center"><p class="text-sm lg:text-lg font-black text-slate-800 leading-relaxed text-center text-balance">「私は（Iメッセージ）」を主語にして、感情的にならずに希望を伝える技術です。「あなたは（Youメッセージ）」で責めるのをやめ、協力をお願いする対話を目指しましょう。</p></div></div>` },
    { title: "精神特な自立を支える「選択」", order: 15, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left text-balance text-center"><h4 class="text-xl lg:text-2xl font-black text-indigo-900 text-center w-full">小さな「選ぶ」を積み重ねる</h4><ul class="space-y-4 lg:space-y-6 text-sm lg:text-xl font-black text-slate-800 pl-0 leading-tight text-center w-full"><li>・着る服の色、食べる順番、散歩の道</li><li>・本人のこだわりを「こだわり」のままに</li><li>・管理の都合で「一つ」に絞らない</li></ul><p class="text-blue-700 font-black text-center w-full mt-4 text-sm lg:text-lg">自己決定が心の活力を生みます</p></div>` },
    { title: "SNSと精神的ケア：心の境界線", order: 16, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-4 lg:space-y-6 px-4 w-full text-balance"><h4 class="text-xl lg:text-2xl font-black text-rose-900 leading-tight">ネットに感情をぶつけない</h4><div class="p-6 bg-rose-50 border-2 border-rose-100 rounded-3xl text-left max-w-3xl space-y-4 shadow-sm mx-auto text-center"><p class="text-sm lg:text-lg font-black text-slate-800 leading-relaxed text-center">SNSでの愚痴は、一時的にスッキリしても、解決にはなりません。むしろ特定のリスクや信頼失墜を招きます。感情は、信頼できる仲間との対面（デブリーフィング）で消化しましょう。</p></div></div>` },
    { title: "メンタルヘルスの3つの予防", order: 17, content: `<div class="flex flex-col items-center justify-center h-full text-left space-y-4 lg:space-y-6 px-6 lg:px-12 w-full text-balance text-center"><h4 class="text-xl lg:text-2xl font-black text-indigo-700 text-center mb-2 uppercase tracking-widest w-full px-4">組織としての守り</h4><div class="space-y-6 lg:space-y-8 font-black text-slate-900 max-w-4xl mx-auto w-full text-center"><div><p class="text-lg lg:text-2xl text-indigo-600 mb-1 flex items-center gap-3 justify-center text-center font-black"><span>●</span> 1次予防：未然に防ぐ</p><p class="text-sm lg:text-lg text-slate-600 font-bold text-center">研修やストレスチェックで環境を整える。</p></div><div><p class="text-lg lg:text-2xl text-indigo-600 mb-1 flex items-center gap-3 justify-center text-center font-black"><span>●</span> 2次予防：早期発見</p><p class="text-sm lg:text-lg text-slate-600 font-bold text-center">声かけや面談で不調をいち早く察知する。</p></div><div><p class="text-lg lg:text-2xl text-indigo-600 mb-1 flex items-center gap-3 justify-center text-center font-black"><span>●</span> 3次予防：再発防止</p><p class="text-sm lg:text-lg text-slate-600 font-bold text-center">復職支援や業務の見直しを行う。</p></div></div></div>` },
    { title: "CASE STUDY 1：帰宅願望への対応", order: 18, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-4 lg:space-y-6 px-4 w-full text-balance text-center"><div class="inline-flex items-center gap-3 px-4 py-1.5 bg-rose-50 text-rose-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-rose-200 mb-2 mx-auto text-center uppercase">事例 1</div><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4 text-center w-full">「子供が待っているの」</h4><div class="p-6 lg:p-8 bg-white border-2 border-slate-100 rounded-[2rem] lg:rounded-[3rem] shadow-xl max-w-4xl text-left space-y-4 w-full text-center"><p class="text-sm lg:text-lg font-bold text-slate-800 leading-relaxed text-balance px-4 text-center">夕方、F様が「家に帰らなきゃ」と玄関へ。実際にはお子様は成人されています。あなたはどう答えますか？</p><div class="h-px bg-slate-100"></div><p class="text-xs lg:text-base font-black text-indigo-700 italic text-center px-4 text-balance text-center w-full">「嘘」をつくのでもなく、<br class="lg:hidden" />その時の「感情」にどう触れますか？</p></div></div>` },
    { title: "CASE STUDY 2：ケアを拒否する方へ", order: 19, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-4 lg:space-y-6 px-4 w-full text-balance text-center"><div class="inline-flex items-center gap-3 px-4 py-1.5 bg-rose-50 text-rose-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-rose-200 mb-2 mx-auto text-center uppercase">事例 2</div><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4 text-center w-full">「あんたなんかに…！」</h4><div class="p-6 lg:p-8 bg-white border-2 border-slate-100 rounded-[2rem] lg:rounded-[3rem] shadow-xl max-w-4xl text-left space-y-4 w-full text-center"><p class="text-sm lg:text-lg font-bold text-slate-800 leading-relaxed text-balance px-4 text-center">入浴介助中、G様から「あっちへ行け！」と怒鳴られ、強く拒否されました。あなたはショックを受けました。</p><div class="h-px bg-slate-100"></div><p class="text-xs lg:text-base font-black text-indigo-700 italic text-center px-4 text-balance text-center w-full">G様の怒りの裏にあるものは？<br class="lg:hidden" />あなたの「傷ついた心」はどうケアしますか？</p></div></div>` },
    { title: "CASE STUDY 3：職員間の連携不足", order: 20, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-4 lg:space-y-6 px-4 w-full text-balance text-center"><div class="inline-flex items-center gap-3 px-4 py-1.5 bg-rose-50 text-rose-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-rose-200 mb-2 mx-auto text-center uppercase">事例 3</div><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4 text-center w-full">「私だけが忙しい」という不満</h4><div class="p-6 lg:p-8 bg-white border-2 border-slate-100 rounded-[2rem] lg:rounded-[3rem] shadow-xl max-w-4xl text-left space-y-4 w-full text-center"><p class="text-sm lg:text-lg font-bold text-slate-800 leading-relaxed text-balance px-4 text-center">同僚が記録ばかりして、自分だけが介助に走り回っている。不満が溜まり、利用者への言葉が荒くなってしまいました。</p><div class="h-px bg-slate-100"></div><p class="text-xs lg:text-base font-black text-indigo-700 italic text-center px-4 text-balance text-center w-full">相手を責める前に、チームで<br class="lg:hidden" />どう「アサーション」できますか？</p></div></div>` },
    { title: "解決：共感と自己防衛のバランス", order: 21, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-4 lg:space-y-6 px-4 w-full text-balance text-center text-center"><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4 text-center w-full text-center">精神的ケアの具体策</h4><div class="p-6 lg:p-10 bg-indigo-50 border-2 border-indigo-100 rounded-[2.5rem] lg:rounded-[4rem] shadow-inner text-left max-w-4xl space-y-4 mx-auto text-center"><div class="grid grid-cols-1 gap-3 text-sm lg:text-base font-bold text-slate-800 text-center"><div class="flex items-center gap-3 lg:gap-4 bg-white p-3 rounded-xl lg:rounded-2xl border border-indigo-100 shadow-sm text-center justify-center lg:justify-start"><span class="w-6 h-6 lg:w-8 lg:h-8 bg-indigo-600 text-white rounded-full flex items-center justify-center text-[10px] lg:text-sm shrink-0 text-center font-black">1</span>「子供たちを思う優しいお母さんですね」と感情を受容</div><div class="flex items-center gap-3 lg:gap-4 bg-white p-3 rounded-xl lg:rounded-2xl border border-indigo-100 shadow-sm text-center justify-center lg:justify-start"><span class="w-6 h-6 lg:w-8 lg:h-8 bg-indigo-600 text-white rounded-full flex items-center justify-center text-[10px] lg:text-sm shrink-0 text-center font-black">2</span>拒否されたら一度離れる。時間を置き、人を替えて再挑戦</div><div class="flex items-center gap-3 lg:gap-4 bg-white p-3 rounded-xl lg:rounded-2xl border border-indigo-100 shadow-sm text-center justify-center lg:justify-start"><span class="w-6 h-6 lg:w-8 lg:h-8 bg-indigo-600 text-white rounded-full flex items-center justify-center text-[10px] lg:text-sm shrink-0 text-center font-black">3</span>「私が悪いのではない」と自分を切り離し、同僚に吐き出す</div></div></div></div>` },
    { title: "満足感：心が通い合う「魔法」", order: 22, content: `<div class="space-y-6 lg:space-y-8 text-center flex flex-col items-center justify-center h-full px-4 w-full text-balance text-center text-balance"><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4 text-center w-full">プロとしての貢献</h4><div class="p-8 lg:p-10 bg-white border-[4px] lg:border-[6px] border-indigo-600 rounded-[2rem] lg:rounded-[3rem] shadow-2xl max-w-3xl mx-auto w-full text-center"><p class="text-xl lg:text-2xl font-black text-indigo-900 leading-relaxed italic text-balance text-center text-center">精神的ケアは、<br/>相手の孤独を終わらせることです。<br/>あなたの共感こそが、最高の治療薬になります。</p></div><p class="font-black text-sm lg:text-lg text-slate-800 mt-2 text-center w-full px-4 text-center">その誇りを持って、日々を支え合いましょう。</p></div>` },
    { title: "人格尊重のあり方：再確認", order: 23, content: `<div class="flex flex-col items-center justify-center h-full text-left space-y-6 lg:space-y-8 px-6 lg:px-12 w-full text-balance text-center text-center"><h4 class="text-xl lg:text-2xl font-black text-indigo-900 text-center mb-4 uppercase tracking-widest w-full text-center text-center">「見られている」意識</h4><div class="p-6 bg-white border-2 border-indigo-100 rounded-3xl text-left max-w-3xl space-y-4 shadow-sm mx-auto text-center text-center text-balance"><p class="text-sm lg:text-lg font-black text-slate-800 leading-relaxed text-center text-balance">人格尊重とはマニュアルではなく、誰も見ていない時に正しい行動ができるかどうか。相手の立場に立ち、「自分ならどう扱ってほしいか」を常に問い続ける心こそが、最高のケア品質です。</p></div></div>` },
    { title: "まとめ：今日から変えられること", order: 24, content: `<div class="flex flex-col items-center text-center space-y-6 lg:space-y-10 w-full h-full justify-center text-slate-900 px-4 text-center text-balance"><div class="w-24 h-24 lg:w-28 h-28 bg-indigo-700 rounded-[2.5rem] lg:rounded-[3rem] flex items-center justify-center shadow-2xl rotate-3 transition-transform hover:rotate-0 duration-500 mx-auto text-center"><svg class="w-12 h-12 lg:w-16 h-16 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z" /></svg></div><h3 class="text-2xl lg:text-4xl font-black leading-tight text-center w-full text-balance">あなたの心が穏やかであれば、<br/>それは最高のケアになります。</h3><div class="pt-8 lg:pt-10 border-t-2 border-slate-200 w-full max-w-md text-center mx-auto"><p class="text-slate-500 font-black text-[8px] lg:text-[10px] uppercase tracking-[0.5em]">研修終了</p></div></div>` },
    { title: "理解度テストのご案内", order: 25, content: `
        <div class="flex flex-col items-center text-center space-y-4 lg:space-y-6 w-full h-full justify-center px-4 text-center text-balance">
          <div class="bg-emerald-600 text-white px-6 py-1.5 rounded-full text-[8px] lg:text-[10px] font-black tracking-[0.3em] uppercase inline-block mb-4 lg:mb-2 shadow-lg px-4 text-center">修了</div>
          <h2 class="text-2xl lg:text-4xl font-black text-slate-900 leading-tight mb-2 text-center w-full text-balance">講義セッション終了</h2>
          <p class="text-emerald-800 text-base lg:text-xl font-black leading-relaxed text-center w-full text-balance px-4">大変お疲れ様でした。<br/>最後に理解度テスト（全10問）を行います。</p>
          <div class="p-4 lg:p-6 bg-indigo-50 rounded-2xl lg:rounded-3xl border-2 border-indigo-100 max-w-lg mx-auto mt-6">
            <p class="text-indigo-900 font-black text-sm lg:text-lg flex items-center justify-center gap-3 text-center">
              <span class="w-2 h-2 bg-indigo-700 rounded-full"></span>    
              全問正解を目指しましょう！
              <span class="w-2 h-2 bg-indigo-700 rounded-full"></span>    
            </p>
          </div>
        </div>
      ` }
  ]

  const questionsData = [
    { text: '利用者の感情に焦点を当て、事実の正誤を問わずに受容し共感するコミュニケーション技法を何というか？', explanation: 'バリデーション（Validation）と呼ばれ、認知症の方の自尊心の回復や不安の軽減に非常に有効な手法です。', order: 1, choices: { create: [{ text: 'バリデーション', isCorrect: true }, { text: 'オリエンテーション', isCorrect: false }, { text: 'コーチング', isCorrect: false }] } },
    { text: '2024年度の法改正で強化された、一律の管理を排し、本人の意向や嗜好を尊重する義務を何というか？', explanation: '「人格の尊重」が全てのケアの基盤として義務化されました。', order: 2, choices: { create: [{ text: '人格の尊重', isCorrect: true }, { text: '効率的な管理', isCorrect: false }, { text: '安全の強制', isCorrect: false }] } },
    { text: '自分自身の感情を管理・抑制しながら働くことで、精神的な負担が生じる労働形態を何というか？', explanation: '「感情労働（Emotional Labor）」と呼ばれます。介護職はこの負担が大きいため、適切なケアが必要です。', order: 3, choices: { create: [{ text: '感情労働', isCorrect: true }, { text: '肉体労働のみ', isCorrect: false }, { text: '単純労働', isCorrect: false }] } },
    { text: 'スタッフの燃え尽き（バーンアウト）を防ぐため、困難な事例の後にチームで感情を共有し合うことを何というか？', explanation: '「デブリーフィング（振り返り）」と呼ばれます。感情を表出することで、精神的な健康を保ちます。', order: 4, choices: { create: [{ text: 'デブリーフィング', isCorrect: true }, { text: 'OJT（職場内訓練）', isCorrect: false }, { text: 'ケーススタディのみ', isCorrect: false }] } },
    { text: 'ユマニチュードの4つの柱に含まれないものはどれか？', explanation: '「見る」「話す」「触れる」「立つ」が4つの柱です。「叱る」は含まれません。', order: 5, choices: { create: [{ text: '叱る', isCorrect: true }, { text: '見る', isCorrect: false }, { text: '触れる', isCorrect: false }, { text: '話す', isCorrect: false }] } },
    { text: '帰宅願望がある利用者に対し、正論で「夜だから帰れません」と説得することへの評価として正しいものは？', explanation: '正論は相手の不安を煽るだけで、解決に繋がりません。まずは「帰りたくなった理由（感情）」を受容します。', order: 6, choices: { create: [{ text: '不安を強めるため不適切である', isCorrect: true }, { text: '事実を伝えるのがプロの誠実さである', isCorrect: false }, { text: '繰り返し説明すれば納得してもらえる', isCorrect: false }] } },
    { text: '「マインドフルネス」などを用いて、自分自身のストレスを軽減する行為を何というか？', explanation: '「セルフケア」と呼ばれます。介護職が長く働き続けるための必須スキルです。', order: 7, choices: { create: [{ text: 'セルフケア', isCorrect: true }, { text: '自己犠牲', isCorrect: false }, { text: 'サービス残業', isCorrect: false }] } },
    { text: '利用者から強い言葉で拒絶された際、介護職が持つべき心構えとして適切なものは？', explanation: '「自分が悪い」と責めず、その方の「病気や不安」がそうさせていると考え、一歩引いて状況を整理します。', order: 8, choices: { create: [{ text: '個人への攻撃ではなく、不安の現れだと考える', isCorrect: true }, { text: 'プロ失格だと自分を責める', isCorrect: false }, { text: '二度とその利用者のケアに入らない', isCorrect: false }] } },
    { text: 'デブリーフィングの場で、最も大切にすべき態度はどれか？', explanation: '他者の感情を否定したり批判したりせず、まずは「共感的に聴く」ことが支え合いの基本です。', order: 9, choices: { create: [{ text: '互いの感情を批判せず、受容する', isCorrect: true }, { text: 'ミスの犯人探しをする', isCorrect: false }, { text: '論理的な解決策だけを話し合う', isCorrect: false }] } },
    { text: '認知症の方とのコミュニケーションで、「正面から見つめる」ことの効果はどれか？', explanation: '視覚的な情報を一致させ、「あなたを大切に思っています」というメッセージを脳に直接届けます。', order: 10, choices: { create: [{ text: '「あなたを認識している」という安心感を与える', isCorrect: true }, { text: '威圧感を与えて制止させる', isCorrect: false }, { text: '監視していることを伝える', isCorrect: false }] } }
  ]

  let course = await prisma.course.findUnique({ where: { slug } })

  if (course) {
    await prisma.choice.deleteMany({ where: { question: { courseId: course.id } } })
    await prisma.question.deleteMany({ where: { courseId: course.id } })
    await prisma.slide.deleteMany({ where: { courseId: course.id } })
    
    course = await prisma.course.update({
      where: { id: course.id },
      data: {
        ...courseData,
        slides: { create: slidesData },
        questions: { create: questionsData }
      }
    })
  } else {
    course = await prisma.course.create({
      data: {
        ...courseData,
        slides: { create: slidesData },
        questions: { create: questionsData }
      }
    })
  }

  return course
}
