import { PrismaClient } from '@prisma/client'

export async function seedPrevention(prisma: PrismaClient) {
  const slug = 'prevention'
  const courseData = {
    slug,
    title: '介護予防・自立支援研修（2024年度）',
    description: '〜自分らしく生きる力を支えるために〜',
    introduction: `
        <div class="flex flex-col items-center justify-center text-center space-y-2 pt-2 px-4">
          <div class="flex items-center gap-4">
            <span class="h-px w-8 lg:w-12 bg-emerald-700 rounded-full"></span>
            <p class="text-emerald-800 font-black tracking-widest text-lg lg:text-xl uppercase">介護予防・自立支援研修</p>
            <span class="h-px w-8 lg:w-12 bg-emerald-700 rounded-full"></span>
          </div>
          <h2 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight">「お世話」が利用者の<br/>力を奪っていませんか？</h2>
          <div class="max-w-2xl space-y-2 text-slate-800 text-sm lg:text-base leading-relaxed font-bold">
            <p>良かれと思って先回りして手助けすることが、<br class="lg:hidden" />実は利用者の「できること」を<br class="lg:hidden" />減らしてしまっているかもしれません。</p>
            <div class="p-3 lg:p-4 bg-emerald-50 rounded-[1.5rem] lg:rounded-[2rem] border-2 border-emerald-200 shadow-inner relative overflow-hidden text-[10px] lg:text-xs text-left">
              <div class="absolute top-0 right-0 w-16 h-16 lg:w-20 lg:h-20 bg-emerald-100/50 rounded-bl-full"></div>
              <p class="relative z-10 italic text-emerald-900 font-black text-xs lg:text-sm">介護予防の本質は、単に機能を維持することではなく、その人が「その人らしく」輝き続けるための意欲を支えることにあります。</p>
            </div>
            <p class="text-[10px] lg:text-sm text-slate-900 font-black">プロとして、利用者の「持てる力」を最大限に引き出す視点を身につけましょう。</p>
          </div>
        </div>
      `,
    learningObjectives: `
        <div class="flex flex-col items-center justify-center text-center space-y-3 pt-2 px-4 w-full">
          <div class="bg-emerald-700 text-white px-6 py-1.5 rounded-full text-[10px] font-black tracking-[0.3em] uppercase mb-1 shadow-lg shadow-emerald-200">Learning Objectives</div>
          <div class="grid grid-cols-1 gap-2 w-full max-w-2xl">
            <div class="group p-3 lg:p-4 bg-white border-2 border-slate-200 rounded-[1.5rem] lg:rounded-[2rem] shadow-sm flex items-center gap-4 lg:gap-6 hover:shadow-xl hover:border-emerald-400 transition-all duration-500">
              <div class="w-10 h-10 lg:w-12 lg:h-12 bg-emerald-700 text-white rounded-xl flex items-center justify-center text-base lg:text-lg font-black shrink-0 shadow-lg shadow-emerald-200">1</div>
              <div class="text-left">
                <h4 class="text-sm lg:text-base font-black text-slate-900">強みに着目する視点を持つ</h4>
                <p class="text-slate-800 text-[10px] lg:text-xs font-bold leading-tight">ICFに基づき、「できないこと」ではなく「できること」を見つけられる。</p>
              </div>
            </div>
            <div class="group p-3 lg:p-4 bg-white border-2 border-slate-200 rounded-[1.5rem] lg:rounded-[2rem] shadow-sm flex items-center gap-4 lg:gap-6 hover:shadow-xl hover:border-emerald-400 transition-all duration-500">
              <div class="w-10 h-10 lg:w-12 lg:h-12 bg-emerald-700 text-white rounded-xl flex items-center justify-center text-base lg:text-lg font-black shrink-0 shadow-lg shadow-emerald-200">2</div>
              <div class="text-left">
                <h4 class="text-sm lg:text-base font-black text-slate-900">2024年改正の要点を理解する</h4>
                <p class="text-slate-800 text-[10px] lg:text-xs font-bold leading-tight">リハ・口腔・栄養の一体的な取り組みと、科学的介護（LIFE）の意義を学ぶ。</p>
              </div>
            </div>
            <div class="group p-3 lg:p-4 bg-white border-2 border-slate-200 rounded-[1.5rem] lg:rounded-[2rem] shadow-sm flex items-center gap-4 lg:gap-6 hover:shadow-xl hover:border-emerald-400 transition-all duration-500">
              <div class="w-10 h-10 lg:w-12 lg:h-12 bg-emerald-700 text-white rounded-xl flex items-center justify-center text-base lg:text-lg font-black shrink-0 shadow-lg shadow-emerald-200">3</div>
              <div class="text-left">
                <h4 class="text-sm lg:text-base font-black text-slate-900">現場での具体的な支援を提案できる</h4>
                <p class="text-slate-800 text-[10px] lg:text-xs font-bold leading-tight">過剰介護を避け、利用者の主体性を引き出す適切な声掛けを実践できる。</p>
              </div>
            </div>
          </div>
        </div>
      `,
    videoUrl: 'https://www.youtube.com/watch?v=JVLmK8A5k1U',
    badgeLabel: '介護予防',
    badgeIcon: 'Zap',
  }

  const slidesData = [
    { title: "介護予防・自立支援研修", order: 0, content: `<div class="flex flex-col items-center justify-center text-center space-y-4 w-full h-full"><div class="relative w-full max-w-4xl px-4"><div class="absolute inset-0 bg-emerald-400 blur-3xl opacity-20 scale-150 animate-pulse"></div><div class="relative bg-transparent lg:bg-white p-0 lg:p-12 rounded-none lg:rounded-[3.5rem] shadow-none lg:shadow-2xl border-none lg:border lg:border-slate-200 w-full mx-auto"><div class="bg-emerald-700 text-white px-4 lg:px-6 py-1 lg:py-1.5 rounded-full text-[8px] lg:text-[10px] font-black tracking-[0.3em] uppercase inline-block mb-6 lg:mb-8 shadow-sm">Legal Training 2024</div><h2 class="text-3xl lg:text-5xl font-black text-slate-900 leading-tight mb-4 text-balance">介護予防・自立支援研修</h2><p class="text-emerald-700 text-sm lg:text-2xl font-black mt-2 whitespace-nowrap">〜自分らしく生きる力を支えるプロとして〜</p></div></div><div class="flex items-center justify-center gap-4 text-slate-500 font-black text-[8px] lg:text-[10px] tracking-widest pt-4"><span class="h-px w-6 lg:w-8 bg-slate-300"></span>CARE LEARNING SYSTEM<span class="h-px w-6 lg:w-8 bg-slate-300"></span></div></div>` },
    { title: "はじめに：『自立』の本質", order: 1, content: `<div class="space-y-4 lg:space-y-6 text-center px-4 h-full flex flex-col justify-center"><div class="inline-flex items-center gap-3 px-4 py-1.5 bg-emerald-100 text-emerald-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-emerald-200 mb-2 uppercase tracking-widest mx-auto">Introduction</div><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight">「なんでもしてあげる」が<br/>利用者を弱らせていませんか？</h4><div class="p-0 lg:p-8 bg-transparent lg:bg-slate-50 border-none lg:border-2 lg:border-emerald-100 shadow-none lg:shadow-xl rounded-none lg:rounded-[3rem] text-center lg:text-left text-sm lg:text-lg font-bold text-emerald-800 space-y-4 leading-relaxed max-w-4xl mx-auto"><p class="font-black text-center lg:text-left">自立支援の本質は、筋トレをすることではありません。その人が「自分の人生を自分で決める」意欲を支え続けることにあります。</p><p class="font-black text-center lg:text-left">プロとして、利用者の「可能性」を信じる勇気を持つことから始めましょう。</p></div></div>` },
    { title: "2024年度 改正の背景", order: 2, content: `<div class="space-y-4 lg:space-y-6 text-center px-4 h-full flex flex-col justify-center"><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight mb-2 text-balance">なぜ今、自立支援が加速しているのか</h4><div class="grid grid-cols-1 lg:grid-cols-2 gap-4 max-w-4xl mx-auto w-full"><div class="p-6 lg:p-8 bg-white border-2 border-slate-200 rounded-[2rem] lg:rounded-[2.5rem] shadow-xl flex flex-col items-center gap-2 lg:gap-4"><p class="font-black text-lg lg:text-xl text-emerald-800">深刻な多死社会の到来</p><p class="text-xs lg:text-sm font-bold text-slate-700 leading-relaxed text-balance">限られた社会保障の中で、一人ひとりがQOLを維持することが不可欠です。</p></div><div class="p-6 lg:p-8 bg-white border-2 border-slate-200 rounded-[2rem] lg:rounded-[2.5rem] shadow-xl flex flex-col items-center gap-2 lg:gap-4"><p class="font-black text-lg lg:text-xl text-emerald-800">重度化防止の義務化</p><p class="text-xs lg:text-sm font-bold text-slate-700 leading-relaxed text-balance">「現状維持」は目標ではなく、改善を目指す姿勢が標準として求められています。</p></div></div></div>` },
    { title: "三位一体：重度化防止の核", order: 3, content: `<div class="space-y-6 lg:space-y-8 text-center h-full flex flex-col justify-center px-4"><div class="inline-flex items-center gap-3 px-4 py-2 bg-red-100 text-red-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-red-200 mb-2 shadow-sm mx-auto"><span class="w-2 h-2 bg-red-700 rounded-full animate-ping"></span>MUST CHECK</div><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight">2024年改正が求める<br/>3つの連動</h4><div class="grid grid-cols-1 lg:grid-cols-3 gap-3 lg:gap-4 max-w-5xl mx-auto w-full"><div class="p-4 lg:p-6 bg-slate-50 border-2 border-slate-200 rounded-2xl lg:rounded-3xl text-center font-black text-sm lg:text-base text-slate-900 shadow-sm hover:border-emerald-400 transition-all">リハビリテーション</div><div class="p-4 lg:p-6 bg-slate-50 border-2 border-slate-200 rounded-2xl lg:rounded-3xl text-center font-black text-sm lg:text-base text-slate-900 shadow-sm hover:border-emerald-400 transition-all">口腔管理の強化</div><div class="p-4 lg:p-6 bg-slate-50 border-2 border-slate-200 rounded-2xl lg:rounded-3xl text-center font-black text-sm lg:text-base text-slate-900 shadow-sm hover:border-emerald-400 transition-all">栄養管理の最適化</div></div><p class="text-emerald-700 font-black text-[10px] lg:text-sm mt-4 underline underline-offset-4 decoration-2 text-balance">※バラバラのケアを統合し、チームで重度化を防ぎます。</p></div>` },
    { title: "ICF（国際生活機能分類）の視点", order: 4, content: `<div class="flex flex-col items-center text-center space-y-4 lg:space-y-6 px-4 h-full justify-center"><div class="p-4 lg:p-6 bg-white rounded-[2rem] lg:rounded-[3.5rem] w-full max-w-2xl shadow-xl border-2 border-slate-200 shrink-0"><h4 class="text-xl lg:text-2xl font-black mb-2 text-slate-900">「強み」を活かすアプローチ</h4><p class="text-[10px] lg:text-sm text-slate-900 font-black">ICFモデルに基づき、可能性を広げましょう</p></div><div class="grid grid-cols-1 lg:grid-cols-2 gap-3 lg:gap-x-12 lg:gap-y-3 font-black text-sm lg:text-base w-full max-w-4xl"><div class="flex flex-col gap-3"><span class="px-6 py-2 lg:py-2.5 bg-blue-50 border-2 border-blue-200 rounded-2xl text-blue-900 shadow-sm text-center">身体機能・構造</span><span class="px-6 py-2 lg:py-2.5 bg-rose-50 border-2 border-rose-200 rounded-2xl text-rose-900 shadow-sm text-center">活動（ADL・生活）</span></div><div class="flex flex-col gap-3"><span class="px-6 py-2 lg:py-2.5 bg-purple-50 border-2 border-purple-200 rounded-2xl text-purple-900 shadow-sm text-center">参加（社会的な役割）</span><span class="px-6 py-2 lg:py-2.5 bg-emerald-50 border-2 border-emerald-200 rounded-2xl text-emerald-900 shadow-sm text-center">環境・個人因子</span></div></div></div>` },
    { title: "1. 運動機能：生活リハの真髄", order: 5, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left"><div class="space-y-4"><h4 class="text-2xl lg:text-4xl font-black text-emerald-900 flex items-center gap-4 lg:gap-6"><span class="w-2 h-8 lg:w-3 lg:h-12 bg-emerald-700 rounded-full"></span>生活そのものが訓練</h4></div><ul class="space-y-4 lg:space-y-6 text-lg lg:text-3xl font-black text-slate-800 pl-0 leading-tight"><li class="whitespace-nowrap">・「座る」「立つ」を生活動線に組み込む</li><li class="whitespace-nowrap">・廃用症候群（動かないことによる衰え）の理解</li><li class="whitespace-nowrap">・道具の力（福祉用具）で「できる」を増やす</li></ul></div>` },
    { title: "廃用症候群：負の連鎖を断つ", order: 6, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left"><div class="space-y-4"><h4 class="text-2xl lg:text-4xl font-black text-rose-800 flex items-center gap-4 lg:gap-6"><span class="w-2 h-8 lg:w-3 lg:h-12 bg-rose-600 rounded-full"></span>安静は毒になり得る</h4></div><ul class="space-y-4 lg:space-y-6 text-lg lg:text-3xl font-black text-slate-800 pl-0 leading-tight"><li class="whitespace-nowrap">・1週間の寝たきりで、15%の筋力が消失</li><li class="whitespace-nowrap">・筋力低下、関節拘縮、認知症の進行</li><li class="whitespace-nowrap">・「座る」だけでも、心肺機能は活性化する</li></ul></div>` },
    { title: "2. 栄養管理：フレイル予防", order: 7, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left"><div class="space-y-4"><h4 class="text-2xl lg:text-4xl font-black text-orange-800 flex items-center gap-4 lg:gap-6"><span class="w-2 h-8 lg:w-3 lg:h-12 bg-orange-600 rounded-full"></span>しっかり食べて筋肉を守る</h4></div><ul class="space-y-4 lg:space-y-6 text-lg lg:text-3xl font-black text-slate-800 pl-0 leading-tight"><li class="whitespace-nowrap">・低栄養はフレイル（虚弱）の入り口</li><li class="whitespace-nowrap text-balance">・体重減少は「老化」ではなく「低栄養」</li><li class="whitespace-nowrap text-balance">・多職種で「食べられない理由」を探る</li></ul></div>` },
    { title: "フレイルサイクル：最悪の連鎖", order: 8, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left"><div class="space-y-4"><h4 class="text-2xl lg:text-4xl font-black text-amber-700 flex items-center gap-4 lg:gap-6"><span class="w-2 h-8 lg:w-3 lg:h-12 bg-amber-600 rounded-full"></span>衰えの加速を止める</h4></div><ul class="space-y-4 lg:space-y-6 text-lg lg:text-3xl font-black text-slate-800 pl-0 leading-tight"><li class="whitespace-nowrap">・食欲低下 → 筋肉減少 → 活動低下</li><li class="whitespace-nowrap">・活動低下 → お腹が空かない → さらに食べない</li><li class="whitespace-nowrap text-balance">・早期発見と、攻めの栄養介入が必要</li></ul></div>` },
    { title: "3. 口腔機能：噛める喜び", order: 9, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left"><div class="space-y-4"><h4 class="text-2xl lg:text-4xl font-black text-blue-900 flex items-center gap-4 lg:gap-6"><span class="w-2 h-8 lg:w-3 lg:h-12 bg-blue-700 rounded-full"></span>オーラルフレイルの予防</h4></div><ul class="space-y-4 lg:space-y-6 text-lg lg:text-3xl font-black text-slate-800 pl-0 leading-tight"><li class="whitespace-nowrap">・「食べこぼし」は機能低下のサイン</li><li class="whitespace-nowrap">・誤嚥性肺炎を未然に防ぐ口腔清掃</li><li class="whitespace-nowrap">・歯科専門職との密な連携が鍵</li></ul></div>` },
    { title: "口腔機能低下のサイン", order: 10, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left"><div class="space-y-4"><h4 class="text-2xl lg:text-4xl font-black text-emerald-900 flex items-center gap-4 lg:gap-6"><span class="w-2 h-8 lg:w-3 lg:h-12 bg-emerald-700 rounded-full"></span>食事の変化を見逃さない</h4></div><ul class="space-y-4 lg:space-y-6 text-lg lg:text-3xl font-black text-slate-800 pl-0 leading-tight"><li class="whitespace-nowrap">・滑舌の悪化、言葉の不明瞭さ</li><li class="whitespace-nowrap">・固いものが噛めなくなった</li><li class="whitespace-nowrap">・汁物でむせることが増えた</li></ul></div>` },
    { title: "改正：栄養・口腔の連携基準", order: 11, content: `<div class="p-4 lg:p-2 relative overflow-hidden text-left max-w-4xl mx-auto flex flex-col items-center h-full justify-center"><div class="absolute -top-10 -right-10 w-64 h-64 bg-emerald-50 rounded-full blur-3xl opacity-50"></div><h4 class="text-[10px] lg:text-[10px] font-black tracking-[0.4em] uppercase text-emerald-800 mb-6 lg:mb-2 text-center py-2 px-6 bg-emerald-50 rounded-full border border-emerald-100 shadow-sm">連携の3ステップ</h4><div class="space-y-4 lg:space-y-2 w-full lg:max-w-3xl text-slate-900"><div><p class="text-emerald-800 text-[10px] lg:text-[8px] mb-1 lg:mb-0 uppercase tracking-widest font-black">01. 初期評価</p><div class="lg:flex lg:items-baseline lg:gap-6"><p class="text-2xl lg:text-3xl font-black whitespace-nowrap mb-1 lg:mb-0">スクリーニング</p><p class="text-sm lg:text-lg font-bold text-slate-600">栄養・口腔の状態を全職員で把握する</p></div></div><div class="h-px bg-slate-100 lg:my-1"></div><div><p class="text-emerald-800 text-[10px] lg:text-[8px] mb-1 lg:mb-0 uppercase tracking-widest font-black">02. 一体的計画</p><div class="lg:flex lg:items-baseline lg:gap-6"><p class="text-2xl lg:text-3xl font-black whitespace-nowrap mb-1 lg:mb-0">個別計画への反映</p><p class="text-sm lg:text-lg font-bold text-slate-600">リハビリ計画に栄養目標を必ず入れる</p></div></div><div class="h-px bg-slate-100 lg:my-1"></div><div><p class="text-emerald-800 text-[10px] lg:text-[8px] mb-1 lg:mb-0 uppercase tracking-widest font-black">03. モニタリング</p><div class="lg:flex lg:items-baseline lg:gap-6"><p class="text-2xl lg:text-3xl font-black whitespace-nowrap mb-1 lg:mb-0">継続的な再評価</p><p class="text-sm lg:text-lg font-bold text-slate-600">3ヶ月ごとに多職種で進捗を確認する</p></div></div></div></div>` },
    { title: "4. 社会参加：役割の重要性", order: 12, content: `<div class="space-y-4 lg:space-y-6 text-center flex flex-col items-center justify-center h-full px-4 w-full"><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight mb-2">役割があるから、人は元気になる</h4><div class="space-y-4 lg:space-y-6 font-black text-slate-800 max-w-4xl text-base lg:text-xl leading-relaxed text-left"><div>1. 「お世話される側」の固定概念を壊す</div><div>2. 施設内での小さな「仕事」や「役割」を見出す</div><div>3. 他者との交流による脳への刺激（認知症予防）</div><div>4. 地域社会との接点を維持し、社会性を保つ</div></div></div>` },
    { title: "社会的孤立というリスク", order: 13, content: `<div class="p-8 lg:p-10 bg-amber-50 rounded-[2.5rem] lg:rounded-[4rem] border-4 border-amber-300 border-dashed text-center shadow-inner max-w-4xl mx-auto flex flex-col items-center justify-center h-full px-4"><div class="bg-amber-700 text-white px-6 lg:px-8 py-1.5 lg:py-2 rounded-full text-[8px] lg:text-[10px] font-black inline-block mb-6 lg:mb-8 uppercase tracking-widest shadow-lg">Crucial Point</div><h4 class="text-xl lg:text-2xl font-black text-amber-950 mb-6 lg:mb-8 italic text-balance">「誰にも必要とされない」<br/>その孤独が機能を奪います</h4><p class="text-lg lg:text-xl font-black text-amber-900 leading-relaxed py-4 lg:py-6 px-4">役割を失った時、身体機能は加速度的に<br/>衰えていくことを理解しましょう。</p></div>` },
    { title: "不適切な「過剰介護」の弊害", order: 14, content: `<div class="space-y-4 lg:space-y-8 text-center flex flex-col items-center justify-center h-full px-4 w-full"><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-relaxed mb-4">「親切」という名の能力剥奪</h4><div class="grid grid-cols-1 gap-4 lg:gap-6 max-w-2xl mx-auto w-full"><div class="p-6 lg:p-8 bg-white border-2 border-slate-200 rounded-3xl shadow-xl text-left flex items-center gap-4 lg:gap-6"><div class="w-10 h-10 lg:w-12 lg:h-12 bg-blue-700 text-white rounded-full flex items-center justify-center shrink-0 font-black text-xs lg:text-base">1</div><div><p class="font-black text-base lg:text-xl text-blue-800 mb-1">効率重視の介助</p><p class="text-[10px] lg:text-sm font-bold text-slate-700 leading-relaxed text-balance">忙しいからと、本人ができる食事や更衣を代行してしまう。</p></div></div><div class="p-6 lg:p-8 bg-white border-2 border-slate-200 rounded-3xl shadow-xl text-left flex items-center gap-4 lg:gap-6"><div class="w-10 h-10 lg:w-12 lg:h-12 bg-blue-700 text-white rounded-full flex items-center justify-center shrink-0 font-black text-xs lg:text-base">2</div><div><p class="font-black text-base lg:text-xl text-blue-800 mb-1">リスク回避の制限</p><p class="text-[10px] lg:text-sm font-bold text-slate-700 leading-relaxed text-balance">「危ないから立たないで」と、意欲を摘み取ってしまう。</p></div></div></div></div>` },
    { title: "自立支援チェック：自己省察", order: 15, content: `<div class="space-y-4 lg:space-y-6 text-center flex flex-col items-center justify-center h-full w-full px-4"><h4 class="text-xl lg:text-2xl font-black text-slate-900 mb-4">今日の自分の関わりを振り返る</h4><div class="space-y-3 lg:space-y-4 font-black text-slate-900 text-sm lg:text-xl max-w-4xl text-left"><div>□ 利用者の「できること」を、1つ以上見つけられたか？</div><div>□ 「〜しましょうか？」より「〜できますか？」と聞いたか？</div><div>□ 効率のために、本人の動作を奪っていなかったか？</div><div>□ 失敗を恐れず、本人の「やってみたい」を応援したか？</div><div>□ できない部分だけをサポートする「引き算の介護」をしたか？</div></div></div>` },
    { title: "ケーススタディ：配膳したいA様", order: 16, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-4 lg:space-y-6 px-4 w-full"><div class="inline-flex items-center gap-3 px-4 py-1.5 bg-amber-50 text-amber-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-amber-200 mb-2 mx-auto">CASE STUDY</div><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4">場面：少し足元が不安定なA様</h4><div class="p-6 lg:p-8 bg-white border-2 border-slate-100 rounded-[2rem] lg:rounded-[3rem] shadow-xl max-w-4xl text-left space-y-4 w-full"><p class="text-sm lg:text-lg font-bold text-slate-800 leading-relaxed text-balance text-center">A様が「私も食事を運びたい」と仰いました。<br class="lg:hidden" />忙しいB職員は、転倒リスクを恐れ、<br class="lg:hidden" /><span class="text-rose-600 font-black">「危ないから座っててください、私がやります」</span><br/>とお断りしてしまいました。</p><div class="h-px bg-slate-100"></div><p class="text-xs lg:text-base font-black text-blue-700 italic text-center px-4">このB職員の対応によって、<br class="lg:hidden" />A様から何が失われたでしょうか？</p></div></div>` },
    { title: "分析：意欲という「資源」", order: 17, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-4 lg:space-y-6 px-4 w-full"><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight">分析：その時、何が起きたか</h4><div class="grid grid-cols-1 lg:grid-cols-2 gap-4 lg:gap-6 max-w-5xl mx-auto w-full"><div class="p-6 lg:p-8 bg-rose-50 border-2 border-rose-100 rounded-[2rem] text-left space-y-3 shadow-sm"><p class="font-black text-base lg:text-lg text-rose-700">喪失したもの</p><ul class="text-[10px] lg:text-xs font-bold text-slate-700 space-y-1"><li>・「役に立ちたい」という自尊心</li><li>・歩行機能を維持する運動機会</li><li>・自分で決めるという主体性</li></ul></div><div class="p-6 lg:p-8 bg-blue-50 border-2 border-blue-100 rounded-[2rem] text-left space-y-3 shadow-sm"><p class="font-black text-base lg:text-lg text-blue-700">プロの提案</p><ul class="text-[10px] lg:text-xs font-bold text-slate-700 space-y-1"><li>・「お箸を並べていただけますか？」と頼む</li><li>・座ったままできる「ふきん畳み」を提案</li><li>・安全を確保して一緒に配膳する</li></ul></div></div></div>` },
    { title: "科学的介護：LIFEの活用手法", order: 18, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-4 lg:space-y-6 px-4 w-full"><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight">データで「自立」を可視化する</h4><div class="p-6 lg:p-10 bg-emerald-50 border-2 border-emerald-100 rounded-[2.5rem] lg:rounded-[4rem] shadow-inner text-left max-w-4xl space-y-4 mx-auto"><p class="text-base lg:text-lg font-black text-emerald-900 text-center">LIFEへの入力は「事務作業」ではない</p><div class="grid grid-cols-1 gap-3 text-sm lg:text-base font-bold text-slate-800"><div class="flex items-center gap-3 lg:gap-4 bg-white p-3 rounded-xl lg:rounded-2xl border border-emerald-100 shadow-sm"><span class="w-6 h-6 lg:w-8 lg:h-8 bg-emerald-600 text-white rounded-full flex items-center justify-center text-[10px] lg:text-sm shrink-0">1</span>数値の変化から、ケアの成果を客観的に見る</div><div class="flex items-center gap-3 lg:gap-4 bg-white p-3 rounded-xl lg:rounded-2xl border border-emerald-100 shadow-sm"><span class="w-6 h-6 lg:w-8 lg:h-8 bg-emerald-600 text-white rounded-full flex items-center justify-center text-[10px] lg:text-sm shrink-0">2</span>全国のデータと比較し、自施設の強みを知る</div><div class="flex items-center gap-3 lg:gap-4 bg-white p-3 rounded-xl lg:rounded-2xl border border-emerald-100 shadow-sm"><span class="w-6 h-6 lg:w-8 lg:h-8 bg-emerald-600 text-white rounded-full flex items-center justify-center text-[10px] lg:text-sm shrink-0">3</span>根拠のあるケア（EBPC）を実践する盾にする</div></div></div></div>` },
    { title: "認知症と自立支援の工夫", order: 19, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-4 lg:space-y-6 px-4 w-full"><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight">「工夫」で不自由を乗り越える</h4><div class="p-8 lg:p-10 bg-white border-4 border-emerald-100 rounded-[2rem] lg:rounded-[3rem] shadow-xl max-w-4xl mx-auto w-full"><p class="text-xl lg:text-2xl font-black leading-relaxed text-center text-slate-900">言葉での説明ではなく、<br/><span class="text-emerald-700 underline underline-offset-8 decoration-4">環境</span>と<span class="text-emerald-700 underline underline-offset-8 decoration-4">習慣</span>で支える。</p></div><p class="text-[10px] lg:text-base font-black text-emerald-800 px-4 text-balance text-center">※昔の習慣（仕事や家事）は、認知症になっても身体が覚えています。</p></div>` },
    { title: "多職種連携：専門性の統合", order: 20, content: `<div class="flex flex-col items-center justify-center h-full text-left space-y-6 lg:space-y-8 px-6 lg:px-12 w-full"><h4 class="text-xl lg:text-2xl font-black text-blue-800 flex items-center gap-4 w-full"><svg class="w-6 h-6 lg:w-8 lg:h-8 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" /></svg>職種の壁を越える</h4><p class="text-sm lg:text-xl font-black leading-relaxed text-slate-900 max-w-4xl bg-blue-50 p-6 lg:p-8 rounded-2xl lg:rounded-3xl border border-blue-100 w-full text-balance">介護職、看護職、リハ職、管理栄養士、歯科衛生士。全員が同じ「自立」という目標を共有しなければ、ケアは成立しません。</p><p class="text-xs lg:text-lg font-black text-blue-800 text-center w-full">24時間の生活を知る介護職の情報こそが、連携の起点です。</p></div>` },
    { title: "尊厳を支えるプロの誇り", order: 21, content: `<div class="flex flex-col items-center justify-center h-full text-left space-y-4 lg:space-y-6 px-6 lg:px-12 w-full"><h4 class="text-xl lg:text-2xl font-black text-emerald-900 text-center mb-2 uppercase tracking-widest w-full">自立支援の倫理基準</h4><div class="space-y-6 lg:space-y-8 font-black text-slate-900 max-w-4xl mx-auto w-full"><div><p class="text-lg lg:text-2xl text-emerald-700 mb-1 flex items-center gap-3"><span>●</span> 自己決定の尊重</p><p class="text-sm lg:text-lg pl-8 lg:pl-12 text-slate-600 font-bold">どんなに衰えても、選ぶ権利は失われません。</p></div><div><p class="text-lg lg:text-2xl text-emerald-700 mb-1 flex items-center gap-3"><span>●</span> 可能性の追求</p><p class="text-sm lg:text-lg pl-8 lg:pl-12 text-slate-600 font-bold">年齢を理由に、改善を諦めない関わりを。</p></div><div><p class="text-lg lg:text-2xl text-emerald-700 mb-1 flex items-center gap-3"><span>●</span> 共同の歩み</p><p class="text-sm lg:text-lg pl-8 lg:pl-12 text-slate-600 font-bold">「支える側」ではなく「共に歩む側」として。</p></div></div></div>` },
    { title: "ケアの鏡：自分だったら？", order: 22, content: `<div class="space-y-6 lg:space-y-8 text-center flex flex-col items-center justify-center h-full px-4 w-full"><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight">自立支援の本質</h4><div class="p-8 lg:p-10 bg-white border-[4px] lg:border-[6px] border-emerald-600 rounded-[2rem] lg:rounded-[3rem] shadow-2xl max-w-3xl mx-auto w-full"><p class="text-xl lg:text-2xl font-black text-emerald-900 leading-relaxed italic text-balance text-center">もしあなたが利用者になった時、<br/>何でも先回りして介助される毎日を<br/>「幸せ」と感じますか？</p></div><p class="font-black text-sm lg:text-lg text-slate-800 mt-2 text-balance">自分でできる喜びを奪わないケア。<br/>それがプロの優しさです。</p></div>` },
    { title: "これからのケア標準モデル", order: 23, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left"><div class="space-y-4"><h4 class="text-2xl lg:text-4xl font-black text-emerald-900 flex items-center gap-4 lg:gap-6"><span class="w-2 h-8 lg:w-3 lg:h-12 bg-emerald-700 rounded-full"></span>2024年以降の姿</h4></div><ul class="space-y-4 lg:space-y-6 text-lg lg:text-3xl font-black text-slate-800 pl-0 leading-tight"><li class="whitespace-nowrap">・テクノロジー（ICT）を対話の創出に活用する</li><li class="whitespace-nowrap">・地域資源（ボランティア等）との積極的な協働</li><li class="whitespace-nowrap">・利用者の「やりたい」を計画の真ん中に置く</li></ul></div>` },
    { title: "家族との協働による自立支援", order: 24, content: `<div class="flex flex-col justify-center h-full space-y-6 lg:space-y-8 px-4 lg:px-12 text-left"><div class="space-y-4"><h4 class="text-2xl lg:text-4xl font-black text-blue-800 flex items-center gap-4 lg:gap-6"><span class="w-2 h-8 lg:w-3 lg:h-12 bg-blue-700 rounded-full"></span>家族の意識改革</h4></div><ul class="space-y-4 lg:space-y-6 text-lg lg:text-3xl font-black text-slate-800 pl-0 leading-tight"><li class="whitespace-nowrap">・「何もしない」が冷たいのではないと共有する</li><li class="whitespace-nowrap">・日々の小さな改善をデータで家族に報告する</li><li class="whitespace-nowrap">・家族と一緒に、自立の目標達成を祝う</li></ul></div>` },
    { title: "明日への一歩", order: 25, content: `<div class="flex flex-col items-center text-center space-y-6 lg:space-y-10 w-full h-full justify-center text-slate-900 px-4"><div class="w-24 h-24 lg:w-28 h-28 bg-emerald-700 rounded-[2.5rem] lg:rounded-[3rem] flex items-center justify-center shadow-2xl rotate-3 transition-transform hover:rotate-0 duration-500"><svg class="w-12 h-12 lg:w-16 h-16 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z" /></svg></div><h3 class="text-2xl lg:text-4xl font-black leading-tight">「お世話」から「伴走」へ。<br/>全員で意識を変えましょう。</h3><div class="pt-8 lg:pt-10 border-t-2 border-slate-200 w-full max-w-md text-center"><p class="text-slate-500 font-black text-[8px] lg:text-[10px] uppercase tracking-[0.5em]">End of Session</p></div></div>` },
    { title: "理解度テストのご案内", order: 26, content: `
        <div class="flex flex-col items-center text-center space-y-4 lg:space-y-6 w-full h-full justify-center px-4">
          <div class="bg-emerald-600 text-white px-6 py-1.5 rounded-full text-[8px] lg:text-[10px] font-black tracking-[0.3em] uppercase inline-block mb-4 lg:mb-2 shadow-lg">Course Completed</div>
          <h2 class="text-2xl lg:text-4xl font-black text-slate-900 leading-tight mb-2">講義セッション終了</h2>
          <p class="text-emerald-800 text-base lg:text-xl font-black leading-relaxed">大変お疲れ様でした。<br/>最後に理解度テスト（全10問）を行います。</p>
          <div class="p-4 lg:p-6 bg-blue-50 rounded-2xl lg:rounded-3xl border-2 border-blue-100 max-w-lg mx-auto mt-6">
            <p class="text-blue-900 font-black text-sm lg:text-lg flex items-center justify-center gap-3">
              <span class="w-2 h-2 bg-blue-700 rounded-full"></span>
              全問正解を目指しましょう！
              <span class="w-2 h-2 bg-blue-700 rounded-full"></span>
            </p>
          </div>
        </div>
      ` }
  ]

  const questionsData = [
    { text: '自立支援・重度化防止の考え方として、適切なものはどれか？', explanation: '本人が「できること」まで代行してしまうと、機能の低下を招きます。残存機能を活かし、強みに着目することが自立支援の基本です。', order: 1, choices: { create: [{ text: '利用者の強み（できること）に着目し、その力を活かす', isCorrect: true }, { text: '効率を重視し、時間がかかる動作は職員が代行する', isCorrect: false }, { text: '転倒を防ぐため、歩行練習よりも車椅子移動を徹底する', isCorrect: false }, { text: 'なんでも「やってあげる」ことが最高の親切である', isCorrect: false }] } },
    { text: 'ICF（国際生活機能分類）において、自立支援で最も重視すべき視点はどれか？', explanation: 'ICFでは「できないこと（障害）」だけでなく、本人の「活動」や「参加」など、ポジティブな要素に焦点を当てることを重視します。', order: 2, choices: { create: [{ text: '「できないこと」を補うだけでなく、「できること」を増やす', isCorrect: true }, { text: '医学的な診断名だけでケア内容を決定する', isCorrect: false }, { text: '身体機能の回復のみを目標とする', isCorrect: false }, { text: '環境の影響は考慮しない', isCorrect: false }] } },
    { text: '2024年度改正で推進されている、三位一体の連携に含まれないものはどれか？', explanation: 'リハビリテーション、口腔管理、栄養管理の3つを一体的に進めることが、重度化防止の核となっています。', order: 3, choices: { create: [{ text: '財務管理', isCorrect: true }, { text: 'リハビリテーション', isCorrect: false }, { text: '口腔管理', isCorrect: false }, { text: '栄養管理', isCorrect: false }] } },
    { text: '科学的介護（LIFE）において、PDCAサイクルを回す目的として正しいものは？', explanation: 'LIFEは、収集したデータを分析・フィードバックし、実際のケアの質を改善（PDCA）していくために活用されます。', order: 4, choices: { create: [{ text: '客観的なデータに基づき、ケアの質を継続的に改善する', isCorrect: true }, { text: '厚生労働省への報告作業を増やすため', isCorrect: false }, { text: '職員の監視を強化するため', isCorrect: false }, { text: '書類を増やすこと自体が目的である', isCorrect: false }] } },
    { text: '「フレイル（虚弱）」を予防するために、栄養面で特に意識すべきことは？', explanation: '筋肉量を維持しフレイルを防ぐためには、適切なエネルギー量に加えて、タンパク質の摂取が重要です。', order: 5, choices: { create: [{ text: 'タンパク質を含め、バランスの良い栄養を摂取する', isCorrect: true }, { text: '低カロリーなものだけを食べる', isCorrect: false }, { text: 'サプリメントのみで補う', isCorrect: false }, { text: '水分さえ摂っていれば問題ない', isCorrect: false }] } },
    { text: '口腔機能の低下が全身に与える影響として、誤っているものはどれか？', explanation: '口腔機能の低下は、噛めないことによる栄養不足や、誤嚥性肺炎のリスクを高めます。「心肺機能が向上する」ことはありません。', order: 6, choices: { create: [{ text: '心肺機能が劇的に向上する', isCorrect: true }, { text: '誤嚥性肺炎のリスクが高まる', isCorrect: false }, { text: '栄養状態が悪化する', isCorrect: false }, { text: '認知機能の低下に繋がることがある', isCorrect: false }] } },
    { text: '「生活リハビリ」の具体的な考え方として、適切なものはどれか？', explanation: 'リハビリは訓練室だけでなく、食事・更衣・移動などの日常生活動作そのものを通じて行うことが最も効果的です。', order: 7, choices: { create: [{ text: '日常生活のあらゆる動作をリハビリの機会として捉える', isCorrect: true }, { text: 'リハビリの時間以外はなるべく安静にしてもらう', isCorrect: false }, { text: '専門職に全てを任せ、介護職は関与しない', isCorrect: false }, { text: '歩行訓練だけをリハビリと呼ぶ', isCorrect: false }] } },
    { text: '社会参加の促進が介護予防に与える効果として、正しいものは？', explanation: '他者との交流や役割を持つことは、孤独を防ぎ、脳を活性化させ、ADL（日常生活動作）の維持に大きく貢献します。', order: 8, choices: { create: [{ text: '生きがいや役割を持つことで、生活意欲と機能維持に繋がる', isCorrect: true }, { text: '社会参加は疲れを招くだけで逆効果である', isCorrect: false }, { text: '一人で静かに過ごすことだけが介護予防である', isCorrect: false }, { text: '認知症の進行には全く影響しない', isCorrect: false }] } },
    { text: '認知症の方への介護予防・自立支援で、大切な視点はどれか？', explanation: 'できないことを指摘するのではなく、今できていることや得意なことを活かし、本人の尊厳と意欲を守る関わりが重要です。', order: 9, choices: { create: [{ text: '「できること」を最大限に褒め、尊厳と意欲を支える', isCorrect: true }, { text: '危ないことは全て禁止し、安全を最優先に管理する', isCorrect: false }, { text: 'できないことを厳しく指摘して訓練させる', isCorrect: false }, { text: '本人の意思よりも職員の都合を優先する', isCorrect: false }] } },
    { text: '自立支援を実践する上で、プロとして今日からできる関わりはどれか？', explanation: '「何でもしてあげる」過剰介護から脱却し、利用者が自分の力を使える場面を根気強く見守り、支えることがプロの関わりです。', order: 10, choices: { create: [{ text: '本人の「やろうとする意思」を尊重し、見守りながら支える', isCorrect: true }, { text: 'なるべく早く終わるように介助をスピードアップする', isCorrect: false }, { text: '本人が声を出すまで何もしない', isCorrect: false }, { text: '自分一人の判断でケアの方法をコロコロ変える', isCorrect: false }] } }
  ]

  let course = await prisma.course.findUnique({ where: { slug } })

  if (course) {
    await prisma.choice.deleteMany({ where: { question: { courseId: course.id } } })
    await prisma.question.deleteMany({ where: { courseId: course.id } })
    await prisma.slide.deleteMany({ where: { courseId: course.id } })
    
    course = await prisma.course.update({
      where: { id: course.id },
      data: {
        ...courseData,
        slides: { create: slidesData },
        questions: { create: questionsData }
      }
    })
  } else {
    course = await prisma.course.create({
      data: {
        ...courseData,
        slides: { create: slidesData },
        questions: { create: questionsData }
      }
    })
  }

  return course
}
