import { PrismaClient } from '@prisma/client'

export async function seedHarassment(prisma: PrismaClient) {
  const slug = 'harassment'
  const courseData = {
    slug,
    title: 'ハラスメント対策研修（2024年度）',
    description: '〜誰もが安心して働ける、尊厳ある職場を創るために〜',
    introduction: `
        <div class="flex flex-col items-center justify-center text-center space-y-3 pt-4 px-4">
          <div class="flex items-center gap-4">
            <span class="h-px w-8 lg:w-12 bg-rose-700 rounded-full"></span>
            <p class="text-rose-800 font-black tracking-widest text-lg lg:text-2xl uppercase">ハラスメント対策研修</p>
            <span class="h-px w-8 lg:w-12 bg-rose-700 rounded-full"></span>
          </div>
          <h2 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight">「その言動、<br class="lg:hidden"/>相手はどう感じていますか？」</h2>
          <div class="max-w-2xl space-y-2 text-slate-800 text-sm lg:text-base leading-relaxed font-bold">
            <p>「熱心な指導のつもりだった」「冗談のつもりだった」<br/>その主観が、知らぬ間に誰かの尊厳を傷つけ、<br class="lg:hidden" />職場を破壊しているかもしれません。</p>
            <div class="p-4 lg:p-5 bg-rose-50 rounded-[1.5rem] lg:rounded-[2rem] border-2 border-rose-200 shadow-inner relative overflow-hidden text-[10px] lg:text-xs text-left mt-4">
              <div class="absolute top-0 right-0 w-16 h-16 lg:w-24 lg:h-24 bg-rose-100/50 rounded-bl-full"></div>
              <p class="relative z-10 italic text-rose-900 font-black text-xs lg:text-sm text-balance leading-relaxed">ハラスメントは個人の尊厳を傷つけるだけでなく、離職の連鎖やケアの質の低下を招く、組織にとっての「猛毒」です。放置すれば、積み上げてきた信頼は一瞬で崩れ去ります。</p>
            </div>
            <p class="text-[10px] lg:text-sm text-slate-900 font-black text-center mt-4 text-balance">2024年度からの義務化に伴い、今、全ての職員に<br/>「正しく恐れ、正しく振る舞う」知性が求められています。</p>
          </div>
        </div>
      `,
    learningObjectives: `
        <div class="flex flex-col items-center justify-center text-center space-y-4 pt-4 px-4 w-full">
          <div class="bg-rose-700 text-white px-6 py-2 rounded-full text-[10px] font-black tracking-[0.3em] uppercase mb-2 shadow-lg shadow-rose-200">Learning Objectives</div>
          <div class="grid grid-cols-1 gap-3 w-full max-w-2xl">
            <div class="group p-4 bg-white border-2 border-slate-200 rounded-[1.5rem] lg:rounded-[2rem] shadow-sm flex items-center gap-4 lg:gap-6 hover:shadow-xl hover:border-rose-400 transition-all duration-500">
              <div class="w-10 h-10 lg:w-12 lg:h-12 bg-rose-700 text-white rounded-xl flex items-center justify-center text-base lg:text-lg font-black shrink-0 shadow-lg shadow-rose-200">1</div>
              <div class="text-left">
                <h4 class="text-sm lg:text-lg font-black text-slate-900">境界線を正しく理解する</h4>
                <p class="text-slate-800 text-[10px] lg:text-xs font-bold leading-relaxed text-balance">パワハラ、セクハラ、カスハラの定義を学び、「指導」と「侵害」の違いを明確に説明できる。</p>
              </div>
            </div>
            <div class="group p-4 bg-white border-2 border-slate-200 rounded-[1.5rem] lg:rounded-[2rem] shadow-sm flex items-center gap-4 lg:gap-6 hover:shadow-xl hover:border-rose-400 transition-all duration-500">
              <div class="w-10 h-10 lg:w-12 lg:h-12 bg-rose-700 text-white rounded-xl flex items-center justify-center text-base lg:text-lg font-black shrink-0 shadow-lg shadow-rose-200">2</div>
              <div class="text-left">
                <h4 class="text-sm lg:text-lg font-black text-slate-900">組織的な対応力を身につける</h4>
                <p class="text-slate-800 text-[10px] lg:text-xs font-bold leading-relaxed text-balance">発生時やカスハラ遭遇時に、独りで抱えずチームで動く手順と、法的リスクを理解する。</p>
              </div>
            </div>
            <div class="group p-4 bg-white border-2 border-slate-200 rounded-[1.5rem] lg:rounded-[2rem] shadow-sm flex items-center gap-4 lg:gap-6 hover:shadow-xl hover:border-rose-400 transition-all duration-500">
              <div class="w-10 h-10 lg:w-12 lg:h-12 bg-rose-700 text-white rounded-xl flex items-center justify-center text-base lg:text-lg font-black shrink-0 shadow-lg shadow-rose-200">3</div>
              <div class="text-left">
                <h4 class="text-sm lg:text-lg font-black text-slate-900">心理的安全性を自ら創る</h4>
                <p class="text-slate-800 text-[10px] lg:text-xs font-bold text-balance leading-relaxed">感情のコントロールやアサーティブな対話を通じ、誰もが意見を言える「最強の現場」を支える。</p>
              </div>
            </div>
          </div>
        </div>
      `,
    badgeLabel: 'ハラスメント',
    badgeIcon: 'ShieldCheck',
  }

  const slidesData = [
    { title: "ハラスメント対策研修", order: 0, content: `<div class="flex flex-col items-center justify-center text-center space-y-6 w-full h-full"><div class="relative w-full max-w-4xl px-4"><div class="absolute inset-0 bg-rose-400 blur-3xl opacity-20 scale-150 animate-pulse"></div><div class="relative bg-transparent lg:bg-white p-0 lg:p-16 rounded-none lg:rounded-[3.5rem] shadow-none lg:shadow-2xl border-none lg:border lg:border-slate-200 w-full mx-auto text-center"><div class="bg-rose-700 text-white px-4 lg:px-6 py-1 lg:py-1.5 rounded-full text-[8px] lg:text-[10px] font-black tracking-[0.3em] uppercase inline-block mb-6 lg:mb-8 shadow-sm">Legal Training 2024</div><h2 class="text-3xl lg:text-5xl font-black text-slate-900 leading-tight mb-4 text-balance">ハラスメント対策研修</h2><p class="text-rose-700 text-sm lg:text-3xl font-black mt-2 whitespace-nowrap">〜誰もが自分らしく輝ける職場へ〜</p></div></div><div class="flex items-center justify-center gap-4 text-slate-500 font-black text-[8px] lg:text-[10px] tracking-widest pt-4"><span class="h-px w-6 lg:w-8 bg-slate-300"></span>CARE LEARNING SYSTEM<span class="h-px w-6 lg:w-8 bg-slate-300"></span></div></div>` },
    
    { title: "はじめに：なぜ今、対策が必要か", order: 1, content: `<div class="space-y-6 lg:space-y-8 text-center px-4 h-full flex flex-col justify-center"><div class="inline-flex items-center gap-3 px-4 py-2 bg-rose-100 text-rose-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-rose-200 mb-2 uppercase tracking-widest mx-auto">Introduction</div><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight px-4 text-balance">ハラスメントは「文化の病」であり<br/>「経営の致命傷」です</h4><div class="p-0 lg:p-10 bg-transparent lg:bg-rose-50 border-none lg:border-2 lg:border-rose-100 shadow-none lg:shadow-xl rounded-none lg:rounded-[3rem] text-center lg:text-left text-sm lg:text-xl font-bold text-rose-800 space-y-4 lg:space-y-6 leading-relaxed max-w-4xl mx-auto px-4"><p class="font-black text-center lg:text-left text-balance">介護現場におけるハラスメントは、職員の心身を蝕むだけでなく、ケアの質の低下、離職の連鎖、さらには虐待の温床となる「負の連鎖」の起点となります。</p><p class="font-black text-rose-700 underline underline-offset-4 text-center lg:text-left text-balance italic">2024年度、全ての事業所にハラスメント防止措置が「完全義務化」されました。</p></div></div>` },

    { title: "ハラスメントが招く「組織の崩壊」", order: 2, content: `<div class="space-y-6 lg:space-y-10 text-center flex flex-col items-center justify-center h-full px-4 w-full"><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-relaxed mb-4 lg:mb-8 text-balance">放置することの「膨大な代償」</h4><div class="grid grid-cols-1 lg:grid-cols-3 gap-4 lg:gap-6 max-w-5xl mx-auto w-full"><div class="p-6 bg-white border-2 border-slate-200 rounded-3xl shadow-xl flex flex-col items-center gap-4"><div class="w-12 h-12 bg-rose-100 rounded-full flex items-center justify-center text-rose-600 font-black">1</div><p class="font-black text-lg text-rose-800">人材の枯渇</p><p class="text-xs lg:text-sm font-bold text-slate-600 text-balance text-center">優秀な職員から先に静かに去り、悪評はSNSで広まり、採用困難な職場へ転落します。</p></div><div class="p-6 bg-white border-2 border-slate-200 rounded-3xl shadow-xl flex flex-col items-center gap-4"><div class="w-12 h-12 bg-rose-100 rounded-full flex items-center justify-center text-rose-600 font-black">2</div><p class="font-black text-lg text-rose-800">サービスの破綻</p><p class="text-xs lg:text-sm font-bold text-slate-600 text-balance text-center">恐怖や不安が蔓延すると職員は思考停止し、ヒヤリハットが隠蔽され、重大事故へ繋がります。</p></div><div class="p-6 bg-white border-2 border-slate-200 rounded-3xl shadow-xl flex flex-col items-center gap-4"><div class="w-12 h-12 bg-rose-100 rounded-full flex items-center justify-center text-rose-600 font-black">3</div><p class="font-black text-lg text-rose-800">法的・社会的制裁</p><p class="text-xs lg:text-sm font-bold text-slate-600 text-balance text-center">損害賠償だけでなく、行政処分や指定取消のリスク、ブランド価値の喪失を招きます。</p></div></div></div>` },

    { title: "1. パワーハラスメント：定義の再確認", order: 3, content: `<div class="flex flex-col justify-center h-full space-y-8 lg:space-y-12 px-4 lg:px-12 text-left"><div class="space-y-4 lg:space-y-6 text-left"><h4 class="text-2xl lg:text-5xl font-black text-blue-900 flex items-center gap-4 lg:gap-6"><span class="w-2 h-10 lg:w-3 lg:h-16 bg-blue-700 rounded-full"></span>パワハラを構成する「3要素」</h4></div><div class="space-y-4 lg:space-y-6 font-black text-slate-800 max-w-4xl"><p class="text-lg lg:text-2xl leading-relaxed">以下の3つを「全て満たすもの」がパワハラです：</p><ul class="space-y-4 lg:space-y-6 text-base lg:text-3xl pl-4"><li class="flex items-start gap-3"><span class="text-blue-700 text-2xl lg:text-4xl">①</span><span>優越的な関係を背景とした言動</span></li><li class="flex items-start gap-3"><span class="text-blue-700 text-2xl lg:text-4xl">②</span><span>業務上必要かつ相当な範囲を超えたもの</span></li><li class="flex items-start gap-3"><span class="text-blue-700 text-2xl lg:text-4xl">③</span><span>就業環境を害するもの（身体・精神的苦痛）</span></li></ul><p class="text-xs lg:text-lg text-slate-500 italic mt-4">※「優越的な関係」とは、職位だけでなく、専門知識や経験の差、集団による孤立化も含まれます。</p></div></div>` },

    { title: "「指導」と「パワハラ」の決定的な違い", order: 4, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-6 lg:space-y-8 px-4 w-full"><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight">境界線は「人格への敬意」にある</h4><div class="grid grid-cols-1 lg:grid-cols-2 gap-4 lg:gap-6 max-w-5xl mx-auto w-full"><div class="p-6 lg:p-8 bg-blue-50 border-2 border-blue-100 rounded-[2rem] text-left space-y-3 shadow-sm"><p class="font-black text-base lg:text-xl text-blue-700">【正当な指導（成長を促す）】</p><ul class="text-[10px] lg:text-sm font-bold text-slate-700 space-y-1"><li>・目的：業務の改善、本人の成長</li><li>・対象：本人の「行為（アクション）」</li><li>・場所：原則として別室、1対1</li><li>・態度：冷静、事実に基づく対話</li></ul></div><div class="p-6 lg:p-8 bg-rose-50 border-2 border-rose-100 rounded-[2rem] text-left space-y-3 shadow-sm"><p class="font-black text-base lg:text-xl text-rose-700">【パワハラ（尊厳を破壊する）】</p><ul class="text-[10px] lg:text-sm font-bold text-slate-700 space-y-1"><li>・目的：感情の発散、支配、排除</li><li>・対象：本人の「人格・存在（キャラ）」</li><li>・場所：皆の前（羞恥心を与える）</li><li>・態度：威圧、感情の爆発、人格否定</li></ul></div></div><p class="text-xs lg:text-lg font-bold text-slate-900 text-balance">「愛のムチ」という言葉は、現代の介護現場では通用しません。</p></div>` },

    { title: "パワハラの6つの典型的な類型", order: 5, content: `<div class="space-y-6 lg:space-y-10 text-center flex flex-col items-center justify-center h-full px-4 w-full"><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-relaxed mb-2">厚労省が定める「攻撃」の形</h4><div class="grid grid-cols-2 lg:grid-cols-3 gap-3 lg:gap-4 max-w-5xl mx-auto w-full"><div class="p-4 bg-white border-2 border-slate-100 rounded-2xl shadow-sm hover:border-blue-400 transition-all"><p class="font-black text-blue-700 text-sm lg:text-base">身体的攻撃</p><p class="text-[8px] lg:text-[10px] text-slate-500">暴行・傷害</p></div><div class="p-4 bg-white border-2 border-slate-100 rounded-2xl shadow-sm hover:border-blue-400 transition-all"><p class="font-black text-blue-700 text-sm lg:text-base">精神的攻撃</p><p class="text-[8px] lg:text-[10px] text-slate-500">脅迫・名誉毀損・暴言</p></div><div class="p-4 bg-white border-2 border-slate-100 rounded-2xl shadow-sm hover:border-blue-400 transition-all"><p class="font-black text-blue-700 text-sm lg:text-base">人間関係の切り離し</p><p class="text-[8px] lg:text-[10px] text-slate-500">隔離・仲間外し・無視</p></div><div class="p-4 bg-white border-2 border-slate-100 rounded-2xl shadow-sm hover:border-blue-400 transition-all"><p class="font-black text-blue-700 text-sm lg:text-base">過大な要求</p><p class="text-[8px] lg:text-[10px] text-slate-500">遂行不可能な業務の強制</p></div><div class="p-4 bg-white border-2 border-slate-100 rounded-2xl shadow-sm hover:border-blue-400 transition-all"><p class="font-black text-blue-700 text-sm lg:text-base">過小な要求</p><p class="text-[8px] lg:text-[10px] text-slate-500">能力以下の雑用のみ</p></div><div class="p-4 bg-white border-2 border-slate-100 rounded-2xl shadow-sm hover:border-blue-400 transition-all"><p class="font-black text-blue-700 text-sm lg:text-base">個の侵害</p><p class="text-[8px] lg:text-[10px] text-slate-500">私的事項への過度な干渉</p></div></div></div>` },

    { title: "2. セクシュアルハラスメント：『不快』が基準", order: 6, content: `<div class="flex flex-col justify-center h-full space-y-8 lg:space-y-12 px-4 lg:px-12 text-left"><div class="space-y-4 lg:space-y-6 text-left"><h4 class="text-2xl lg:text-5xl font-black text-purple-900 flex items-center gap-4 lg:gap-6"><span class="w-2 h-10 lg:w-3 lg:h-16 bg-purple-700 rounded-full"></span>セクハラは「意図」を問わない</h4></div><div class="space-y-6 lg:space-y-10 max-w-4xl"><p class="text-lg lg:text-3xl font-black text-slate-800 leading-relaxed text-balance">性的言動により相手が「不快」と感じ、働く意欲が削がれればセクハラです。</p><div class="grid grid-cols-1 gap-4 font-black text-slate-700 text-sm lg:text-2xl"><div>・「食事にいつ行くの？」といった執拗な誘い</div><div>・「男（女）のくせに」といったジェンダーハラスメント</div><div>・SOGI（性的指向・性自認）に関する揶揄やアウティング</div><div>・不必要な身体への接触、外見の評価</div></div><p class="text-xs lg:text-lg font-bold text-rose-700 bg-rose-50 p-4 rounded-xl text-balance">※加害者が「褒めたつもり」「コミュニケーションのつもり」だったとしても、免罪符にはなりません。</p></div></div>` },

    { title: "3. マタニティ・パタニティハラスメント", order: 7, content: `<div class="flex flex-col items-center justify-center h-full text-left space-y-6 lg:space-y-10 px-6 lg:px-12 w-full"><h4 class="text-xl lg:text-3xl font-black text-emerald-800 flex items-center gap-4 w-full text-left"><span class="w-2 h-10 lg:w-3 lg:h-16 bg-emerald-600 rounded-full"></span>ライフステージへの敬意</h4><p class="text-sm lg:text-2xl font-black leading-relaxed text-slate-900 max-w-4xl bg-emerald-50 p-6 lg:p-8 rounded-2xl lg:rounded-3xl border border-emerald-100 w-full text-balance">妊娠・出産・育児・介護といった人生の節目にある職員に対し、「忙しい時に迷惑だ」「休むならボーナスを減らす」などの嫌がらせや不利益な扱いは法律で厳禁されています。</p><p class="text-xs lg:text-xl font-black text-slate-700 text-center w-full">「お互い様」と言い合えるチームこそが、持続可能な現場を作ります。</p></div>` },

    { title: "4. カスタマーハラスメント（カスハラ）", order: 8, content: `<div class="p-8 lg:p-12 bg-amber-50 rounded-[2.5rem] lg:rounded-[4rem] border-4 border-amber-300 border-dashed text-center shadow-inner max-w-4xl mx-auto flex flex-col items-center justify-center h-full px-4"><div class="bg-amber-700 text-white px-6 lg:px-8 py-1.5 lg:py-2 rounded-full text-[8px] lg:text-[10px] font-black inline-block mb-6 lg:mb-8 uppercase tracking-widest shadow-lg">介護現場の最重要課題</div><h4 class="text-xl lg:text-3xl font-black text-amber-950 mb-6 lg:mb-8 italic text-balance text-center">利用者・家族からの<br/>暴言・暴力・不当な要求</h4><p class="text-lg lg:text-xl font-black text-amber-900 leading-relaxed py-4 lg:py-6 px-4">「金払ってるんだから言うことを聞け」<br/>その一線を超えた要求は、サービスではなく『権利侵害』です。</p><p class="text-xs lg:text-sm font-bold text-amber-800 mt-4 text-center text-balance">職員の心を守ることは、事業所の「安全配慮義務」の一環です。</p></div>` },

    { title: "カスハラへの『組織的』対応フロー", order: 9, content: `<div class="flex flex-col items-center justify-center h-full text-left space-y-6 lg:space-y-8 px-6 lg:px-12 w-full"><h4 class="text-xl lg:text-3xl font-black text-slate-900 text-center mb-4 uppercase tracking-widest w-full px-4">独りで抱え込まない・解決しない</h4><div class="space-y-6 lg:space-y-10 font-black text-slate-900 max-w-4xl mx-auto w-full"><div><p class="text-lg lg:text-2xl text-amber-700 mb-1 flex items-center gap-3"><span>1.</span> 記録と報告：</p><p class="text-sm lg:text-xl pl-8 lg:pl-12 text-slate-600 font-bold">言動、時間、場所を正確にメモ。スマホ等での録音も有効な証拠になります。即座に上司へ報告を。</p></div><div><p class="text-lg lg:text-2xl text-amber-700 mb-1 flex items-center gap-3"><span>2.</span> 複数人対応：</p><p class="text-sm lg:text-xl pl-8 lg:pl-12 text-slate-600 font-bold">密室を避け、必ず2名以上で対応。組織として「これ以上の暴言は承れません」と姿勢を示します。</p></div><div><p class="text-lg lg:text-2xl text-amber-700 mb-1 flex items-center gap-3"><span>3.</span> 法的措置の検討：</p><p class="text-sm lg:text-xl pl-8 lg:pl-12 text-slate-600 font-bold">不当な要求が続く場合、契約解除や警察への被害届、弁護士連携も厭わないのがプロの組織です。</p></div></div></div>` },

    { title: "アンコンシャス・バイアス：無意識の武器", order: 10, content: `<div class="space-y-6 lg:space-y-10 text-center flex flex-col items-center justify-center h-full px-4 w-full"><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-relaxed mb-4 lg:mb-8">「普通は〜でしょ」が仲間を殺す</h4><div class="p-8 lg:p-12 bg-white border-[4px] border-slate-200 rounded-[2rem] shadow-xl max-w-3xl mx-auto w-full space-y-6"><p class="text-lg lg:text-2xl font-black text-slate-800 italic text-balance text-center">「最近の若い子は根性がない」「男のくせに力仕事が下手」「介護職なんだからこれくらい我慢しろ」</p><div class="h-px bg-slate-100"></div><p class="text-sm lg:text-xl font-bold text-blue-700 leading-relaxed text-balance text-center">自分の「当たり前」を押し付けることは、相手の多様な背景と努力を否定する『心理的暴力』になり得ます。常に自分の眼鏡が曇っていないか問いましょう。</p></div></div>` },

    { title: "アンガーマネジメント：6秒の壁を越える", order: 11, content: `<div class="p-6 lg:p-4 relative overflow-hidden text-left max-w-4xl mx-auto flex flex-col items-center h-full justify-center text-left"><div class="absolute -top-10 -right-10 w-64 h-64 bg-rose-50 rounded-full blur-3xl opacity-50"></div><h4 class="text-[10px] lg:text-[10px] font-black tracking-[0.4em] uppercase text-rose-800 mb-6 lg:mb-4 text-center py-2 px-6 bg-rose-50 rounded-full border border-rose-100 shadow-sm">Emotional Intelligence</h4><div class="space-y-4 lg:space-y-6 w-full lg:max-w-3xl text-slate-900 text-left"><div><p class="text-rose-800 text-[10px] lg:text-[10px] mb-1 uppercase tracking-widest font-black text-left">Step 01. 衝動のコントロール</p><div class="lg:flex lg:items-baseline lg:gap-6"><p class="text-2xl lg:text-4xl font-black whitespace-nowrap mb-1">6秒待つ</p><p class="text-sm lg:text-xl font-bold text-slate-600">怒りのホルモンが脳を支配するのは最初の6秒。深呼吸、数を数える、その場を離れる。この6秒で人生が変わります。</p></div></div><div class="h-px bg-slate-100 lg:my-1"></div><div><p class="text-rose-800 text-[10px] lg:text-[10px] mb-1 uppercase tracking-widest font-black text-left">Step 02. 言葉の変換</p><div class="lg:flex lg:items-baseline lg:gap-6"><p class="text-2xl lg:text-4xl font-black whitespace-nowrap mb-1 text-left">「私」を主語に</p><p class="text-sm lg:text-xl font-bold text-slate-600">「お前はいつも〜」という攻撃を捨て、「私は（こうされると困る・こうして欲しい）」というI-メッセージへ。</p></div></div></div></div>` },

    { title: "アサーション：爽やかな自己主張の技術", order: 12, content: `<div class="space-y-6 lg:space-y-10 text-center flex flex-col items-center justify-center h-full px-4 w-full"><h4 class="text-xl lg:text-3xl font-black text-emerald-900 leading-relaxed mb-4 lg:mb-8 text-balance">相手を立てながら、自分を殺さない</h4><div class="grid grid-cols-1 lg:grid-cols-2 gap-4 lg:gap-6 max-w-4xl mx-auto w-full"><div class="p-6 lg:p-8 bg-white border-2 border-slate-200 rounded-3xl shadow-xl text-left flex items-center gap-4 lg:gap-6 text-left"><div class="w-10 h-10 lg:w-12 lg:h-12 bg-emerald-700 text-white rounded-full flex items-center justify-center shrink-0 font-black text-xs lg:text-base">1</div><div class="text-left"><p class="font-black text-base lg:text-xl text-emerald-800 mb-1">DESC法で伝える</p><p class="text-[10px] lg:text-sm font-bold text-slate-700 leading-relaxed text-balance">Describe（事実）→Explain（気持ち）→Suggest（提案）→Choose（選択）の順で話します。</p></div></div><div class="p-6 lg:p-8 bg-white border-2 border-slate-200 rounded-3xl shadow-xl text-left flex items-center gap-4 lg:gap-6 text-left"><div class="w-10 h-10 lg:w-12 lg:h-12 bg-emerald-700 text-white rounded-full flex items-center justify-center shrink-0 font-black text-xs lg:text-base">2</div><div class="text-left"><p class="font-black text-base lg:text-xl text-emerald-800 mb-1 text-left">ノーを恐れない</p><p class="text-[10px] lg:text-sm font-bold text-slate-700 leading-relaxed text-balance">断ることは相手への拒絶ではなく、自分の境界線を示す『誠実な行動』です。</p></div></div></div></div>` },

    { title: "相談窓口と通報者の法的保護", order: 13, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-6 lg:space-y-8 px-4 w-full"><h4 class="text-xl lg:text-3xl font-black text-blue-900 leading-tight">声を上げたあなたが『盾』で守られる</h4><div class="p-8 lg:p-10 bg-white border-4 border-blue-100 rounded-[2rem] lg:rounded-[3rem] shadow-xl max-w-4xl mx-auto w-full space-y-6"><p class="text-lg lg:text-2xl font-black leading-relaxed text-slate-900 text-balance text-center">相談者のプライバシーは徹底的に保護されます。<br/><span class="text-rose-700 underline underline-offset-8 decoration-4">通報を理由とした不利益な扱いは法律で厳禁</span>されており、事業所にはそれを守る義務があります。</p><div class="h-px bg-slate-100"></div><p class="text-xs lg:text-lg font-bold text-slate-600 text-balance text-center">一人で耐え忍ぶことが美徳ではありません。壊れる前に、設置された窓口へアクセスしてください。</p></div></div>` },

    { title: "管理職の重い責任：『不作為の罪』", order: 14, content: `<div class="flex flex-col justify-center h-full space-y-8 lg:space-y-12 px-4 lg:px-12 text-left"><div class="space-y-4 lg:space-y-6 text-left"><h4 class="text-2xl lg:text-5xl font-black text-rose-900 flex items-center gap-4 lg:gap-6"><span class="w-2 h-10 lg:w-3 lg:h-16 bg-rose-700 rounded-full"></span>「見て見ぬふり」は加害者と同じ</h4></div><div class="space-y-6 lg:space-y-8 font-black text-slate-800 max-w-4xl text-base lg:text-2xl leading-relaxed text-left text-left text-left"><div>1. **早期発見**: 職場の空気を読み取り、異変を察知する。</div><div>2. **迅速な調査**: 曖昧にせず、公平な立場で事実を確認する。</div><div>3. **被害者の保護**: 物理的・心理的な距離を確保し、ケアを行う。</div><div>4. **行為者の是正**: 毅然とした態度で指導を行い、再発を防ぐ。</div></div><p class="text-xs lg:text-lg font-bold text-rose-800 italic mt-4 text-left text-left">※管理職がハラスメントを放置した場合、組織としての安全配慮義務違反に問われます。</p></div>` },

    { title: "ケーススタディ1：情熱という名の暴走", order: 15, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-6 lg:space-y-8 px-4 w-full"><div class="inline-flex items-center gap-3 px-4 py-2 bg-rose-50 text-rose-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-rose-200 mb-2 mx-auto uppercase">CASE STUDY 01</div><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4 text-balance">場面：新人教育の場での公開処刑</h4><div class="p-6 lg:p-8 bg-white border-2 border-slate-100 rounded-[2rem] shadow-xl max-w-4xl text-left space-y-4 w-full"><p class="text-sm lg:text-xl font-bold text-slate-800 leading-relaxed text-balance text-center">ベテラン職員のAさんは、新人のBさんのケアのミスに対し、申し送り中に他の職員の前で「何度言えばわかるの？センスないんじゃない？やる気がないなら帰っていいよ」と30分間罵倒しました。</p><div class="h-px bg-slate-100"></div><p class="text-xs lg:text-lg font-black text-rose-700 italic text-center px-4 text-balance">Aさんは「期待しているから厳しく言った。本人のためだ」と主張しています。あなたの判断は？</p></div></div>` },

    { title: "分析1：『期待』という免罪符の無効性", order: 16, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-6 lg:space-y-8 px-4 w-full"><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight px-4 text-balance">分析：これは明白な「精神的攻撃」です</h4><div class="grid grid-cols-1 lg:grid-cols-2 gap-4 lg:gap-6 max-w-5xl mx-auto w-full"><div class="p-6 lg:p-8 bg-rose-50 border-2 border-rose-100 rounded-[2rem] text-left space-y-3 shadow-sm text-left"><p class="font-black text-base lg:text-xl text-rose-700 text-left text-left">【アウトな要素】</p><ul class="text-[10px] lg:text-sm font-bold text-slate-700 space-y-1 text-left"><li>・公開の場での叱責（羞恥心と見せしめ）</li><li>・人格否定（センスない・やる気ない）</li><li>・雇用不安の煽り（帰っていい）</li><li>・必要以上の長時間（30分間）</li></ul></div><div class="p-6 lg:p-8 bg-blue-50 border-2 border-blue-100 rounded-[2rem] text-left space-y-3 shadow-sm text-left"><p class="font-black text-base lg:text-xl text-blue-700 text-left text-left">【プロの指導への変換】</p><ul class="text-[10px] lg:text-sm font-bold text-slate-700 space-y-1 text-left"><li>・場所を変え、1対1で行う</li><li>・ミスという「事象」と「改善策」のみに絞る</li><li>・相手の言い分を聴き、障害を取り除く</li><li>・感情をぶつけず、冷静なトーンを維持する</li></ul></div></div></div>` },

    { title: "ケーススタディ2：カスハラの泥沼", order: 17, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-6 lg:space-y-8 px-4 w-full"><div class="inline-flex items-center gap-3 px-4 py-2 bg-amber-50 text-amber-800 rounded-full text-[10px] lg:text-xs font-black ring-1 ring-amber-200 mb-2 mx-auto uppercase">CASE STUDY 02</div><h4 class="text-xl lg:text-2xl font-black text-slate-900 leading-tight px-4 text-balance">場面：利用者家族からの土下座要求</h4><div class="p-6 lg:p-8 bg-white border-2 border-slate-100 rounded-[2rem] shadow-xl max-w-4xl text-left space-y-4 w-full"><p class="text-sm lg:text-xl font-bold text-slate-800 leading-relaxed text-balance text-center">些細な洗濯物の入れ間違いに対し、家族が事務所に乗り込み「誠意を見せろ！担当者をここに呼んで土下座させろ！できないならネットで実名を晒すぞ」と2時間怒鳴り続けました。</p><div class="h-px bg-slate-100"></div><p class="text-xs lg:text-lg font-black text-amber-700 italic text-center px-4 text-balance">担当職員は恐怖で震えています。管理者であるあなたは、どう動きますか？</p></div></div>` },

    { title: "分析2：『お客様』ではなく『加害者』", order: 18, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-6 lg:space-y-8 px-4 w-full"><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight px-4 text-balance text-center">分析：屈従は解決になりません</h4><div class="grid grid-cols-1 lg:grid-cols-2 gap-4 lg:gap-6 max-w-5xl mx-auto w-full"><div class="p-6 lg:p-8 bg-rose-50 border-2 border-rose-100 rounded-[2rem] text-left space-y-3 shadow-sm text-left"><p class="font-black text-base lg:text-xl text-rose-700 text-left">【NG対応：火に油を注ぐ】</p><ul class="text-[10px] lg:text-sm font-bold text-slate-700 space-y-1 text-left text-left"><li>・担当者一人に謝罪させ続ける（生贄）</li><li>・要求に屈して土下座や過度なサービスをする</li><li>・「申し訳ございません」とだけ繰り返し、内容を精査しない</li></ul></div><div class="p-6 lg:p-8 bg-emerald-50 border-2 border-emerald-100 rounded-[2rem] text-left space-y-3 shadow-sm text-left"><p class="font-black text-base lg:text-xl text-emerald-700 text-left text-left text-left">【プロ対応：組織の防衛】</p><ul class="text-[10px] lg:text-sm font-bold text-slate-700 space-y-1 text-left text-left text-left"><li>・「これ以上の暴言は承れません」と警告し話を打ち切る</li><li>・脅迫に対しては法的措置を宣言し、録音を開始する</li><li>・職員を別室へ隔離し、メンタルケアを優先する</li><li>・事実関係を記録し、契約解除の手続きを進める</li></ul></div></div></div>` },

    { title: "SNSとハラスメント：デジタル時代の刃", order: 19, content: `<div class="space-y-6 lg:space-y-10 text-center flex flex-col items-center justify-center h-full px-4 w-full text-center"><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-relaxed mb-4 lg:mb-8 text-balance">ネットに『匿名』など存在しません</h4><div class="p-8 lg:p-12 bg-white border-[4px] border-rose-200 rounded-[2rem] shadow-xl max-w-3xl mx-auto w-full space-y-6"><p class="text-sm lg:text-xl font-bold text-slate-800 leading-relaxed text-balance">同僚への誹謗中傷、特定の利用者への不適切な言及、職場内の隠し撮りの投稿。これらは職場外の行為であっても、就業規則違反や名誉毀損罪に問われる重大なハラスメントです。</p><div class="h-px bg-slate-100"></div><p class="text-xs lg:text-lg font-black text-rose-700 text-balance text-center">デジタルタトゥーとして一生消えず、あなたの人生を破壊することを自覚しましょう。送信ボタンを押す前に、その言葉を『家族の前で言えるか』考えてください。</p></div></div>` },

    { title: "心理的安全性の構築：『最強の現場』の条件", order: 20, content: `<div class="flex flex-col items-center justify-center h-full text-center space-y-6 lg:space-y-10 px-4 w-full"><h4 class="text-xl lg:text-3xl font-black text-blue-900 leading-tight">ケアを救うのは『空気』です</h4><div class="p-8 lg:p-12 bg-blue-50 border-2 border-blue-200 rounded-[2.5rem] lg:rounded-[4rem] shadow-inner text-left max-w-4xl space-y-4 lg:space-y-6 mx-auto text-left"><div class="grid grid-cols-1 lg:grid-cols-2 gap-4 lg:gap-8 text-left"><div class="bg-white p-6 rounded-3xl shadow-sm border border-blue-100 text-left"><p class="text-blue-800 font-black mb-2 text-lg text-left">● ミスを宝にする空気</p><p class="text-sm font-bold text-slate-600 leading-relaxed text-left text-left">責められないからこそ、ミスを即報告でき、重大事故を未然に防げます。</p></div><div class="bg-white p-6 rounded-3xl shadow-sm border border-blue-100 text-left text-left"><p class="text-blue-800 font-black mb-2 text-lg text-left">● 健全な衝突を歓迎する</p><p class="text-sm font-bold text-slate-600 leading-relaxed text-left">忖度せず「それ、危ないですよ」と言い合える関係が、利用者の命を守ります。</p></div></div></div></div>` },

    { title: "自己変革：あなたから始める職場改革", order: 21, content: `<div class="space-y-6 lg:space-y-8 text-center flex flex-col items-center justify-center h-full w-full px-4"><h4 class="text-xl lg:text-3xl font-black text-slate-900 mb-4 lg:mb-6">職場を『心理的聖域』にするチェック</h4><div class="space-y-3 lg:space-y-4 font-black text-slate-900 text-sm lg:text-2xl max-w-4xl text-left text-left text-left"><div>□ 仲間の小さな変化（疲れ・悩み）に声をかけていますか？</div><div>□ 挨拶を「相手の目を見て」自分から行っていますか？</div><div>□ 「ありがとう」を具体的に、口に出して伝えていますか？</div><div>□ 自分の感情を『察してちゃん』にならず、言葉にしていますか？</div><div>□ 仲間の失敗を「明日は我が身」として支え合っていますか？</div></div></div>` },

    { title: "プロフェッショナルとしての誇り", order: 22, content: `<div class="space-y-6 lg:space-y-10 text-center flex flex-col items-center justify-center h-full px-4 w-full"><h4 class="text-xl lg:text-3xl font-black text-slate-900 leading-tight">私たちの『敵』は誰か？</h4><div class="p-8 lg:p-12 bg-white border-[4px] lg:border-[6px] border-rose-600 rounded-[2rem] lg:rounded-[3rem] shadow-2xl max-w-3xl mx-auto w-full"><p class="text-xl lg:text-3xl font-black text-rose-900 leading-relaxed italic text-balance text-center text-center">敵は隣にいる同僚ではありません。<br/>ハラスメントという「慢心と暴力」です。<br/>専門性を認め合い、手を取り合いましょう。</p></div><p class="font-black text-sm lg:text-xl text-slate-800 mt-4 text-balance">あなたの笑顔が、利用者の安心に直結しています。</p></div>` },

    { title: "全15科目、完遂おめでとうございます", order: 23, content: `<div class="flex flex-col items-center text-center space-y-8 lg:space-y-12 w-full h-full justify-center text-slate-900 px-4 text-center"><div class="w-24 h-24 lg:w-32 h-32 bg-rose-700 rounded-[2.5rem] lg:rounded-[3.5rem] flex items-center justify-center shadow-2xl shadow-rose-200 rotate-3 transition-transform hover:rotate-0 duration-500 mx-auto"><svg class="w-12 h-12 lg:w-16 h-16 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg></div><h3 class="text-2xl lg:text-5xl font-black leading-tight text-center text-center">全課程の修了、心より敬意を表します。<br/>現場を変える力が、今あなたに宿っています。</h3><div class="pt-8 lg:pt-12 border-t-2 border-slate-200 w-full max-w-md text-center mx-auto"><p class="text-slate-500 font-black text-[8px] lg:text-[10px] uppercase tracking-[0.5em] text-center">Mastery of All Sessions Accomplished</p></div></div>` },

    { title: "理解度テストのご案内", order: 24, content: `
        <div class="flex flex-col items-center text-center space-y-6 lg:space-y-8 w-full h-full justify-center px-4 text-center">
          <div class="bg-emerald-600 text-white px-6 py-1.5 rounded-full text-[8px] lg:text-[10px] font-black tracking-[0.3em] uppercase inline-block mb-4 lg:mb-6 shadow-lg text-center">Course Completed</div>
          <h2 class="text-2xl lg:text-5xl font-black text-slate-900 leading-tight mb-2 lg:mb-4 text-center">最終関門：理解度テスト</h2>
          <p class="text-emerald-800 text-base lg:text-2xl font-black leading-relaxed text-center">大変お疲れ様でした。<br/>最後に理解度テスト（全10問）を行います。</p>
          <div class="p-4 lg:p-6 bg-rose-50 rounded-2xl lg:rounded-3xl border-2 border-rose-100 max-w-lg mx-auto mt-6 lg:mt-8 text-center text-center">
            <p class="text-rose-900 font-black text-sm lg:text-xl flex items-center justify-center gap-3 text-center">
              <span class="w-2 h-2 bg-rose-700 rounded-full text-center"></span>
              全問正解で、真のリーダーへ
              <span class="w-2 h-2 bg-rose-700 rounded-full text-center"></span>
            </p>
          </div>
        </div>
      ` }
  ]

  const questionsData = [
    { text: 'パワーハラスメントの3要素を「すべて満たす」行為はどれか？', explanation: '優越的な関係を背景に、業務上必要かつ相当な範囲を超え、就業環境を害するものがパワハラです。人格否定や羞恥心を与える行為がこれに該当します。', order: 1, choices: { create: [{ text: '皆の前で「センスがない」「やる気がないなら帰れ」と長時間罵倒する', isCorrect: true }, { text: 'ミスをした部下を別室に呼び、原因と改善策を1対1で話し合う', isCorrect: false }, { text: '業務上、緊急性が高いため、強い口調で指示を出す', isCorrect: false }, { text: '能力に見合った難易度の高い業務を割り当てる', isCorrect: false }] } },
    { text: 'セクシュアルハラスメントの判断基準として、誤っている考え方はどれか？', explanation: 'セクハラは「加害者の意図」ではなく「被害者の主観（不快感）」が最大の基準です。冗談のつもりでも許されません。', order: 2, choices: { create: [{ text: '加害者が「褒めたつもり」であれば、ハラスメントにはならない', isCorrect: true }, { text: '性的言動により相手が不快に感じ、働く意欲が削がれれば該当する', isCorrect: false }, { text: '「男のくせに」といったジェンダーハラスメントも含まれる', isCorrect: false }, { text: '一度きりの言動であっても、重大な侵害であれば該当する', isCorrect: false }] } },
    { text: 'カスタマーハラスメント（カスハラ）への組織的対応として、最も「避けるべき」ものはどれか？', explanation: 'カスハラを現場の職員一人に解決させようとする「生贄」対応は、さらなる被害と離職を招きます。必ず組織（複数人）で対応します。', order: 3, choices: { create: [{ text: '担当職員一人で最後まで誠意を持って謝罪させ続け、場を収めさせる', isCorrect: true }, { text: '事実関係を正確に記録（メモ・録音）し、上司へ即座に報告する', isCorrect: false }, { text: '「これ以上の暴言は承れません」と警告し、毅然とした態度で話を打ち切る', isCorrect: false }, { text: '著しい権利侵害に対しては、警察への相談や契約解除を検討する', isCorrect: false }] } },
    { text: '妊娠・出産・育児等を理由とした不利益な扱いや嫌がらせを指す言葉はどれか？', explanation: 'マタニティハラスメント（マタハラ）やパタニティハラスメント（パタハラ）と呼ばれ、2024年度の義務化対象に含まれます。', order: 4, choices: { create: [{ text: 'マタニティハラスメント・パタニティハラスメント', isCorrect: true }, { text: 'ジェンダーハラスメント', isCorrect: false }, { text: 'シルバーハラスメント', isCorrect: false }, { text: 'エイジハラスメント', isCorrect: false }] } },
    { text: '自分の「普通・当たり前」という偏見が相手を傷つけることを何というか？', explanation: 'アンコンシャス・バイアス（無意識の偏見）と呼ばれます。これがハラスメントの無意識の引き金となります。', order: 5, choices: { create: [{ text: 'アンコンシャス・バイアス', isCorrect: true }, { text: 'アサーティブ・コミュニケーション', isCorrect: false }, { text: 'アンガーマネジメント', isCorrect: false }, { text: 'セルフ・コンパッション', isCorrect: false }] } },
    { text: '怒りの感情のピークをやり過ごすために有効とされる「6秒の魔法」とは？', explanation: '怒りのホルモンが脳を支配するピークは約6秒とされるため、その間待つことで衝動的な暴言を防ぐアンガーマネジメントの技術です。', order: 6, choices: { create: [{ text: '衝動的な言動を抑えるため、最初の6秒間を待つ', isCorrect: true }, { text: '6秒以内に相手の非を論破して言い返す', isCorrect: false }, { text: '6秒間、怒鳴り続けて感情をすべて発散する', isCorrect: false }, { text: '6秒以内にその場から全力で逃げ出す', isCorrect: false }] } },
    { text: '相手を尊重しつつ、自分の意見を誠実に伝える技術を何というか？', explanation: 'アサーション（アサーティブ・コミュニケーション）です。DESC法などの技術を用いて、爽やかに自己主張を行います。', order: 7, choices: { create: [{ text: 'アサーション', isCorrect: true }, { text: 'マインドフルネス', isCorrect: false }, { text: 'コーチング', isCorrect: false }, { text: 'ファシリテーション', isCorrect: false }] } },
    { text: 'ハラスメントの相談を受けた管理職や事業所の「安全配慮義務」として、正しいものはどれか？', explanation: '通報を理由とした不利益な扱いは法律で厳禁されており、相談者のプライバシー保護と身の安全の確保が最優先です。', order: 8, choices: { create: [{ text: '通報者のプライバシーを保護し、不利益な扱いを受けないよう守る', isCorrect: true }, { text: '「お互い様だから」と、相談をうやむやにして処理する', isCorrect: false }, { text: '加害者側に、誰がどのような相談をしたかすぐにすべて伝える', isCorrect: false }, { text: '証拠が不十分であれば、調査を行わずに様子を見る', isCorrect: false }] } },
    { text: 'SNSなどのネット上での誹謗中傷や職場内情報の投稿について、正しい理解はどれか？', explanation: '職場外の行為であっても、実名特定や名誉毀損に繋がる投稿は、ハラスメントとして懲戒や法的責任の対象になります。', order: 9, choices: { create: [{ text: '職場外の投稿であっても、就業環境を害すれば懲戒や法的責任の対象になる', isCorrect: true }, { text: '匿名アカウントであれば、何を書いても責任を問われない', isCorrect: false }, { text: '事実であっても、ネットに晒すことは正当な告発として認められる', isCorrect: false }, { text: '愚痴の範囲であれば、実名を特定できる投稿をしても問題ない', isCorrect: false }] } },
    { text: '「心理的安全性の高い職場」がもたらす介護現場への最大のメリットはどれか？', explanation: '誰もが非難を恐れずに発言できる空気は、ミスの早期報告（隠蔽の防止）に繋がり、結果として重大事故を未然に防ぎます。', order: 10, choices: { create: [{ text: 'ミスを隠さず即座に報告でき、重大事故を未然に防げる', isCorrect: true }, { text: '上司の機慣を損ねないよう、全員が細心の注意を払える', isCorrect: false }, { text: '職場の飲み会やイベントが強制されることで団結力が高まる', isCorrect: false }, { text: '波風が立たないよう、問題があっても誰も意見を言わない', isCorrect: false }] } }
  ]

  let course = await prisma.course.findUnique({ where: { slug } })

  if (course) {
    await prisma.choice.deleteMany({ where: { question: { courseId: course.id } } })
    await prisma.question.deleteMany({ where: { courseId: course.id } })
    await prisma.slide.deleteMany({ where: { courseId: course.id } })
    
    course = await prisma.course.update({
      where: { id: course.id },
      data: {
        ...courseData,
        slides: { create: slidesData },
        questions: { create: questionsData }
      }
    })
  } else {
    course = await prisma.course.create({
      data: {
        ...courseData,
        slides: { create: slidesData },
        questions: { create: questionsData }
      }
    })
  }

  return course
}
